```{r}
library(terra)
library(here)
library(sf)
library(tidyverse)
source(here("general_functions.R"))
source(here("analysis", "genetic_diversity", "functions_genetic_diversity.R"))

plotpath <- here("analysis", "gea", "plots")
adaptive_path <- here("analysis", "adaptive", "outputs", "RDA_bio1_ndvi")

adapind_load <- rast(here(adaptive_path, "adapind_load.tif"))
offset <- rast(here(adaptive_path, "offset_load_RCP85.tif"))
offset_total <- sum(offset)

pdf(here(plotpath, "adaptive_index.pdf"), width = 10, height = 10)
plot(adapind_load, main = "Adaptive index loadings", axes = FALSE)
plot(offset, main = "Adaptive index offset", axes = FALSE)
plot(offset_total, main = "Adaptive index offset (total)", axes = FALSE, col = viridis::inferno(100))
dev.off()
```

```{r}
coords <- get_coords(sf = TRUE)

genes <- 
  format_het(here("analysis", "gea", "outputs", "genes.het"), callable_sites = 1) %>%
  mutate(Ho_genes = 1 - `O(HOM)`/`N(NM)`) %>%
  dplyr::rename(SampleID = IID) %>%
  dplyr::select(SampleID, Ho_genes) %>%
  left_join(get_het())

offset_df <- 
  terra::extract(offset_total, coords, ID = FALSE) %>%
  mutate(SampleID = coords$SampleID) %>%
  as_tibble() %>%
  dplyr::rename(offset = sum) %>%
  left_join(genes) %>%
  drop_na(Ho, Ho_genes) %>%
  mutate(resids = residuals(lm(Ho_genes ~ Ho, data = .)))

#devtools::source_url("https://raw.githubusercontent.com/austinwpearce/SoilTestCocaCola/main/quad_plateau.R")


pdf(here(plotpath, "offset_vs_ho.pdf"), width = 4, height = 4)
ggplot(offset_df, aes(y = (offset), x = Ho, col = offset)) +
  geom_point() +
  geom_smooth(method = "lm", col = "black") +
  xlab("Genome-wide heterozygosity") +
  ylab("Future genomic offset") +
  scale_color_viridis_c(option = "inferno") +
  ggpubr::stat_cor() +
  theme_classic() +
  theme(legend.position = "none")

ggplot(offset_df, aes(y = (offset), x = Ho_genes, col = offset)) +
  geom_point() +
  geom_smooth(method = "lm", col = "black") +
  xlab("Adaptive heterozygosity") +
  ylab("Future genomic offset") +
  ggpubr::stat_cor() +
  scale_color_viridis_c(option = "inferno") +
  theme_classic()+
  theme(legend.position = "none")

ggplot(offset_df, aes(y = (offset), x = resids, col = offset)) +
  geom_point() +
  geom_smooth(method = "lm", col = "black") +
  xlab("Residuals of adaptive heterozygosity") +
  ylab("Future genomic offset") +
  ggpubr::stat_cor() +
  scale_color_viridis_c(option = "inferno") +
  theme_classic()+
  theme(legend.position = "none")
dev.off()
```

```{r}
source(here("analysis", "adaptive", "adaptive_index.R"))
bio1ndvi_envlayers <- import_env_files(type = "ind_layers", future = TRUE)
change = (bio1ndvi_envlayers$env_fut$CHELSA_bio1_2071.2100_gfdl.esm4_ssp585_V.2.1/10 - 273.15) -  bio1ndvi_envlayers$env_pres$BIO1 
pdf(here(plotpath, "env_future.pdf"), width = 10, height = 10)
plot(change, main = "Future environmental change", axes = FALSE, col = viridis::inferno(100))
dev.off()


change_df <- coords %>% mutate(change = terra::extract(change, coords, ID = FALSE)) %>% left_join(genes)

pdf(here(plotpath, "change_vs_env.pdf"), width = 4, height = 4)

plot(change, main = "Future environmental change", axes = FALSE, col = viridis::inferno(100))
ggplot(change_df, aes(y = (change), x = Ho_genes, col = change)) +
  geom_point() +
  geom_smooth(method = "lm", col = "black") +
  xlab("Adaptive heterozygosity") +
  ylab("Future temperature change") +
  ggpubr::stat_cor() +
  scale_color_viridis_c(option = "inferno") +
  theme_classic()+
  theme(legend.position = "none")
dev.off()
```
