```{r}
library(wingen)
library(here)
library(sf)
library(tidyverse)
library(terra)
library(vcfR)
library(cowplot)
library(spdep)
library(spatialreg)
library(furrr)
source(here("general_functions.R"))
source(here("analysis", "genetic_diversity", "functions_genetic_diversity.R"))
plotpath <- here("analysis", "gea", "plots")
```

```{r}
dos <- read_table(here("analysis", "gea", "outputs", "nonsyn.raw"))
# Load coords and model dataframe
coords <- 
  get_coords(sf = TRUE) %>% 
  filter(SampleID %in% dos$IID) %>% 
  st_transform(3310) %>%
  # REMOVE CHANNEL ISLAND
  filter(SampleID != "Scelocci_CCGPMC_MW01-3-14") 

mod_df <- read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv"))
mod_df <- left_join(coords, mod_df)

pop_df <- get_pops()

make_het <- function(path, coords){
  dos <- read_table(path)
  dos <- dos[dos$IID %in% coords$SampleID, ]

  # Check SampleIDs
  stopifnot(all(dos$IID == coords$SampleID))
  het <- dos[, -(1:6)]
  het <- matrix(ifelse(het == 1, 1, 0), nrow = nrow(het), ncol = ncol(het))

  # Confirm conversion works (same number of 1s)
  stopifnot(sum(het == 1, na.rm = TRUE) == sum(dos[, -(1:6)] == 1, na.rm = TRUE))
  
  return(het)
}

# Load dosage data and convert to het
nonsyn_het <- make_het(here("analysis", "gea", "outputs", "nonsyn.raw"), coords)
syn_het <- make_het(here("analysis", "gea", "outputs", "syn.raw"), coords)
neutral_het <- make_het(here("analysis", "gea", "outputs", "frqmatch.raw"), coords)
allnonsyn_het <- make_het(here("analysis", "gea", "outputs", "allnonsyn_frqmatch.raw"), coords)

# Make test dataset for later extractions
test_df <- 
  data.frame(
    ho_nonsyn = rowMeans(nonsyn_het, na.rm = TRUE), 
    ho_syn = rowMeans(syn_het, na.rm = TRUE), 
    ho_neutral = rowMeans(neutral_het, na.rm = TRUE),
    ho_allnonsyn = rowMeans(allnonsyn_het, na.rm = TRUE),
    coords
  )
``` 

```{r}
# Create raster with 10km resolution
lyr <- coords_to_raster(coords, res = 10000, buffer = 10)

png(here(plotpath, "gea_genes.png"), width = 800, height = 800)
sc <- preview_gd(lyr, coords, wdim = 9, sample_count = FALSE)
#sc[sc == 0] <- NA
#plot(sc)
dev.off()

# Load env list
env_paths <- list.files(here("data", "env", "model_rasters"))
env_list <- map(here("data", "env", "model_rasters", env_paths), rast)
names(env_list) <- gsub(".tif", "", env_paths)
# Resample all rasters to lyr
env_list <- map(env_list, ~resample(.x, lyr))

```

```{r}
# Run wingen for different wdim
run_wingen <- function(wdim, min_n = 1, cache = TRUE, overwrite = TRUE) {
  path <- here("analysis", "gea", "outputs", paste0("windowed_ho_gea_wdim_", wdim, "_min_n_", min_n, ".tif"))

  # Load existing raster if available
  if (file.exists(path) && cache) {
    message("Loading cached raster stack from: ", path)
    cached_stack <- rast(path)
    cached_layers <- names(cached_stack)
  } else {
    cached_stack <- NULL
    cached_layers <- character()
  }

  future::plan("multisession", workers = 10)

  # Define heterozygosity types
  het_types <- list(
    nonsyn = nonsyn_het,
    syn = syn_het,
    neutral = neutral_het,
    allnonsyn = allnonsyn_het
  )

  # Load or generate heterozygosity layers
  het_results_ls <- imap(het_types, function(data, name) {
    if (name %in% cached_layers) {
      message("Using cached heterozygosity layer: ", name)
      cached_stack[[name]]
    } else {
      message("Generating heterozygosity layer: ", name)
      window_general(data, coords, lyr, stat = "Ho", wdim = wdim, min_n = min_n)[["Ho"]]
    }
  })

  # Convert list to raster stack
  het_results <- rast(het_results_ls)

  # Validate input data
  stopifnot(all(names(env_list) %in% names(mod_df)))
  stopifnot(identical(mod_df$SampleID, coords$SampleID))

  # Define environmental variables
  env_vars <- names(env_list)
  names(env_vars) <- env_vars
  cached_env <- env_vars[env_vars %in% cached_layers]
  missing_env <- env_vars[!env_vars %in% cached_layers]

  # Load or generate environmental layers
  env_results_ls <- imap(env_vars, function(var, name) {
    if (name %in% cached_env) {
      message("Using cached environmental layer: ", name)
      cached_stack[[name]]
    } else {
      message("Generating env layer: ", name)
      custom_mean <- function(x) mean(x, na.rm = TRUE)
      window_general(mod_df[[var]], coords, lyr, stat = custom_mean, wdim = wdim, min_n = min_n)[[1]]
    }
  })

  # Convert list to raster stack
  env_results <- rast(env_results_ls)

  # Combine heterozygosity and environmental layers
  final_stack <- c(het_results, env_results)

  # Write only if new layers or overwrite is requested
  if (overwrite) {
    message("Writing updated raster stack to: ", path)
    final_stack <- final_stack + 0 # Load in memory before overwriting old file, workaround to get around terra's file locking
    writeRaster(final_stack, filename = path, overwrite = TRUE)
  } else {
    message("No new layers generated; using existing cache.")
  }

  future::plan("sequential")
  return(final_stack)
}

ca <- get_ca() %>% st_transform(st_crs(3310))

# Run wingen
# Mask to california so ocean values don't mess things up 
options(future.globals.maxSize = 1e9)
raw_stack <- map(c(3, 5, 7, 9), ~run_wingen(wdim = .x, min_n = 1, cache = TRUE))
stack <- map(raw_stack, ~mask(.x, ca, filename = "", overwrite = TRUE))
names(stack) <- c("wdim3", "wdim5", "wdim7", "wdim9")

pdf(here(plotpath, "wingen.pdf"), width = (5 * nlyr(stack[[1]]))/2, height = 10)
map(stack, ~do.call(plot_grid, c(ggplot_gd(.x, ca), nrow = 2)))
dev.off()
```

```{r}
env_df <- read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv"))
# Make wingen df
wingen_df <- 
  map(stack, ~{
    data.frame(terra::extract(.x, y = coords), SampleID = coords$SampleID, geometry = coords$geometry)
  }) %>% 
  bind_rows(.id = "wdim") %>%
  left_join(pop_df) %>%
  drop_na(cluster) %>%
  mutate(socal = case_when(cluster == 9 ~ "S. CA", TRUE ~ "Other")) %>%
  mutate(wsize = gsub("wdim", "", wdim)) %>%
  mutate(wsize = as.numeric(wsize)) %>%
  mutate(wsize = wsize * res(stack[[1]])[1]/1000) %>%
  mutate(wsize = paste0(round(wsize, 2), " km window")) %>%
  left_join(env_df, by = "SampleID") 

names(wingen_df) <- gsub("\\.y", "", names(wingen_df))  

wingen_stack_df <- 
  map(stack, ~as.data.frame(.x, xy = TRUE)) %>%
  bind_rows(.id = "wdim")  %>%
  mutate(wsize = gsub("wdim", "", wdim)) %>%
  mutate(wsize = as.numeric(wsize)) %>%
  mutate(wsize = wsize * res(stack[[1]])[1]/1000) %>%
  mutate(wsize = paste0(round(wsize, 2), " km window")) 
  
```
```{r}
gg_df <- wingen_df %>% pivot_longer(c("syn", "nonsyn", "allnonsyn"))
gg_df2 <- wingen_df %>% pivot_longer(c("syn", "nonsyn", "allnonsyn", "neutral")) %>% st_as_sf()
gg_stack_df <- wingen_stack_df %>% pivot_longer(c("syn", "nonsyn", "allnonsyn", "neutral"))

pdf(here(plotpath, "wingen_map.pdf"), width = 9, height = 9)
ggplot(gg_stack_df) +
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = value)) +
  geom_sf(data = gg_df2, col = "black", pch = 21, cex = 0.8)  + 
  facet_grid(name~wsize) +
  theme_void() + 
  scale_fill_viridis_c(option = "turbo")
dev.off()

pdf(here(plotpath, "wingen_prelim.pdf"), width = 10, height = 3)
ggplot(gg_df, aes(x = neutral, y = value)) +
  geom_smooth(aes(lty = name), method = "lm", se = FALSE, lwd = 0.8, col = "black") +
  geom_point(aes(col = cluster, pch = name), alpha = 0.5, cex = 1) +
  scale_linetype_manual(values = c("dotted", "solid", "dashed")) +
  theme_classic() +
  facet_wrap(~wsize, nrow = 1) +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(color = "gray")
  )

ggplot(gg_df, aes(x = neutral, y = value, col = socal, pch = name, lty = name)) +
  geom_point(alpha = 0.3, cex = 1) +
  geom_smooth(method = "lm", se = FALSE, lwd = 0.8) +
  theme_classic() +
  scale_shape_manual(values = c(16, 1, 3)) +
  scale_linetype_manual(values = c("dotted", "solid", "dashed")) +
  xlab("Neutral diversity") +
  ylab("Adaptive diversity") +
  facet_wrap(~wsize, nrow = 1) +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(color = "gray")
  )
dev.off()
```
f
```{r}
gg_df <- 
  wingen_df %>% 
  drop_na(nonsyn, syn, neutral, csi_past, tmean_dif) %>%
  mutate(resid_tmean_dif_y = residuals(lm(nonsyn ~ neutral + csi_past + bio1, data = .))) %>%
  mutate(resid_tmean_dif_x = residuals(lm(tmean_dif ~ neutral + csi_past + bio1, data = .))) %>%
  mutate(resid_csi_past_x = residuals(lm(csi_past ~ neutral + tmean_dif + bio1, data = .))) %>%
  mutate(resid_csi_past_y = residuals(lm(nonsyn ~ neutral + tmean_dif + bio1, data = .))) %>%
  mutate(resid_neutral_x = residuals(lm(neutral ~ csi_past + tmean_dif + bio1, data = .))) %>%
  mutate(resid_neutral_y = residuals(lm(nonsyn ~ csi_past + tmean_dif + bio1, data = .))) %>%
  mutate(resid_bio1_x = residuals(lm(bio1 ~ neutral + csi_past + tmean_dif, data = .))) %>%
  mutate(resid_bio1_y = residuals(lm(nonsyn ~ neutral + csi_past + tmean_dif, data = .))) %>%
  pivot_longer(c("syn", "nonsyn")) %>% 
  filter(wdim == "wdim7") %>%
  mutate(name = case_when(
    name == "nonsyn" ~ "GEA non-synonymous",
    name == "syn" ~ "GEA synonymous"
  )) %>%
  filter(!grepl("CHI138_DAW5-46-21", SampleID), !grepl("CCGPMC_MW01-3-14", SampleID)) 

cs1 <- viridis::mako(4, begin = 0.3, end = 0.8)
names(cs1) <- c("7", "5", "4", "1")
cs2 <- viridis::rocket(9-4, begin = 0.3, end = 0.9)
names(cs2) <- c("9", "8", "6", "2", "3")
cs <- c(cs1, cs2)

plt1 <-
  ggplot(gg_df, aes(x = neutral)) +
  geom_point(aes(y = value, col = cluster, pch = name), alpha = 0.8, cex = 3) +
  geom_smooth(aes(y = value, lty = name), method = "lm", se = TRUE, col = "black", lwd = 1) +
  scale_shape_manual(values = c(16, 3)) +
  scale_linetype_manual(values = c("solid", "dotted")) +
  scale_color_manual(values = cs) +
  theme_classic() +
  xlab("Neutral diversity") + 
  ylab("Adaptive diversity") +
  labs(col = "Population", pch = "Mutation type", lty = "Mutation type") +
  theme(axis.title = element_text(size = 14))

plt2 <- 
  ggplot(gg_df, aes(x = resid_tmean_dif_x, y = resid_tmean_dif_y)) +
  geom_point(aes(col = cluster), alpha = 0.6, cex = 2) +
  geom_smooth(method = "lm", se = TRUE, lwd = 0.8, col = "black") +
  scale_color_manual(values = cs) +
  theme_classic() +
  xlab("Partial climate change") +
  ylab("Partial adaptive diversity") +
  ggpubr::stat_cor() +
  labs(col = "Population") +
  theme(legend.position = "none")

plt3 <-
  ggplot(gg_df, aes(x = resid_csi_past_x, y = resid_csi_past_y)) +
  geom_point(aes(col = cluster), alpha = 0.6, cex = 2) +
  geom_smooth(method = "lm", se = TRUE, lwd = 0.8, col = "black") +
  scale_color_manual(values = cs) +
  theme_classic() +
  xlab("Partial climate stability") +
  ylab("Partial adaptive diversity") +
  ggpubr::stat_cor() + 
  labs(col = "Population") +
  theme(legend.position = "none")

plt4 <-
  ggplot(gg_df, aes(x = resid_neutral_x, y = resid_neutral_y)) +
  geom_point(aes(col = cluster), alpha = 0.6, cex = 2) +
  geom_smooth(method = "lm", se = TRUE, lwd = 0.8, col = "black") +
  scale_color_manual(values = cs) +
  theme_classic() +
  xlab("Partial neutral diversity") +
  ylab("Partial adaptive diversity") +
  ggpubr::stat_cor() + 
  labs(col = "Population") +
  theme(legend.position = "none")

plt5 <-
  ggplot(gg_df, aes(x = resid_bio1_x, y = resid_bio1_y)) +
  geom_point(aes(col = cluster), alpha = 0.6, cex = 2) +
  geom_smooth(method = "lm", se = TRUE, lwd = 0.8, col = "black") +
  scale_color_manual(values = cs) +
  theme_classic() +
  xlab("Partial contemporary temperature") +
  ylab("Partial adaptive diversity") +
  ggpubr::stat_cor() + 
  labs(col = "Population") +
  theme(legend.position = "none")

pdf(here(plotpath, "committee_meeting.pdf"), width = 14, height = 6)
pltgrp1 <- cowplot::plot_grid(plt4, plt3, plt2, plt5, ncol = 2, labels = c("A", "B", "C", "D"), align = "hv")
pltgrp2 <- cowplot::plot_grid(plt1, nrow = 1, labels = c("D"))

cowplot::plot_grid(pltgrp2, pltgrp1, nrow = 1, rel_widths = c(1, 0.8))
dev.off()

```

```{r}
gg_df <- 
  wingen_df %>% 
  pivot_longer(c("syn", "nonsyn", "allnonsyn")) %>% 
  filter(wdim == "wdim7") %>%
  mutate(name = case_when(
    name == "nonsyn" ~ "GEA non-synonymous",
    name == "syn" ~ "GEA synonymous"
    name == "allnonsyn" ~ "All non-synonymous",
  ))

gg_df2 <- 
  wingen_df %>% 
  pivot_longer(c("syn", "nonsyn", "allnonsyn", "neutral")) %>%
  mutate(name = case_when(
    name == "nonsyn" ~ "GEA non-synonymous",
    name == "syn" ~ "GEA synonymous",
    name == "allnonsyn" ~ "All non-synonymous",
    name == "neutral" ~ "Neutral"
  )) %>%
  mutate(name = factor(name, levels = c("Neutral", "GEA synonymous", "GEA non-synonymous", "All non-synonymous"))) %>%
  st_as_sf() 

gg_stack_df <- 
  wingen_stack_df %>% 
  pivot_longer(c("syn", "nonsyn", "neutral", "allnonsyn")) %>% 
  filter(wdim == "wdim7") %>%
  mutate(name = case_when(
    name == "nonsyn" ~ "GEA non-synonymous",
    name == "syn" ~ "GEA synonymous",
    name == "allnonsyn" ~ "All non-synonymous",
    name == "neutral" ~ "Neutral"
  )) %>%
  mutate(name = factor(name, levels = c("Neutral", "GEA synonymous", "GEA non-synonymous", "All non-synonymous"))) 

plt1 <-
  ggplot(gg_stack_df) +
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = value)) +
  geom_sf(data = gg_df2, pch = 21, cex = 1, aes(col = socal, fill = value))  + 
  facet_grid(~name) +
  theme_void() + 
  scale_linetype_manual(values = c("dotted", "solid", "dashed")) +
  scale_color_manual(values = c("black", "red")) +
  scale_fill_viridis_c(option = "turbo") +
  labs(fill = "Ho", col = "Population")

plt2 <- ggplot(gg_df, aes(x = neutral, y = value, col = socal, pch = name, lty = name)) +
  geom_point(alpha = 0.3, cex = 1) +
  geom_smooth(method = "lm", se = FALSE, lwd = 0.8) +
  theme_classic() +
  scale_shape_manual(values = c(16, 1, 3)) +
  scale_linetype_manual(values = c("dotted", "solid", "dashed")) +
  scale_color_manual(values = c("black", "red")) +
  xlab("Neutral diversity") +
  ylab("Adaptive diversity") +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(color = "gray")
  ) + 
  labs(fill = "Ho", col = "Population", pch = "Mutation type", lty = "Mutation type")

plt2 <- ggplot(gg_df, aes(x = neutral, y = value, col = socal, pch = name, lty = name)) +
  geom_point(alpha = 0.3, cex = 2) +
  geom_smooth(method = "lm", se = FALSE, lwd = 0.8) +
  theme_classic() +
  scale_shape_manual(values = c(16, 1, 3)) +
  scale_color_manual(values = c("black", "red")) +
  scale_linetype_manual(values = c("dotted", "solid", "dashed")) +
  xlab("Neutral diversity") +
  ylab("Adaptive diversity") +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(color = "gray")
  ) + 
  labs(fill = "Ho", col = "Population", pch = "Type", lty = "Type")


pdf(here(plotpath, "wingen_wdim7_map.pdf"), width = 16, height = 4)
cowplot::plot_grid(plt1, plt2, nrow = 1, rel_widths = c(2, 1))
dev.off()

pdf(here(plotpath, "wingen_prelim.pdf"), width = 5, height = 4)
ggplot(gg_df, aes(x = neutral, y = value)) +
  geom_smooth(aes(lty = name), method = "lm", se = FALSE, lwd = 0.8, col = "black") +
  geom_point(aes(col = cluster, pch = name), alpha = 0.5, cex = 1) +
  theme_classic() +
  facet_wrap(~wsize, nrow = 1) +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(color = "gray")
  )

ggplot(gg_df, aes(x = neutral, y = value, col = socal, pch = name, lty = name)) +
  geom_point(alpha = 0.3, cex = 1) +
  geom_smooth(method = "lm", se = FALSE, lwd = 0.8) +
  theme_classic() +
  scale_shape_manual(values = c(16, 1, 3)) +
  xlab("Neutral diversity") +
  ylab("Adaptive diversity") +
  facet_wrap(~wsize, nrow = 1) +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(color = "gray")
  )
dev.off()
```

```{r}
df <- as.data.frame(stack[[3]])
cor_matrix <- cor(df, use = "pairwise.complete.obs")
high_cor_pairs <- which(abs(cor_matrix) > 0.6 & abs(cor_matrix) < 1, arr.ind = TRUE)
high_cor_pairs <- high_cor_pairs[high_cor_pairs[, 1] < high_cor_pairs[, 2], ]
high_cor_pairs <- data.frame(
  var1 = rownames(cor_matrix)[high_cor_pairs[, 1]],
  var2 = colnames(cor_matrix)[high_cor_pairs[, 2]],
  cor = cor_matrix[high_cor_pairs]
)
high_cor_pairs
```

# Models

```{r}
run_models <- function(stack, wdim){
  # Model variables
  # Note: Correlated variables were removed based on correlation matrix from previous step
  mod_vars <- c("NDVI", "gHM", "bio1", "csi_past", "tmean_dif")

  # Create dataframe from stack
  df <- as.data.frame(stack, xy = TRUE) %>% drop_na(nonsyn, syn, neutral, all_of(mod_vars))
  scale_df <- df %>% mutate_all(scale)
    
  # Convert to sf and sp objects (sp needed for semivariograms)
  df_sf <- st_as_sf(df, coords = c("x", "y"), crs = 3310)
  sf_data_sp <- as(df_sf, "Spatial")

  # Compute the semivariogram for heterozygosity
  variogram_model <- gstat::variogram(neutral ~ 1, sf_data_sp)
  vgm_model <- gstat::fit.variogram(variogram_model, model = gstat::vgm("Exp"))

  # Get the range value and use as the radius (the distance at which the semivariogram reaches its sill)
  radius <- vgm_model$range[2]

  # Estimate neighborhood radius based on window size
  #radius <- wdim * res(stack)[1] * sqrt(2)
  message("Radius: ", radius)

  # Create weights list based on neighborhood radius and coordinates
  wcoords <- st_as_sf(scale_df, coords = c("x", "y"), crs = st_crs(3310))
  nb <- dnearneigh(wcoords, d1 = 0, d2 = radius)
  listw <- nb2listw(nb, style = "W", zero.policy = TRUE)

  # Non-synonymous diversity model
  f_nonsyn <- paste("nonsyn ~", paste(mod_vars, collapse = " + "))
  sem_nonsyn <- errorsarlm(f_nonsyn, data = scale_df, listw = listw, na.action = "na.omit", zero.policy = TRUE)

  # Adaptive diversity model
  f_syn <- paste("syn ~", paste(mod_vars, collapse = " + "))
  sem_syn <- errorsarlm(f_syn, data = scale_df, listw = listw, na.action = "na.omit", zero.policy = TRUE)

  # Adaptive diversity ~ neutral diversity model
  sem_gendiv <- errorsarlm("nonsyn ~ neutral", data = scale_df, listw = listw, na.action = "na.omit", zero.policy = TRUE)

  # Adaptive diversity ~ neutral diversity model + climate
  sem_gendiv2 <- errorsarlm("nonsyn ~ neutral + NDVI + gHM + bio1 + csi_past + tmean_dif", data = scale_df, listw = listw, na.action = "na.omit", zero.policy = TRUE)

  # Get adaptive residuals and run residual model
  df$resids <- residuals(sem_gendiv)
  scale_df$resids <- df$resids
  resid_f <- "resids ~ NDVI + gHM + bio1 + csi_past + tmean_dif"
  sem_resid <- errorsarlm(resid_f, data = scale_df, listw = listw, na.action = "na.omit", zero.policy = TRUE)

  # Plots
  create_plots(df, wdim)

  # Combine and return models
  models <- list(
    sem_nonsyn = sem_nonsyn,
    sem_syn = sem_syn,
    sem_gendiv = sem_gendiv,
    sem_resid = sem_resid
  )

  # Results
  results <- list(model = models, df = df, stack = stack, wdim = wdim, radius = radius)

  return(results)
}


run_models_adaptive <- function(x, wdim, coords){
  # Model variables
  # Note: Correlated variables were removed based on correlation matrix from previous step
  mod_vars <- c("NDVI", "gHM", "bio1", "csi_past", "tmean_dif", "neutral")

  # Create dataframe from stack
  df <- 
    x %>%
    filter(wdim == paste0("wdim", !!wdim))
  scale_df <- 
    df %>% 
    mutate(across(c(nonsyn, syn, neutral, all_of(mod_vars)), scale)) %>% 
    left_join(coords, by = "SampleID")
    
  # Convert to sf and sp objects (sp needed for semivariograms)
  df_sf <- st_as_sf(scale_df, crs = 3310)
  sf_data_sp <- as(df_sf, "Spatial")

  # Compute the semivariogram for heterozygosity
  variogram_model <- gstat::variogram(nonsyn ~ 1, sf_data_sp)
  vgm_model <- gstat::fit.variogram(variogram_model, model = gstat::vgm("Exp"))

  # Get the range value and use as the radius (the distance at which the semivariogram reaches its sill)
  radius <- vgm_model$range[2]

  # Estimate neighborhood radius based on window size
  #radius <- wdim * res(stack)[1] * sqrt(2)
  message("Radius: ", radius)

  # Create weights list based on neighborhood radius and coordinates
  wcoords <- st_as_sf(scale_df, crs = st_crs(3310))
  nb <- dnearneigh(wcoords, d1 = 0, d2 = radius)
  listw <- nb2listw(nb, style = "W", zero.policy = TRUE)

  # Non-synonymous diversity model
  f_nonsyn <- paste("nonsyn ~", paste(mod_vars, collapse = " + "))
  sem_nonsyn <- errorsarlm(f_nonsyn, data = scale_df, listw = listw, na.action = "na.omit", zero.policy = TRUE)
  
  # Results
  results <- list(model = sem_nonsyn, df = df, stack = x, wdim = wdim, radius = radius)

  return(results)
}

create_plots <- function(df, wdim){
  
  plts1a <- do.call(plot_grid, c(map(mod_vars, ~ gglm(.x, "neutral", drop_na(df))), nrow = 1))
  plts1b <- do.call(plot_grid, c(map(mod_vars, ~ ggpartial(.x, "neutral", mod_vars, drop_na(df))), nrow = 1))
  plts2a <- do.call(plot_grid, c(map(mod_vars, ~ gglm(.x, "nonsyn", drop_na(df))), nrow = 1))
  plts2b <- do.call(plot_grid, c(map(mod_vars, ~ ggpartial(.x, "nonsyn", mod_vars, drop_na(df))), nrow = 1))
  plts3a <- do.call(plot_grid, c(map(mod_vars, ~ gglm(.x, "resids", drop_na(df))), nrow = 1))
  plts3b <- do.call(plot_grid, c(map(mod_vars, ~ ggpartial(.x, "resids", mod_vars, drop_na(df))), nrow = 1))

  plotpath <- here("analysis", "gea", "plots")
  plotname <- paste0("all_model_results_wdim", wdim, ".pdf")
  pdf(here(plotpath, plotname), width = 21, height = 7)
  print(plot_grid(plts1a, plts1b, nrow = 2))
  print(plot_grid(plts2a, plts2b, nrow = 2))
  print(plot_grid(plts3a, plts3b, nrow = 2))
  dev.off()
}

create_plots_adaptive <- function(df, wdim, mod_vars = c("NDVI", "gHM", "bio1", "csi_past", "tmean_dif", "neutral"), partial_only = FALSE){
  plts2a <- do.call(plot_grid, c(map(mod_vars, ~ gglm(.x, "nonsyn", drop_na(df))), nrow = 1, align = "hv"))
  plts2b <- do.call(plot_grid, c(map(mod_vars, ~ ggpartial(.x, "nonsyn", mod_vars, drop_na(df))), nrow = 1, align = "hv"))

  if (partial_only) return(plts2b)

  combined_plot <- plot_grid(plts2a, plts2b, nrow = 2)
  
  title <- 
    ggdraw() +
    draw_label(paste0("wdim: ", wdim),
               fontface = "bold",
               x = 0.5,
               hjust = 0.5)
  
  final_plot <- plot_grid(title, combined_plot, ncol = 1, rel_heights = c(0.15, 1))
  final_plot
}
```


```{r}
# Run models
wdim <- c(3, 5, 7, 9)
names(wdim) <- paste0("wdim", wdim)

# Note: can't use parallel processing here because of the terra rast objects
results <- map(wdim, ~run_models_adaptive(x = wingen_df, wdim = .x, coords = coords), .progress = TRUE)

results_df <-
  map(results, "model") %>%
  map(broom::tidy) %>%
  bind_rows(.id = "wdim")

results_df %>% filter(p.value < 0.05)

results_df %>% filter(p.value > 0.05) %>% filter(term == "tmean_dif")

sig <- 
  results_df %>% 
  group_by(term) %>% 
  filter(term != "(Intercept)", term != "lambda") %>%
  summarize(
    mean = mean(estimate), 
    min = min(estimate), 
    max = max(estimate), 
    sd = var(estimate),
    sig = mean(p.value < 0.05)
  ) %>%
  filter(sig > 0) %>%
  arrange(desc(abs(mean)))
sig

mod_vars <- c("NDVI", "gHM", "bio1", "csi_past", "tmean_dif", "neutral")
model_dfs <- map(results, "df") 
pdf(here(plotpath, "adaptive_model_results.pdf"), width = 18, height = 7)
walk2(model_dfs, wdim, ~create_plots_adaptive(.x, .y, mod_vars = mod_vars), .progress = TRUE)
dev.off()

pdf(here(plotpath, "adaptive_model_results_sig.pdf"), width = 13, height = 7)
walk2(model_dfs, wdim, ~create_plots_adaptive(.x, .y, mod_vars = sig$term), .progress = TRUE)
dev.off()

plt4 <- cowplot::plot_grid(plt1, plt2, nrow = 1, rel_widths = c(1.6, 1), labels = c("A", "B"))
plt3 <- create_plots_adaptive(model_dfs[[3]], wdim = 7, mod_vars = sig$term, partial_only = TRUE)


pdf(here(plotpath, "adaptive_model_results_sig_wdim7.pdf"), width = 14, height = 7)
plot_grid(plt4, plt3, nrow = 2, rel_heights = c(1, 0.9), labels = c("", "C"))
dev.off()

```

```{r}
final_df <- model_dfs[[3]] %>% left_join()
plt4 <- cowplot::plot_grid(plt1, plt2, nrow = 1, rel_widths = c(1.6, 1), labels = c("A", "B"))
mod_vars = c("NDVI", "gHM", "bio1", "csi_past", "tmean_dif", "neutral")
plts2b <- do.call(plot_grid, c(map(mod_vars, ~ ggpartial(.x, "nonsyn", mod_vars, drop_na(model_dfs[[3]]), col = )), nrow = 1, align = "hv"))

pdf(here(plotpath, "adaptive_model_results_sig_wdim7.pdf"), width = 14, height = 7)
plot_grid(plt4, plt3, nrow = 2, rel_heights = c(1, 0.9), labels = c("", "C"))
dev.off()
```

# OLD:
```{r}
library(MuMIn)
df <- as.data.frame(stack, xy = TRUE)
scale_df <- df %>% mutate_all(scale)
f_Ho <- paste("Ho ~", paste(mod_vars, collapse = " + "))
dredge <- dredge(lm(f_Ho, data = scale_df, na.action = na.fail))
best_model_f <- MuMIn::get.models(dredge, subset = 1)[[1]]$call
mod_Ho <- lm(best_model_f, data = scale_df)
vars_Ho <- broom::tidy(mod_Ho)$term[-1]

f_Ho_gea <- paste("Ho_gea ~", paste(mod_vars, collapse = " + "))
dredge <- dredge(lm(f_Ho_gea, data = scale_df, na.action = na.fail))
best_model_f <- MuMIn::get.models(dredge, subset = 1)[[1]]$call
mod_Ho_gea <- lm(best_model_f, data = scale_df)
vars_Ho_gea <- broom::tidy(mod_Ho_gea)$term[-1]

df$resids <- residuals(lm(Ho_gea ~ Ho, data = df))

coords_df <- 
  extract(stack, st_as_sf(test_df), ID = FALSE) %>%
  mutate(across(all_of(mod_vars), scale))

lm(f_Ho, data = coords_df) %>% broom::tidy()
lm(f_Ho_gea, data = coords_df) %>% broom::tidy()

pdf(here(plotpath, "wingen_lm_wdim11.pdf"), width = 24, height = 12)
plot_list1 <- purrr::map(vars_Ho, ~ gglm(.x, "Ho", scale_df))
partial_plot_list1 <- purrr::map(vars_Ho, ~ ggpartial(.x, "Ho", mod_vars, drop_na(scale_df)))
plot_list2 <- purrr::map(vars_Ho_gea, ~ gglm(.x, "Ho_gea", scale_df))
partial_plot_list2 <- purrr::map(vars_Ho_gea, ~ ggpartial(.x, "Ho_gea", mod_vars, drop_na(scale_df)))
do.call(plot_grid, c(plot_list1, partial_plot_list1, plot_list2, partial_plot_list2, nrow = 4))
dev.off()

ca <- get_ca() %>% st_transform(st_crs(stack))
plt1 <-
  ggplot(scale_df) + 
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = Ho)) +
  scale_fill_viridis_c(option = "mako") +
  labs(fill = "Genome-wide\nheterozygosity") +
  theme_void() 

plt2 <- 
  ggplot(df) + 
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = Ho_gea)) +
  scale_fill_viridis_c(option = "mako") +
  labs(fill = "Adaptive\nheterozygosity") +
  theme_void()

plt3 <- 
  ggplot(df) + 
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = resids)) +
  scale_fill_viridis_c(option = "mako") +
  labs(fill = "Residuals") +
  theme_void()

plt4 <- 
  ggplot(df) + 
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = tmean_dif)) +
  scale_fill_viridis_c(option = "mako") +
  labs(fill = "Contemporary\ntemperature\nchange") +
  theme_void()

pltA <- 
  ggplot(df, aes(x = Ho, y = Ho_gea)) +
  geom_point(aes(col = tmean_dif), alpha = 0.1) +
  geom_smooth(method = "lm", se = TRUE, col = "black") +
  scale_color_viridis_c(option = "mako") +
  theme_classic() +
  stat_cor() +
  labs(x = "Genome-wide heterozygosity", y = "Adaptive heterozygosity", col = "Contemporary\ntemperature\nchange") 

pltB <- ggpartial("tmean_dif", "resids", c("tmean_dif", "csi_past"), df, col = FALSE)

pdf(here("analysis", "gea", "plots", "wingen.pdf"), width = 15, height = 3)
cowplot::plot_grid(plt1, plt2, plt3, plt4, nrow = 1)
dev.off()

pdf(here("analysis", "gea", "plots", "wingen_model.pdf"), width = 9.5, height = 4)
cowplot::plot_grid(pltA, pltB, nrow = 1, rel_widths = c(1, 0.8))
dev.off()
```

```{r}
mod_sf <-
  extract(stack, coords, ID = FALSE, xy = TRUE) %>%
  st_as_sf(coords = c("x", "y"), crs = 3310)

library(spdep)
library("spatialreg")

dim = 11 * res(stack)[1]
diag = sqrt(2) * dim
radius = diag / 2

nb <- dnearneigh(mod_sf, d1 = 0, d2 = radius)
listw <- nb2listw(nb, style = "W", zero.policy = TRUE)
f <- formula("Ho ~ NDVI + gHM + bio1 + lgm_lig + csi_past + glacier + tmean_dif + Q")
slm_model <- lagsarlm(f , data = mod_sf, listw = listw, na.action = "na.omit", zero.policy = TRUE)
sem_model <- errorsarlm(f, data = mod_sf, listw = listw, na.action = "na.omit", zero.policy = TRUE)

nb <- dnearneigh(mod_sf, d1 = 0, d2 = radius)
listw <- nb2listw(nb, style = "W", zero.policy = TRUE)
f <- formula("Ho ~ NDVI + gHM + bio1 + lgm_lig + csi_past + glacier + tmean_dif + Q")
slm_model <- lagsarlm(f , data = mod_sf, listw = listw, na.action = "na.omit", zero.policy = TRUE)
sem_model <- errorsarlm(f, data = mod_sf, listw = listw, na.action = "na.omit", zero.policy = TRUE)

data.frame(slm = AIC(slm_model), sem = AIC(sem_model), radius = radius)

library(furrr)
plan(multisession, workers = 10)
dredge_result <- sem_dredge(f, data = mod_sf, listw = listw)

stack_df <- as.data.frame(stack, xy = TRUE) %>% st_as_sf(coords = c("x", "y"), crs = 3310)
sub <- stack_df[sample(nrow(stack_df), 1000),]
nb <- dnearneigh(sub, d1 = 0, d2 = radius)
listw <- nb2listw(nb, style = "W", zero.policy = TRUE)
dredge_result2 <- sem_dredge(f, data = sub, listw = listw)
plan(sequential)

dredge_result %>% arrange(AIC) %>% head(3)
best_model_formula <- dredge_result %>% arrange(AIC) %>% head(1) %>% pull(model_formula)
best_model_vars <- all.vars(formula(best_model_formula))[-1]
best_model <- errorsarlm(best_model_formula, data = mod_sf, listw = listw, na.action = "na.omit", zero.policy = TRUE)
summary(best_model)

pdf(here("analysis", "gea", "plots", "wingen_spmod.pdf"), width = 12, height = 4)
do.call(plot_grid, c(map(best_model_vars, ~ gglm(.x, "Ho", drop_na(mod_sf))), nrow = 1))
do.call(plot_grid, c(map(best_model_vars, ~ ggpartial(.x, "Ho", best_model_vars, drop_na(mod_sf))), nrow = 1))
do.call(plot_grid, c(map(best_model_vars, ~ gglm(.x, "Ho", drop_na(df))), nrow = 1))
do.call(plot_grid, c(map(best_model_vars, ~ ggpartial(.x, "Ho", best_model_vars, drop_na(df))), nrow = 1))
dev.off()

```


## wdim = 15
```{r}
library(MuMIn)
df <- as.data.frame(stack2, xy = TRUE)
scale_df <- df %>% mutate_all(scale)
mod_vars <- c("NDVI", "gHM", "bio1", "csi_past", "lgm_lig", "csi_past", "glacier", "tmean_dif", "Q")
f_Ho <- paste("Ho ~", paste(mod_vars, collapse = " + "))
dredge <- dredge(lm(f_Ho, data = scale_df, na.action = na.fail))
best_model_f <- MuMIn::get.models(dredge, subset = 1)[[1]]$call
mod_Ho <- lm(best_model_f, data = scale_df)
vars_Ho <- broom::tidy(mod_Ho)$term[-1]

f_Ho_gea <- paste("Ho_gea ~", paste(mod_vars, collapse = " + "))
dredge <- dredge(lm(f_Ho_gea, data = scale_df, na.action = na.fail))
best_model_f <- MuMIn::get.models(dredge, subset = 1)[[1]]$call
mod_Ho_gea <- lm(best_model_f, data = scale_df)
vars_Ho_gea <- broom::tidy(mod_Ho_gea)$term[-1]

df$resids <- residuals(lm(Ho_gea ~ Ho, data = df))

coords_df <- 
  extract(stack, st_as_sf(test_df), ID = FALSE) %>%
  mutate(across(all_of(mod_vars), scale))

lm(f_Ho, data = coords_df) %>% broom::tidy()
lm(f_Ho_gea, data = coords_df) %>% broom::tidy()

pdf(here(plotpath, "wingen_lm_wdim15.pdf"), width = 24, height = 12)
plot_list1 <- purrr::map(vars_Ho, ~ gglm(.x, "Ho", scale_df))
partial_plot_list1 <- purrr::map(vars_Ho, ~ ggpartial(.x, "Ho", mod_vars, drop_na(scale_df)))
plot_list2 <- purrr::map(vars_Ho_gea, ~ gglm(.x, "Ho_gea", scale_df))
partial_plot_list2 <- purrr::map(vars_Ho_gea, ~ ggpartial(.x, "Ho_gea", mod_vars, drop_na(scale_df)))
do.call(plot_grid, c(plot_list1, partial_plot_list1, plot_list2, partial_plot_list2, nrow = 4))
dev.off()

ca <- get_ca() %>% st_transform(st_crs(stack))
plt1 <-
  ggplot(scale_df) + 
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = Ho)) +
  scale_fill_viridis_c(option = "mako") +
  labs(fill = "Genome-wide\nheterozygosity") +
  theme_void() 

plt2 <- 
  ggplot(df) + 
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = Ho_gea)) +
  scale_fill_viridis_c(option = "mako") +
  labs(fill = "Adaptive\nheterozygosity") +
  theme_void()

plt3 <- 
  ggplot(df) + 
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = resids)) +
  scale_fill_viridis_c(option = "mako") +
  labs(fill = "Residuals") +
  theme_void()

plt4 <- 
  ggplot(df) + 
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = tmean_dif)) +
  scale_fill_viridis_c(option = "mako") +
  labs(fill = "Contemporary\ntemperature\nchange") +
  theme_void()

pltA <- 
  ggplot(df, aes(x = Ho, y = Ho_gea)) +
  geom_point(aes(col = tmean_dif), alpha = 0.1) +
  geom_smooth(method = "lm", se = TRUE, col = "black") +
  scale_color_viridis_c(option = "mako") +
  theme_classic() +
  stat_cor() +
  labs(x = "Genome-wide heterozygosity", y = "Adaptive heterozygosity", col = "Contemporary\ntemperature\nchange") 

pltB <- ggpartial("tmean_dif", "resids", c("tmean_dif", "csi_past"), df, col = FALSE)

pdf(here("analysis", "gea", "plots", "wingen.pdf"), width = 15, height = 3)
cowplot::plot_grid(plt1, plt2, plt3, plt4, nrow = 1)
dev.off()

pdf(here("analysis", "gea", "plots", "wingen_model.pdf"), width = 9.5, height = 4)
cowplot::plot_grid(pltA, pltB, nrow = 1, rel_widths = c(1, 0.8))
dev.off()
```

```{r}
mod_sf <-
  extract(stack, coords, ID = FALSE, xy = TRUE) %>%
  st_as_sf(coords = c("x", "y"), crs = 3310)

library(spdep)
library("spatialreg")

dim = 11 * res(stack)[1]
diag = sqrt(2) * dim
radius = diag / 2

nb <- dnearneigh(mod_sf, d1 = 0, d2 = radius)
listw <- nb2listw(nb, style = "W", zero.policy = TRUE)
f <- formula("Ho ~ NDVI + gHM + bio1 + lgm_lig + csi_past + glacier + tmean_dif + Q")
slm_model <- lagsarlm(f , data = mod_sf, listw = listw, na.action = "na.omit", zero.policy = TRUE)
sem_model <- errorsarlm(f, data = mod_sf, listw = listw, na.action = "na.omit", zero.policy = TRUE)

data.frame(slm = AIC(slm_model), sem = AIC(sem_model), radius = radius)

library(furrr)
plan(multisession, workers = 10)
f <- formula("Ho ~ NDVI + gHM + bio1 + csi_past + lgm_lig + csi_past + glacier + tmean_dif + Q")
dredge_result <- sem_dredge(f, data = mod_sf, listw = listw)
plan(sequential)

dredge_result %>% arrange(AIC) %>% head(3)
best_model_formula <- dredge_result %>% arrange(AIC) %>% head(1) %>% pull(model_formula)
best_model_vars <- all.vars(formula(best_model_formula))[-1]
best_model <- errorsarlm(best_model_formula, data = mod_sf, listw = listw, na.action = "na.omit", zero.policy = TRUE)
summary(best_model)

pdf(here("analysis", "gea", "plots", "wingen_spmod_wdim15.pdf"), width = 20, height = 4)
do.call(plot_grid, c(map(best_model_vars, ~ gglm(.x, "Ho", drop_na(mod_sf))), nrow = 1))
do.call(plot_grid, c(map(best_model_vars, ~ ggpartial(.x, "Ho", best_model_vars, drop_na(mod_sf))), nrow = 1))
do.call(plot_grid, c(map(best_model_vars, ~ gglm(.x, "Ho", drop_na(df))), nrow = 1))
do.call(plot_grid, c(map(best_model_vars, ~ ggpartial(.x, "Ho", best_model_vars, drop_na(df))), nrow = 1))
dev.off()

```