```{r}
library(tidyverse)
library(here)
source(here("analysis", "gea", "functions_go.R"))
source(here("analysis", "gea", "functions_selection_stats.R"))
outpath <- here("analysis", "gea", "outputs")
plotpath <- here("analysis", "gea", "plots")
```

# Check for genes of interest
# Proteins of interest
```{r}
genes_nonsyn <- get_gea_genes(nonsyn = TRUE)

genes_nonsyn %>% distinct(gene_name) %>% filter(!grepl("egapxtmp", gene_name)) %>% write_tsv(here("ALL_GENES.tsv"))

search <- function(x, y = NULL, strict = FALSE) {
  if (is.null(y)) y <- genes_nonsyn
  # Create different case versions of x
  x_variants <- unique(c(
    x,
    tolower(x),
    toupper(x),
    str_to_title(x),
    str_to_sentence(x)
  ))

  if (strict) x_variants <- x

  gene_descrip <- 
    y %>%
    filter(reduce(x_variants, ~ .x | str_detect(full_name, .y), .init = FALSE)) %>%
    distinct(full_name) %>%
    pull(full_name) %>%
    str_extract("description=([^;]+)") %>%
    str_remove("^description=")

  gene_id <-
    y %>%
    filter(reduce(x_variants, ~ .x | str_detect(full_name, .y), .init = FALSE)) %>%
    distinct(full_name) %>%
    pull(full_name) %>%
    str_extract("Name=([^;]+)") %>%
    str_remove("^Name=") 

  writeLines(paste(gene_id, gene_descrip, sep = ": "))
}

#Humans
#HSP70 (Heat Shock Protein 70): This protein helps protect cells from stress-induced damage, including heat stress. It plays a crucial role in protein folding and repair.
search("HSP") # many of these! Heat shock 70 kDA is included in the list
search("heat shock")  # many of these! Heat shock 70 kDA is included in the list
search("Hsp70") 

#UCP1 (Uncoupling Protein 1): Found in brown adipose tissue, UCP1 is involved in thermogenesis, helping humans generate heat in cold environments.
search("UCP1")
search("UCP") # Uncoupling protein 2
search("Uncoupling")

#MC1R (Melanocortin 1 Receptor): This receptor is involved in pigmentation and can affect skin's response to UV radiation, which is a crucial adaptation in different climates.
search("MC1R") 
search("Melanocortin") # melanocortin 2 receptor 

#EPAS1 (Endothelial PAS Domain Protein 1): This gene, also known as HIF-2α, is involved in the response to hypoxia and is associated with high-altitude adaptation.
search("EPAS1") 
search("PAS", strict = TRUE)# "neuronal PAS domain protein 2"                 "neuronal PAS domain protein 4"  
search("Endothelial") 

#Mice
#FGF21 (Fibroblast Growth Factor 21): This protein helps regulate metabolism and energy expenditure, playing a role in cold adaptation by promoting brown fat activity.
search("FGF21")
search("Fibroblast growth factor 21")
search("Fibroblast growth factor") #several

#PRDM16 (PR Domain Containing 16): Important in the development of brown adipose tissue, which is crucial for thermoregulation in cold environments.
search("PRDM16")
search("PRDM", strict = TRUE)

#HIF1A (Hypoxia-Inducible Factor 1 Alpha): Similar to humans, this protein helps mice adapt to low oxygen levels by regulating genes involved in oxygen homeostasis.
search("HIF1A")
search("HIF")
search("Hypoxia") # [1] "egl-9 family hypoxia inducible factor 3"        [2] "hypoxia up-regulated protein 1-like" [3] "HIG1 hypoxia inducible domain family member 1A"

# ADRB3 (Beta-3 Adrenergic Receptor): This receptor is involved in the regulation of lipolysis and thermogenesis in brown fat, aiding in cold adaptation.
search("ADRB3") # Found! "adrenoceptor beta 3"

#Chickens
#UCP (Uncoupling Protein): Chickens also have uncoupling proteins that play a role in thermogenesis, helping them cope with temperature fluctuations.
search("UCP") # Uncoupling protein 2 found

#TRPV4 (Transient Receptor Potential Vanilloid 4): This protein is involved in temperature sensation and regulation.
#TRP in general is associated with thermosensation
# https://www.sciencedirect.com/science/article/abs/pii/S0959438815000306
search("TRPV4")
search("TRPV") #transient receptor potential cation channel subfamily V member 1
search("Transient receptor potential")
# transient receptor potential cation channel subfamily M member 5
# transient receptor potential cation channel subfamily M member 6
# polycystin 2 like 2%2C transient receptor potential cation channel
# transient receptor potential cation channel subfamily C member 4
# polycystin 2 like 1%2C transient receptor potential cation channel
# transient receptor potential cation channel subfamily C member 6
# short transient receptor potential channel 2-like
# transient receptor potential cation channel subfamily A member 1
# polycystin 2%2C transient receptor potential cation channel
# transient receptor potential cation channel subfamily M member 4
# transient receptor potential cation channel subfamily M member 7
# transient receptor potential cation channel subfamily M member 1
# polycystin 1%2C transient receptor potential channel interacting
# transient receptor potential cation channel subfamily V member 2-like
# transient receptor potential cation channel subfamily V member 1
# transient receptor potential cation channel subfamily C member 3
search("TRP", strict = TRUE)
# transient receptor potential cation channel subfamily M member 5
# transient receptor potential cation channel subfamily M member 6
# transient receptor potential cation channel subfamily C member 4
# transient receptor potential cation channel subfamily C member 6
# transient receptor potential cation channel subfamily A member 1
# TRPM8 channel associated factor 2
# TRPM8 channel-associated factor homolog
# transient receptor potential cation channel subfamily M member 4
# transient receptor potential cation channel subfamily M member 7
# transient receptor potential cation channel subfamily M member 1
# tRNA phosphotransferase 1
# transient receptor potential cation channel subfamily V member 1
# transient receptor potential cation channel subfamily C member 3

#ADRB2 (Beta-2 Adrenergic Receptor): This receptor plays a role in the regulation of metabolic processes and is involved in the adaptation to cold stress.
search("ADRB2")

#Additional 
#Aquaporins (AQPs): These proteins are involved in water transport across cell membranes and play a role in osmoregulation, which can be crucial in adapting to varying humidity levels.
search("Aquaporin")
# aquaporin 11
# aquaporin 4
# aquaporin 1 (Colton blood group)
# aquaporin 8
# aquaporin 10

#Leptin: This hormone, involved in regulating energy balance, can influence how organisms respond to different climatic conditions, especially in terms of energy storage and expenditure.
search("Leptin") # leptin receptor overlapping transcript
search("leptin")

# From this paper on mammals: https://www.nature.com/articles/s41598-021-95816-8
# specific candidate variants and genes are related to the neuronal system (ITPR1, ITPR2, and GRIA4) and neuroactive ligand–receptor interaction functions for heat tolerance (NPFFR2, CALCR, and GHR), providing a novel insight that can help to develop genetic and management approaches to combat heat stress.
search("Inositol 1,4,5-trisphosphate receptor type 1") 
search("Inositol 1,4,5-trisphosphate receptor type 2") 
search("ITPR2") # found!
search("ITPR1") 
search("Glutamate receptor ionotropic")
search("NPFFR2") # found!
search("Neuropeptide")
search("Calcitonin receptor") 
search("Growth hormone receptor") 
search("growth hormone") #growth hormone 1

# From this paper on sticklebacks: https://www.nature.com/articles/s41598-021-95816-8
# We determined maximum critical thermal limits (CTmax) and the associated gene expression responses in three heat shock (hsp60, hsp70, hsp90) and two key metabolic (idh2, fbp2) genes at ecologically relevant moderate heat stress (26 °C) as well as at the critical thermal limit (CTmax)
search("Heat shock 70") # found!
search("Hsp70") # found!
search("Heat shock 90")
search("Hsp90") # Found!
search("Heat shock 60")
search("Hsp60") # Found!
search("Isocitrate dehydrogenase") # Found IDH but not IDH2
search("bisphosphatase")

# # From this paper on bees/thermal stress/gene expression: 
# https://www.researchgate.net/figure/The-expression-levels-of-DnaJB6-DnaJshv-DnaJB13-and-DnaJB14-under-heat-stress-The_fig4_360260597
# https://www.frontiersin.org/journals/ecology-and-evolution/articles/10.3389/fevo.2022.873791/full
# CHatGPT summary: DNAJB6 is a molecular chaperone belonging to the Hsp40 family, known for assisting in protein folding and preventing aggregation, especially under stress conditions. In the eastern honeybee (Apis cerana cerana), studies have shown that DNAJB6 expression is upregulated in response to elevated temperatures. Specifically, when exposed to temperatures of 40°C, 43°C, and 46°C for durations up to 5 hours, there was a notable increase in DNAJB6 mRNA levels, indicating its role in the heat stress response
# DnaJ homolog subfamily B member 6 
search("DnaJ homolog subfamily B member 6") 
search("DnaJ")
search("DNAJB6") 
# From this paper on reptiles/thermosensation: https://www.sciencedirect.com/science/article/pii/S1744117X25000061 
#TRPP1L2, TRPP1L3, and TRPV1 were involved in heat-sensitive responses (> 36°C).
search("TRPP1L2")
search("TRPP1L3")
search("TRPV1") # Found!

#TRPV3, TRPA1, and TRPM8 were involved in cold-sensitive responses (< 20°C).
search("TRPV3")
search("Transient receptor potential cation channel subfamily V member 3") 
search("TRPA1") # transient receptor potential cation channel subfamily A member 1
search("Transient receptor potential cation channel subfamily A member 1") 
search("TRPM8") 
```

# Genes from literature
```{r}
# Genes to look for from literature
lit_genes <- read_tsv(here("analysis", "gea", "genes_from_literature.txt"))

# Create df
goi_df <- 
  genes_nonsyn %>% 
  filter(gene_name %in% lit_genes$gene) %>%
  # Move gene_name to first column
  select(gene_name, everything()) %>%
  # Remove egapxtmp genes
  filter(!grepl("egapxtmp", gene_name))

# Confirm that all genes in discussion section are in the goi list
discussed_genes <- c(
  "ITPR2",
  "NPFFR2",
  "TRPV1",
  "TRPA1",
  "HSPA2", # Hsp70
  "HSPA12B" # Hsp70
)

all(discussed_genes %in% goi_df$gene_name) # TRUE

write_csv(goi_df, here(outpath, "genes_of_interest.csv"))
```

```{r}
trpm4 <- 
  goi_df %>% 
  filter(gene_name == "TRPM4")

png(here(plotpath, "TRPM4.png"), width = 6, height = 4, units = "in", res = 300)
ggplot(trpm4) +
  # Plot bar that is gene with gene_start and gene_end
  geom_segment(aes(x = gene_start, xend = gene_end, y = 0, yend = 0), size = 5, color = "steelblue") +
  # Plot mutations as vertical lines
  geom_segment(aes(x = position, xend = position, y = -0.5, yend = 0.5), color = "darkred") +
  labs(title = "TRPM4 Gene with Nonsynonymous Mutations",
       x = "Genomic Position",
       y = "") +
  theme_minimal() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
dev.off()

```


```{r}
# Write out Table S7 
# With gene, function, citations, position
goi_table <- 
  lit_genes %>%
  rename(gene_function = `function`) %>%
  filter(gene %in% goi_df$gene_name) %>%
  left_join(goi_df %>% select(gene_name, scaffold, position), by = c("gene" = "gene_name"))
write_tsv(goi_table, here(outpath, "Table_S7.txt")) # For supplements
write_csv(goi_table, here(outpath, "Table_S7.csv")) # For analysis
```