```{r}
library(tidyverse)
library(here)
outpath <- here("analysis", "gea", "outputs")
plotpath <- here("analysis", "gea", "plots")
```


# Check for genes of interest
# Proteins of interest
```{r}
genes_nonsyn <- get_gea_genes(nonsyn = TRUE)

search <- function(x, y = NULL) {
  if (is.null(y)) y <- genes_nonsyn
  y %>%
    filter(str_detect(full_name, x)) %>%
    distinct(full_name) %>%
    pull(full_name) %>%
    str_extract("Name=([^\\[]+)\\[.*?:([^\\(]+)") %>%
    str_remove("^Name=") %>%
    str_replace("\\[.*?:", " (") %>%
    str_remove("\\s+$") %>%
    str_c(")")
}

#Humans
#HSP70 (Heat Shock Protein 70): This protein helps protect cells from stress-induced damage, including heat stress. It plays a crucial role in protein folding and repair.
search("HSP70")
search("HSP")
search("Heat shock") # many of these! Heat shock 70 kDA is included in the list
search("Heat shock 70") # found!
length(search("Heat shock"))
search("heat shock")

#UCP1 (Uncoupling Protein 1): Found in brown adipose tissue, UCP1 is involved in thermogenesis, helping humans generate heat in cold environments.
search("UCP1")
search("UCP")
search("Uncoupling")
search("uncoupling")

#MC1R (Melanocortin 1 Receptor): This receptor is involved in pigmentation and can affect skin's response to UV radiation, which is a crucial adaptation in different climates.
search("MC1R") 
search("Melanocortin") #"Melanocortin-2 receptor accessory protein 2 [Q96G30.2:Homo sapiens (Human)]"
search("melanocortin")
#EPAS1 (Endothelial PAS Domain Protein 1): This gene, also known as HIF-2α, is involved in the response to hypoxia and is associated with high-altitude adaptation.
search("EPAS1") 
search("PAS")# a hit! "Neuronal PAS domain-containing protein 4 [Q8IUM7.1:Homo sapiens (Human)]"
search("Endothelial") 

#Mice
#FGF21 (Fibroblast Growth Factor 21): This protein helps regulate metabolism and energy expenditure, playing a role in cold adaptation by promoting brown fat activity.
search("FGF21")
search("FGF") 
search("Fibroblast growth factor 21")
search("Fibroblast growth factor") #several

#PRDM16 (PR Domain Containing 16): Important in the development of brown adipose tissue, which is crucial for thermoregulation in cold environments.
search("PRDM16")
search("PRDM")

#HIF1A (Hypoxia-Inducible Factor 1 Alpha): Similar to humans, this protein helps mice adapt to low oxygen levels by regulating genes involved in oxygen homeostasis.
search("HIF1A")
search("HIF")
search("Hypoxia") # [1] "Hypoxia up-regulated protein 1 [Q5ZLK7.1:Gallus gallus (Chicken)]"

# ADRB3 (Beta-3 Adrenergic Receptor): This receptor is involved in the regulation of lipolysis and thermogenesis in brown fat, aiding in cold adaptation.
search("ADRB3")
search("Adrenergic")
search("ADR")

#Chickens
#UCP (Uncoupling Protein): Chickens also have uncoupling proteins that play a role in thermogenesis, helping them cope with temperature fluctuations.
search("UCP") 

#TRPV4 (Transient Receptor Potential Vanilloid 4): This protein is involved in temperature sensation and regulation.
#TRP in general is associated with thermosensation
# https://www.sciencedirect.com/science/article/abs/pii/S0959438815000306
search("TRPV4")
search("TRPV")
search("Transient receptor potential")
# [1] "Transient receptor potential cation channel subfamily M member 6 [Q9BX84.2:Homo sapiens (Human)]"
# [2] "Transient receptor potential cation channel subfamily A member 1 [Q8BLA8.1:Mus musculus (Mouse)]"
# [3] "Transient receptor potential cation channel subfamily M member 4 [Q8TD43.1:Homo sapiens (Human)]"
# [4] "Transient receptor potential cation channel subfamily M member 1 [Q7Z4N2.2:Homo sapiens (Human)]"
# [5] "Transient receptor potential cation channel subfamily V member 2 [Q9WTR1.2:Mus musculus (Mouse)]"
# [6] "Transient receptor potential cation channel subfamily V member 3 [Q8K424.2:Mus musculus (Mouse)]"
search("TRP")
# [1] "TRPM8 channel-associated factor homolog [Q5XHI4.1:Xenopus laevis (African clawed frog)]"
# [2] "TRPM8 channel-associated factor 2 [A6NFQ2.2:Homo sapiens (Human)]"   

#ADRB2 (Beta-2 Adrenergic Receptor): This receptor plays a role in the regulation of metabolic processes and is involved in the adaptation to cold stress.
search("ADRB2")

#Additional 
#Aquaporins (AQPs): These proteins are involved in water transport across cell membranes and play a role in osmoregulation, which can be crucial in adapting to varying humidity levels.
search("Aquaporin")
# [1] "Aquaporin-2 [P79099.2:Bos taurus (Bovine)]"  
# [2] "Aquaporin-11 [Q8NBQ7.1:Homo sapiens (Human)]"

#Leptin: This hormone, involved in regulating energy balance, can influence how organisms respond to different climatic conditions, especially in terms of energy storage and expenditure.
search("Leptin")
search("leptin")

# From this paper on mammals: https://www.nature.com/articles/s41598-021-95816-8
# specific candidate variants and genes are related to the neuronal system (ITPR1, ITPR2, and GRIA4) and neuroactive ligand–receptor interaction functions for heat tolerance (NPFFR2, CALCR, and GHR), providing a novel insight that can help to develop genetic and management approaches to combat heat stress.
search("Inositol 1,4,5-trisphosphate receptor type 1") 
search("Inositol 1,4,5-trisphosphate receptor type 2") # found! (ITPR2)
search("Glutamate receptor ionotropic") # Found Glutamate receptor ionotropic but not type 4 (only GRIK and GRIN, not GRIA)
search("Neuropeptide FF receptor 1") # Found NFFR1 but not 2
search("Calcitonin receptor") 
search("Growth hormone receptor") # Found! (GHR)

# From this paper on sticklebacks: https://www.nature.com/articles/s41598-021-95816-8
# We determined maximum critical thermal limits (CTmax) and the associated gene expression responses in three heat shock (hsp60, hsp70, hsp90) and two key metabolic (idh2, fbp2) genes at ecologically relevant moderate heat stress (26 °C) as well as at the critical thermal limit (CTmax)
search("Heat shock 70") # found!
search("Heat shock 90")
search("Heat shock 60")
search("Isocitrate dehydrogenase") # Found IDH but not IDH2
search("bisphosphatase") # Found FBP 

# From this paper on reptiles/thermosensation: https://www.sciencedirect.com/science/article/pii/S1744117X25000061 
#TRPP1L2, TRPP1L3, and TRPV1 were involved in heat-sensitive responses (> 36°C).
search("TRPP1L2")
search("TRPP1L3")
search("TRPV1")
search("Transient receptor potential cation channel subfamily V member 1")
#TRPV3, TRPA1, and TRPM8 were involved in cold-sensitive responses (< 20°C).
search("TRPV3")
search("Transient receptor potential cation channel subfamily V member 3") # Found!
search("TRPA1")
search("Transient receptor potential cation channel subfamily A member 1") # Found!
search("TRPM8") # Found!

# # From this paper on bees/thermal stress/gene expression: 
# https://www.researchgate.net/figure/The-expression-levels-of-DnaJB6-DnaJshv-DnaJB13-and-DnaJB14-under-heat-stress-The_fig4_360260597
# https://www.frontiersin.org/journals/ecology-and-evolution/articles/10.3389/fevo.2022.873791/full
# CHatGPT summary: DNAJB6 is a molecular chaperone belonging to the Hsp40 family, known for assisting in protein folding and preventing aggregation, especially under stress conditions. In the eastern honeybee (Apis cerana cerana), studies have shown that DNAJB6 expression is upregulated in response to elevated temperatures. Specifically, when exposed to temperatures of 40°C, 43°C, and 46°C for durations up to 5 hours, there was a notable increase in DNAJB6 mRNA levels, indicating its role in the heat stress response
# DnaJ homolog subfamily B member 6 
search("DnaJ homolog subfamily B member 6") # found! (DNAJB6)
```
```{r}
# Tick related for sceloporus clearing parasite
search("Factor B")
search("Properdin") 
# [1] "Properdin  (Mus musculus)"
search("Complement")
# [1] "Complement C4-B  (Homo sapiens)"                                       
# [2] "Complement factor B  (Bos taurus)"                                     
# [3] "Complement C1s subcomponent  (Sus scrofa)"                             
# [4] "Complement component C9  (Homo sapiens)"                               
# [5] "Complement C1q subcomponent subunit A  (Sus scrofa)"                   
# [6] "Complement C5  (Homo sapiens)"                                         
# [7] "Complement C1q tumor necrosis factor-related protein 1  (Mus musculus)"
# [8] "Complement C1q subcomponent subunit C  (Rattus norvegicus)"            

```

```{r}

# I manually curated a list of genes of interest based on the above searches
source(here("analysis", "gea", "get_selection_stats.R"))
goi <- get_goi_names()

# Z-scores
# NOTE: only has score along axis it was significant on
rda_z <- read_csv(here(outpath, "bio1ndvi_zscores.csv")) %>% filter(locus %in% genes_nonsyn$locus)
rda_genes <-
  genes_nonsyn %>%
  right_join(rda_z) 

# Look at HSP 70
hsp70 <- rda_genes %>% filter(grepl("Heat shock 70", full_name)) %>% dplyr::select(loading, axis, full_name)
nrow(hsp70)

rda_genes$HSP70 <- grepl("Heat shock 70", rda_genes$full_name)
rda_genes$goi <- rowSums(bind_cols(map(goi, ~grepl(.x, rda_genes$full_name)))) > 0
rda_genes$goi_name <- map_chr(rda_genes$full_name, function(name) {
  match <- keep(goi, ~ str_detect(name, .x))
  if (length(match) > 0) match[[1]] else NA_character_
}, .progress = TRUE)


gg_df <- 
  rda_genes %>% 
  distinct(locus, loading, axis, HSP70, goi, goi_name) %>% 
  pivot_wider(names_from = "axis", values_from = "loading")

pdf(here(plotpath, "goi_hist.pdf"), width = 10, height = 3)
ggplot(gg_df) +
  geom_histogram(aes(x = `1`)) +
  geom_vline(data = filter(gg_df, HSP70), aes(xintercept = `1`))
ggplot(gg_df) +
  geom_histogram(aes(x = `2`)) +
  geom_vline(data = filter(gg_df, HSP70), aes(xintercept = `2`))
ggplot(gg_df) +
  geom_histogram(aes(x = `1`)) +
  geom_vline(data = filter(gg_df, goi), aes(xintercept = `1`, col = goi_name)) + 
  theme_classic() +
  labs(col = "Genes of interest")
ggplot(gg_df) +
  geom_histogram(aes(x = `2`)) +
  geom_vline(data = filter(gg_df, goi), aes(xintercept = `2`, col = goi_name))+ 
  theme_classic() +
  labs(col = "Genes of interest")
dev.off()
```
