```{r}
library(tidyverse)
library(here)
library(sf)
library(vcfR)

source(here("general_functions.R"))
source(here("analysis", "gea", "functions_selection_stats.R"))
outpath <- here("analysis", "gea", "outputs")
plotpath <- here("analysis", "gea", "plots")
ca <- get_ca()
```

```{r}
# Get non-synonymous GEA SNPs
df <- read_csv(here(outpath, "bio1ndvi_gea_genes_nonsyn.csv"))

# Load dosage data
dos <- read_table(here("analysis", "gea", "outputs", "genes.raw"))

# Load coords and model dataframe
coords <- 
  get_coords(sf = TRUE) %>% 
  filter(SampleID %in% dos$IID) %>% 
  st_transform(3310) %>%
  # REMOVE CHANNEL ISLAND
  filter(SampleID != "Scelocci_CCGPMC_MW01-3-14") 

# Subset to only samples in coords
dos <- dos[dos$IID %in% coords$SampleID, ]

# Confirm orders are the same
stopifnot(all(dos$IID == coords$SampleID))

# CORRECT DOS NAMES
colnames(dos) <- gsub("_[A-Z]$", "", colnames(dos))
```

```{r}
plot_genes <- function(gene, gene_name = NULL, df){
  if (is.null(gene_name)) gene_name <- gene
  gene_loci <- df %>% filter(grepl(gene, full_name)) %>% pull(locus)
  if (length(gene_loci) == 0) gene_loci <- df %>% filter(full_name == gene) %>% pull(locus)
  if (length(gene_loci) == 0) {
    warning("No loci found for ", gene, "; Skipping")
    return(NULL)
  }

  gene_dos <- dos[, gene_loci]
  gene_dos$SampleID <- dos$IID

  nona_dos <- 
    gene_dos %>%
    mutate(across(everything(), ~ ifelse(is.na(.), median(., na.rm = TRUE), .)))

  gene_df <- 
    coords %>% 
    left_join(gene_dos, by = "SampleID")  %>%
    pivot_longer(-c(SampleID, geometry), names_to = "locus", values_to = "dos")

  plt1 <- 
    ggplot(gene_df) +
    geom_sf(data = ca) +
    geom_sf(aes(col = factor(dos))) +
    theme_void() +
    theme(legend.position = "bottom") +
    labs(title = gene_name) + 
    facet_wrap(~locus)

  nloci <- ncol(gene_dos) - 1 # -1 for SampleID
  if (nloci < 2) {
    return(list(dos = plt1, pca = NULL))
  }
  
  # Run PCA
  gene_pca <- prcomp(dplyr::select(nona_dos, -SampleID))

  # Get variable loadings
  gene_loadings <- 
    as.data.frame(gene_pca$rotation) %>%
    rownames_to_column("locus")

  pc_df <- 
    coords %>% 
    left_join(gene_dos, by = "SampleID") %>%
    mutate(PC1 = gene_pca$x[, 1], PC2 = gene_pca$x[,2]) 
  
  gene_df <-
    pc_df %>%
    pivot_longer(-c(SampleID, geometry, PC1), names_to = "locus", values_to = "dos")

  plt2 <-
    ggplot(gene_df) +
    geom_sf(data = ca) +
    geom_sf(aes(fill = PC1), pch = 21, size = 2, color = "black") +
    scale_fill_viridis_c(option = "turbo") +
    theme_void() +
    theme(legend.position = "bottom") +
    labs(title = paste0(gene_name, " (n = ", nloci, ")")) 
  
  return(list(dos = plt1, pca = plt2, loadings = gene_loadings, pc_df = pc_df))
}

# Get genes of interest
genes <- get_goi_names()

# Make plots for SNPs in genes of interest
plt_list <- imap(genes, \(x, i) plot_genes(gene = x, gene_name = i, df)) %>% compact()

# Pull out dosage and PCA plots
plt_dos <- map(plt_list, pluck, "dos")
plt_pca <- map(plt_list, pluck, "pca") %>% compact()

pdf(here(plotpath, "maps_of_gea_genes.pdf"), width = 8, height = 8)
plt_dos
dev.off()

pdf(here(plotpath, "maps_of_gea_gene_pcas.pdf"), width = 18, height = 18)
cowplot::plot_grid(plotlist = plt_pca, nrow = 3)
dev.off()

```

```{r}
dfs <- map(plt_list, pluck, "pc_df") %>% compact()
loadings <- map(plt_list, pluck, "loadings") %>% compact()

hsp70df <- dfs[[1]] 
hsp70loadings <- loadings[[1]] %>% mutate(clean_locus = sub("_[^_]*_[^_]*$", "", locus))

# Make PCA plot
pdf(here(plotpath, "hsp70_pca.pdf"), width = 6, height = 5)

ggplot(hsp70df) +
  geom_hline(yintercept = 0, color = "gray", linetype = "solid") +
  geom_vline(xintercept = 0, color = "gray", linetype = "solid") +
  # annotate("text", x = max(hsp70df$PC1), y = 0.1, label = "PC1", hjust = -0.1, vjust = 0.1, color = "gray") +
  # annotate("text", x = 0.1, y = max(hsp70df$PC2), label = "PC2", vjust = 0.1, color = "gray") +
  geom_point(aes(x = PC1, y = PC2, col = PC1)) +
  geom_segment(data = hsp70loadings, aes(x = 0, y = 0, xend = PC1 * 5, yend = PC2 * 5), 
         arrow = arrow(length = unit(0.2, "cm")), color = "black") +
  geom_text(data = hsp70loadings, aes(x = PC1 * 5, y = PC2 * 5, label = clean_locus), 
        hjust = 0.5, vjust = -0.5, color = "black") +
  scale_color_viridis_c(option = "turbo") +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))
dev.off()

gene_str <- get_gene_structure()
chr9_loci <- hsp70loadings %>% filter(grepl("chr9", locus)) %>% pull(locus)

dos[, gene_loci] %>% distinct()

hsp70_str <- gene_str %>% filter(full_name %in% hsp70_chr9$full_name)
hsp70_chr9 <- 
  df %>% 
  filter(locus %in% chr9_loci) %>% 
  mutate(clean_locus = sub("_[^_]*_[^_]*$", "", locus)) %>% 
  left_join(distinct(hsp70_str, gene_start, gene_end, full_name, gene_name))

hsp70_chr9 %>% dplyr::select(full_name, locus)


pdf(here(plotpath, "hsp70_pca.pdf"), width = 10, height = 2)
ggplot(hsp70_chr9) +
  geom_rect(data = hsp70_str, aes(xmin = gene_start, xmax = gene_end, ymin = 0, ymax = 0.5), fill = "lightgray") +
  geom_rect(data = hsp70_str, aes(xmin = exon_start, xmax = exon_end, ymin = 0, ymax = 0.5), fill = "gray") +
  geom_rect(data = hsp70_str, aes(xmin = cds_start, xmax = cds_end, ymin = 0, ymax = 0.5), fill = "darkgray") +
  geom_text(data = distinct(hsp70_chr9, gene_start, gene_end, gene_name), aes(x = (gene_start + gene_end) / 2, y = 0.5, label = gene_name), 
        color = "black", size = 3, vjust = -1) +
  # geom_rect(aes(xmin = exon_start, xmax = exon_end, ymin = 0, ymax = 1, fill = "exon")) +
  # geom_rect(aes(xmin = cds_start, xmax = cds_end, ymin = 0, ymax = 1, fill = "CDS")) +
  # Lollipop stems: lines from y = 1 to y = 1.15 (height of stick)
  geom_segment(aes(x = position, xend = position, y = 0, yend = 1, col = clean_locus), linewidth = 0.6) +
  # Lollipop heads: points at the end of each stick
  geom_point( aes(x = position, y = 1, col = clean_locus), size = 2, alpha = 0.5) +
  # Styling
  theme_classic() +
  labs(x = "", fill = "", col = "") +
  theme(legend.position = "bottom") 

ggplot(hsp70_chr9) +
  geom_segment(aes(x = gene_start, xend = gene_end, y = 1, yend = full_name),
               color = "gray40", size = 1.5) +
  geom_segment(aes(x = position, xend = position,
                   y = 1, yend = as.numeric(as.factor(full_name)) + 0.3),
               color = "black") +
  geom_point(aes(x = position,
                 y = 1.5,
                 color = csq),
             size = 3) 

ggplot(hsp70df) +
  geom_hline(yintercept = 0, color = "gray", linetype = "solid") +
  geom_vline(xintercept = 0, color = "gray", linetype = "solid") +
  # annotate("text", x = max(hsp70df$PC1), y = 0.1, label = "PC1", hjust = -0.1, vjust = 0.1, color = "gray") +
  # annotate("text", x = 0.1, y = max(hsp70df$PC2), label = "PC2", vjust = 0.1, color = "gray") +
  geom_point(aes(x = PC1, y = PC2, col = PC1)) +
  geom_segment(data = hsp70loadings, aes(x = 0, y = 0, xend = PC1 * 5, yend = PC2 * 5), 
         arrow = arrow(length = unit(0.2, "cm")), color = "black") +
  geom_text(data = hsp70loadings, aes(x = PC1 * 5, y = PC2 * 5, label = clean_locus), 
        hjust = 0.5, vjust = -0.5, color = "black") +
  scale_color_viridis_c(option = "turbo") +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))
dev.off()

```

# Compare HSP70 and temperature

```{r}
mod_df <- read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv")) 
coords_df <- left_join(coords, mod_df)
gene_loci <- 
  df %>% filter(grepl("Heat shock", full_name)) %>% pull(locus)
gene_dos <- dos[, gene_loci]
gene_dos$SampleID <- dos$IID

nona_dos <- 
  gene_dos %>%
  mutate(across(everything(), ~ ifelse(is.na(.), median(., na.rm = TRUE), .)))

gene_pca <- prcomp(dplyr::select(nona_dos, -SampleID))

gene_df <- 
  coords_df %>% 
  left_join(gene_dos, by = "SampleID") %>%
  mutate(PC1 = gene_pca$x[, 1]) %>%
  drop_na()

nona_dos <- nona_dos %>% filter(SampleID %in% gene_df$SampleID)

cor(gene_df$bio1, gene_df$NDVI) # 0.11

library(ggpubr)
pdf(here(plotpath, "gene_map.pdf"), width = 8, height = 4)
plt1 <- ggpartial("bio1", "PC1", c("NDVI", "bio1"), gene_df, col = "PC1") + scale_color_viridis_c(option = "turbo")
plt2 <- ggpartial("NDVI", "PC1", c("bio1", "NDVI"), gene_df, col = "PC1") + scale_color_viridis_c(option = "turbo")
cowplot::plot_grid(plt1, plt2, nrow = 1)
dev.off()

summary(lm(PC1 ~ bio1 + NDVI, data = gene_df))

cor_results <- map_dfr(select(nona_dos, -SampleID), ~{
  cor_result <- cor.test(.x, gene_df$bio1)
  tibble(r = cor_result$estimate, p = cor_result$p.value)
})
cor_results$locus <- colnames(select(nona_dos, -SampleID))

cor_results %>% arrange(desc(abs(r)))                                               
#  1 -0.278  0.000385 Scaffold_13__1_contigs__length_49873245_13302027_C_T
#  2  0.271  0.000537 chr7_47088909_A_G                                   
#  3  0.248  0.00164  chr9_25970915_C_T                                   
#  4 -0.242  0.00208  chr9_25967268_G_A                                   
#  5 -0.234  0.00302  chr9_25986335_C_T                                   
#  6  0.202  0.0106   chr9_25986389_C_T                                   
#  7  0.198  0.0125   chr9_25967457_C_T                                   
#  8 -0.154  0.0530   chr1_366003709_G_C                                  
#  9  0.144  0.0705   chr4_246620258_C_T                                  
# 10 -0.0815 0.307    chr5_187268636_C_T                                  
# 11  0.0773 0.333    chr3_213287000_G_C                                  
# 12  0.0737 0.356    chr7_60251840_C_A                                   
# 13 -0.0572 0.474    Scaffold_13__1_contigs__length_49873245_13301778_T_C
```


```{r}
mod_df <- read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv"))
coords_df <- left_join(coords, mod_df)

gene_loci <- 
  df %>% filter(grepl("TRPM8", full_name)) %>% pull(locus)
dos <- dos[dos$IID %in% coords_df$SampleID, ]
gene_dos <- dos[, gene_loci]
gene_dos$SampleID <- dos$IID

nona_dos <- 
  gene_dos %>%
  mutate(across(everything(), ~ ifelse(is.na(.), median(., na.rm = TRUE), .)))

gene_pca <- prcomp(select(nona_dos, -SampleID)) 

gene_df <- 
  coords_df %>% 
  right_join(gene_dos, by = "SampleID") %>%
  mutate(PC1 = gene_pca$x[, 1]) %>%
  drop_na()   
nona_dos <- nona_dos %>% filter(SampleID %in% gene_df$SampleID)

pdf(here(plotpath, "gene_map2.pdf"), width = 8, height = 4)
plt1 <- ggpartial("bio1", "PC1", c("NDVI", "bio1"), gene_df, col = "PC1") + scale_color_viridis_c(option = "turbo")
plt2 <- ggpartial("NDVI", "PC1", c("bio1", "NDVI"), gene_df, col = "PC1") + scale_color_viridis_c(option = "turbo")
cowplot::plot_grid(plt1, plt2, nrow = 1)

ggplot(gene_df, aes(y = chr5_7801341_G_A, x = bio1)) +
  geom_smooth(method = "lm") +
  geom_point()

ggplot(gene_df, aes(y = chr5_7801341_G_A, x = tmean_dif)) +
  geom_smooth(method = "lm") +
  geom_point()
dev.off()

summary(lm(PC1 ~ bio1, data = gene_df))

cor_results <- map_dfr(select(nona_dos, -SampleID), ~{
  cor_result <- cor.test(.x, gene_df$bio1)
  tibble(r = cor_result$estimate, p = cor_result$p.value)
})
cor_results$locus <- colnames(select(nona_dos, -SampleID))

cor_results %>% arrange(desc(abs(r))) 

#         r          p locus                                              
#     <dbl>      <dbl> <chr>                                              
# 1 -0.357  0.00000475 chr5_7801341_G_A                                   
# 2  0.246  0.00195    chr5_7833956_A_C                                   
# 3 -0.227  0.00442    Scaffold_138__1_contigs__length_2391489_2298866_T_C
# 4 -0.0724 0.369      Scaffold_138__1_contigs__length_2391489_2298855_C_T
```

# Similarity to core map

```{r}
mod_df <- 
  read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv")) %>%
  left_join(get_pops()) %>%
  st_as_sf(coords = c("x", "y"), crs = 4326)

socal_temp <- 
  mod_df %>%
  group_by(cluster) %>%
  summarize(bio1 = mean(bio1, na.rm = TRUE)) %>%
  filter(cluster == 9) %>%
  pull(bio1)

mod_df <- mod_df %>% mutate(tempdif_from_socal = bio1 - socal_temp)

pdf(here(plotpath, "temp_dif_from_socal_map.pdf"), width = 5, height = 5)
ggplot(mod_df) +
  geom_sf(data = ca) +
  geom_sf(aes(col = tempdif_from_socal)) +
  scale_color_viridis_c() +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(title = "Temperature difference from SoCal")
dev.off()
```

```{r}
socal_dif_test <- function(gene, gene_name = NULL, df, mod_df){
  if (is.null(gene_name)) gene_name = gene
  gene_loci <- df %>% filter(grepl(gene, full_name)) %>% pull(locus)
  if (length(gene_loci) == 0) {
    warning("No loci found for ", gene, "; Skipping")
    return(NULL)
  }

  dos <- dos[dos$IID %in% mod_df$SampleID, ]
  gene_dos <- dos[, gene_loci]
  gene_dos$SampleID <- dos$IID

  nona_dos <- 
    gene_dos %>%
    mutate(across(everything(), ~ ifelse(is.na(.), median(., na.rm = TRUE), .)))

  gene_df <- 
    mod_df %>% 
    select(SampleID, tempdif_from_socal, geometry) %>%
    left_join(gene_dos, by = "SampleID")  %>%
    pivot_longer(-c(SampleID, geometry, tempdif_from_socal), names_to = "locus", values_to = "dos")

  cor_test <-
    gene_df %>%
    group_by(locus) %>%
    summarize(
      p_value = cor.test(dos, tempdif_from_socal, method = "pearson")$p.value,
      r = cor.test(dos, tempdif_from_socal, method = "pearson")$estimate
    ) %>%
    mutate(p_adj = p.adjust(p_value, method = "fdr")) %>%
    filter(p_adj < 0.05) %>%
    st_drop_geometry()
  
  gene_df <- 
    gene_df %>% 
    right_join(cor_test, by = "locus") 
  
  nona_dos <- nona_dos[, c("SampleID", cor_test$locus)]
   
  plt1 <- 
    ggplot(cor_test) +
    geom_sf(data = ca) +
    geom_sf(aes(col = dos)) +
    scale_color_viridis_c() +
    theme_void() +
    theme(legend.position = "bottom") +
    labs(title = gene_name) +
    facet_wrap(~locus)

  if (ncol(nona_dos) < 2) {
    return(list(dos = plt1, pca = NULL, gene_df = gene_df))
  }
  
  gene_pca <- prcomp(select(nona_dos, -SampleID))

  gene_df2 <- 
    mod_df %>% 
    select(SampleID, geometry) %>%
    left_join(gene_dos[, c("SampleID", cor_test$locus)], by = "SampleID") %>%
    mutate(PC1 = gene_pca$x[, 1]) %>%
    pivot_longer(-c(SampleID, geometry, PC1), names_to = "locus", values_to = "dos")

  plt2 <-
    ggplot(gene_df2) +
    geom_sf(data = ca) +
    geom_sf(aes(fill = PC1), pch = 21, cex = 2, col = rgb(0,0,0,0)) +
    scale_fill_viridis_c(option = "turbo") +
    theme_void() +
    theme(legend.position = "bottom") +
    labs(title = gene_name) 
  
  return(list(dos = plt1, pca = plt2, gene_df = gene_df))
}

genes <- get_goi_names()

plt_list <- imap(genes, \(x, i) socal_dif_test(gene = x, gene_name = i, df, mod_df)) %>% compact()

plt_dos <- map(plt_list, pluck, "dos")
plt_pca <- map(plt_list, pluck, "pca") %>% compact()
gene_df <- map(plt_list, pluck, "gene_df") %>% compact() %>% bind_rows(.id = "gene_name")

top <-
  gene_df %>% 
  group_by(locus) %>% 
  # WANT POSITIVE RELATIONSHIP
  arrange(desc((r))) %>% 
  slice(1:5) %>% 
  ungroup()


pdf(here(plotpath, "socal_tempdif_test.pdf"), width = 8, height = 8)
#plt_dos

ggplot(top, aes(x = tempdif_from_socal, y = dos)) +
  geom_point() +
  geom_smooth(se  = FALSE) + 
  facet_wrap(~gene_name + locus) 
dev.off()

```

# IDEA: Identify loci that are found in non-adjacent populations (bonus if those pops have similar climates)

# DISTANCE BASED

```{r}

library(sf)
library(dplyr)
library(tidyr)
library(purrr)
library(units)

#-----------------------------#
# FUNCTION 1: Allele frequency
#-----------------------------#
compute_pop_frequencies <- function(sf_data) {
  sf_data %>%
    st_drop_geometry() %>%
    group_by(cluster, locus) %>%
    summarize(freq = mean(dos, na.rm = TRUE), .groups = "drop")
}

#---------------------------------------------#
# FUNCTION 2: Get adjacent/nonadjacent clusters
#---------------------------------------------#
get_adjacent_clusters <- function(focal_cluster, dat_proj, dist_thresh) {
  focal_inds <- dat_proj %>% filter(cluster == focal_cluster)

  nearby_matrix <- st_is_within_distance(focal_inds, dat_proj, dist = dist_thresh)
  nearby_inds <- unique(unlist(nearby_matrix))

  neighbors <- dat_proj[nearby_inds, ] %>%
    filter(cluster != focal_cluster)

  adjacent_pops <- unique(neighbors$cluster)
  all_pops <- unique(dat_proj$cluster)
  non_adjacent_pops <- setdiff(all_pops, c(focal_cluster, adjacent_pops))

  list(adjacent = adjacent_pops, non_adjacent = non_adjacent_pops)
}

#--------------------------------------------------------------#
# FUNCTION 3: Find informative loci for a given focal cluster
#--------------------------------------------------------------#
find_private_loci <- function(focal_cluster, pop_freqs, adj_pops, nonadj_pops,
                              adj_threshold = 0.1, nonadj_threshold = 0.4, min_nonadj = 2) {
  focal_freqs <- pop_freqs %>% filter(cluster == focal_cluster)
  adj_freqs   <- pop_freqs %>% filter(cluster %in% adj_pops)
  nonadj_freqs <- pop_freqs %>% filter(cluster %in% nonadj_pops)

  high_in_focal <- focal_freqs %>% filter(freq > nonadj_threshold)

  good_loci <- high_in_focal$locus[!high_in_focal$locus %in% (
    adj_freqs %>%
      filter(locus %in% high_in_focal$locus, freq >= adj_threshold) %>%
      pull(locus)
  )]

  if (length(good_loci) == 0) return(NULL)

  matching_nonadj <- nonadj_freqs %>%
    filter(locus %in% good_loci, freq > nonadj_threshold) %>%
    group_by(locus) %>%
    filter(n() >= min_nonadj) %>%
    ungroup() %>%
    mutate(focal_cluster = focal_cluster,
           nonadj_cluster = cluster) %>%
    select(focal_cluster, nonadj_cluster, locus, freq)

  if (nrow(matching_nonadj) > 0) return(matching_nonadj) else return(NULL)
}

#---------------------------#
# FUNCTION 4: Master wrapper
#---------------------------#
detect_private_loci <- function(dat, dist_thresh,
                                adj_threshold = 0.1,
                                nonadj_threshold = 0.4,
                                min_nonadj = 2,
                                crs_proj = 3310) {
  dat_proj <- st_transform(dat, crs = crs_proj)
  dist_thresh <- set_units(dist_thresh, "m")

  pop_freqs <- compute_pop_frequencies(dat_proj)
  all_clusters <- unique(dat_proj$cluster)

  results <- map(all_clusters, function(pop) {
    neighbor_info <- get_adjacent_clusters(pop, dat_proj, dist_thresh)

    find_private_loci(
      focal_cluster = pop,
      pop_freqs = pop_freqs,
      adj_pops = neighbor_info$adjacent,
      nonadj_pops = neighbor_info$non_adjacent,
      adj_threshold = adj_threshold,
      nonadj_threshold = nonadj_threshold,
      min_nonadj = min_nonadj
    )
  }) %>% compact()

  bind_rows(results)
}

final_result <- detect_private_loci(
  dat = dat, # TODO: figure out what dat is supposed to be
  dist_thresh = 10000,
  adj_threshold = 0.1,
  nonadj_threshold = 0.1,
  min_nonadj = 2
)

pdf(here(plotpath, "nonadjacency_test.pdf"))
length(unique(final_result$locus))
dat_filtered <- dat %>% filter(locus %in% final_result$locus)
ggplot(dat_filtered) +
  geom_sf(data = ca) +
  geom_sf(aes(col = (dos))) +
  theme_void() +
  theme(legend.position = "bottom") +
  facet_wrap(~locus) +
  labs(title = "High frequency loci in non-adjacent populations")
dev.off()

```


# PCA of all GEA SNPs [NOT CURRENTLY USED]

```{r}
process_pca <- function(path){
  pca <- read.table(path)
  pca <- 
    pca %>% 
    rename(SampleID = V2) %>% 
    select(-V1) %>% 
    rename(PC1 = V3, PC2 = V4, PC3 = V5) %>%
    # add RGB
    mutate(RGB_PC1 = scales::rescale(PC1, to = c(0, 1)),
           RGB_PC2 = scales::rescale(PC2, to = c(0, 1)),
           RGB_PC3 = scales::rescale(PC3, to = c(0, 1))
    )
  return(pca)
}

coords <- get_coords(sf = TRUE)
pca_genes <- 
  process_pca(here("analysis", "gea", "outputs", "genes.eigenvec")) %>%
  left_join(coords, by = "SampleID") %>%
  filter(SampleID != "Scelocci_CHI1382_DAW5-46-21") %>%
  st_as_sf()
pca_nogea <- 
  process_pca(here("analysis", "gea", "outputs", "nogea.eigenvec"))  %>%
  left_join(coords, by = "SampleID") %>%
  filter(SampleID != "Scelocci_CHI1382_DAW5-46-21") %>% 
  mutate(PC2 = -PC2, RGB_PC2 = scales::rescale(PC2, to = c(0, 1))) %>%
  mutate(PC1 = PC1, RGB_PC1 = scales::rescale(PC1, to = c(0, 1))) %>%
  mutate(PC3 = -PC3, RGB_PC3 = scales::rescale(PC3, to = c(0, 1))) %>%
  st_as_sf()

# Plot RGB 
outpath <- here("analysis", "gea", "plots")
pdf(here(outpath, "genes_pca.pdf"), width = 6, height = 3)
minvals <- min(pca_genes$PC1, pca_genes$PC2)
maxvals <- max(pca_genes$PC1, pca_genes$PC2)
leg <- 
  ggplot(pca_genes) +
  geom_point(aes(x = PC1, y = PC2, color = rgb(RGB_PC1, RGB_PC2, RGB_PC3))) +
  theme_void() +
  scale_color_identity() +
  annotate("segment", x = minvals * 1.1, xend = maxvals * 1.1, y = 0, yend = 0, arrow = arrow(length = unit(0.2, "cm"))) +
  annotate("segment", x = 0, xend = 0, y = minvals * 1.1, yend = maxvals * 1.1, arrow = arrow(length = unit(0.2, "cm"))) +
  annotate("text", x = maxvals * 1.1, y = 0, label = "PC1", color = "black", hjust = -0.1) +
  annotate("text", x = 0, y = maxvals * 1.1, label = "PC2", color = "black", vjust = -0.1) +
  coord_cartesian(xlim = c(minvals * 1.4, maxvals * 1.4), ylim = c(minvals * 1.4, maxvals * 1.4))
plt <- 
  ggplot(pca_genes) +
  #geom_sf(data = ca) +
  geom_sf(aes(color = rgb(RGB_PC1, RGB_PC2, RGB_PC3))) +
  theme_void() +
  scale_color_identity()

plot_grid(plt, leg, ncol = 2, rel_widths = c(1, 1))


minvals <- min(pca_nogea$PC1, pca_nogea$PC2)
maxvals <- max(pca_nogea$PC1, pca_nogea$PC2)
leg <- 
  ggplot(pca_nogea) +
  geom_point(aes(x = PC1, y = PC2, color = rgb(RGB_PC1, RGB_PC2, RGB_PC3))) +
  theme_void() +
  scale_color_identity() +
  annotate("segment", x = minvals * 1.1, xend = maxvals * 1.1, y = 0, yend = 0, arrow = arrow(length = unit(0.2, "cm"))) +
  annotate("segment", x = 0, xend = 0, y = minvals * 1.1, yend = maxvals * 1.1, arrow = arrow(length = unit(0.2, "cm"))) +
  annotate("text", x = maxvals * 1.1, y = 0, label = "PC1", color = "black", hjust = -0.1) +
  annotate("text", x = 0, y = maxvals * 1.1, label = "PC2", color = "black", vjust = -0.1) +
  coord_cartesian(xlim = c(minvals * 1.4, maxvals * 1.4), ylim = c(minvals * 1.4, maxvals * 1.4))
plt <- 
  ggplot(pca_nogea) +
  #geom_sf(data = ca) +
  geom_sf(aes(color = rgb(RGB_PC1, RGB_PC2, RGB_PC3))) +
  theme_void() +
  scale_color_identity()

plot_grid(plt, leg, ncol = 2, rel_widths = c(1, 1))
dev.off()
```

# Look at genes with multiple SNPs

```{r}
nonsyn <- get_gea_genes(nonsyn = TRUE)
gene_str <- get_gene_structure()

high_nsnp <- 
  nonsyn %>% 
  # Use full-name because the same uniprotIDs can be assigned to multiple genes in the genome
  group_by(full_name) %>%
  filter(grepl("Name=", full_name)) %>% 
  summarize(n = n()) %>%
  arrange(desc(n)) 

high_nsnp

sd <- 
  nonsyn %>% 
  filter(full_name == high_nsnp$full_name[1]) 
head(sd)

sd_str <-
  gene_str %>%
  filter(full_name == high_nsnp$full_name[1]) 

ca <- get_ca()
pdf(here(plotpath, "multi_snp_genes.pdf"), width = 5, height = 5)
plot_genes(gene = high_nsnp$full_name[1], gene_name = "Interferon-induced very large GTPase 1", df)
dev.off()


pdf(here(plotpath, "multi_snp_genes.pdf"), width = 8, height = 2)
ggplot(sd_str) +
  geom_rect(aes(xmin = gene_start, xmax = gene_end, ymin = 0, ymax = 1, fill = "gene")) +
  geom_rect(aes(xmin = exon_start, xmax = exon_end, ymin = 0, ymax = 1, fill = "exon")) +
  geom_rect(aes(xmin = cds_start, xmax = cds_end, ymin = 0, ymax = 1, fill = "CDS")) +

  # Lollipop stems: lines from y = 1 to y = 1.15 (height of stick)
  geom_segment(data = sd, aes(x = position, xend = position, y = 1, yend = 1.15, col = factor(csq)), linewidth = 0.6) +

  # Lollipop heads: points at the end of each stick
  geom_point(data = sd, aes(x = position, y = 1.15, col = factor(csq)), size = 2) +

  # Styling
  theme_classic() +
  scale_fill_manual(values = c("gene" = "#CBD5E1", "exon" = "#94A3B8", "CDS" = "#475569")) +
  theme(
    legend.position = "bottom",
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line.y = element_blank()
  ) +
  labs(x = "", fill = "", col = "")
dev.off()


```