```{r}
library(tidyverse)
library(here)
outpath <- here("analysis", "gea", "outputs")
plotpath <- here("analysis", "gea", "plots")

gea <- read_csv(here("analysis", "gea", "outputs", "bio1ndvi_gea_gene_snp.csv"))


gea <- 
  gea %>% 
  mutate(
    id = str_extract(full_name, "GNX-\\d+"),
    name = str_extract(full_name, "(?<=Name=)[^\\[]+"),
    uniprotid = str_extract(full_name, "(?<=\\[)[^:]+")
  )

goi_names <- c("Heat shock", "Inositol 1,4,5-trisphosphate receptor type 1", "Inositol 1,4,5-trisphosphate receptor type 2", "Neuropeptide FF receptor 1", "Calcitonin receptor", "Growth hormone receptor", "Transient receptor potential cation channel subfamily V member 3", "Transient receptor potential cation channel subfamily A member 1", "TRPM8", "Endothelial PAS domain-containing protein 1")

goi <- 
  gea %>% 
  filter(reduce(map(goi_names, ~str_detect(full_name, .x)), `|`)) %>%
  filter(grepl("chr", scaffold)) %>%
  rename(CHROM = scaffold)

all_genes <- 
  read.table(here(outpath, "all_genes.bed"), sep="\t", quote="", fill=TRUE, stringsAsFactors=FALSE) %>%
  rename(CHROM = V1, start = V4, end = V5, full_name = V9)
 
genes <- 
  all_genes %>%
  filter(full_name %in% goi$full_name)
```

```{r}
tjd <- read_table(here(outpath, "58-Sceloporus_50kb_tajimad_pop9.Tajima.D"))
fst <- read_table(here(outpath, "58-Sceloporus_50kb_fst_pop9pop6.windowed.weir.fst"))

tjd_files <- list.files(here(outpath), pattern = "100kb_tajimad.*\\.Tajima\\.D$", full.names = TRUE)
tjd_pops <- str_extract(tjd_files, "pop[0-9]+") %>% unique()
names(tjd_files) <- tjd_pops

tjd <- 
  map(tjd_files, read_table) %>% 
  bind_rows(.id = "pop") %>%
  mutate(TajimaD = as.numeric(TajimaD)) %>%
  filter(grepl("chr", CHROM)) %>%
  mutate(CHROM = factor(CHROM, levels = paste0("chr", 1:11))) %>%
  mutate(top5 = if_else(TajimaD > quantile(TajimaD, 0.95, na.rm = TRUE), 1, 0), bottom5 = if_else(TajimaD < quantile(TajimaD, 0.05, na.rm = TRUE), 1, 0)) %>%
  mutate(outliers = case_when(top5 == 1 ~ "Top 5%", bottom5 == 1 ~ "Bottom 5%", TRUE ~ NA))

pdf(here(plotpath, "tajimaD.pdf"), width = 10, height = 10)

tjd %>%
  group_by(pop) %>%
  group_split() %>%
  map(~ ggplot(.x) +
        ggtitle(unique(.x$pop)) +
        geom_rect(data = genes, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf),  fill = "black", col = "black") +
        geom_line(aes(x = BIN_START, y = TajimaD), color = "gray") +
        geom_point(aes(x = BIN_START, y = TajimaD, color = outliers), size = 0.5) +
        geom_hline(yintercept = 0, linetype = "dashed") +
        labs(x = "Position (bp)", y = "Tajima's D") +
        scale_x_continuous(labels = scales::comma, expand = c(0, 0)) +
        scale_y_continuous(labels = scales::comma) +
        theme_classic() +
        facet_wrap(~CHROM, scales = "fixed", ncol = 1) +
        theme(axis.text.x = element_blank(), 
              axis.title.x = element_blank(), 
              axis.line.x = element_blank(),
              strip.background = element_blank(),
              strip.text.x = element_text(hjust = 0)))

ggplot(tjd) +
  geom_rect(data = genes, aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf),  fill = "black", col = "black") +
  geom_line(aes(x = BIN_START, y = TajimaD, color = pop), alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(x = "Position (bp)", y = "Tajima's D", color = "Population") +
  scale_x_continuous(labels = scales::comma, expand = c(0, 0)) +
  scale_y_continuous(labels = scales::comma) +
  theme_classic() +
  facet_wrap(~CHROM, scales = "fixed", ncol = 1) +
  theme(axis.text.x = element_blank(), 
        axis.title.x = element_blank(), 
        axis.line.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_text(hjust = 0, size = 10), legend.position = "bottom") 
dev.off()

pop7chr5 <- filter(tjd, pop == "pop2" & CHROM == "chr5")
pdf(here(plotpath, "tajimaD_pop7_chr5.pdf"), width = 20, height = 2)
ggplot(pop7chr5) +
  geom_rect(data = filter(genes, CHROM == "chr5"), aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf),  fill = "black", col = "black") +
  geom_line(aes(x = BIN_START, y = TajimaD), color = "gray") +
  geom_point(aes(x = BIN_START, y = TajimaD, color = outliers), size = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(x = "Position (bp)", y = "Tajima's D") +
  scale_x_continuous(labels = scales::comma, expand = c(0, 0)) +
  scale_y_continuous(labels = scales::comma) +
  theme_classic() +
  theme(axis.text.x = element_text(size = 10), 
        axis.title.x = element_text(size = 10), 
        axis.line.x = element_line(size = 0.5),
        strip.background = element_blank(),
        strip.text.x = element_text(hjust = 0))
dev.off()

gene_bins <- 
  all_genes %>%
  group_by(CHROM, full_name) %>%
  group_split() %>%
  map(~{
    bin <- 
      tjd %>% 
      filter(CHROM == .x$CHROM) %>% 
      filter(BIN_START <= .x$start) %>%
      filter(BIN_START + 100000 >=.x$end) %>%
      mutate(full_name = .x$full_name)
  }, .progress = TRUE) %>% bind_rows()

goi_gene_bins <- gene_bins %>% filter(full_name %in% genes$full_name)
goi_gene_bins %>% 
  filter(TajimaD < 0) %>% 
  arrange(TajimaD) %>% 
  dplyr::select(CHROM, pop, TajimaD, outliers, full_name) %>%
  head(20)

goi_gene_bins %>% 
  filter(TajimaD < 0) %>% 
  arrange(TajimaD) %>% 
  dplyr::select(CHROM, pop, TajimaD, outliers, full_name) %>%
  filter(grepl("Heat shock 70", full_name)) 

negtjd_genes <- 
  gene_bins %>% 
  filter(outliers == "Bottom 5%") %>% 
  arrange(TajimaD) %>% 
  # Include only genes with descriptions
  filter(grepl("\\[", full_name)) %>%
  left_join(all_genes)

pop1chr3 <- filter(tjd, pop == "pop1" & CHROM == "chr3")
negtjd_genes %>% filter(CHROM == "chr3", pop == "pop1") %>% dplyr::select(full_name)

hsp70 <- 
  negtjd_genes %>% 
  filter(grepl("Heat shock 70", full_name)) %>% 
  filter(CHROM == "chr3", pop == "pop1") %>%
  dplyr::select(full_name, start, end)

tjd10kb_pop1_chr3 <- 
  read_table(here(outpath, "58-Sceloporus_10kb_tajimad_pop1.Tajima.D")) %>% 
  filter(CHROM == "chr3") %>% 
  rename(scaffold = CHROM) %>%
  mutate(TajimaD = as.numeric(TajimaD)) 

tjd_q05 <- tjd %>% group_by(pop) %>% summarize(q05 = quantile(TajimaD, 0.05, na.rm = TRUE))

pdf(here(plotpath, "tajimaD_pop1_chr3.pdf"), width = 11, height = 3)
ggplot(tjd10kb_pop1_chr3) +  
  geom_rect(data = filter(negtjd_genes, CHROM == "chr3", pop == "pop1", grepl("Heat", full_name)), aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf,  fill = full_name)) +
  geom_line(aes(x = BIN_START, y = TajimaD), color = "gray") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = filter(tjd_q05, pop == "pop1")$q05, linetype = "dotted", col = "red") +
  labs(x = "Position (bp)", y = "Tajima's D") +
  scale_x_continuous(labels = scales::comma, expand = c(0, 0), limits = range(hsp70$start - 100*1e4, hsp70$end + 100*1e4)) +
  scale_y_continuous(labels = scales::comma) +
  theme_classic() +
  theme(axis.text.x = element_text(size = 10), 
        axis.title.x = element_text(size = 10), 
        axis.line.x = element_line(size = 0.5),
        strip.background = element_blank(),
        strip.text.x = element_text(hjust = 0), legend.position = "bottom")
dev.off()

# ggplot(pop1chr3) +  
#   geom_rect(data = filter(negtjd_genes, CHROM == "chr3", pop == "pop1"), aes(xmin = start, xmax = end, ymin = -Inf, ymax = Inf,  col = full_name)) +
#   geom_line(aes(x = BIN_START, y = TajimaD), color = "gray") +
#   geom_rect(data = filter(genes, CHROM == "chr3"), aes(xmin = start, xmax = end, ymin = -0.5, ymax = 0.5), col = "black") +
#   #geom_point(aes(x = BIN_START, y = TajimaD, color = outliers), size = 0.5) +
#   geom_hline(yintercept = 0, linetype = "dashed") +
#   labs(x = "Position (bp)", y = "Tajima's D") +
#   scale_x_continuous(labels = scales::comma, expand = c(0, 0)) +
#   scale_y_continuous(labels = scales::comma) +
#   theme_classic() +
#   theme(axis.text.x = element_text(size = 10), 
#         axis.title.x = element_text(size = 10), 
#         axis.line.x = element_line(size = 0.5),
#         strip.background = element_blank(),
#         strip.text.x = element_text(hjust = 0))

```