---
title: "Admixture analysis"
output:
  github_document:
    toc: TRUE
---
```{r, include = FALSE}
library(here)
library(tidyverse)
library(sf)
library(terra)
library(ggpubr)
library(algatr)
library(viridis)
library(vcfR)
library(hierfstat)
library(tigris)
source(here("analysis", "admixture", "functions_admixture.R"))
source(here("general_functions.R"))
# Set global options for caching
knitr::opts_chunk$set(
  cache = TRUE,
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  result = FALSE
)

plotpath <- here("analysis", "admixture", "plots")
outpath <- here("analysis", "admixture", "outputs")
```

```{r, echo = FALSE, message = FALSE, include=FALSE}
# Load the U.S. state boundaries data
ca <- get_ca()
# make theme for plotting
theme_custom <- 
  theme(
    strip.background = element_rect(color = "gray", fill = "gray"),
    panel.background = element_rect(color = "gray", fill = NA),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    strip.text = element_text(size = 16, face = "italic")
    )
```

```{r, include = FALSE}
# get coordinates 
coords <- get_coords(all = TRUE)
```

# 2. ADMIXTURE
```{r}
cv <- get_cv(K = 2:15)

png(here(plotpath, "cv_error.png"), width = 10, height = 5, units = "in", res = 300)
ggplot(cv, aes(x = K, y = cv_error, group = 1)) +
  geom_point() +
  geom_line() +
  theme_bw()
dev.off()
```

```{r admixture, fig.width = 13, fig.height = 6}
# join with coords
Kvals <- c(2:15)
Q <-
 map(Kvals, ~get_Q(K = .x) %>% 
 mutate(K = .x)) %>%
 bind_rows() %>%
 arrange(across(starts_with("V"))) %>%
 mutate(SampleID = factor(SampleID, levels = unique(SampleID))) %>%
 pivot_longer(starts_with("V"), names_to = "PopGroup", values_to = "Q")
 
df <-
 left_join(Q, coords[,c("x", "y", "SampleID")], by = "SampleID") %>%
 st_as_sf(coords = c("x", "y")) %>%
 st_set_crs(st_crs(4326))

pdf(here(plotpath, "admixture.pdf"), width =20, height = 10)
ggplot(df) +
  geom_sf(data = ca) +
  geom_sf(aes(col = cluster)) +
  facet_wrap(~K, nrow = 2) +
  theme_void() +
  scale_color_manual(values = viridis::turbo(max(Kvals))) 

barplots <- map(Kvals, ~structure_plot(qmat = get_Q(K = .x, qmat_only = TRUE)) + scale_fill_manual(values = viridis::turbo(max(Kvals))))
do.call(ggpubr::ggarrange, c(barplots, ncol = 1))
dev.off()
```

```{r}
qdf <- df %>% group_by(SampleID, K) %>% summarize(score = 1 - max(Q, na.rm = TRUE))

pdf(here(plotpath, "admixture_scores.pdf"), width = 10, height = 10)
ggplot(qdf) +
  geom_sf(data = ca) +
  geom_sf(aes(col = score)) +
  theme_void() +
  scale_color_viridis_c(option = "plasma") +
  facet_wrap(~K) +
  labs(col = "Admixture score")
dev.off()
```

```{r}
library(algatr)
library(wingen)
ca_proj <- ca %>% st_transform(3310)
grid <- coords_to_raster(coords_proj, res = 5000, buffer = 25)
grid <- crop(grid, ca_proj)

qmat_samples <- get_Q(K = 8, qmat_only = FALSE)

coords_proj <- 
  get_coords(sf= TRUE) %>%
  st_transform(3310) %>% 
  filter(SampleID %in% qmat_samples$SampleID) %>% 
  drop_na()

qmat <- get_Q(K = 8, qmat_only = TRUE)

# kriging
krig_admix <- tess_krig(qmat, coords_proj, grid)
crs(krig_admix) <- crs(grid)

# Get admixture score for each cell
max_admix <- 1 - max(krig_admix)

pdf(here(plotpath, "kriging.pdf"), width = 5, height = 5)
plot(max_admix)
dev.off()

writeRaster(max_admix, here("analysis", "admixture", "outputs", "max_admix.tif"), overwrite = TRUE)
```

## Pie charts
```{r}
library(scatterpie)
ca_longlat <- st_transform(ca, 4326)
plts <-
  df %>%
  group_by(K) %>%
  group_split() %>%
  map(~{
    gg_df <- 
      .x %>%
      bind_cols(st_coordinates(.x)) %>%
      drop_na(Q) %>%
      select(-cluster) %>%
      group_by(SampleID, X, Y, PopGroup) %>%
      pivot_wider(names_from = PopGroup, values_from = Q, values_fill = 0)

    ggplot() +
      geom_sf(data = ca_longlat) +
      geom_scatterpie(
        data = st_drop_geometry(gg_df),
        aes(x = X, y = Y, group = SampleID),
        cols = paste0("V", 1:unique(.x$K)),
        pie_scale = 0.7
      ) +
      theme_void() +
      labs(fill = "Population") +
      ggtitle(paste("K =", .x$K[1]))
  })

pdf(here(plotpath, "admixture_pie_charts.pdf"), width = 6, height = 6)
plts
dev.off()
```


## Switched coordinates
```{r}
df8 <- 
  df %>% 
  filter(K == 8) %>%
  group_by(SampleID) %>%
  select(geometry, SampleID, PopGroup, Q, cluster) %>%
  bind_cols(st_coordinates(.)) 
problem_coords <- get_corrected_coords() %>% pull(SampleID)
problem_df <-  
  df8 %>% 
  filter(SampleID %in% problem_coords) %>% 
  group_by(SampleID) %>%
  filter(Q == max(Q, na.rm = TRUE)) 
problem_df

df8 %>% filter(grepl("213197", SampleID) | grepl("214858", SampleID)) %>% 
  group_by(SampleID) %>%
  filter(Q == max(Q, na.rm = TRUE)) 

df_clean <- 
  df8 %>%
  drop_na(Q) %>%
  select(-cluster) %>%
  group_by(SampleID, X, Y, PopGroup) %>%
  pivot_wider(names_from = PopGroup, values_from = Q, values_fill = 0)

pdf(here(plotpath, "potentially_incorrect_coordinates.pdf"), width = 10, height = 8)
# Plot
library(scatterpie)
ggplot() +
  geom_sf(data = ca) +
  geom_scatterpie(
    data = st_drop_geometry(df_clean),
    aes(x = X, y = Y, group = SampleID),
    cols = paste0("V", 1:8),
    pie_scale = 0.7
  ) +
  theme_void() 

ggplot(df8) +
  geom_sf(data = ca) +
  geom_sf(aes(col = cluster)) +
  geom_sf(data = problem_df, aes(col = cluster), size = 3) +
  geom_sf(data = problem_df, size = 3, pch = 1) +
  ggrepel::geom_text_repel(data = problem_df, aes(x = X, y = Y, label = SampleID), size = 3, vjust = 0.5) +
  theme_void()
dev.off()

pdf(here(plotpath, "labelled_coordinates.pdf"), width = 20, height = 25)
ggplot(distinct(df8, SampleID, cluster, geometry, X, Y)) +
  geom_sf(data = ca) +
  geom_sf(aes(col = cluster)) +
  ggrepel::geom_text_repel(aes(x = X, y = Y, label = SampleID), size = 4, vjust = 0.5) +
  theme_void()
dev.off()
```
## Write out Q files 
```{r}
# FOR LINEAR MODELS: 
# Write out Q files for K = 8
# cluster = final cluster assignment for SampleID given max Q
# PopGroup = Q values for each cluster
Q %>% 
  # only keep the pop group/Q values corresponding to the cluster
  mutate(PopGroup = as.numeric(gsub("V", "", PopGroup))) %>%
  filter(cluster == PopGroup, K == 8) %>%
  write_csv(here(outpath, "Q8.csv"))

# write out Q values for the assigned population
Q %>%
  filter(K == 8) %>%
  # only keep the pop group/Q values corresponding to the cluster
  mutate(PopGroup = as.numeric(gsub("V", "", PopGroup))) %>%
  filter(cluster == PopGroup) %>%
  mutate(pop = paste0("pop", cluster)) %>%
  group_by(cluster) %>%
  group_split() %>%
  map(~as.character(pull(.x, SampleID))) %>%
  iwalk(\(x, idx) write(x, here(outpath, paste0("pop", idx, ".txt"))))
```

```{r, fig.width = 13, fig.height = 6}
# Check for consistency
# simplified df with only cluster assignments and not Q values
simplified_df <- 
  df %>%
  # doesn't matter which pop group is selected, cluster is repeated
  filter(PopGroup == "V1") %>%
  dplyr::select(SampleID, cluster, K)
IDs <- unique(simplified_df$SampleID)

same_all_df <-
  map(IDs, ~{
    pop <- 
      simplified_df %>%
      filter(SampleID == .x) %>%
      st_drop_geometry() %>%
      rename(reference_cluster = cluster, reference_id = SampleID)
    same_df <-
      simplified_df %>%
      left_join(pop, by = "K") %>%
      mutate(same = (cluster == reference_cluster)) %>%
      group_by(SampleID, reference_id) %>%
      summarize(same = mean(same), .groups = "drop")
    return(same_df)
  }) %>% 
  bind_rows()
same_summarize_df <-
  same_all_df %>%
  group_by(SampleID) %>%
  summarize(same = mean(same), .groups = "drop")
ggplot(same_summarize_df) +
  geom_sf(aes(col = same)) +
  scale_color_viridis_c(option = "plasma")
```

# Write out individuals for SMC++ and window calculations
```{r}
library(here)
library(tidyverse)
library(sf)
source(here("analysis", "admixture", "functions_admixture.R"))
source(here("general_functions.R"))
outpath <- here("analysis", "admixture", "outputs")
plotpath <- here("analysis", "admixture", "plots")

# FOR ROH/SMCPP:
k8 <- 
  get_Q(K = 8) %>%
  pivot_longer(starts_with("V"), names_to = "group", values_to = "Q") %>%
  group_by(SampleID) %>%
  filter(Q == max(Q, na.rm = TRUE)) 

# Confirm that group == cluster
stopifnot(all(k8$group == paste0("V", k8$cluster)))

# Filter for individuals with low max Q values (admixed individuals)
k8 %>%
  filter(Q < 0.8) 

# Filter out admixed individuals
k8_filter <- 
  k8 %>%
  filter(Q > 0.8) 

# Count individuals per population
pop_count <-
  k8_filter %>%
  group_by(cluster) %>%
  summarize(n = n(), .groups = "drop") %>%
  arrange(desc(n))
print(pop_count)

# Check that n > 10 for each population
stopifnot(all(pop_count$n > 10))

# Write out individuals for SMC++ and window calculations
# Write out individual pop assignments for Q = 8
k8_filter %>% 
  group_by(cluster) %>% 
  group_split() %>%
  iwalk(\(x, idx) write(x$SampleID, here(outpath, paste0("k8_pop", idx, ".txt"))))

# Write out distinguished individuals by taking the top 10 individuals with the highest Q values for each population
k8_filter %>%
  group_by(cluster) %>%
  arrange(desc(Q)) %>%
  slice_head(n = 10) %>%
  group_split() %>%
  iwalk(\(x, idx) write(x$SampleID, here(outpath, paste0("k8_pop", idx, "_distinguished_individuals.txt"))))
  
# Check population locations
# Read in files and bind with coords 
pop_files <- list.files(here(outpath), full.names = TRUE, pattern = "k8")
coords <- get_coords(all = TRUE)
pop_df <- 
  map(pop_files, ~{
    pop <- read_lines(.x)
    pop_df <- tibble(SampleID = pop, pop = basename(.x) %>% gsub(".txt", "", .))
    return(pop_df)
  }) %>%
  bind_rows() %>%
  left_join(coords, by = "SampleID") %>%
  st_as_sf(coords = c("x", "y")) %>%
  st_set_crs(st_crs(4326))

pdf(here(plotpath, "pop_locations.pdf"), width = 10, height = 10)
ggplot(pop_df) +
  geom_sf(aes(col = pop))
dev.off()
```
