
```{r}
library("rpaleoclim")
library("here")
library("tidyverse")
library("ggpubr")
library("terra")
library("sf")
library("gridExtra")
library("rpaleoclim")
source("general_functions.R")
source(here("analysis", "genetic_diversity", "genetic_diversity.R"))
source(here("analysis", "sdm", "paleovars.R"))
ca <- get_ca()
pdfpath <- here("analysis", "sdm", "pdfs")

coords <- get_coords()
het <- get_het()
dem <- get_dem(r= TRUE)
```

# Hypothesis 1: Genetic diversity explained by geography of range expansion
Get ecoregions:
```{r}
ecol3 <- st_read(here("data", "env", "ecoregions", "ca_eco_l3.shp")) %>% st_transform(crs = 3310)
ecol4 <- st_read(here("data", "env", "ecoregions", "ca_eco_l4.shp")) %>% st_transform(crs = 3310)
ecol30 <- st_read(here("data", "env", "ecoregions", "ACE_Ecoregions_BaileyDerived_2022.shp")) %>% st_transform(crs = 3310)

ggplot() + geom_sf(data = ecol3, aes(fill = US_L3NAME)) 
ggplot() + geom_sf(data = ecol4, aes(fill = US_L4CODE)) +theme(legend.position = "none")
ggplot() + geom_sf(data = ecol30, aes(fill = ECOREGION_))
```
wget https://gis.data.cnra.ca.gov/api/download/v1/items/d5ab2f9c5f7c45e682fd7e9a6ba8ad59/shapefile?layers=0

wget https://gaftp.epa.gov/EPADataCommons/ORD/Ecoregions/ca/ca_eco_l3.zip

wget https://gaftp.epa.gov/EPADataCommons/ORD/Ecoregions/ca/ca_eco_l4.zip

Ecoregions: https://www.epa.gov/eco-research/ecoregion-download-files-state-region-9#pane-04

Making resistance layer based on elevation + removing central valley
```{r}
# Higher elevation = higher resistance = lower connectivity
# rescale dem from 0 to 1
ca <- get_ca()

coords_sf <- get_coords(sf = TRUE)

coords_sf_buffer <- st_buffer(coords_sf, 50000)

dem <- elevatr::get_elev_raster(coords_sf_buffer, z = 5)

dem <- crop(dem, coords_sf_buffer)

dem[dem < 0] <- NA

# Plot the result
plot(dem, zlim = c(0,4000))
points(coords_sf)

dem <- rast(dem)

minr <- global(dem, "min", na.rm = TRUE)[,1]
maxr <- global(dem, "max", na.rm = TRUE)[,1]
dem01 <- (dem - minr) / (maxr - minr)

connectivity <- 1 - dem01

plot(connectivity)
points(coords_sf)
# INVERSE IS WEIRD FIGURE OUT LAYER

valley <- ecol3 %>% filter(US_L3NAME == "Central California Valley") %>% st_transform(st_crs(dem))
connectivity_mask <- mask(connectivity, valley, inverse = TRUE) 
connectivity_mask[is.na(connectivity_mask)] <- global(connectivity, "min", na.rm = TRUE)[,1]
connectivity_mask <- mask(connectivity_mask, dem)
connectivity_mask <- project(connectivity_mask, "EPSG:3310")
coords_sf <- st_transform(get_coords(sf =TRUE), "EPSG:3310")
plot(connectivity_mask)
points(coords_sf)

# Calculate resistance distance
# COME BACK AND COMPARE TO BIO2 AND EACH OTHER
lyr <- aggregate(connectivity_mask, 6, fun = mean, na.rm = TRUE)
plot(lyr, col = viridis::inferno(100))
# we know the central valley was a barrier
#lyr <- aggregate(connectivity, 5, fun = mean, na.rm = TRUE)

# convert coords to matrix and rename
coords_mat <- 
  get_coords(sf = TRUE) %>% 
  st_transform(crs = st_crs(lyr)) %>% 
  st_coordinates() %>% 
  as.matrix()

# create transition surface
trSurface <- gdistance::transition(raster::raster(lyr), transitionFunction = mean, directions = 8)

# note: type = "c" is for least cost distances
trSurface <- gdistance::geoCorrection(trSurface, type = "c", scl = FALSE)

# plot transition surface
plot(raster::raster(trSurface), col = viridis::inferno(100))

# NOTE: If you get an out of bounds error that means you have coordinates on the edge, increase the edge aroudn your raster (buffer it)
resdist <- as.matrix(gdistance::commuteDistance(trSurface, coords_mat))

# Get southern-most point
southern_point <- which(coords_mat[,2] == min(coords_mat[,2]))

# Get the resistance distance from the southern-most point to all other points
southern_resdist <- resdist[southern_point,]

# Get the geographic distance from the southern-most point to all other points
southern_dist <- as.vector(st_distance(coords_sf[southern_point,], coords_sf))

df <- 
  get_coords(sf = TRUE) %>%
  mutate(resdist = southern_resdist, geodist = southern_dist) %>% 
  # remove channel islands
  filter(resdist != min(resdist, na.rm = TRUE)) %>%
  # and weird northern point (could be a mistake)
  filter(resdist != max(resdist, na.rm = TRUE)) %>%
  left_join(get_het()) %>%
  pivot_longer(c(resdist, geodist), names_to = "distance_type", values_to = "distance") %>%
  mutate(distance_type = case_when(
    distance_type == "resdist" ~ "B. Resistance distance",
    distance_type == "geodist" ~ "A. Geographic distance"
  ))

ggplot(df) +
  geom_sf(aes(color = resdist)) +
  theme_minimal() + 
  scale_color_viridis_c(option = "plasma")

ggplot(df, aes(x = distance, y = Ho)) +
  geom_point() + 
  theme_classic() +
  labs(x = "Distance from southern-most point", y = "Ho") +
  facet_wrap(~distance_type, scales = "free_x") +
  # add correlation
  geom_smooth(method = "lm", se = TRUE) +
  stat_regline_equation(
        aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
        formula = y ~ x
      ) +
  stat_cor(label.y = 0) +
  theme(strip.background = element_blank(), strip.text.x = element_text(hjust = 0, size = 12))

# AIC TEST AGAIN BIO2 DIF
# I mean it is def not as good a fit, but that could be because I didn't parameterize resistance correctly or somethign
```

# Hypothesis 2: Genetic diversity explained by paleoclimate

```{r}
# Get paleoclimate data
# Created using paleoclimate.Rmd
paleovars <- rast(here("data", "env", "paleoclim", "paleoclim.tif"))

# Select current, late holocene, LGM, and LIG
paleovars <- 
bio2_dif <- paleovars$cur_bio_2 - paleovars$lh_bio_2
bio2_dif_vals <- terra::extract(bio2_dif, coords, ID = FALSE)[,1]
bio2_dif_df <- data.frame(SampleID = coords$SampleID, bio2_dif = bio2_dif_vals)

```

# FULL MODELS
```{r}
library(terra)
library(sf)
library(here)
library(tidyverse)
source(here("general_functions.R"))
source(here("analysis", "genetic_diversity", "genetic_diversity.R"))
coords <- get_coords(sf = TRUE)
# LOOK INTO: If you use bio1 dif instead of bio2 dif the model is super different (correlations)
source(here("analysis", "sdm", "paleovars.R"))
paleovars <- rast(here("data", "env", "paleoclim", "paleoclim.tif"))
bio2_dif <- paleovars$cur_bio_2 - paleovars$lh_bio_2
bio2_dif_vals <- terra::extract(bio2_dif, coords, ID = FALSE)[,1]
bio2_dif_df <- data.frame(SampleID = coords$SampleID, bio2_dif = bio2_dif_vals)

env_data <- rast(here("data", "env", "california_env_stack.tif"))
env_vals <- data.frame(terra::extract(env_data, coords, ID = FALSE))
env_vals$SampleID <- coords$SampleID

csi_past <- rast(here("data", "env", "stability", "Layers", "past", "csi_past.tif"))
csi_vals <- data.frame(csi = terra::extract(csi_past, coords, ID = FALSE)[,1])
csi_vals$SampleID <- coords$SampleID

q <- read_csv(here("analysis", "admixture", "outputs", "Q6.csv"))
q <- 
  q %>%
  # only keep the pop group corresponding to the cluster
  mutate(PopGroup = as.numeric(gsub("V", "", PopGroup))) %>%
  filter(cluster == PopGroup) %>%
  dplyr::select(SampleID, Q)


dem <- get_dem()

mod_df <- 
  get_coords() %>% 
  left_join(get_het()) %>%
  left_join(get_roh()) %>%
  left_join(env_vals) %>%
  left_join(bio2_dif_df) %>%
  left_join(dem) %>%
  left_join(q) %>%
  left_join(csi_vals) %>%
  mutate(BurnDate = BurnDate > 0) %>%
  drop_na(Ho, BurnDate, NDVI, gHM, bio2_dif, elev, CHELSA_bio1_1981.2010_V.2.1, Q, csi)

mod_sf <- st_as_sf(mod_df)
ggplot(mod_sf) +
  geom_sf(aes(col = BurnDate))

cor(mod_df[,c("NDVI", "gHM", "CHELSA_bio1_1981.2010_V.2.1", "elev", "BurnDate", "bio2_dif", "Q", "csi")], use = "pairwise.complete.obs")

# with Q
summary(lm(Ho ~ BurnDate + NDVI + gHM + CHELSA_bio1_1981.2010_V.2.1 + bio2_dif + elev + Q + csi, data = mod_df))

# without Q
summary(lm(Ho ~ BurnDate + NDVI + gHM + CHELSA_bio1_1981.2010_V.2.1 + bio2_dif + elev + csi, data = mod_df))

# Note how Q is predicted by BurnDateTRUE/CHELSA_bio1_1981.2010_V.2.1 which are the variables that drop out in the with Q model
summary(lm(Q ~ BurnDate + NDVI + gHM + CHELSA_bio1_1981.2010_V.2.1 + bio2_dif + elev + csi, data = mod_df))
# therefore, I don't think Q should be a predictor variable, but I think it is circular (already a measure of genetic variation)
# we may want to add Q models however to get models of predicted admixture


plot(mod_df$gHM, mod_df$Ho)
plot(mod_df$BurnDate, mod_df$Ho)
plot(mod_df$CHELSA_bio1_1981.2010_V.2.1, mod_df$Ho)

ggplot(mod_df,aes(x = BurnDate, y = Ho)) +
  geom_boxplot() +
  geom_jitter(width = 0.1) +
  theme_classic()
 
ggplot(st_as_sf(mod_df)) +
  geom_sf(aes(col = BurnDate)) 
  
```