---
title: "Genetic diversity"
output:
  github_document:
    toc: TRUE
---

```{r, include = FALSE}
library(here)
library(tidyverse)
library(sf)
library(terra)
library(ggpubr)
library(algatr)
library(viridis)
library(tigris)
library(raster)
library(igraph)
library(sp)
library(gridExtra)
library(wingen)
devtools::load_all()

# Set global options for caching
knitr::opts_chunk$set(
  cache = TRUE,
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  result = FALSE
)

source(here("analysis", "genetic_diversity", "functions_genetic_diversity.R"))
source(here("general_functions.R"))
plotpath <- here("analysis", "genetic_diversity", "plots")
```

```{r, echo = FALSE, message = FALSE, include=FALSE}
# Load the U.S. state boundaries data
ca <- get_ca()
coords <- get_coords(sf = TRUE)
```

# Dosage
```{r heterozygosity, fig.width = 7, fig.height = 7}
# get dosage data
dos <- read_table(here("analysis", "genetic_diversity", "outputs", "thinned.raw"))
dosmat <- dos %>% dplyr::select(-FID, -PAT, - MAT, -SEX, -PHENOTYPE) %>% rename(SampleID = IID)

# Combine coords and dosage data
coords <- 
  left_join(coords, dosmat, by = "SampleID")
```

```{r heterozygosity window, fig.width = 7, fig.height = 7, eval = FALSE}
# Project coordinates and boundary to equal area projection (California Albers)
coords_proj <- st_transform(coords, 3310)
ca_proj <- st_transform(ca, 3310)

# Convert coordinates to a raster layer
lyr <- coords_to_raster(coords_proj, buffer = 10, res = 5000)

pdf(here(plotpath, "preview_wingen.pdf"), width = 7, height = 7)
sc <- preview_gd(lyr, coords_proj, wdim = 5, sample_count = TRUE)
sc[sc <= 0] <- NA
plot(sc)
dev.off()

# Calculate windowed mean of Ho
het <- coords_proj %>% dplyr::select(starts_with("chr")) %>% st_drop_geometry()
het[het == 2] <- 0 # Convert to heterozygosity

future::plan(future::multisession, workers = 8)
distmat <- get_geodist(coords_proj, lyr = lyr)
window_Ho <- map(c(1000, 5000, 10000, 50000), ~circle_general(het, coords = coords_proj, lyr = lyr, distmat = distmat, maxdist = .x, min_n = 0, stat = "Ho"), .progress = TRUE)
future::plan(future::sequential)

pdf(here(plotpath, "preview_wingen_windowed.pdf"), width = 21, height = 7)
walk(window_Ho, plot_gd)
dev.off()

mod_df <- read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv"))
mod_sf <- 
  get_coords(sf = TRUE) %>% 
  right_join(mod_df) %>% 
  st_transform(3310)

# GLS can't handle 0 distances, so take the average of the coordinates
mod_vars <- c("NDVI", "gHM", "csi_past", "glacier", "Q", "tmean_dif", "bio1")
mod_sf_unique <- 
  mod_sf %>%
  group_by(x, y) %>%
  summarise_at(c(mod_vars, "Ho"), mean, na.rm = TRUE) %>%
  ungroup()

# Scale data
mod_sf_unique_scaled <-
  mod_sf_unique %>%
  mutate(
    across(
      all_of(setdiff(mod_vars, "glacier")),
      ~ as.numeric(scale(.x))   # <- drop matrix
    )
  )

# Confirm that all glacier values are 0 and 1
stopifnot(all(mod_sf_unique_scaled$glacier %in% c(0, 1)))

# Convert glacier to factor
mod_sf_unique_scaled$glacier_factor <- as.factor(mod_sf_unique$glacier)
mod_sf_unique$glacier_factor <- as.factor(mod_sf_unique$glacier)

f <- formula("Ho ~ NDVI + gHM + glacier_factor + csi_past + Q + tmean_dif + bio1")
final_model <- gls(f, correlation = corExp(form = ~ x + y, nugget = FALSE), data = mod_sf_unique_scaled)
summary(final_model)$tTable %>% 
  as.data.frame() %>% 
  mutate(term = rownames(.)) %>% 
  filter(`p-value` < 0.05 & term != "(Intercept)")

fit_lm <- function(x, mod_sf_unique_scaled){
  vals <- extract(x, mod_sf_unique_scaled)[,"custom"]
  mod_sf_unique_scaled$Ho_wingen <- vals

  # Create formula
  f <- formula("Ho_wingen ~ NDVI + gHM + glacier_factor + csi_past + Q + tmean_dif + bio1")

  # Fit model
  library(nlme)
  final_model <-  lm(f, data = mod_sf_unique_scaled)

  # Results
  mod_result <- summary(final_model)
  mod_result

  # Extract coefficients and stats
  coef_table <- broom::tidy(mod_result)

  return(coef_table)
}

fit_gls <- function(x, mod_sf_unique_scaled){
  vals <- extract(x, mod_sf_unique_scaled)[,"custom"]
  mod_sf_unique_scaled$Ho_wingen <- vals

  # Create formula
  # NOTE: adding glacier makes ghm ns
  f <- formula("Ho_wingen ~ NDVI + gHM + glacier_factor + csi_past + Q + tmean_dif + bio1")

  # Fit model
  library(nlme)
  safe_gls <- purrr::safely(gls)
  final_model <- safe_gls(f, correlation = corExp(form = ~ x + y, nugget = FALSE), data = mod_sf_unique_scaled)
  if(!is.null(final_model$error)) {
    warning("GLS model failed to converge. Returning NULL.")
    return(NULL)
  }
  final_model <- final_model$result

  # Results
  mod_result <- summary(final_model)
  mod_result

  # Extract coefficients and stats
  coef_table <- as.data.frame(mod_result$tTable)

  # Add variable names as a column
  coef_table$term <- rownames(coef_table)
  rownames(coef_table) <- NULL

  return(coef_table)
}

results_lm <- map(window_Ho, ~fit_lm(.x, mod_sf_unique_scaled = mod_sf_unique_scaled))

sig_vars <- map(results_lm, ~filter(.x, `p.value` < 0.05 & term != "(Intercept)"))
sig_vars

results_gls <- map(window_Ho, ~fit_gls(.x, mod_sf_unique_scaled = mod_sf_unique_scaled))

sig_vars_gls <- map(compact(results_gls), ~filter(.x, `p-value` < 0.05 & term != "(Intercept)"))
sig_vars_gls

```
