---
title: "Genetic diversity"
output:
  github_document:
    toc: TRUE
---

```{r, include = FALSE}
library(here)
library(tidyverse)
library(sf)
library(terra)
library(ggpubr)
library(algatr)
library(viridis)
library(tigris)
library(raster)
library(igraph)
library(sp)
library(gridExtra)
library(wingen)
devtools::load_all()

# Set global options for caching
knitr::opts_chunk$set(
  cache = TRUE,
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  result = FALSE
)

source(here("analysis", "genetic_diversity", "functions_genetic_diversity.R"))
source(here("general_functions.R"))
plotpath <- here("analysis", "genetic_diversity", "plots")
```

```{r, echo = FALSE, message = FALSE, include=FALSE}
# Load the U.S. state boundaries data
ca <- get_ca()
dem <- get_dem()
coords <- get_coords(sf = TRUE)
```


# Heterozygosity
```{r heterozygosity, fig.width = 7, fig.height = 7}
# get het data
het <- get_het()

# Combine coords and het data
coords <- 
  left_join(coords, het, by = "SampleID") %>% 
  drop_na(Ho)
```

```{r heterozygosity window, fig.width = 7, fig.height = 7, eval = FALSE}
# Project coordinates and boundary to equal area projection (California Albers)
coords_proj <- st_transform(coords, 3310)
ca_proj <- st_transform(ca, 3310)

# Convert coordinates to a raster layer
lyr <- coords_to_raster(coords_proj, buffer = 10, res = 10000)

pdf(here(plotpath, "preview_wingen.pdf"), width = 7, height = 7)
sc <- preview_gd(lyr, coords_proj, wdim = 5, sample_count = TRUE)
sc[sc <= 0] <- NA
plot(sc)
dev.off()

# Calculate windowed mean of Ho
custom_mean <- function(x) mean(x, na.rm = TRUE)
window_Ho <- window_general(coords_proj$Ho, coords = coords_proj, lyr = lyr, wdim = 5, min_n = 1, stat = custom_mean)

names(window_Ho) <- c("Ho", "sample_count")
writeRaster(window_Ho, here(outpath, "wingen.tif"), overwrite = TRUE)

# Perform kriging interpolation on windowed mean of Ho
weighted_results <- krig_gd2(window_Ho[[1]], window_Ho[[2]])
weighted_krig_Ho <- weighted_results$prediction
unweighted_krig_Ho <- krig_gd2(window_Ho[[1]])
unweighted_krig_Ho <- unweighted_krig_Ho$prediction

# Apply a mask to the kriging result
range_map <- get_range()
weighted_mask_Ho <- mask(weighted_krig_Ho, range_map)
unweighted_mask_Ho <- mask(unweighted_krig_Ho, range_map)

# Plot results# Adjusted color function with dynamic limits
col_function <- function(values, extend_scale = 0.1) {
  # Get min and max from data
  r_min <- min(values, na.rm = TRUE)
  r_max <- max(values, na.rm = TRUE)
  
  # Extend the limits based on the extend_scale
  # This will extend the range by a percentage of the original range
  extended_max <- r_max + (r_max - r_min) * extend_scale
  extended_min <- r_min - (r_max - r_min) * extend_scale
  # Get the max of each so it is an even scale
  limits <- c(extended_min, extended_max)

  scale_fill_gradientn(
    colors = rev(MetBrewer::met.brewer("Hiroshige", type = "continuous")),
    limits = limits,
    oob = scales::squish  # Squeeze outliers into color scale range
  )
}

# Adjusted custom_plot() to use dynamic col_function
custom_plot <- function(r, coords = NULL, extend_scale = 0.1) {
  r_df <- as.data.frame(r, xy = TRUE, na.rm = TRUE)
  names(r_df)[3] <- "layer"
  
  plt <- ggplot(r_df) +
    geom_sf(data = ca_proj, fill = "gray90", col = NA) +
    geom_tile(aes(x = x, y = y, fill = layer), color = NA) +
    col_function(r_df$layer, extend_scale = extend_scale) +
    labs(fill = "Heterozygosity") +
    theme_void()
  
  if (!is.null(coords)) {
    plt <- plt + geom_sf(data = coords_proj, pch = 21, aes(fill = Ho), col = "#00000087", cex = 1.1)
  }
  
  return(plt)
}


window_Ho2 <- mask_gd(window_Ho[[1]], window_Ho[[2]], minval = 2)
pdf(here(plotpath, "wingen.pdf"), width = 5, height = 5)
custom_plot(weighted_mask_Ho)
custom_plot(unweighted_mask_Ho)
custom_plot(window_Ho) 
custom_plot(window_Ho2)
custom_plot(weighted_mask_Ho, coords = coords_proj)
custom_plot(window_Ho, coords = coords_proj)
dev.off()

names(weighted_mask_Ho) <- "Ho"
writeRaster(weighted_mask_Ho, here(outpath, "Ho_kriged_masked.tif"), overwrite = TRUE)
```

# ROH
```{r ROH, fig.width = 7, fig.height = 7}
roh <- get_roh()

ggplot(roh) +
 geom_sf(data = ca) +
 geom_sf(aes(geometry = geometry, fill = froh), col = "#00000087", pch = 21, cex = 2.5) +
 scale_fill_viridis_c(option = "inferno", labels = scales::label_number(scale = 1, accuracy = 0.001)) +
 theme_void()

ggplot(roh) +
 geom_sf(data = ca) +
 geom_sf(aes(geometry = geometry, fill = log(froh + 1e-6)), col = "#00000087", pch = 21, cex = 2.5) +
 scale_fill_viridis_c(option = "inferno", labels = scales::label_number(scale = 1, accuracy = 0.001)) +
 theme_void()

ggplot(roh) +
 geom_sf(data = ca) +
 geom_sf(aes(geometry = geometry, fill = froh0), col = "#00000087", pch = 21, cex = 2.5) +
 scale_fill_viridis_c(option = "inferno", labels = scales::label_number(scale = 1, accuracy = 0.001)) +
 labs(fill = "FROH") +
 theme_void()

ggplot(roh) +
 geom_sf(data = ca) +
 geom_sf(aes(geometry = geometry, fill = log(froh0 + 1e-6)), col = "#00000087", pch = 21, cex = 2.5) +
 scale_fill_viridis_c(option = "inferno", labels = scales::label_number(scale = 1, accuracy = 0.001)) +
 labs(fill = "log(FROH + 1e-6)") +
 theme_void()

ggplot(roh) +
 geom_sf(data = ca) +
 geom_sf(aes(geometry = geometry, col = pop), cex = 2.5) +
 theme_void()

ggplot(roh) +
 geom_sf(data = ca) +
 geom_raster(data = dem, aes(x = x, y = y, fill = elev)) + 
 geom_sf(aes(geometry = geometry, col = log(froh + 1e-6)), pch = 16, cex = 2.5) +
 scale_color_viridis_c(option = "inferno", labels = scales::label_number(scale = 1, accuracy = 0.001)) +
 scale_fill_gradient(low = "gray40", high = "white", na.value = NA) +
 theme_void()

```


```{r roh window, fig.width = 7, fig.height = 7, eval = FALSE}
# project roh 
coords_proj <- roh %>% st_as_sf() %>% st_transform(3310)

# Calculate windowed mean of froh
window_froh <- window_general(coords_proj$froh0, coords = coords_proj, lyr = lyr, wdim = 9, stat = mean, na.rm = TRUE)

# Plot windowed mean of froh
ggplot_gd(window_froh, bkg = ca_proj, col = magma(100))

# Perform kriging interpolation on windowed mean of froh
krig_froh <- krig_gd(window_froh, grd = lyr, disagg_grd = 2)

# Apply a mask to the kriging result
count_mask <- resample(window_froh$sample_count, krig_froh)
mask_froh <- mask_gd(krig_froh, ca_proj)
#mask_froh <- mask_gd(mask_froh, count_mask, minval = 1)

# Plot masked kriging result
ggplot_gd(mask_froh, bkg = ca_proj, col = magma(100))
```