```{r}
library(tidyverse)
library(here)
source(here("general_functions.R"))
source(here("analysis", "genetic_diversity", "functions_genetic_diversity.R"))
plotpath <- here("analysis", "genetic_diversity", "plots")
outpath <- here("analysis", "genetic_diversity", "outputs")

# Read in heterozygosity files
nonsyn_het <- 
  get_het("allnonsyn.het") %>%
  mutate(Ho_nonsyn = 1 - `O(HOM)`/`N(NM)`) %>%
  select(SampleID, Ho_nonsyn)
syn_het <-
  get_het("allsyn.het") %>%
  mutate(Ho_syn = 1 - `O(HOM)`/`N(NM)`) %>%
  select(SampleID, Ho_syn)
geanonsyn_het <-
  get_het("nonsyn.het") %>%
  mutate(Ho_geanonsyn = 1 - `O(HOM)`/`N(NM)`) %>%
  select(SampleID, Ho_geanonsyn)

het_df <- 
  get_het("58-Sceloporus_chr.het") 

het_df <- left_join(het_df, nonsyn_het) %>% left_join(geanonsyn_het) %>% left_join(syn_het) %>% 
# Scale
  mutate(
    Ho_scaled = as.numeric(scale(Ho)),
    Ho_nonsyn_scaled = as.numeric(scale(Ho_nonsyn)),
    Ho_geanonsyn_scaled = as.numeric(scale(Ho_geanonsyn)),
    Ho_syn_scaled = as.numeric(scale(Ho_syn)))


```

```{r}
library(terra)
library(sf)
model_df <- read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv"))
future <- rast(here("analysis", "gea", "outputs", "scelop_adaptive_env_layers","env_fut_2071-2100_GFDL-ESM4_ssp126_ssp585.tif"))[[2]]
names(future)
current <- rast(here("data", "env", "california_chelsa_bioclim_1981-2010_V.2.1.tif"))[["CHELSA_bio1_1981-2010_V.2.1"]]
coords <- get_coords(sf = TRUE)
df <- left_join(coords, het_df, by = "SampleID")
df$future_bio1 <- extract(future, df, ID = FALSE, method = "bilinear")[,1]
df$current_bio1 <- extract(current, df, ID = FALSE, method = "bilinear")[,1]
df$future_change <- df$future_bio1 - df$current_bio1

model_df <- left_join(model_df, df %>% st_drop_geometry() %>% dplyr::select(SampleID, future_change, current_bio1, Ho_nonsyn), by = "SampleID")
names(model_df)
```

```{r}
# COME BACK AND USE MOD_SF_UNIQUE
nonsyn_model_df <-
  model_df %>%
  mutate(
    glacier = factor(glacier, levels = c("OutsideGlacier", "InsideGlacier")),
    fire_recent = factor(fire_recent, levels = c("Unburned", "Burned")),
    fire_frq = factor(fire_frq, levels = c("Infrequent/No Fire Regime", "Intermediate Frequency", "High Frequency")),
    evt = relevel(as.factor(evt), ref = "Shrubland")
  )

numeric_vars <- c("csi_past", "tmean_dif", "bio1")
nonsyn_model_df_scaled <-
  nonsyn_model_df %>%
  mutate(across(all_of(numeric_vars), ~as.numeric(scale(.x))))

model_nonsyn <- lm(Ho_nonsyn ~ poly(csi_past, 2, raw = TRUE) + tmean_dif + bio1 + fire_frq*fire_recent + evt, data = nonsyn_model_df_scaled)
summary(model_nonsyn)

car::Anova(model_nonsyn)

emmeans(model_nonsyn, ~ fire_recent | fire_frq) %>% pairs(infer = TRUE)
emmeans(model_nonsyn, ~ fire_frq) %>% pairs(infer = TRUE)
emmeans(model_nonsyn, ~ evt) %>% pairs(infer = TRUE) %>% data.frame() %>% filter(p.value < 0.05)
```

```{r}
wingen_r <- 
  terra::rast(here(outpath, "Ho_nonsyn_kriged_masked.tif")) %>% 
  as.data.frame(xy = TRUE, na.rm = TRUE) 
names(wingen_r)[3] <- "layer"  # ensure 'layer' is the raster value column

ca_proj <- get_ca() %>% st_transform(3310)


scale_met_cont <- function(values, aesthetic = c("fill", "colour"), extend_scale = 0.1) {
  aesthetic <- match.arg(aesthetic)
  r_min <- min(values, na.rm = TRUE)
  r_max <- max(values, na.rm = TRUE)
  rng   <- r_max - r_min
  lims  <- c(r_min - rng*extend_scale, r_max + rng*extend_scale)

  pal <- rev(MetBrewer::met.brewer("Hiroshige", type = "continuous"))
  if (aesthetic == "fill") {
    ggplot2::scale_fill_gradientn(colors = pal, limits = lims, oob = scales::squish)
  } else {
    ggplot2::scale_colour_gradientn(colors = pal, limits = lims, oob = scales::squish)
  }
}
```

```{r}
library(ggpubr)
model_sf <- left_join(get_coords(sf = TRUE), model_df)
# A: wingen map of heterozygosity 
pltA <- 
  ggplot(wingen_r) +
  geom_sf(data = ca_proj, fill = "gray90", colour = NA, size = 2) +
  geom_tile(aes(x = x, y = y, fill = layer), colour = NA) +
  scale_met_cont(c(model_df$Ho_nonsyn, wingen_r$layer), aesthetic = "fill", extend_scale = 0.1) +
  labs(fill = "Non-synonymous\nheterozygosity") +
  theme_void() +
  geom_sf(data = model_sf, shape = 21, aes(fill = Ho_nonsyn), colour = "#00000087", size = 2) +
  theme(
    plot.margin = margin(1, 1, 1, 1, unit = "mm"),
    legend.position = "right",
    legend.key.height = unit(0.7, "cm"),
    legend.key.width  = unit(0.7, "cm"),
    legend.title = element_text(size = 16),
    legend.text  = element_text(size = 14),
    plot.margin = margin(5,5,5,25)
  )


# B: Predicted vs observed values for non-synonymous Ho
pltB <-
  ggplot(model_df, aes(x = predict(model_nonsyn), y = Ho_nonsyn)) +
  geom_point(aes(col = Ho_nonsyn), shape = 16, size = 2) +
  geom_smooth(method = "lm", colour = "black") +
  scale_met_cont(c(model_df$Ho_nonsyn, wingen_r$layer), aesthetic = "colour", extend_scale = 0.1) +
  theme_classic() +
  labs(x = "Predicted non-synonymous heterozygosity", y = "Observed non-synonymous heterozygosity", col = "Non-synonymous\nheterozygosity") +
  ggpubr::stat_cor(size = 6) +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 16),
    axis.text  = element_text(size = 14),
    plot.margin = margin(5,5,5,25)
  )

# C: Plot of non-syn vs genome-wide Ho
pltC <- 
  ggplot(df, aes(x = Ho, y = Ho_nonsyn)) +
  geom_point(size = 2, aes(col = future_change)) +
  geom_smooth(method = "lm", col = "black") +
  ggpubr::stat_cor(method = "pearson", size = 6) +
  scale_color_viridis_c(option = "plasma") +
  labs(
    x = "Genome-wide heterozygosity",
    y = "Non-synonymous heterozygosity",
    col = "Future\nclimate\nchange"
  ) +
  theme_classic() +
  theme(
    plot.margin = margin(1, 1, 1, 1, unit = "mm"),
    legend.position = "right",
    legend.key.height = unit(0.8, "cm"),
    legend.key.width  = unit(0.8, "cm"),
    legend.title = element_text(size = 16),
    legend.text  = element_text(size = 14),
    axis.title = element_text(size = 16),
    axis.text  = element_text(size = 14),
    plot.margin = margin(5,5,5,25)
  )

# Plot of future-change vs non-syn Ho
pltD <- 
  ggplot(df, aes(x = future_change, y = Ho_nonsyn, color = future_change)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", col = "black") +
  ggpubr::stat_cor(method = "pearson", size = 6) +
  labs(x = "Future climate change",
       y = "Non-synonymous heterozygosity", col = "Future\nclimate\nchange") +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.title = element_text(size = 16),
    axis.text  = element_text(size = 14),
    plot.margin = margin(5,5,5,25)
  ) +
  scale_color_viridis_c(option = "plasma")
#hiroshige_cols <- rev(c("#042346", "#295580", "#6bb2cc", "#9cd3dd", "#fecd6d", "#f7a957", "#ec7b4c", "#f04f32"))

# extract legends
legA <- cowplot::get_legend(pltA + theme(legend.position = "right"))
legC <- cowplot::get_legend(pltC + theme(legend.position = "right"))

# drop legends from panels
pltA_noleg <- pltA + theme(legend.position = "none")
pltC_noleg <- pltC + theme(legend.position = "none")

# rows: (A, B, legendA) and (C, D, legendC)
row1 <- cowplot::plot_grid(pltA_noleg, pltB, nrow = 1, align = "hv", labels = c("A", "B"), label_size = 18)
row2 <- cowplot::plot_grid(pltC_noleg, pltD, nrow = 1, align = "hv", labels = c("C", "D"), label_size = 18)
legends <- cowplot::plot_grid(legA, legC, ncol = 1, align = "v")
rows <- cowplot::plot_grid(row1, row2, ncol = 1, align = "v")
final <- cowplot::plot_grid(
  rows, legends,
  ncol = 2,
  rel_widths = c(1, 0.25),
  align = "hv"
)

png(here(plotpath, "nonsyn_vs_het_vs_climate_change.png"),
    width = 11.5, height = 9.5, units = "in", res = 300)
final
dev.off()
```


```{r}
# Plot all variables
all_vars <- c("csi_past", "tmean_dif", "bio1", "fire_frq", "fire_recent", "fire_frq", "glacier", "gHM", "evt")
interact <- rep(TRUE, length(all_vars))
interact[4] <- FALSE

new_df_scaled <- nonsyn_model_df_scaled %>% dplyr::select(Ho = Ho_nonsyn, all_of(all_vars))
new_df <- nonsyn_model_df %>% dplyr::select(Ho = Ho_nonsyn, all_of(all_vars))
final_model_nonsyn <- lm(Ho ~ poly(csi_past, 2, raw = TRUE) + tmean_dif + bio1 + fire_frq * fire_recent + glacier + gHM + evt, data = new_df_scaled)
summary(final_model_nonsyn)
# Partial residuals 
plts_residual_y <- 
  purrr::map2(
    all_vars,
    interact,
    # Use unscaled data for plotting
    ~plot_mod(.x, "Ho", new_df, model = final_model_nonsyn, col_var = "Ho_original", residual = TRUE, interact = .y)
  ) %>% 
  map(~ .x + theme(plot.margin = margin(10, 10, 10, 25))) %>%
  map(~ .x + ylab("Residual non-synonymous heterozygosity"))

# B: Raw values
plts_raw_y <- 
  purrr::map2(
    all_vars,
    interact, 
    # Use unscaled data for plotting
    ~plot_mod(.x, "Ho", new_df, model = final_model_nonsyn, col_var = "Ho_original", residual = FALSE, bump_legend = 0.1, interact = .y)
  ) %>% 
  map(~ .x + theme(plot.margin = margin(10, 10, 10, 25))) %>%
  map(~ .x + ylab("Observed non-synonymous heterozygosity"))

plt_residual <- cowplot::plot_grid(plotlist = plts_residual_y, ncol = 3, align = "v", labels = LETTERS[1:length(plts_residual_y)], label_size = 18, rel_widths = 1)

plt_raw <- cowplot::plot_grid(plotlist = plts_raw_y, ncol = 3, align = "v", labels = LETTERS[1:length(plts_raw_y)], label_size = 18)

png(here(plotpath, "figure_Ho_nonsyn_allvars_residual.png"), height = 14, width = 15, res = 300, units = "in")
plt_residual
dev.off()

png(here(plotpath, "figure_Ho_nonsyn_allvars_raw.png"), height = 14, width = 15, res = 300, units = "in")
plt_raw
dev.off()
```


# old:
```{r}
pop_df <- 
  read_csv(here("analysis", "admixture", "outputs", "Q8.csv")) %>% 
  distinct(cluster, SampleID) %>%
  mutate(cluster = as.factor(cluster))
mod_df <- 
  left_join(het_df, read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv")), by = "SampleID") %>%
  left_join(pop_df) 

# Confirm Ho.x == Ho from het_df (need to do tolerance due to floating point issues)
isTRUE(all.equal(mod_df$Ho.x, mod_df$Ho.y, tolerance = 1e-10))
mod_df$Ho <- mod_df$Ho.x
```

```{r}

mod_df_unique <- 
  mod_df %>%
  st_drop_geometry() %>%
  bind_cols(st_coordinates(mod_df)) %>%
  group_by(X, Y) %>%
  mutate(cluster = as.numeric(cluster)) %>%
  summarize_at(
    vars(Ho, Ho_nonsyn, Ho_syn, tmean_dif, bio1, NDVI, glacier, csi_past, Q, gHM, cluster),
    ~mean(.x, na.rm = TRUE)
  ) %>%
  mutate(cluster = as.factor(cluster)) %>%
  ungroup() %>%
  # Scale all model variables
  mutate_at(
    vars(Ho, Ho_nonsyn, Ho_syn, tmean_dif, bio1, NDVI, glacier, csi_past, Q, gHM),
    ~as.numeric(scale(.x))
  ) 

all(!is.na(as.integer(unique(mod_df_unique$cluster))))

# Fit model
library(nlme)
Ho_mod <-  gls(Ho ~ NDVI + gHM +  csi_past + glacier + Q + tmean_dif + bio1, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = mod_df_unique)
Ho_tb <- summary(Ho_mod)$tTable %>% as.data.frame()
Ho_tb %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))

nonsyn_mod <-  gls(Ho_nonsyn ~ Ho + NDVI + gHM +  csi_past + glacier + Q + tmean_dif + bio1, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = mod_df_unique)
nonsyn_tb <- summary(nonsyn_mod)$tTable %>% as.data.frame()
nonsyn_tb %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))

nonsyn_mod_no_Ho <-  gls(Ho_nonsyn ~ NDVI + gHM +  csi_past + glacier + Q + tmean_dif + bio1, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = mod_df_unique)
nonsyn_tb_no_Ho <- summary(nonsyn_mod_no_Ho)$tTable %>% as.data.frame()
nonsyn_tb_no_Ho %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))

syn_mod <-  gls(Ho_nonsyn ~ Ho_syn + NDVI + gHM +  csi_past + glacier + Q + tmean_dif + bio1, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = mod_df_unique)
syn_mod_tb <- summary(syn_mod)$tTable %>% as.data.frame()
syn_mod_tb %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))

# Within cluster tests, not spatial model because within clusters spatial autocorrelation should be low
mod <- lm(Ho_nonsyn ~ Ho + cluster * (NDVI + gHM + csi_past + glacier + Q + tmean_dif + bio1) , data = mod_df_unique)
library(emmeans)
# get estimated slopes ("simple slopes") for each cluster
emm <- emtrends(mod, ~ cluster, var = "csi_past", infer = c(TRUE, TRUE), adjust = "fdr")
# see estimated slopes and SEs
summary(emm)

pdf(here(plotpath, "nonsyn_model.pdf")) 
ggplot(mod_df, aes(col = cluster)) +
  geom_sf()

ggplot(mod_df, aes(x = tmean_dif, y = Ho_nonsyn)) +
  geom_point() +
  geom_smooth(method = "lm") +
  ggpubr::stat_cor(method = "pearson") +
  theme_classic()

ggplot(mod_df, aes(x = tmean_dif, y = resids)) +
  geom_point(aes(color = cluster)) +
  geom_smooth(method = "lm", aes(color = cluster), se = FALSE) +
  ggpubr::stat_cor(method = "pearson") +
  theme_classic()

ggplot(mod_df, aes(x = csi_past, y = resids)) +
  geom_point() +
  geom_smooth(method = "lm") +
  ggpubr::stat_cor(method = "pearson") +
  theme_classic()
dev.off()
```

# Nice plots

```{r}
# Define a color scale function using MetBrewer with an argument to extend the scale for better visualization
scale_met_cont <- function(values, aesthetic = c("fill", "colour"), extend_scale = 0.1) {
  aesthetic <- match.arg(aesthetic)
  r_min <- min(values, na.rm = TRUE)
  r_max <- max(values, na.rm = TRUE)
  rng   <- r_max - r_min
  lims  <- c(r_min - rng*extend_scale, r_max + rng*extend_scale)

  pal <- rev(MetBrewer::met.brewer("Hiroshige", type = "continuous"))
  if (aesthetic == "fill") {
    ggplot2::scale_fill_gradientn(colors = pal, limits = lims, oob = scales::squish)
  } else {
    ggplot2::scale_colour_gradientn(colors = pal, limits = lims, oob = scales::squish)
  }
}

# Make residual plots for model
plot_mod <- function(x, y, df, model, 
                     mod_vars = c("NDVI","gHM","bio1","csi_past","glacier","tmean_dif","Q"),
                     color_var = c("x","y")) {

  # Calculate residuals for y variable given x variable
  # MAKE SURE ORIGINAL MODEL USED SCALED VARIABLES
  df[[y]] <- residuals(model) + coef(model)[[x]] * as.numeric(scale(df[[x]]))

  # Choose whether to color by x or y variable
  col_var <- if (color_var == "x") x else y

  ggplot(df, aes(x = .data[[x]], y = .data[[y]])) +
    geom_point(aes(col = .data[[col_var]])) +
    geom_smooth(method = "lm", colour = "black") +
    scale_met_cont(df[[col_var]], aesthetic = "colour", extend_scale = 0.1) +
    ggpubr::stat_cor() +
    labs(x = stringr::str_to_sentence(make_pretty_names(x)), 
      y = stringr::str_to_sentence("Residual non-synonymous heterozygosity")) +
    theme_classic() +
    theme(legend.position = "none",
          axis.title = element_text(size = 14),
          axis.text  = element_text(size = 10))

}

summary(nonsyn_mod)

resid_plots <- map(c("Ho", "tmean_dif", "csi_past", "bio1", "NDVI", "glacier"), ~plot_mod(.x, "Ho_nonsyn", mod_df_unique, nonsyn_mod, color_var = "x"))

resid_plots_no_Ho <- map(c("tmean_dif", "csi_past", "bio1", "NDVI", "glacier"), ~plot_mod(.x, "Ho_nonsyn", mod_df_unique, nonsyn_mod_no_Ho, color_var = "x"))
resid_plots_no_Ho <- c(list(NULL), resid_plots_no_Ho)  # to align with previous plots

resid_plots_Ho <- map(c("tmean_dif", "csi_past", "bio1", "NDVI", "glacier"), ~plot_mod(.x, "Ho", mod_df_unique, Ho_mod, color_var = "x"))
resid_plots_Ho <- c(list(NULL), resid_plots_Ho)  # to align with previous plots

resid_plot_syn <- map(c("Ho_syn", "tmean_dif", "csi_past", "bio1", "NDVI", "glacier"), ~plot_mod(.x, "Ho_nonsyn", mod_df_unique, syn_mod, color_var = "x"))

pdf(here(plotpath, "nonsyn_models.pdf"), width = 6*5, height = 5)
cowplot::plot_grid(plotlist = resid_plots_Ho, nrow = 1, align = "hv")
cowplot::plot_grid(plotlist = resid_plots_no_Ho, nrow = 1, align = "hv")
cowplot::plot_grid(plotlist = resid_plots, nrow = 1, align = "hv")
cowplot::plot_grid(plotlist = resid_plot_syn, nrow = 1, align = "hv")
dev.off()
```

simple plots for explaining: 

```{r}
simple_plot <- function(x, y, df){
  x_vs_y <-
    ggplot(df, aes(x = .data[[x]], y = .data[[y]])) +
    geom_point() +
    geom_smooth(method = "lm") +
    ggpubr::stat_cor() +
    labs(x = make_pretty_names(x), 
         y = make_pretty_names(y)) +
    theme_classic() +
    theme(axis.title = element_text(size = 14),
          axis.text  = element_text(size = 10))

  x_map <-
    ggplot(df) +
    geom_sf(data = get_ca()) +
    geom_sf(aes(fill = .data[[x]]), pch = 21, cex = 2) +
    scale_met_cont(df[[x]], aesthetic = "fill", extend_scale = 0.1) +
    labs(fill = gsub(" ", "\n", make_pretty_names(x))) +
    theme_void()

  y_map <-
    ggplot(df) +
    geom_sf(data = get_ca()) +
    geom_sf(aes(fill = .data[[y]]), pch = 21, cex = 2) +
    scale_met_cont(df[[y]], aesthetic = "fill", extend_scale = 0.1) +
    labs(fill = gsub(" ", "\n", make_pretty_names(y))) +
    theme_void()

  xy_maps <- cowplot::plot_grid(x_map, y_map, nrow = 1, align = "hv")
  cowplot::plot_grid(x_vs_y, xy_maps, nrow = 1, rel_widths = c(1, 2) )
}


mod_df$nonsyn_residuals <- residuals(lm(Ho_nonsyn ~ Ho, data = mod_df))

pdf(here(plotpath, "weird_nonsyn_pattern.pdf"), width = 15, height = 5)
simple_plot("Ho", "Ho_nonsyn", mod_df)
simple_plot("csi_past", "Ho", mod_df)
simple_plot("tmean_dif", "Ho", mod_df)
simple_plot("csi_past", "Ho_nonsyn", mod_df)
simple_plot("tmean_dif", "Ho_nonsyn", mod_df)
simple_plot("csi_past", "nonsyn_residuals", mod_df)
simple_plot("tmean_dif", "nonsyn_residuals", mod_df)
dev.off()
```

# Check holocene climate change
```{r}
extract_impute <- function(r, coords) {
  x <- extract(r, coords, ID = FALSE, method = "simple")[,1]
  na_vals <- which(is.na(x))
  if (length(na_vals) > 0) {
    message("Imputing ", length(na_vals), " missing values")
    new_vals <- terra::extract(r, coords[na_vals,], ID = FALSE, method = "bilinear")[,1]

    # Check if new vals are more than 1 SD greater than non-na values
    sd_x <- sd(x, na.rm = TRUE)
    mean_x <- mean(x, na.rm = TRUE)
    too_high <- which(new_vals > (mean_x + sd_x) | new_vals < (mean_x - sd_x))

    # Replace too high values with NA
    if (length(too_high) > 0) {
      message("  ", length(too_high), " imputed values were > 1 SD from mean; replacing with NA")
      new_vals[too_high] <- NA
    }

    x[na_vals] <- new_vals
  }
  return(x)
}

library(terra)
source(here("analysis", "genetic_diversity", "functions_paleovars.R"))
paleovars <- c("lig", "hs1", "ba", "yds", "eh", "mh", "lh")
paleolist <- 
  get_paleovars(paleovars) %>% 
  map(~.x[["bio_1"]])
paleovals <-
  paleolist %>% 
  map(~extract_impute(.x, mod_df_unique[,c("X", "Y")])) %>% 
  bind_cols()/10 # Convert to C

# Get current climate data (NOTE: not using paleoclim data because they use CHELSA V1.2 instead of V2.1)
bioclim <- rast(here("data", "env", "california_chelsa_bioclim_1981-2010_V.2.1.tif"))
cur <- bioclim[["CHELSA_bio1_1981-2010_V.2.1"]]
names(cur) <- "cur"

# Get LGM climate data (NOTE: not using paleoclim data because they use CHELSA V1.2 instead of V2.1)
lgm <- rast(here("data", "env", "california_chelsa_pmip_ccsm4.tif"))
names(lgm) <- "lgm"

lgm_vals <- extract_impute(lgm, mod_df_unique[,c("X", "Y")])
cur_vals <- extract_impute(cur, mod_df_unique[,c("X", "Y")])

paleo_df <- 
  mod_df_unique %>% 
  bind_cols(paleovals) %>%
  mutate(
    cur = cur_vals,
    lgm = lgm_vals
  ) %>%
  mutate(
    lig_lgm = lgm - lig,
    lgm_eh = eh - lgm,
    eh_lh = lh - eh,
    lh_cur = cur - lh
  ) %>%
  st_as_sf(coords = c("X", "Y"), crs = 4326) %>%
  st_transform(3310) %>%
  bind_cols(st_coordinates(.)) %>%
  mutate(resids = residuals(lm(Ho_nonsyn ~ Ho, data = .))) %>%
  drop_na() # Removes 2 missing values from two extreme paleoclimate values to impute

# Calculate correlations between change variables
correlations <- 
  cor(paleo_df %>% st_drop_geometry() %>% 
  select(lig_lgm, lgm_eh, eh_lh, lh_cur, tmean_dif), use = "pairwise.complete.obs")

# Get pairs greater than 0.7
high_cor_pairs <- which(abs(correlations) > 0.7 & abs(correlations) < 1, arr.ind = TRUE)
high_cor_pairs_df <- 
  as.data.frame(high_cor_pairs) %>%
  mutate(var1 = rownames(correlations)[row],
         var2 = colnames(correlations)[col],
         cor_value = correlations[high_cor_pairs]) %>%
  select(var1, var2, cor_value)
high_cor_pairs_df
unique(c(high_cor_pairs_df$var1, high_cor_pairs_df$var2))
# lgm_eh vs lig_lgm = -0.99

pdf(here(plotpath, "paleochange.pdf"), width = 15, height = 5)
simple_plot("lig_lgm", "resids", paleo_df)
simple_plot("lgm_eh", "resids", paleo_df)
simple_plot("eh_lh", "resids", paleo_df)
simple_plot("lh_cur", "resids", paleo_df)
simple_plot("tmean_dif", "resids", paleo_df)
dev.off()

# Confirm that eh_lh and tmean_dif are not highly correlated
cor.test(paleo_df$eh_lh, paleo_df$tmean_dif)
cor.test(paleo_df$lig_lgm, paleo_df$lgm_eh)
cor.test(paleo_df$eh_lh, paleo_df$lh_cur)
cor.test(paleo_df$csi_past, paleo_df$lig_lgm)

summary(lm(resids ~  eh_lh + tmean_dif, data = paleo_df)) # Both significant

Ho_paleo_mod <- 
  gls(Ho ~ lig_lgm + eh_lh + lh_cur + tmean_dif + bio1 + NDVI + gHM + glacier, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = drop_na(paleo_df))

Ho_nonsyn_paleo_mod <- 
  gls(Ho_nonsyn ~ lig_lgm + eh_lh + lh_cur + tmean_dif + bio1 + NDVI + gHM + glacier, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = drop_na(paleo_df))

Ho_resid_paleo_mod <- 
  gls(Ho_nonsyn ~ Ho + lig_lgm + eh_lh + lh_cur + tmean_dif + bio1 + NDVI + gHM + glacier, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = drop_na(paleo_df))

summary(Ho_paleo_mod)$tTable %>% as.data.frame() %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))
summary(Ho_nonsyn_paleo_mod)$tTable %>% as.data.frame() %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))
summary(Ho_resid_paleo_mod)$tTable %>% as.data.frame() %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))
```


```{r}
trace <- rast(here("data", "env", "california_chelsa_trace21k.tif"))

# Extract values at coordinates
coords <- get_coords(sf = TRUE)
time_key <- data.frame(timeid = rev(seq(-200, 20, 1)), timepoint = seq(0, 22, 0.1))
trace_vals <- 
  terra::extract(trace, paleo_df, ID = TRUE, method = "bilinear") %>%
  mutate(X = paleo_df$X,
         Y = paleo_df$Y) %>%
  pivot_longer(-c(X, Y), names_to = "variable", values_to = "value") %>%
  filter(grepl("_bio01_", variable)) %>%
  mutate(timeid = gsub("_V1.0", "", gsub("CHELSA_TraCE21k_bio01_", "", variable))) %>%
  mutate(timeid = as.numeric(timeid)) %>%
  # Convert to k BP
  left_join(time_key) %>%
  # Convert to BP
  mutate(yearbp = timepoint*1000) 

trace_summary <- 
  trace_vals %>%
  group_by(yearbp) %>%
  summarize(mean_val = mean(value, na.rm = TRUE),
            sd_val = sd(value, na.rm = TRUE))


# lh	Late Holocene: Meghalayan	4.2-0.3 ka	Fordham  et al. 2017
# mh	Mid Holocene: Northgrippian	8.326-4.2 ka	Fordham  et al. 2017
# eh	Early Holocene: Greenlandian	11.7-8.326 ka	Fordham  et al. 2017
# yds	Pleistocene: Younger Dryas Stadial	12.9-11.7 ka	Fordham  et al. 2017
# ba	Pleistocene: Bølling-Allerød	14.7-12.9 ka	Fordham  et al. 2017
# hs1	Pleistocene: Heinrich Stadial 1	17.0-14.7 ka	Fordham  et al. 2017
# lgm	Pleistocene: Last Glacial Maximum	ca. 21 ka	CHELSA (putting 16 to 31 ka since that is full extent)
# lig Pleistocene: Last Interglacial	ca. 130 ka (115 ka to 130 ka; doi:10.1038/nature11789)
# cur Current	1950-2021	CHELSA (to convert to BP, use 1950 as "present")
chelsa_time_key <-
  data.frame(
    period = c("lig", "lgm", "hs1", "ba", "yds", "eh", "mh", "lh", "cur"),
    start_ka = c(115, 16, 17, 14.7, 12.9, 11.7, 8.326, 4.2, (1950 - 1981)/1000),
    end_ka = c(130, 31, 14.7, 12.9, 11.7, 8.326, 4.2, 0.3, (1950 - 2021)/1000)
  ) %>%
  mutate(
    start_bp = start_ka * 1000,
    end_bp = end_ka * 1000,
    mid_bp = (start_bp + end_bp)/2
  )

chelsa_summary <-
  paleo_df %>%
  st_drop_geometry() %>%
  select(all_of(c("lig", "lgm", "hs1", "ba", "yds", "eh", "mh", "lh", "cur"))) %>%
  pivot_longer(everything(), names_to = "period", values_to = "temp") %>%
  left_join(chelsa_time_key, by = "period") %>%
  group_by(period, start_bp, end_bp, mid_bp) %>%
  summarize(mean_temp = mean(temp, na.rm = TRUE))
chelsa_summary_sub <- chelsa_summary %>% filter(period %in% c("lig", "lgm", "eh", "lh", "cur"))

chelsa_change <-
  chelsa_summary_sub %>%
  ungroup() %>%
  arrange(desc(start_bp)) %>%                               # ensure chronological order
  mutate(
    temp_change = mean_temp - lag(mean_temp),
    change_label = paste(lag(period), "→", period),  # label from previous to current
    change_start = lag(mid_bp),
    change_end = mid_bp,
    temp_start = lag(mean_temp),
    temp_end = mean_temp
  ) %>%
  filter(!is.na(temp_change))     

chelsa_change %>% select(period, change_label, start_bp, end_bp, change_start, change_end)

pdf(here(plotpath, "paleochange.pdf"), width = 13, height = 5)
simple_plot("lig_lgm", "resids", paleo_df)
simple_plot("lgm_eh", "resids", paleo_df)
simple_plot("eh_lh", "resids", paleo_df)
simple_plot("lh_cur", "resids", paleo_df)
simple_plot("tmean_dif", "resids", paleo_df)
ggplot() +
  geom_line(data = trace_summary, aes(x = yearbp, y = mean_val)) +
  geom_segment(data = chelsa_summary, aes(x = start_bp, xend = end_bp, y = mean_temp, yend = mean_temp), color = "red", linewidth = 2) +
  geom_text(data = chelsa_summary, aes(x = mid_bp, y = mean_temp, label = period), vjust = -1, color = "red") +
  scale_x_log10() +
  labs(x = "Years before present", y = "Mean Annual Temperature (°C)") +
  theme_classic()
ggplot() +
  geom_line(data = trace_summary, aes(x = yearbp, y = mean_val)) +
  geom_segment(data = filter(chelsa_summary, period != "lig"), aes(x = start_bp, xend = end_bp, y = mean_temp, yend = mean_temp), color = "red", linewidth = 2) +
  geom_text(data = filter(chelsa_summary, period != "lig"), aes(x = mid_bp, y = mean_temp, label = period), vjust = -1, color = "red") +
  scale_x_reverse() + 
  labs(x = "Years before present", y = "Mean Annual Temperature (°C)") +
  theme_classic()
ggplot() +
  geom_line(data = trace_summary, aes(x = yearbp, y = mean_val), alpha = 0.5) +
  geom_segment(data = chelsa_summary_sub, aes(x = start_bp, xend = end_bp, y = mean_temp, yend = mean_temp), color = "#32a3ff", linewidth = 2) +
  geom_text(data = chelsa_summary_sub, aes(x = mid_bp, y = mean_temp, label = toupper(period)), vjust = 2, color = "#32a3ff") +
  geom_segment(data = chelsa_change, aes(x = change_start, xend = change_end, y = temp_start, yend = temp_end), color = "tomato1", linetype = "dashed", arrow = arrow(length = unit(0.2, "cm"), ends = "last")) +
  ggrepel::geom_text_repel(data = chelsa_change, aes(x = (change_start + change_end)/2, y = (temp_start + temp_end)/2, label = toupper(change_label)), vjust = -1, color = "tomato2") +
  scale_x_reverse() + 
  labs(x = "Years before present", y = "Mean Annual Temperature (°C)") +
  theme_classic()
dev.off()

```


# Using Trace21k values for holocene
```{r}

extract_impute_stack <- function(r, coords) {
  x <- extract(r, coords, ID = FALSE, method = "simple")
  na_rows <- which(is.na(x[,1]))
  if (length(na_rows) > 0) {
    message("Imputing ", length(na_rows), " missing values")
    new_vals <- terra::extract(r, coords[na_rows,], ID = FALSE, method = "bilinear")

    x[na_rows,] <- new_vals
  }
  return(x)
}


trace_df <- 
  mod_df_unique %>% 
  st_as_sf(coords = c("X", "Y"), crs = 4326) %>%
  st_transform(3310) %>%
  bind_cols(st_coordinates(.)) 

time_key <- data.frame(timeid = rev(seq(-200, 20, 1)), timepoint = seq(0, 22, 0.1))
trace_vals <- 
  extract_impute_stack(trace, trace_df) %>%
  mutate(X = trace_df$X,
         Y = trace_df$Y) %>%
  pivot_longer(-c(X, Y), names_to = "variable", values_to = "value") %>%
  filter(grepl("_bio01_", variable)) %>%
  mutate(timeid = gsub("_V1.0", "", gsub("CHELSA_TraCE21k_bio01_", "", variable))) %>%
  mutate(timeid = as.numeric(timeid)) %>%
  # Convert to k BP
  left_join(time_key) %>%
  # Convert to BP
  mutate(yearbp = timepoint*1000) 

range(trace_vals$yearbp)

# eh	Early Holocene: Greenlandian	11.7-8.326 ka	Fordham  et al. 2017
eh_vals <- 
  trace_vals %>%
  filter(yearbp <= 11700 & yearbp >= 8326) %>%
  group_by(X, Y) %>%
  summarize(eh = mean(value, na.rm = TRUE)) %>%
  select(X, Y, eh)

# lh	Late Holocene: Meghalayan	4.2-0.3 ka	Fordham  et al. 2017
lh_vals <-
  trace_vals %>%
  filter(yearbp <= 4200 & yearbp >= 300) %>%
  group_by(X, Y) %>%
  summarize(lh = mean(value, na.rm = TRUE)) %>%
  select(X, Y, lh)

range(eh_vals$eh - lh_vals$lh)

lig_vals <- get_paleovars("lig")[["lig"]][["bio_1"]] %>% extract_impute_stack(., trace_df)/10
lgm_vals <- extract_impute_stack(lgm, trace_df)
cur_vals <- extract_impute_stack(cur, trace_df)

trace_mod_df <-
  mutate(
    trace_df,
    lig = lig_vals[,1],
    lgm = lgm_vals[,1],
    eh = eh_vals$eh,
    lh = lh_vals$lh,
    cur = cur_vals[,1]
  ) %>%
  mutate(
    # ! NOTE: raw not absolute
    lig_lgm = (lgm - lig),
    lgm_eh = (eh - lgm),
    eh_lh = (lh - eh),
    lh_cur = (cur - lh),
    eh_cur = cur - eh # Checked this and it is the same as lh_cur (leaving so I remember I checked)
  )%>% 
  mutate(resids = residuals(lm(Ho_nonsyn ~ Ho, data = .)))
  
trace_mod_df_scaled <-
  trace_mod_df %>%
  # Scale the model variables
  mutate_at(
    vars(lig_lgm, lgm_eh, eh_lh, lh_cur, bio1, NDVI, glacier, tmean_dif, csi_past, gHM),
    ~as.numeric(scale(.x))
  ) 

pdf(here(plotpath, "trace21k.pdf"), width = 15, height = 5)
simple_plot("lig_lgm", "Ho", trace_mod_df)
simple_plot("lig_lgm", "resids", trace_mod_df)
simple_plot("lgm_eh", "resids", trace_mod_df)
simple_plot("eh_lh", "resids", trace_mod_df)
simple_plot("lh_cur", "resids", trace_mod_df)
simple_plot("tmean_dif", "resids", trace_mod_df)
simple_plot("tmean_dif", "Ho", trace_mod_df)
simple_plot("tmean_dif", "Ho_nonsyn", trace_mod_df)
dev.off()

# Checking correlations 
# lgm_eh and lig_lgm have correlation of -0.60
# lh_cur and lgm_eh have correlation of -0.80
# Removing lgm_eh from model 
# csi_past and lig_lgm have correlation of 0.90
# csi_past and lgm_eh have correlation of -0.70
# Removing csi_past as well
cor(st_drop_geometry(trace_mod_df)[, c("lig_lgm", "lgm_eh", "eh_lh", "lh_cur", "eh_cur", "tmean_dif", "csi_past")], use = "pairwise.complete.obs")

Ho_paleo_mod <- 
  gls(Ho ~ lig_lgm + eh_lh + lh_cur + tmean_dif + bio1 + NDVI + gHM + glacier, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = trace_mod_df_scaled)

Ho_nonsyn_paleo_mod <- 
  gls(Ho_nonsyn ~ lig_lgm + eh_lh + lh_cur + tmean_dif + bio1 + NDVI + gHM + glacier, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = trace_mod_df_scaled)

Ho_resid_paleo_mod <- 
  gls(Ho_nonsyn ~ Ho + lig_lgm + eh_lh + lh_cur + tmean_dif + bio1 + NDVI + gHM + glacier, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = trace_mod_df_scaled)

gls(Ho ~ lig_lgm, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = trace_mod_df_scaled) %>% summary()

summary(Ho_paleo_mod)$tTable %>% as.data.frame() %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))
summary(Ho_nonsyn_paleo_mod)$tTable %>% as.data.frame() %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))
summary(Ho_resid_paleo_mod)$tTable %>% as.data.frame() %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))
```

# Rasmus meeting plots

## Comparing LIG - LGM vs LGM - EH
```{r}
# Correlation check
cor(st_drop_geometry(trace_mod_df)[, c("lig_lgm", "lgm_eh", "eh_lh", "tmean_dif")], use = "pairwise.complete.obs")
#lgm_eh and lig_lgm have a correlation of -0.60

# Comparing lig_lgm vs lgm_eh

# LIG - LGM
gls(resids ~ Ho + lig_lgm + eh_lh + tmean_dif, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = trace_mod_df_scaled) %>% summary()
#                   Value  Std.Error   t-value p-value
# (Intercept)  0.00145155 0.01346247  0.107822  0.9142
# Ho           0.13055928 0.01665550  7.838810  0.0000
# lig_lgm     -0.13498521 0.01580030 -8.543206  0.0000
# eh_lh       -0.11875594 0.01589016 -7.473553  0.0000
# tmean_dif   -0.12230371 0.01576419 -7.758324  0.0000

# LGM - EH
gls(resids ~ Ho + lgm_eh + eh_lh + tmean_dif, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = trace_mod_df_scaled) %>% summary()
#                   Value  Std.Error   t-value p-value
# (Intercept)  0.00474681 0.01478724  0.321007  0.7485
# Ho           0.10097113 0.01773954  5.691868  0.0000
# lgm_eh       0.07720517 0.01640078  4.707409  0.0000
# eh_lh       -0.09343164 0.01699506 -5.497577  0.0000
# tmean_dif   -0.10647776 0.01706200 -6.240637  0.0000

# Both together
gls(resids ~ Ho + lgm_eh + lig_lgm + eh_lh + tmean_dif, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = trace_mod_df_scaled) %>% summary()
#                   Value  Std.Error   t-value p-value
# (Intercept)  0.00166287 0.01347430  0.123411  0.9019
# Ho           0.13484129 0.01710262  7.884249  0.0000
# lgm_eh       0.01839399 0.01732237  1.061863  0.2893 *n.s.
# lig_lgm     -0.12542479 0.01816613 -6.904320  0.0000
# eh_lh       -0.11919924 0.01591143 -7.491423  0.0000
# tmean_dif   -0.12229425 0.01577298 -7.753402  0.0000

# I think LIG to LGM makes the most sense to include
```
```{r}
Ho_paleo_mod <- 
  gls(Ho ~ lig_lgm + eh_lh + lh_cur + tmean_dif + bio1 + NDVI + gHM + glacier, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = trace_mod_df_scaled)

Ho_nonsyn_paleo_mod <- 
  gls(Ho_nonsyn ~ lig_lgm + eh_lh + lh_cur + tmean_dif + bio1 + NDVI + gHM + glacier, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = trace_mod_df_scaled)

Ho_resid_paleo_mod <- 
  gls(Ho_nonsyn ~ Ho + lig_lgm + eh_lh + lh_cur + tmean_dif + bio1 + NDVI + gHM + glacier, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = trace_mod_df_scaled)

summary(Ho_paleo_mod)$tTable %>% as.data.frame() %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))
summary(Ho_nonsyn_paleo_mod)$tTable %>% as.data.frame() %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))
summary(Ho_resid_paleo_mod)$tTable %>% as.data.frame() %>% filter(`p-value` < 0.05) %>% arrange(desc(abs(Value)))
```

```{r}
# Get non-scaled tmean_dif values and gendiv for plotting
tmean_dif_r <- rast(here("data", "env", "model_rasters", "tmean_dif.tif"))
tmean_dif_vals <- extract_impute(tmean_dif_r, trace_mod_df[,c("X", "Y")])

Ho <- get_het() %>% select(SampleID, Ho = Ho)
Ho_nonsyn <- get_het("allnonsyn.het") %>% select(SampleID, Ho_nonsyn = Ho)
Ho_df <- 
  coords %>% 
  left_join(Ho, by = "SampleID") %>% 
  left_join(Ho_nonsyn, by = "SampleID") %>%
  st_transform(3310) %>%
  bind_cols(st_coordinates(.)) %>%
  st_drop_geometry() %>%
  group_by(X, Y) %>%
  summarize(
    Ho = mean(Ho, na.rm = TRUE),
    Ho_nonsyn = mean(Ho_nonsyn, na.rm = TRUE)
  )

simple_df <- 
  trace_mod_df %>% 
  mutate(tmean_dif = tmean_dif_vals, lgm_cc = abs(lig_lgm)) %>%
  select(-Ho, -Ho_nonsyn) %>%
  left_join(Ho_df, by = c("X", "Y")) 

sum(is.na(simple_df$Ho))

make_pretty_temp <- function(x) {
  if (x == "Ho") return("Genome-wide Ho")
  if (x == "Ho_nonsyn") return("Non-synonymous Ho")
  if (x == "resids") return("Residual non-synonymous Ho")
  if (x == "eh_lh") return("Holocene climate change (°C)")
  if (x == "lgm_eh") return("Post-glacial warming (°C)")
  if (x == "lig_lgm") return("LGM climate change (°C)")
  if (x == "lgm_cc") return("LGM climate change (°C)")
  if (x == "tmean_dif") return("Recent climate change (°C)")
}

scatter_plot <- function(x, y, df){
  plt <-
    ggplot(df, aes(x = .data[[x]], y = .data[[y]])) +
    geom_point(size = 1) +
    geom_smooth(method = "lm") +
    ggpubr::stat_cor() +
    theme_classic() +
    labs(
      x = make_pretty_temp(x), 
      y = make_pretty_temp(y)
    ) +
    theme(
      axis.text = element_text(size = 12),
      axis.title = element_text(size = 14)
    )

  if (x == "lig_lgm") plt <- plt + scale_x_reverse()

  return(plt)
}

residual_plot <- function(x, y, df) {
  f <- formula(paste0(y, " ~ lig_lgm + eh_lh  + tmean_dif + bio1 + NDVI + gHM + Q + glacier"))
  model <- gls(f, correlation = corExp(form = ~ X + Y, nugget = FALSE), data = df)
  
  # Calculate residuals for y variable given x variable
  df[[y]] <- residuals(model) + coef(model)[[x]] * as.numeric(df[[x]])

  scatter_plot(x, y, df) +
    labs(
      x = make_pretty_temp(x), 
      y = paste("Partial", make_pretty_temp(y))
    ) 

}

map_vars <- c("lig_lgm", "eh_lh", "tmean_dif")
Ho_plts <- map(map_vars, ~scatter_plot(.x, "Ho", simple_df))
nonsyn_plts <- map(map_vars, ~scatter_plot(.x, "Ho_nonsyn", simple_df))
resids_plts <- map(map_vars, ~scatter_plot(.x, "resids", simple_df))

# Reminder of correlations
cor(st_drop_geometry(simple_df)[, map_vars], use = "pairwise.complete.obs")
Ho_resid_plts <- map(map_vars, ~residual_plot(.x, "Ho", simple_df))
nonsyn_resid_plts <- map(map_vars, ~residual_plot(.x, "Ho_nonsyn", simple_df))
resids_resid_plts <- map(map_vars, ~residual_plot(.x, "resids", simple_df))

library(cowplot)
pdf(here(plotpath, "rasmus_meeting_plots.pdf"), width = 12, height = 7.5)

plot_grid(plotlist = c(Ho_plts, Ho_resid_plts), nrow = 2, align = "hv")
plot_grid(plotlist = c(nonsyn_plts, nonsyn_resid_plts), nrow = 2, align = "hv")
plot_grid(plotlist = c(resids_plts, resids_resid_plts), nrow = 2, align = "hv")

ggplot() +
  geom_line(data = trace_summary, aes(x = yearbp, y = mean_val)) +
  geom_segment(data = filter(chelsa_summary, period != "lig"), aes(x = start_bp, xend = end_bp, y = mean_temp, yend = mean_temp), color = "tomato2", linewidth = 2) +
  geom_text(data = filter(chelsa_summary, period != "lig"), aes(x = mid_bp, y = mean_temp, label = toupper(period)), vjust = -1, color = "tomato2") +
  scale_x_reverse() + 
  labs(x = "Years before present", y = "Mean Annual Temperature (°C)") +
  theme_classic() +
  theme(
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12)
  )
dev.off()
```