---
title: "SDM"
output:
  github_document:
    toc: TRUE
---
```{r}
library("rpaleoclim")
library("here")
library("tidyverse")
library("ggpubr")
library("terra")
library("sf")
library("gridExtra")
library("rpaleoclim")
source("general_functions.R")
source(here("analysis", "genetic_diversity", "genetic_diversity.R"))
source(here("analysis", "sdm", "paleovars.R"))
library("MuMIn")
ca <- get_ca()
pdfpath <- here("analysis", "sdm", "pdfs")
```

```{r}
# get paleovars
env_list <- get_paleovars()
paleokey <- get_paleokey()

# Drop mis19
env_list <- env_list[names(env_list) != "mis19"]

# Assign the loaded and processed data to individual variables
list2env(env_list, envir = .GlobalEnv)

# Create example map (divide by 10 to convert to C)
stk <- c(env_list$cur$bio_1, env_list$lgm$bio_1)/10
names(stk) <- c("Current", "LGM")
env_df <-
  as.data.frame(stk, xy = TRUE) %>%
  mutate(Change = Current - LGM)
```

```{r}
plt2 <-
  ggplot(env_df) +
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = Current)) +
  scale_fill_viridis_c(option = "viridis", direction = -1, limits = c(-15, 30)) +
  theme_void()

plt1 <-
  ggplot(env_df) +
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = LGM)) +
  scale_fill_viridis_c(option = "viridis", direction = -1, limits = c(-15, 30)) +
  theme_void()

plt3 <-
  ggplot(env_df) +
  geom_sf(data = ca) +
  geom_raster(aes(x = x, y = y, fill = Change)) +
  labs(fill = "Change in temp\nsince the LGM") +
  scale_fill_viridis_c(option = "rocket") +
  theme_void()

grid.arrange(plt1, plt2, plt3, nrow = 1)
```


```{r}
# get coordinates
df <- get_coords()

# get genetic diversity measures
het <- get_het()
#roh <- get_roh()

# combine together
#df <- left_join(df, het) %>% left_join(roh)
df <- left_join(df, het) 

# use data list to get vars
env_df_vals <- map(env_list, ~ data.frame(df, extract(.x, df[,c("x", "y")], ID = FALSE)))
diff_vars <- names(env_list) %>% setdiff("cur")
diff_vals <- map(diff_vars, ~ {
  diff <- cur - get(.x)
  return(data.frame(df, extract(diff, df[,c("x", "y")], ID = FALSE)))
})
env_df_vals <- c(env_df_vals, diff_vals)
names(env_df_vals) <- c(names(env_list), paste0("dif_", diff_vars))
```

# Correlation tests
```{r}
# check for strong correlations
# only strong correlation is with the late holocene/bio2
map(env_df_vals, ~ {
  cordf <- .x %>% dplyr::select(Ho, contains("bio")) %>% drop_na(Ho)
  strong <- cor(cordf, use = "complete.obs")["Ho", -1]
  which(abs(strong) > 0.5)
})
```
```{r}
cor_vals <- 
  map(env_df_vals, ~ {
    cordf <- .x %>% dplyr::select(Ho, contains("bio")) %>% drop_na(Ho)
    res <- cor(cordf, use = "complete.obs")["Ho", -1]
  }) 

map(cor_vals, ~ which(abs(.x) > 0.6))

cor_df <- 
  cor_vals %>% 
  bind_rows(.id = "timeperiod") %>% 
  pivot_longer(contains("bio")) %>%
  mutate(timeperiod = factor(timeperiod, levels = names(env_df_vals))) %>%
  mutate(bioclim = as.factor(as.numeric(gsub("bio_", "", name))))

pdf(here(pdfpath, "correlation_heatmap.pdf"), width = 5, height = 3.75)
ggplot(cor_df, aes(x = bioclim, y = timeperiod, fill = value)) +
  geom_tile() +
  labs(fill = expression(r[Ho])) +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_minimal()

ggplot(cor_df, aes(x = bioclim, y = timeperiod, fill = abs(value))) +
  geom_tile() +
  scale_fill_viridis_c(option = "rocket", direction = -1) +
  labs(fill = expression(r[Ho])) +
  theme_minimal()
dev.off()
```

```{r}
# confirmed no correlation with ROH:
map(env_df_vals, ~ {
  r <- cor(.x %>% dplyr::select(froh, contains("bio")) %>% drop_na(froh))["froh", -1]
  which(abs(r) > 0.6)
})
```

# Linear models

## Linear models with all variables (excluding correlated pairs)
```{r}

# Run linear models (dropping correlated variables for models, but adding them back in for visualization)
run_lm <- function(df, model_name){
  safe_collinear <- possibly(spatialEco::collinear)
  drop_vars <- safe_collinear(df %>% dplyr::select(contains("bio")), p = 0.6)
  uncorrelated <- names(df %>% dplyr::select(contains("bio"))) %>% setdiff(drop_vars)
  if (is.null(uncorrelated)) {
    uncorrelated <- names(df %>% dplyr::select(contains("bio")))
    correlated <- data.frame(corvars = NA, var = uncorrelated, model = model_name)
  } else {
    cormat <- cor(df %>% dplyr::select(contains("bio")))
    correlated <- 
      map(uncorrelated, ~ data.frame(corvars = names(which(abs(cormat[.x,]) > 0.5)), var = .x)) %>% 
      bind_rows() %>%
      mutate(model = model_name)
  }

  fHo <- formula(paste0("Ho ~", paste0(uncorrelated, collapse = " + ")))
  mod <- summary(lm(fHo, data=df))

  result <- 
    data.frame(mod$coefficients) %>% 
    mutate(model = model_name) %>%
    mutate(adj_rsqr = mod$adj.r.squared) %>%
    mutate(var = rownames(.)) %>% 
    filter(var != "(Intercept)") %>%
    left_join(correlated) 
  return(result)
}

lm_result <- imap(env_df_vals, \(x, idx) run_lm(x, idx)) %>% bind_rows()

sigvars <- 
  lm_result %>% 
  dplyr::select(-corvars) %>% 
  distinct() %>% 
  filter(`Pr...t..` < 0.05) %>%
  arrange(desc(Estimate))
```

```{r}
plts <-
  map(unique(lm_result$model), ~ {
    sig_df <-
    lm_result %>% 
    filter(model == .x) %>%
    filter(`Pr...t..` < 0.05)

    sig_env_df <- 
      env_df_vals[[.x]] %>% 
      pivot_longer(contains("bio"), names_to = "var") %>% 
      #include correlated vars
      filter(var %in% unique(sig_df$corvars))

    title <- paste0(.x, " (adj R^2 = ", round(unique(sig_df$adj_rsqr), 2), ")" )

    if (nrow(sig_env_df) == 0) return(NULL)
    plt <-
    ggplot(sig_env_df, aes(value, Ho)) +
      geom_point(alpha = 0.7) +
      facet_wrap(~var, scales = "free", ncol = 5, nrow = 3) +
      stat_regline_equation(
        aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
        formula = y ~ x
      ) +
      geom_smooth(method = "lm") +
      stat_cor(label.y = 0) +
      theme_classic() +
      ggtitle(title)

    plt
  })

pdf(here(pdfpath, "env_sigvars_with_corvars.pdf"), width = 20, height = 15)
walk(plts, print)
dev.off()

plts <-
  map(unique(lm_result$model), ~ {
    sig_df <- lm_result %>% filter(model == .x) %>% filter(`Pr...t..` < 0.05)
    sig_env_df <- env_df_vals[[.x]] %>% pivot_longer(contains("bio"), names_to = "var") %>% filter(var %in% unique(sig_df$var))
    title <- paste0(.x, " (adj R^2 = ", round(unique(sig_df$adj_rsqr), 2), ")" )

    if (nrow(sig_env_df) == 0) return(NULL)
    plt <-
    ggplot(sig_env_df, aes(value, Ho)) +
      geom_point(alpha = 0.7) +
      facet_wrap(~var, scales = "free", nrow = 1) +
      stat_regline_equation(
        aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
        formula = y ~ x
      ) +
      geom_smooth(method = "lm") +
      stat_cor(label.y = 0) +
      theme_classic() +
      ggtitle(title)

    plt
  })

```

## PC-based variable selection

```{r}
# PCA of all variables split by change or single timeperiod variables
timeperiods = c("cur", "lh", "lgm", "lig", "dif_lh", "dif_lig", "dif_lgm")

# Only use tmean, tmax, and tmin related variables
# BIO1 = Annual Mean Temperature
# BIO5 = Max Temperature of Warmest Month
# BIO6 = Min Temperature of Coldest Month
env_wide <- 
  bind_rows(env_df_vals, .id = "timeperiod") %>% 
  dplyr::select("Ho", "bio_1", "bio_5", "bio_6", "timeperiod") %>%
  drop_na("Ho") %>%
  filter(timeperiod %in% timeperiods) %>%
  # Filter out rows where all bio values are NA
  filter(!rowSums(is.na(dplyr::select(., contains("bio"))) == ncol(dplyr::select(., contains("bio"))))) %>%
  pivot_longer(contains("bio")) %>% 
  pivot_wider(names_from = "timeperiod", values_from = value) %>% 
  pivot_wider(names_from = "name", values_from = all_of(timeperiods)) %>%
  drop_na(contains("bio"))
```

PCA with all variables
```{r}
# Get just single timeperiod variables
pca <- prcomp(env_wide %>% dplyr::select(-Ho), scale = TRUE)
plot(pca)

# calculate when 90% of the variance is explained
varexp <- cumsum(pca$sdev^2) / sum(pca$sdev^2)
npcs <- which(varexp > 0.8)[1]
  
# Run lm with PCs
pcs <- data.frame(pca$x[,1:npcs])
mod_df <- data.frame(pcs, Ho = env_wide$Ho)

# Use dredge to determine what combination of pcs is best
full_model <- lm(Ho ~ ., data = mod_df, na.action = na.fail)

# Use dredge for model selection
model_set <- dredge(full_model)

# Select the best models based on ΔAIC < 2
best_models <- get.models(model_set, subset = delta < 2)

# There are two best models 
length(best_models)
sapply(best_models, AIC)

mod <- best_models[[which.min(sapply(best_models, AIC))]]
mod_summary <- - data.frame(summary(mod)$coefficients) 

# Get the significant PCs
sigpcs <- 
  mod_summary %>% 
  filter(`Pr...t..` < 0.05) %>%
  mutate(var = row.names(.)) %>% 
  filter(var != "(Intercept)") %>%
  pull(var)

ggdf <-
  data.frame(mod_df) %>%
  pivot_longer(contains("PC")) %>%
  filter(name %in% sigpcs)

ggplot(ggdf, aes(value, Ho)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),
    formula = y ~ x
  ) +
  facet_wrap(~name, scales = "free") +
  stat_cor(label.y = 0) +
  theme_classic()

# Get variables strongly correlated with each PC
important_vars <-  map(sigpcs, ~{
  # Get variables correlated with the PC
  cor_results <- 
    map(names(env_wide)[-1], \(column) {
      cor.test(env_wide[[column]], mod_df[, .x])
    })  

  data.frame(
    r = map_dbl(cor_results, "estimate"),
    p = map_dbl(cor_results, "p.value"),
    PC = .x,
    var = names(env_wide)[-1]
  ) %>%
  filter(p < 0.05) 

}) %>% bind_rows()

vars <- important_vars %>% pull(var) %>% unique()

important_df <- 
  env_wide %>% 
  pivot_longer(contains("bio")) %>% 
  filter(name %in% vars) %>%
  mutate(splitname = name) %>%
  mutate(splitname = gsub("dif_", "dif-", splitname)) %>%
  separate(splitname, into = c("timeperiod", "bio", "bion"), sep = "_") %>%
  mutate(bio = paste0("bio_", bion)) 

ggplot(important_df, aes(value, Ho)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),
    formula = y ~ x
  ) +
  facet_wrap(~name, scales = "free") +
  stat_cor(label.y = 0) +
  theme_classic()

biokey <- get_biokey()
count_df <- left_join(important_df, biokey) %>% dplyr::select(-value) %>% distinct()
count(count_df, vartype)
count(count_df, bio) %>% arrange(desc(n))
```

```{r}
# Calculate correlation of each var with Ho
Ho_cors <- 
  env_wide %>% 
  select(Ho, all_of(vars)) %>%
  cor(use = "complete.obs") %>% 
  .["Ho", -1] %>%
  bind_rows() %>%
  pivot_longer(everything(), names_to = "var", values_to = "r_Ho") %>%
  arrange(desc(abs(r_Ho))) %>%
  left_join(important_vars, by = "var")

# See top vars:
head(Ho_cors)

# For each significant PC, get the variable with the highest r_Ho
Ho_vars <- 
  Ho_cors %>% 
  # First, for variables that have significant associations with more than one PC, get the one with the highest r with the PC
  group_by(var) %>%
  filter(abs(r) == max(abs(r))) %>% 
  # Then, filter to get the variable with the highest correlation with Ho for each PC
  group_by(PC) %>% 
  filter(abs(r_Ho) == max(abs(r_Ho))) %>% 
  ungroup() %>% 
  pull(var)

# Check correlations
cors <- cor(env_wide[, Ho_vars])
diag(cors) <- 0
stopifnot(max(cors) < 0.7)

# Build linear model with the explanatory variables
mod_df2 <- env_wide %>% dplyr::select(Ho, all_of(Ho_vars))
mod <- lm(Ho ~ ., data = mod_df2, na.action = na.fail)

# Run dredge again
model_set <- dredge(mod)

# Select the best models based on ΔAIC < 2
best_models <- get.models(model_set, subset = delta < 2)

# There are three best models
length(best_models)

# Get the best of them
best_mod <- best_models[[which.min(sapply(best_models, AIC))]]
summary(best_mod)
mod_result <- data.frame(summary(best_mod)$coefficients) %>% filter(`Pr...t..` < 0.05)
# The best mod is dif_lh_bio_2 and dif_lig_bio_2

# Get variables strongly correlated with each of the significant variables from the best model
cor_df <- data.frame(cor(env_wide, select(env_wide, any_of(row.names(mod_result)))))
cor_df$var <- row.names(cor_df)
cor_df %>% 
  pivot_longer(-var) %>% 
  # filter out identity correlation
  filter(value != 1) %>%
  # get remaining vars
  filter(abs(value) > 0.7)

# Plot all the important variables
ggdf <- 
  env_wide %>% 
  dplyr::select(Ho, all_of(cor_df$var)) %>%
  pivot_longer(-Ho) 

pdf("Rplots.pdf", width =10)
ggplot(ggdf, aes(value, Ho)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),
    formula = y ~ x
  ) +
  facet_wrap(~name, scales = "free") +
  stat_cor(label.y = 0) +
  theme_classic()
dev.off()

```

## Showing off BIO1
```{r}
mod_df <- env_df_vals[["dif_lig"]]
plt2 <-
  ggplot(mod_df) +
    geom_sf(data = ca) +
    geom_point(aes(x = x, y = y, color = bio_1), cex = 2) +
    labs(color = "Change\nin annual temp") +
    scale_color_viridis_c(option = "magma", direction = -1) +
    theme_void() 

plt3 <-
  ggplot(mod_df) +
    geom_sf(data = ca) +
    geom_point(aes(x = x, y = y, color = Ho), cex = 2) +
    theme_void() +
    scale_color_viridis_c(option = "magma")

plt1 <- 
  ggplot(mod_df, aes(bio_2, Ho)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),
    formula = y ~ x
  ) +
  xlab("Change in annual temp") +
  stat_cor(label.y = 0) +
  xlim(-7.5, NA) +
  theme_classic()

pdf(here(pdfpath, "lig_bio1.pdf"), width = 15, height = 5)
grid.arrange(plt1, plt2, plt3, nrow = 1)
dev.off()
```

### Evaluating variance in variables 
```{r}
mega_df <- 
  bind_rows(env_df_vals, .id = "timeperiod") %>% 
  mutate(timeperiod = factor(timeperiod, levels = names(env_df_vals)))

var_df <- 
  mega_df %>%
  filter(timeperiod %in% c("cur", "lh", "lgm", "lig")) %>%
  select(SampleID, bio_1, bio_5, bio_6, Ho) %>%
  group_by(SampleID) %>%
  summarise(across(contains("bio"), ~ var(., na.rm =TRUE))) %>%
  ungroup() 
cor(drop_na(dplyr::select(var_df, contains("bio"))), use = "complete.obs")

# bio 1 is not significant
coords <- get_coords() %>% left_join(get_het())
var_df$Ho <- coords$Ho
mod <- lm(Ho ~ bio_1, var_df)
summary(mod)

var_df_long <- 
  var_df %>%
  pivot_longer(c(bio_1))

pdf(here(pdfpath, "var.pdf"), width = 13, height = 10)
ggplot(var_df_long, aes(value, Ho)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),
    formula = y ~ x
  ) +
  facet_wrap(~name, scales = "free") +
  stat_cor(label.y = 0) +
  theme_classic() +
  xlab("value")
dev.off()
```

### Looking at change over time
```{r}
# create start and end times (approx) for each period
paleokey_split <- 
  get_paleokey() %>%
  filter(id != "mis19") %>%
  mutate(time = 
    case_when(
      # 1950 is usually the reference point for "present", so since the CHELSA data is 1979-2013
      # We will call that -29 - (-63) or -0.029 - -0.063 ka years ago which is approximately 0
      period == "Current" ~ "0 ka", 
      .default = time
      )
    ) %>%
  separate(time, into = c("start_time", "end_time"), sep = "-", convert = TRUE, fill = "right") %>%
  mutate(across(c(start_time, end_time), ~ case_when(
    # Only end_time has the unit for some and start_time has unit for others
    str_detect(end_time, "ka") | str_detect(start_time, "ka") ~ as.numeric(str_remove(str_remove(.x, "ka"), "ca.")) * 1000,
    str_detect(end_time, "Ma") | str_detect(start_time, "Ma")  ~ as.numeric(str_remove(str_remove(.x, "Ma"), "ca.")) * 1000000,
    TRUE ~ as.numeric(.x)
  )))


# Create timeline
gg_timeline <- 
  paleokey_split %>% 
  mutate(
    start_time = case_when(start_time == 0 ~ 100, TRUE ~ start_time),
    end_time = case_when(is.na(end_time) ~ start_time + 4, TRUE ~ end_time)
  ) %>%
  filter(start_time < 1e6) 

ggplot(gg_timeline) +
  geom_rect(aes(xmin = end_time, xmax = start_time, ymin = 0, ymax = 10, fill = period), alpha = 0.5) +
  scale_x_log10() 


gg_timeline2 <- 
  paleokey_split %>% 
  mutate(
    start_time = case_when(start_time == 0 ~ 100, TRUE ~ start_time),
    end_time = case_when(is.na(end_time) ~ start_time + 100, TRUE ~ end_time)
  ) %>%
  filter(id %in% c("cur", "lh", "mh", "eh", "lgm", "lig"))

change_df <- 
  mega_df %>%
  left_join(gg_timeline2, by = c("timeperiod" ="id")) %>%
  pivot_longer(c(start_time, end_time), names_to = "start_end", values_to = "time") %>%
  drop_na(time) %>%
  group_by(time) %>%
  summarize(bio_1 = mean(bio_1, na.rm =TRUE)) 

ggplot(gg_timeline2) +
  geom_rect(aes(xmin = end_time, xmax = start_time, ymin = 0, ymax = 1, fill = period), alpha = 1) +
  geom_vline(aes(xintercept = end_time, col = period), lwd =1) +
  geom_vline(aes(xintercept = 0, col = "Current"), lwd = 1) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(breaks = seq(0, max(gg_timeline2$start_time), by = 20000), labels = scales::comma, expand = c(0.01,0.01)) +
  labs(y = "Years before present", col = "Timeperiod", fill = "Timeperiod") +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_rect(fill = "azure1"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line.x = element_line(color = "azure4", size = 2))

ggplot(gg_timeline2) +
  geom_rect(aes(xmin = end_time, xmax = start_time, ymin = 0, ymax = Inf, fill = period), alpha = 1) +
  geom_vline(aes(xintercept = end_time, col = period), lwd =1) +
  geom_vline(aes(xintercept = 0, col = "Current"), lwd = 1) +
  geom_line(data = change_df, aes(x = time, y = bio_1), col = "#0b1b26", lwd = 1, lty = "dashed") +
  scale_y_continuous(expand = c(0,0)) +
  #scale_x_log10(breaks = seq(0, max(gg_timeline2$start_time), by = 20000), labels = scales::comma, expand = c(0.01,0.01)) +
  scale_x_continuous(breaks = seq(0, max(gg_timeline2$start_time), by = 20000), labels = scales::comma, expand = c(0.01,0.01)) +
  labs(x = "Years before present", y = "Temperature", col = "Timeperiod",  fill = "Timeperiod") +
  theme(panel.background = element_rect(fill = "azure1"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line.x = element_line(color = "azure4", size = 2))

# get values
change_df <- 
  mega_df %>%
  left_join(paleokey_split, by = c("timeperiod" ="id")) %>%
  pivot_longer(c(start_time, end_time), names_to = "start_end", values_to = "time") %>%
  drop_na(time)

mean_change <-
  change_df %>%
  group_by(time) %>%
  summarize(bio_1 = mean(bio_1, na.rm =TRUE)) %>%
  drop_na(time)

ggplot() +
  geom_line(data = change_df, aes(x = time, y = bio_1, group = SampleID, col = "Samples"), alpha = 0.3) +
  geom_line(data = mean_change, aes(x = time, y = bio_1, col = "Mean"), lwd = 2) +
  scale_color_manual(values = c("#007c8f", "darkgray")) + 
  labs(col = "") +
  scale_x_log10()  +
  theme_classic()
```

### Checking with bouzid data
```{r}
vcf <- vcfR::read.vcfR(here("data", "bouzid", "populations_r20.haplotypes.filtered_m70_randomSNP.vcf"))
coords <- read_table(here("data", "bouzid", "Scelop.coord"), col_names =FALSE) %>% rename(x = X1, y = X2)
dos <- algatr::vcf_to_dosage(vcf)
dos_to_het <- function(dos){
  dos[dos == 1] <- 1
  dos[dos != 1] <- 0
  het <- rowMeans(dos, na.rm = TRUE)
  return(het)
}
df <- data.frame(coords, Ho = dos_to_het(dos))

ggplot(df) +
  geom_sf(data = ca) +
  geom_point(aes(x = x, y = y, color = Ho)) +
  scale_color_viridis_c(option = "magma") +
  theme_void()

lig <- load_paleoclim(here("data", "env", "LIG_v1_2_5m.zip"))
cur <- load_paleoclim(here("data", "env", "CHELSA_cur_V1_2B_r2_5m.zip"))
dif <- cur - lig
lig_vals <- extract(dif, df[,c("x", "y")], ID = FALSE)

mod_df <- data.frame(df, lig_vals)

ggplot(mod_df, aes(bio_1, Ho)) +
    geom_point(alpha = 0.7) +
    stat_regline_equation(
      aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
      formula = y ~ x
    ) +
    geom_smooth(method = "lm") +
    stat_cor(label.y = 0) +
    theme_classic() 

#bio5 (max temperature of warmest month)
#bio6 (min temperature of coldest month)
```
