
```{r}
library("rpaleoclim")
library("here")
library("tidyverse")
library("ggpubr")
library("terra")
library("sf")
library("gridExtra")
source("general_functions.R")
source(here("analysis", "genetic_diversity", "genetic_diversity.R"))
ca <- get_ca()
```
```{r}yds	Pleistocene: Younger Dryas Stadial	12.9-11.7 ka	Fordham  et al. 2017

paleovars <- c("lig", "lgm", "hs1", "ba", "yds", "eh", "mh", "lh", "cur")
# download data
walk(paleovars, ~ {
  paleoclim(.x, "2_5m", region = ext(ca), cache_path = here("data", "env", "paleoclim"))
})

# Create a key with layer information
paleokey <- data.frame(
  id = c("cur", "lh", "mh", "eh", "yds", "ba", "hs1", "lgm", "lig", "mis19", "mpwp", "m2"),
  period = c("Current", "Late Holocene: Meghalayan", "Mid Holocene: Northgrippian", "Early Holocene: Greenlandian", "Pleistocene: Younger Dryas Stadial", "Pleistocene: Bølling-Allerød", "Pleistocene: Heinrich Stadial 1", "Pleistocene: Last Glacial Maximum", "Pleistocene: Last Interglacial", "Pleistocene: MIS19", "Pliocene: Mid-Pliocene warm period", "Pliocene: M2"),
  time = c("1979 – 2013", "4.2-0.3 ka", "8.326-4.2 ka", "11.7-8.326 ka", "12.9-11.7 ka", "14.7-12.9 ka", "17.0-14.7 ka", "ca. 21 ka", "ca. 130 ka", "ca. 787 ka", "3.205 Ma", "ca. 3.3 Ma"),
  source = c("CHELSA", "Fordham et al. 2017", "Fordham et al. 2017", "Fordham et al. 2017", "Fordham et al. 2017", "Fordham et al. 2017", "Fordham et al. 2017", "CHELSA", "Otto-Bliesner et al. 2006", "Brown et al. 2018", "Hill 2015", "Dolan et al. 2015")
)

# Print the dataframe
print(df) 
# Define the file names and paths
file_names <- c("LIG_v1_2_5m.zip", "chelsa_LGM_v1_2B_r2_5m.zip", "HS1_v1_2_5m.zip", "BA_v1_2_5m.zip", "YDS_v1_2_5m.zip", "EH_v1_2_5m.zip", "MH_v1_2_5m.zip", "LH_v1_2_5m.zip", "CHELSA_cur_V1_2B_r2_5m.zip")
file_paths <- file.path(here("data", "env", "paleoclim"), file_names)

# Load and process the data using purrr
env_list <- purrr::map(file_paths, ~ {
  data <- load_paleoclim(.x)
  data <- crop(data, ca)
  data <- mask(data, ca)
  data
})
names(env_list) <- paleovars

# Assign the loaded and processed data to individual variables
lig <- env_list[[1]]
lgm <- env_list[[2]]
hs1 <- env_list[[3]]
ba <- env_list[[4]]
yds <- env_list[[5]]
eh <- env_list[[6]]
mh <- env_list[[7]]
lh <- env_list[[8]]
cur <- env_list[[9]]

# export
env_stack <- rast(env_list)
writeRaster(env_stack, here("data", "env", "paleoclim", "paleoclim.tif"), overwrite = TRUE)

```

```{r}
cur_range <- cur$bio_5 - cur$bio_6 - 273.15
lh_range <- lh$bio_5 - lh$bio_6- 273.15
lh_dif_range <- cur_range - lh_range

pdf("bio2_test_vars.pdf", fig.width = 10, fig.height = 30)
par(mfrow = c(3,2))
plot(cur_range, col = viridis::turbo(100), main = "Manual Bio 2 (current)")
plot(cur$bio_2, col = viridis::turbo(100), main = "Bio 2 (current)")

plot(lh_range, col = viridis::turbo(100), main = "Manual Bio 2 (lh)")
plot(lh$bio_2, col = viridis::turbo(100), main = "Bio 2 (lh)")

plot(cur_range - lh_range, col = viridis::turbo(100), main = "Manual change in Bio 2")
plot(cur$bio_2 - lh$bio_2, col = viridis::turbo(100), main = "Change in Bio 2")
dev.off()
```

# running linear models
```{r}
# get coordinates
df <- get_coords()

# get genetic diversity measures
het <- get_het()
roh <- get_roh()

# combine together
df <- left_join(df, het) %>% left_join(roh)

# use data list to get vars
env_df_vals <- map(env_list, ~ data.frame(df, extract(.x, df[,c("x", "y")], ID = FALSE)))
diff_vars <- names(env_list) %>% setdiff("cur")
diff_vals <- map(diff_vars, ~ {
  diff <- cur - get(.x)
  return(data.frame(df, extract(diff, df[,c("x", "y")], ID = FALSE)))
})
env_df_vals <- c(env_df_vals, diff_vals)
names(env_df_vals) <- c(paleovars, paste0("dif_", diff_vars))

# check for strong correlations
# only strong correlation is with the late holocene/bio2
map(env_df_vals, ~ {
  cordf <- .x %>% select(Ho, contains("bio")) %>% drop_na(Ho)
  strong <- cor(cordf, use = "complete.obs")["Ho", -1]
  which(abs(strong) > 0.5)
})

cor_vals <- 
  map(env_df_vals, ~ {
    cordf <- .x %>% select(Ho, contains("bio")) %>% drop_na(Ho)
    res <- cor(cordf, use = "complete.obs")["Ho", -1]
  }) 

map(cor_vals, ~ which(abs(.x) > 0.6))

cor_df <- 
  cor_vals %>% 
  bind_rows(.id = "timeperiod") %>% 
  pivot_longer(contains("bio")) %>%
  mutate(timeperiod = factor(timeperiod, levels = names(cor_vals))) %>%
  mutate(bioclim = gsub("bio_", "", name)) 

ggplot(cor_df, aes(x = bioclim, y = timeperiod, fill = (value))) +
  geom_tile() +
  labs(col = "r") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_minimal()

ggplot(cor_df, aes(x = bioclim, y = timeperiod, fill = abs(value))) +
  geom_tile() +
  scale_fill_viridis_c(option = "rocket", direction = -1) +
  labs(fill = "|r|") +
  theme_minimal()
```

```{r}
# confirmed no correlation with ROH:
map(env_df_vals, ~ {
  r <- cor(.x %>% select(froh, contains("bio")) %>% drop_na(froh))["froh", -1]
  which(abs(r) > 0.6)
})
```

```{r}
run_lm <- function(df, model_name){
  safe_collinear <- possibly(spatialEco::collinear)
  drop_vars <- safe_collinear(df %>% select(contains("bio")), p = 0.6)
  uncorrelated <- names(df %>% select(contains("bio"))) %>% setdiff(drop_vars)
  if (is.null(uncorrelated)) {
    uncorrelated <- names(df %>% select(contains("bio")))
    correlated <- data.frame(corvars = NA, var = uncorrelated, model = model_name)
  } else {
    cormat <- cor(df %>% select(contains("bio")))
    correlated <- 
      map(uncorrelated, ~ data.frame(corvars = names(which(abs(cormat[.x,]) > 0.5)), var = .x)) %>% 
      bind_rows() %>%
      mutate(model = model_name)
  }

  fHo <- formula(paste0("Ho ~", paste0(uncorrelated, collapse = " + ")))
  mod <- summary(lm(fHo, data=df))

  result <- 
    data.frame(mod$coefficients) %>% 
    mutate(model = model_name) %>%
    mutate(adj_rsqr = mod$adj.r.squared) %>%
    mutate(var = rownames(.)) %>% 
    filter(var != "(Intercept)") %>%
    left_join(correlated) 
  return(result)
}

lm_result <- imap(env_df_vals, \(x, idx) run_lm(x, idx)) %>% bind_rows()

sigvars <- lm_result %>% select(-corvars) %>% distinct() %>% filter(`Pr...t..` < 0.05) %>% arrange(desc(Estimate))
```

```{r}
plts <-
map(unique(lm_result$model), ~ {
  sig_df <-
   lm_result %>% 
   filter(model == .x) %>%
   filter(`Pr...t..` < 0.05)

  sig_env_df <- 
    env_df_vals[[.x]] %>% 
    pivot_longer(contains("bio"), names_to = "var") %>% 
    #include correlated vars
    filter(var %in% unique(sig_df$corvars))

  title <- paste0(.x, " (adj R^2 = ", round(unique(sig_df$adj_rsqr), 2), ")" )

  if (nrow(sig_env_df) == 0) return(NULL)
  plt <-
  ggplot(sig_env_df, aes(value, Ho)) +
    geom_point(alpha = 0.7) +
    facet_wrap(~var, scales = "free", ncol = 5, nrow = 3) +
    stat_regline_equation(
      aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
      formula = y ~ x
    ) +
    geom_smooth(method = "lm") +
    stat_cor(label.y = 0) +
    theme_classic() +
    ggtitle(title)

  plt
})

pdf("env_sigvars_with_corvars.pdf", width = 20, height = 15)
walk(plts, print)
dev.off()


plts <-
map(unique(lm_result$model), ~ {
  sig_df <- lm_result %>% filter(model == .x) %>% filter(`Pr...t..` < 0.05)
  sig_env_df <- env_df_vals[[.x]] %>% pivot_longer(contains("bio"), names_to = "var") %>% filter(var %in% unique(sig_df$var))
  title <- paste0(.x, " (adj R^2 = ", round(unique(sig_df$adj_rsqr), 2), ")" )

  if (nrow(sig_env_df) == 0) return(NULL)
  plt <-
  ggplot(sig_env_df, aes(value, Ho)) +
    geom_point(alpha = 0.7) +
    facet_wrap(~var, scales = "free", nrow = 1) +
    stat_regline_equation(
      aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
      formula = y ~ x
    ) +
    geom_smooth(method = "lm") +
    stat_cor(label.y = 0) +
    theme_classic() +
    ggtitle(title)

  plt
})

```

```{r}
# showing off bio2
mod_df <- env_df_vals[["dif_lh"]]

plt2 <-
ggplot(mod_df) +
  geom_sf(data = ca) +
  geom_point(aes(x = x, y = y, color = bio_2), cex = 2) +
  labs(color = "Change\nin mean\ndiurnal\nrange") +
  scale_color_viridis_c(option = "magma", direction = -1) +
  theme_void() 

plt3 <-
ggplot(mod_df) +
  geom_sf(data = ca) +
  geom_point(aes(x = x, y = y, color = Ho), cex = 2) +
  theme_void() +
  scale_color_viridis_c(option = "magma")
  

plt1 <- ggplot(mod_df, aes(bio_2, Ho)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),
    formula = y ~ x
  ) +
  xlab("Change in mean diurnal range") +
  stat_cor(label.y = 0) +
  xlim(-7.5, NA) +
  theme_classic()

pdf(here("bio2.pdf"), width = 15, height = 5)
grid.arrange(plt1, plt2, plt3, nrow = 1)
dev.off()
```

### Evaluating other time periods
```{r}
mega_df <- bind_rows(env_df_vals, .id = "timeperiod") %>% mutate(timeperiod = factor(timeperiod, levels = names(env_df_vals)))
mega_df2 <- 
  mega_df %>% 
  filter(grepl("dif", timeperiod)) %>%
  mutate(id = gsub("dif_", "", timeperiod)) %>%
  left_join(paleokey) %>%
  mutate(dif = paste0("Current to ", period, "\n(", time, ")")) %>%
  mutate(dif = factor(dif, levels = unique(dif)))

ggplot(mega_df2, aes(bio_2, Ho)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),
    formula = y ~ x
  ) +
  facet_wrap(~dif, scales = "free", nrow = 2) +
  xlab("Change in mean diurnal range") +
  stat_cor(label.y = 0) +
  theme_classic()
```


### Checking BIO1 / variables correlated with bio2 back in time
```{r}

# check correlation between bio1 and bio2 from the different time periods
cor(mod_df2[,c("bio_1_dif_lig", "bio_2_dif_lig")], mod_df2[,c("bio_1_dif_lh", "bio_2_dif_lh")])
```

### Evaluating variables correlated with bio2
```{r}
wide_df <- 
  mega_df %>% 
  # note: pivot wider requires rows be uniquely identified (so sampleID is included here)
  select(timeperiod, Ho, SampleID, contains("bio")) %>%
  pivot_wider(names_from = "timeperiod", values_from = contains("bio"))

bio2_cors <- cor(wide_df %>% select(contains("bio")), use = "complete.obs")[,"bio_2_dif_lh"]
bio2_cors <- names(bio2_cors[abs(bio2_cors) > 0.6])
#bio1 - mean annual temperature
#bio6 - min temperature of coldest month (bio6)
#bio5 - max temperature of warmest month (bio5)
#bio7 - temperature annual range (bio5-bio6)
#bio2 - mean diurnal range (mean of monthly (max temp - min temp)
#bio12 - annual precipitation
#bio13 - precipitation of wettest month

gg_df <- 
  wide_df %>% 
  pivot_longer(all_of(bio2_cors)) %>%
  left_join(get_coords())

plt1 <- ggplot(gg_df, aes(value, Ho)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),
    formula = y ~ x
  ) +
  facet_wrap(~name, scales = "free") +
  stat_cor(label.y = 0) +
  theme_classic() +
  xlab("value")

plt_list <- gg_df %>%
  split(.$name) %>%
  map(~ {
    limit <- max(abs(.x[["value"]])) * c(-1, 1)
    ggplot(.x) +
        geom_sf(data = ca, fill = "darkgray") +
        labs(color = "value") +
        geom_point(aes(x = x, y = y, color = value), cex = 2) +
        scale_color_distiller(type = "div", limit = limit) +
        facet_wrap(~name) +
        theme_void()}
        )

plt3 <-
ggplot(gg_df) +
  geom_sf(data = ca) +
  geom_point(aes(x = x, y = y, color = Ho)) +
  ggtitle("E. Genetic diversity") +
  theme_void() +
  scale_color_viridis_c(option = "magma")  

pdf("correlated_vars.pdf", width = 10, height = 10)
print(plt1)
do.call(grid.arrange, c(c(plt_list), nrow = 3))
print(plt3)
dev.off()
```

### big lazy model
```{r}
no_na_df <- wide_df %>% drop_na(contains("bio"), Ho)
pca <- prcomp(drop_na(select(no_na_df, contains("bio"))))
pcs <- pca$x[,1:3]
#make a screeplot
screeplot(pca, type="lines", main="Screeplot of PCA")

mod_df_pca <- data.frame(Ho = no_na_df$Ho, pcs)

summary(lm(Ho ~ . , data = mod_df_pca))

all_cors <- cor(no_na_df %>% select(contains("bio")))

```

```{r}
all_cors <- abs(cor(select(no_na_df, contains("bio"))))

groups <- map(1:ncol(all_cors), ~{
  strong_cor <- all_cors[, .x] > 0.6
  names(which(strong_cor))
  })

# Function to recursively combine groups with common elements
combine_groups <- function(groups) {
  has_intersection <- function(lst, i) {
    sapply(lst, function(x) length(intersect(x, lst[[i]])) > 0)
  }
  
  for (i in seq_along(groups)) {
    # Find groups that intersect with the current group
    intersecting_indices <- which(has_intersection(groups, i))
    
    if (length(intersecting_indices) > 1) {
      # Combine intersecting groups
      combined_group <- unique(unlist(groups[intersecting_indices]))
      
      # Remove the intersecting groups and add the combined group
      groups <- groups[-intersecting_indices]
      groups <- c(groups, list(combined_group))
      
      # Recurse, as the list structure has changed
      return(combine_groups(groups))
    }
  }
  
  return(groups)
}

# Combine the groups based on intersections
combined_groups <- combine_groups(groups)

selected_vars <- 
map_chr(combined_groups, ~ {
  if (length(.x) == 1) return(.x)
  vars <- no_na_df %>% select(all_of(.x))
  # find var with strongest correlation with Ho
  Ho_cor <- cor(vars, no_na_df$Ho, use = "complete.obs")
  var <- row.names(Ho_cor)[which.max(abs(Ho_cor))]
  return(var)
}) %>% as.vector()

check_df <- select(no_na_df, all_of(selected_vars))
check_cor <- cor(check_df, use = "complete.obs")
diag(check_cor) <- 0
all(abs(check_cor) < 0.6)

mod_df_no_cor <- no_na_df %>% select(all_of(selected_vars), Ho)
mod <- lm(Ho ~ ., data = mod_df_no_cor)
summary(mod)


df <- data.frame(predicted = mod$fitted.values, observed = mod_df_no_cor$Ho)
names(mod)

ggplot(df, aes(x = observed, y = predicted)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation(
    aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
    formula = y ~ x
  ) +
  stat_cor(label.y = 0) +
  theme_classic()
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```
### Testing for effects of population structure
```{r}
source(here("analysis", "admixture", "admixture.R"))
admix <- get_Q(K = 5)
head(admix)
coords <- get_coords()
mod_df <- left_join(mod_df, admix)

# bio2 is still significant after controling for clusters
summary(lm(Ho ~ cluster + bio_2, data = mod_df))
# nothing is significant once an interaction term is added but I think that is due to low power
summary(lm(Ho ~ cluster + bio_2, data = mod_df))

# look at heterozygosity by cluster and remove largest cluster
mod_df %>% group_by(cluster) %>% summarise(mean = mean(Ho, na.rm = TRUE)) %>% arrange(desc(mean))
# when you remove the southern pop with really high genetic diversity (cluster 3), the pattern still exists (albeit weaker)
plt1 <- ggplot(mod_df[mod_df$cluster != 3, ], aes(bio_2, Ho)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),
    formula = y ~ x
  ) +
  stat_cor(label.y = 0) +
  theme_classic()

plt2 <- ggplot(mod_df[mod_df$cluster != 3, ]) +
  geom_sf(data = ca) +
  geom_point(aes(x = x, y = y, color = bio_2), cex = 2) +
  labs(color = "bio_2") +
  theme_void() +
  scale_color_viridis_c(option = "magma", direction = -1)

plt3 <- ggplot(mod_df[mod_df$cluster != 3, ]) +
  geom_sf(data = ca) +
  geom_point(aes(x = x, y = y, color = Ho), cex = 2) +
  theme_void() +
  scale_color_viridis_c(option = "magma")

grid.arrange(plt1, plt2, plt3, nrow = 1)
```

### Checking with bouzid data
```{r}
vcf <- vcfR::read.vcfR("../wingen/paperex/empex/data/populations_r20.haplotypes.filtered_m70_randomSNP.vcf")
coords <- read_table("../wingen/paperex/empex/data/Scelop.coord", col_names =FALSE) %>% rename(x = X1, y = X2)
dos <- algatr::vcf_to_dosage(vcf)
dos_to_het <- function(dos){
  dos[dos == 1] <- 1
  dos[dos != 1] <- 0
  het <- rowMeans(dos, na.rm = TRUE)
  return(het)
}
df <- data.frame(coords, Ho = dos_to_het(dos))

ggplot(df) +
  geom_sf(data = ca) +
  geom_point(aes(x = x, y = y, color = Ho)) +
  scale_color_viridis_c(option = "magma") +
  theme_void()

lh <- load_paleoclim(here("data", "env", "LH_v1_2_5m.zip"))
cur <- load_paleoclim(here("data", "env", "CHELSA_cur_V1_2B_r2_5m.zip"))
dif <- cur - lh
lh_vals <- extract(dif, df[,c("x", "y")], ID = FALSE)

mod_df <- data.frame(df, lh_vals)

ggplot(mod_df, aes(bio_2, Ho)) +
    geom_point(alpha = 0.7) +
    stat_regline_equation(
      aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
      formula = y ~ x
    ) +
    geom_smooth(method = "lm") +
    stat_cor(label.y = 0) +
    theme_classic() 

#bio5 (max temperature of warmest month)
#bio6 (min temperature of coldest month)
```

# SDM (IGNORE IMCOMPLETE)
```{r}

# # Load required libraries
library(biomod2)

# Load your environmental data
env_data <- cur
species_data <- data.frame(coords[,c("x", "y")], presence = 1)
pseudo_absence <- spatSample(env_data, 100, xy = TRUE, na.rm = TRUE)
pseudo_absence$presence <- 0
species_data <- bind_rows(species_data, pseudo_absence) %>% select(x, y, presence) 

plot(cur[[1]])
points(species_data[,c("x", "y")], col = species_data$presence + 1)
# Prepare the data for biomod2
myBiomodData <- BIOMOD_FormatingData(resp.var = species_data$presence,
                                     expl.var = env_data,
                                     resp.xy = species_data[, c('x', 'y')],
                                     resp.name = 'Sceloporus')

# Define the models you want to run

# Define the models you want to run
myBiomodModelOut <- BIOMOD_Modeling(myBiomodData,
                                    models = 'RF',
                                    modeling.id = 'test',
                                    CV.perc = 0.9,
                                    CV.nb.rep = 10)

myProjection <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                  new.env = env_data,
                                  proj.name = 'MyProjection',
                                  selected.models = 'all')    

LH <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                  new.env = lgm,
                                  proj.name = 'LH',
                                  selected.models = 'all')                                    

cur_sdm <- mean(get_predictions(myProjection))/1000
lh_sdm <- mean(get_predictions(LH))/1000
plot(cur_sdm)
plot(lh_sdm)
plot(cur_sdm - lh_sdm, col = palette)

source(here("analysis", "genetic_diversity", "genetic_diversity.R"))
het <- get_het()
coords <- left_join(coords, het)
dif_lgm <- cur - lgm
dif_vals <- extract(dif_lgm, coords[,c("x", "y")], ID = FALSE)
mod_df <- data.frame(Ho = coords$Ho, dif_vals)
pc <- prcomp(mod_df[,-1], scale = TRUE)

res <- summary(lm(Ho ~ ., data = mod_df))
sigvars <- names(which(res$coefficients[,"Pr(>|t|)"] < 0.05))[-1]

gg_df <- mod_df %>% pivot_longer(all_of(sigvars))
ggplot(gg_df) + 
  geom_point(aes(x = value, y = Ho)) + 
  geom_smooth(aes(x = value, y = Ho), method = "lm") +
  facet_wrap(~name, scales = "free")

gg_df <- mod_df %>% pivot_longer(all_of("bio_9"))
ggplot(gg_df) + 
  geom_point(aes(x = value, y = Ho)) + 
  geom_smooth(aes(x = value, y = Ho), method = "lm") +
  facet_wrap(~name, scales = "free")
plot(dif_lgm[["bio_9"]])

pcs <- data.frame(pc$x[,1:3])
pcmod_df <- data.frame(Ho = coords$Ho, pcs)
res <- summary(lm(Ho ~ ., data = pcmod_df))
sigvars <- names(which(res$coefficients[,"Pr(>|t|)"] < 0.05))[-1]
gg_df <- pcmod_df %>% pivot_longer(all_of(sigvars))
ggplot(gg_df) + 
  geom_point(aes(x = value, y = Ho)) + 
  geom_smooth(aes(x = value, y = Ho), method = "lm") +
  facet_wrap(~name, scales = "free")
#sdm <- sdm(coordinates =  coords[,c("x", "y")], envlayers = stack(lgm), models = "RF", nbkg = 1000, tune = TRUE)
```

# Recent climate
Download PRISM max temperature data from historical data: https://prism.oregonstate.edu/historical/
```{r}
caladapt <- map(list.files(here("data", "env", "caladapt"), pattern = ".tif", full.names = TRUE), rast) %>% rast()

names(caladapt)

caladapt1950 <- caladapt[["livneh_year_Tmax_clip_15Oct2014.1950"]]
caladapt2013 <- caladapt[["livneh_year_Tmax_clip_15Oct2014.2013"]]
dif <- caladapt2013 - caladapt1950
plot(dif)
```

```{r}
# Function to calculate yearly average from monthly files
coords <- get_coords(sf = TRUE)
year = 1895
calculate_yearly_avg <- function(year  = 1895, type = "historical") {
  if (type == "historical") directory_path <- here::here("data", "env", "prism", "PRISM_tmax_stable_4kmM3_189501_198012_bil")
  if (type == "current") directory_path <- here::here("data", "env", "prism", "PRISM_tmax_stable_4kmM3_198101_202308_bil")
  monthly_files <- list.files(directory_path, pattern = "*.bil.bil$", full.names = TRUE)
  monthly_files <- monthly_files[grepl(paste0("PRISM_tmax_stable_4kmM3_", year), monthly_files)]
  if (length(monthly_files) > 0) {
    rasters <- purrr::map(monthly_files, terra::rast)
    rasters <- terra::rast(rasters)
    vals <- terra::extract(rasters, st_transform(coords, st_crs(rasters)))
    annual_avg <- rowMeans(vals, na.rm = TRUE)
    rm(rasters)
    gc()
    return(data.frame(year = year, tmax = annual_avg, SampleID = coords$SampleID))
  } else {
    return(NULL)
  }
}

# Loop over the years of interest
years <- 1895:1925 # Update this to the range of years you have data for
tmax_his <- map(1895:1925, ~calculate_yearly_avg(.x, type = "historical"), .progress =TRUE) %>% bind_rows()  
tmax_his <- tmax_his %>% group_by(SampleID) %>% summarise(tmax_his = mean(tmax, na.rm = TRUE))
tmax_cur <- map(1986:2016, ~calculate_yearly_avg(.x, type = "current"), .progress =TRUE) %>% bind_rows()  
tmax_cur <- tmax_cur %>% group_by(SampleID) %>% summarise(tmax_cur = mean(tmax, na.rm = TRUE))
tmax <- 
left_join(tmax_his, tmax_cur) %>% 
mutate(dif = tmax_cur - tmax_his) %>%
right_join(coords) %>% st_as_sf()

ggplot(tmax) +
  geom_sf(data = ca) +
  geom_sf(aes(color = dif)) +
  scale_color_viridis_c(option = "magma", direction = -1) +
  theme_void()

froh <- get_roh()
tmax <- left_join(tmax, froh)

summary(lm(froh0 ~ dif, data =tmax))
summary(lm(froh0 ~ tmax_cur, data =tmax))
```

```{r}

# Compute the long-term average from 1895 to 1925
# Assuming you have all the annual averages from 1895 to 1925 stored in 'annual_averages'
long_term_avg <- app(stack(annual_averages), mean)
```