---
title: "IBD/IBE analysis"
output:
  github_document:
    toc: TRUE
---

# Format genetic distances
```{r}
library(tidyverse)
library(here)
library(algatr)
library(terra)
library(sf)
library(cowplot)
source(here("general_functions.R"))
source(here("analysis", "ibdibe", "functions_ibdibe.R"))
plotpath <- here("analysis", "ibdibe", "plots")
```

```{r}
# Format distances and write out file
format_dist()
```

```{r}
ca <- get_ca()
range_map <- get_range()
coords <- get_coords()
```


```{r}
gendist <- get_gendist() 
stopifnot(dim(gendist) == c(259, 259))

genedist <- get_genedist()

gendist_coords <- 
  coords %>% 
  filter(SampleID %in% row.names(gendist)) %>%
  mutate(SampleID = factor(SampleID, levels = row.names(gendist))) %>%
  arrange(SampleID)

stopifnot(gendist_coords$SampleID == row.names(gendist))
stopifnot(gendist_coords$SampleID == row.names(genedist))
```

```{r}
envstack <- 
  rast(here("data", "env", "california_chelsa_bioclim_1981-2010_V.2.1_pca.tif")) %>%
  terra::project("epsg:3310")
env_agg <- mask(envstack, get_range())

bioclim <- rast(here("data", "env", "california_chelsa_bioclim_1981-2010_V.2.1.tif"))  %>% project("epsg:3310")
bio1 <- bioclim[["CHELSA_bio1_1981-2010_V.2.1"]]
ndvi <- rast(here("data", "env", "california_ndvi_mean_2000_2020.tif")) %>% project("epsg:3310")
ndvi <- resample(ndvi, bio1, method = "bilinear")
envstack <- c(bio1, ndvi)
names(envstack) <- c("Temperature", "NDVI")
env_agg <- mask(envstack, get_range())
#plot(envstack, axes = FALSE, box = FALSE)

```

# GDM

```{r, fig.width = 5, fig.height = 5}
coords_proj <- 
  gendist_coords[,c("x", "y")] %>% 
  st_as_sf(coords = c("x", "y"), crs = 4326) %>% 
  st_transform(3310)

env <- terra::extract(envstack, coords_proj, ID = FALSE)

gdm <- gdm_do_everything(gendist = gendist, coords = gendist_coords[,c("x", "y")], env = env, quiet = TRUE)

print(gdm$coeff_df)

pdf(here("gdm_out.pdf"))
maps <- gdm_map(gdm$model, env_agg, coords_proj, plot_vars = FALSE)
dev.off()

ca_proj <- ca %>% st_transform(3310) 
coords_rgb <-
  cbind(coords_proj, terra::extract(maps$pcaRastRGB, coords_proj, ID = FALSE)) %>%
  mutate(across(starts_with("PC"), ~ scales::rescale(.x, to = c(0, 1)))) %>%
    drop_na()


rgb_df <- 
  as.data.frame(maps$pcaRastRGB, xy = TRUE) %>%
  mutate(across(starts_with("PC"), ~ scales::rescale(.x, to = c(0, 1))))

rgb_map <-
 ggplot(rgb_df) +
  geom_sf(data = ca_proj) +
  geom_raster(aes(x = x, y = y, fill = rgb(PC1, PC2, PC3))) +
  geom_sf(data = coords_rgb, aes(fill = rgb(PC1, PC2, PC3)), col = "black", pch = 21, alpha = 0.7, cex = 3) +
  theme_void() +
  scale_fill_identity() +
  theme(legend.position = "none")

rgb_legend <- 
  gdm_pc(gdm$model, env_agg, coords_proj, scl = 0.6) +
  theme(
    plot.background = element_rect(fill = NA, color = NA),       # transparent background
    panel.background = element_rect(fill = NA, color = NA)
  ) +
  coord_equal(clip = "off")

rgb_plt <- 
  ggdraw() +
  draw_plot(rgb_map) +  # main plot
  draw_plot(rgb_legend, 
            x = 0.5, y = 0.5, 
            width = 0.45, height = 0.45)  # inset

```
```{r}
plt1 <- gdm_plot_diss(gdm$model) 
plt2 <- gdm_plot_isplines(gdm$model, env = env, coords = coords, scales = "free_x", nrow = 1)
group1 <- plot_grid(plt1, plt2, ncol = 1, labels = c("A", "B"))

pdf(here(plotpath, "gdm_outputs.pdf"), width = 15, height = 7)
plot_grid(group1, rgb_plt, ncol = 2, rel_widths = c(1, 0.8), labels = c("", "C")) 
dev.off()

png(here(plotpath, "gdm_outputs.png"), width = 15*300, height = 7*300, res = 300)
plot_grid(group1, rgb_plt, ncol = 2, rel_widths = c(1, 0.8), labels = c("", "C"))
dev.off()

```

```{r}
future <- rast(here("analysis", "gea", "outputs", "scelop_adaptive_env_layers","env_fut_2071-2100_GFDL-ESM4_ssp126_ssp585.tif"))[[2:3]] %>% project("epsg:3310")
names(future) <- c("bio1", "ndvi")
future <- crop(future, envstack)
future <- mask(future, envstack)
gdm_offset_map <- predict(gdm$model, envstack, time = TRUE, predRasts = future)

pdf(here(plotpath, "gdm_offset_map.pdf"), width = 5, height = 5)
plot(gdm_offset_map, axes = FALSE, box = FALSE, col = viridis::rocket(100))
dev.off()

source(here("general_functions.R"))
source(here("analysis", "genetic_diversity", "functions_genetic_diversity.R"))
model_df <- read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv"))
df <- 
  read_table(here("data", "ccgp_data_may2025backup", "58-Sceloporus.coords.txt"), col_names = c("SampleID", "x", "y")) %>%
  st_as_sf(coords = c("x", "y"), crs = 4326) %>%
  left_join(get_het()) %>%
  st_transform(3310) 
  
df$gdm_offset <- terra::extract(gdm_offset_map, df, ID = FALSE)[,1]

df2 <- model_df %>% left_join(get_coords(sf = TRUE)) %>% st_as_sf()
df2$bio1 <- terra::extract(envstack[["bio1"]], df2, ID = FALSE)[,1]
df2$bio1_future <- terra::extract(future[["bio1"]], df2, ID = FALSE)[,1]
df2$future_change <- df2$bio1_future - df2$bio1
df2$gdm_offset <- terra::extract(gdm_offset_map, df2, ID = FALSE)[,1]

cor.test(df2$tmean_dif, df2$gdm_offset)

cor.test(df$Ho, df$gdm_offset, method = "pearson")

pdf(here(plotpath, "gdm_offset_vs_pastcc.pdf"), width = 4, height = 4)
ggplot(df2, aes(x = tmean_dif, y = Ho)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE, col = "black") +
  labs(x = "Past climate change", y = "Genome-wide heterozygosity") +
  theme_classic() +
  scale_color_viridis_c(option = "rocket") +
  #ggpubr::stat_cor(label.y = min(df$Ho, na.rm = TRUE)) +
  theme(legend.position = "none")

ggplot(df2, aes(x = tmean_dif, y = gdm_offset)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE, col = "black") +
  labs(y = "Future genomic offset", x = "Past climate change (°C)") +
  theme_classic() +
  scale_color_viridis_c(option = "rocket") +
  ggpubr::stat_cor(label.y = min(df2$gdm_offset, na.rm = TRUE)) +
  theme(legend.position = "none")
ggplot(df2, aes(x = tmean_dif, y = future_change)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE, col = "black") +
  labs(y = "Future genomic offset", x = "Past climate change (°C)") +
  theme_classic() +
  scale_color_viridis_c(option = "rocket") +
  ggpubr::stat_cor(label.y = min(df2$future_change, na.rm = TRUE)) +
  theme(legend.position = "none")
ggplot(df2, aes(x = future_change, y = Ho)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE, col = "black") +
  labs(y = "Ho", x = "Future climate change (°C)") +
  theme_classic() +
  scale_color_viridis_c(option = "rocket") +
  ggpubr::stat_cor(label.y = min(df2$Ho, na.rm = TRUE)) +
  theme(legend.position = "none")
dev.off()
gdm_offset_df <- 
  as.data.frame(gdm_offset_map, xy = TRUE) %>%
  filter(lyr1 < max(df$gdm_offset, na.rm = TRUE), lyr1 > min(df$gdm_offset, na.rm = TRUE)) 

pdf(here(plotpath, "gdm_isplines.pdf"), width = 8, height = 3)
gdm_plot_isplines(gdm$model)
dev.off()

pdf(here(plotpath, "gdm_maps.pdf"), width = 5, height = 5)
map <- gdm_map(gdm$model, envstack,  coords_proj, plot_vars = TRUE)
dev.off()

raw_map_df <-
  envstack %>%
  as.data.frame(xy = TRUE) %>%
  select(bio1, ndvi, x, y) %>%
  mutate_at(vars(bio1, ndvi), scale) %>%
  pivot_longer(cols = -c(x, y), names_to = "variable", values_to = "value") %>%
  mutate(type = "Original env layers")

trans_map_df <- 
  map$rastTrans %>% 
  as.data.frame(xy = TRUE) %>% 
  select(bio1, ndvi, x, y) %>% 
  mutate_at(vars(bio1, ndvi), scale) %>%
  pivot_longer(cols = -c(x, y), names_to = "variable", values_to = "value") %>%
  mutate(type = "Transformed env layers") %>%
  bind_rows(raw_map_df) 


pdf(here(plotpath, "gdm_transform.pdf"), width = 6, height = 6)
ggplot(trans_map_df) +
  geom_sf(data = st_transform(ca, 3310)) +
  geom_raster(aes(x = x, y = y, fill = value)) +
  facet_grid(type~variable) +
  scale_fill_viridis_c(option = "viridis", na.value = NA) +
  theme_void() +
  theme(legend.position = "none")
dev.off()

pdf(here(plotpath, "gdm_offset_vs_het.pdf"), width = 8.5, height = 4)
plt1 <- 
  ggplot(gdm_offset_df) +
  geom_sf(data = st_transform(ca, 3310)) +
  geom_raster(aes(x = x, y = y, fill = lyr1)) +
  geom_sf(data = df, aes(fill = gdm_offset), pch = 21, cex = 1.5) +
  scale_fill_viridis_c(option = "rocket", na.value = NA, direction = -1) +
  theme_void()  +
  labs(fill = "Future\ngenomic\noffset") +
  theme(legend.position = "right") 

plt2 <- 
  ggplot(df, aes(x = (gdm_offset), y = Ho)) +
  geom_point(aes(col = gdm_offset)) +
  geom_smooth(method = "lm", se = TRUE, col = "black") +
  labs(y = "Genome-wide heterozygosity", x = "Future genomic offset") +
  theme_classic()+
  scale_color_viridis_c(option = "rocket") +
  ggpubr::stat_cor(label.y = min(df$Ho, na.rm = TRUE)) +
  theme(legend.position = "none")

cowplot::plot_grid(plt2, plt1, nrow = 1, rel_widths = c(1, 1))
dev.off()
```

```{r}
ggmaps <- 
  as.data.frame(maps$pcaRastRGB, xy = TRUE) %>% 
  pivot_longer(cols = -c(x, y), names_to = "variable", values_to = "value")

ggplot(ggmaps) +
  geom_sf(data = st_transform(ca, 3310)) +
  geom_raster(aes(x = x, y = y, fill = value)) +
  facet_wrap(~variable, nrow = 1) +
  scale_fill_viridis_c(option = "magma", na.value = NA) +
  theme_void()
```

# MMRR
```{r, fig.width = 6.5, fig.height = 6}
coords_proj <- 
  gendist_coords[,c("x", "y")] %>% 
  st_as_sf(coords = c("x", "y"), crs = 4326) %>% 
  st_transform(3310)

env <- terra::extract(envstack, coords_proj, ID = FALSE)

mmrr <- mmrr_do_everything(gendist = gendist, coords = gendist_coords[,c("x", "y")], env = env, quiet = FALSE)

print(mmrr$coeff_df)

mmrr_df <- 
  dist_to_df(mmrr$Y, mmrr$X, stdz = TRUE) %>%
  mutate(var = 
    case_when(
      var == "geodist" ~ "Geographic distance",
      var == "ndvi" ~ "NDVI distance",
      var == "bio1" ~ "Temperature distance"
    )
  )

mod_xy <- 
  mmrr_df %>%
  group_by(var) %>%
  summarize(X = max(X, na.rm = TRUE), Y = min(Y, na.rm = TRUE)) 

mod_df <- 
  mmrr$coeff_df %>% 
  mutate(estimate = round(estimate, 2)) %>%
  filter(var != "Intercept") %>%
  mutate(var = 
    case_when(
      var == "geodist" ~ "Geographic distance",
      var == "ndvi" ~ "NDVI distance",
      var == "bio1" ~ "Temperature distance"
    )
  ) %>%
  left_join(mod_xy, by = "var")

png(here("analysis", "ibdibe", "plots", "mmrr.png"), width = 8, height = 3, units = "in", res = 300)
ggplot(mmrr_df, aes(x = X, y = Y)) +
  geom_hex(bins = 50) +
  scale_fill_viridis_c(option = "magma", na.value = NA) +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~var, scales = "free") +
  geom_text(data = mod_df, aes(label = paste("Estimate:", estimate, "\n", "p:", p)), hjust = 1, vjust = -0.3, cex = 3.5) +
  labs(y = "Genetic distance", x = "Predictor distance") +
  theme_classic() +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(size = 10))
dev.off()
```

# GENE GDM

```{r}
coords_proj <- 
  gendist_coords[,c("x", "y")] %>% 
  st_as_sf(coords = c("x", "y"), crs = 4326) %>% 
  st_transform(3310)

env <- terra::extract(envstack, coords_proj, ID = FALSE)

gdm <- gdm_do_everything(gendist = genedist, coords = gendist_coords[,c("x", "y")], env = env, quiet = TRUE)

print(gdm$coeff_df)

gdm_plot_isplines(gdm$model)

pdf(here("analysis", "ibdibe", "plots", "gene_gdm.pdf"), width = 5, height = 5)
maps <- gdm_map(gdm$model, env_agg, coords_proj, plot_vars = TRUE)
dev.off()

rgb_mask <- mask(maps$pcaRastRGB, get_range())
#plotRGB(rgb_mask)
#rgb_envonly <- stack_to_rgb(maps$rastTrans[[3:5]])
#plotRGB(rgb_envonly)
#points(coords_proj, pch = 1, cex = 1)

rgb_df <- 
  as.data.frame(rgb_mask, xy = TRUE) %>%
  mutate(across(starts_with("PC"), ~ scales::rescale(.x, to = c(0, 1))))
ca_proj <- ca %>% st_transform(3310) 
coords_rgb <-
  cbind(coords_proj, terra::extract(rgb_mask, coords_proj, ID = FALSE)) %>%
  mutate(across(starts_with("PC"), ~ scales::rescale(.x, to = c(0, 1))))


pdf(here("analysis", "ibdibe", "plots", "gdm_genes.pdf"), width = 5, height = 5)
ggplot(rgb_df) +
  geom_sf(data = ca_proj) +
  geom_raster(aes(x = x, y = y, fill = rgb(PC1, PC2, PC3))) +
  geom_sf(data = coords_rgb, aes(fill = rgb(PC1, PC2, PC3)), col = "black", pch = 21, alpha = 0.7) +
  theme_void() +
  scale_fill_identity() +
  theme(legend.position = "none")
dev.off()
```

## Paleoclimate

```{r, eval = FALSE}
envstack <- rast(here("data", "env", "paleoclim", "paleoclim.tif"))
lhstack <- envstack[[grepl("lh", names(envstack))]]
lhpcs <- RStoolbox::rasterPCA(lhstack, nComp = 3, scale = TRUE)
lhpcs <- lhpcs$map

coords_proj <- gendist_coords[,c("x", "y")] %>% st_as_sf(coords = c("x", "y"), crs = 4326) 
env <- terra::extract(lhpcs, coords_proj, ID = FALSE)

gdm_lh <- gdm_do_everything(gendist = gendist, coords = gendist_coords[,c("x", "y")], env = env, quiet = TRUE)

print(gdm_lh$coeff_df)

maps_lh <- gdm_map(gdm_lh$model, lhpcs, coords_proj, plot_vars = FALSE)

#rgb_envonly <- stack_to_rgb(maps_lh$rastTrans[[3:5]])
#rgb_envonly <- stack_to_rgb(maps_lh$rastTrans)
plotRGB(maps_lh$pcaRastRGB)
points(coords_proj, pch = 1, cex = 1)
```
```{r, eval = FALSE}
curstack <- envstack[[grepl("cur", names(envstack))]]
curpcs <- RStoolbox::rasterPCA(curstack, nComp = 3, scale = TRUE)
curpcs <- curpcs$map

coords_proj <- gendist_coords[,c("x", "y")] %>% st_as_sf(coords = c("x", "y"), crs = 4326) 
env <- terra::extract(curpcs, coords_proj, ID = FALSE)

gdm_cur <- gdm_do_everything(gendist = gendist, coords = gendist_coords[,c("x", "y")], env = env, quiet = TRUE)

print(gdm_cur$coeff_df)

maps <- gdm_map(gdm_cur$model, curpcs, coords_proj, plot_vars = FALSE)
plotRGB(maps$pcaRastRGB)
points(coords_proj, pch = 1, cex = 1)
```

```{r, eval = FALSE}
bio2 <- envstack[[grepl("lh_2", names(envstack))]]

coords_proj <- gendist_coords[,c("x", "y")] %>% st_as_sf(coords = c("x", "y"), crs = 4326) 
env <- terra::extract(bio2, coords_proj, ID = FALSE)

gdm_bio2 <- gdm_do_everything(gendist = gendist, coords = gendist_coords[,c("x", "y")], env = env, quiet = TRUE)

print(gdm_bio2$coeff_df)

maps <- gdm_map(gdm_bio2$model, bio2, coords_proj, plot_vars = FALSE)
plotRGB(maps$pcaRastRGB)
points(coords_proj, pch = 1, cex = 1)
print(gdm_bio2$coeff_df)
```

```{r, eval = FALSE}
print(gdm_cur$coeff_df)
print(gdm_lh$coeff_df)
```  
