analysis/ibdibe/notebook_ibdibe.Rmd---
title: "IBD/IBE analysis"
output:
  github_document:
    toc: TRUE
---

# Format genetic distances
```{r}
library(tidyverse)
library(here)
library(algatr)
library(terra)
library(sf)
library(cowplot)
source(here("general_functions.R"))
source(here("analysis", "ibdibe", "functions_ibdibe.R"))
plotpath <- here("analysis", "ibdibe", "plots")
```

```{r}
# Format distances and write out file
format_dist()
```

```{r}
ca <- get_ca()
range_map <- get_range()
coords <- get_coords()
```

```{r}
gendist <- get_gendist() 
stopifnot(dim(gendist) == c(259, 259))

genedist <- get_genedist()

gendist_coords <- 
  coords %>% 
  filter(SampleID %in% row.names(gendist)) %>%
  mutate(SampleID = factor(SampleID, levels = row.names(gendist))) %>%
  arrange(SampleID)

gendist <- gendist[as.character(gendist_coords$SampleID), as.character(gendist_coords$SampleID)]
genedist <- genedist[as.character(gendist_coords$SampleID), as.character(gendist_coords$SampleID)]

stopifnot(gendist_coords$SampleID == row.names(gendist))
stopifnot(gendist_coords$SampleID == row.names(genedist))
```

```{r}
# Get current environment layers
bioclim <- rast(here("data", "env", "california_chelsa_bioclim_1981-2010_V.2.1.tif"))
bio1 <- bioclim[["CHELSA_bio1_1981-2010_V.2.1"]]
ndvi <- rast(here("data", "env", "california_ndvi_mean_2000_2020.tif"))

# Get paleoclimate layers
source(here("analysis", "genetic_diversity", "functions_paleovars.R"))
lig <- get_paleovars("lig")[["lig"]][["bio_1"]]/10
names(lig) <- "LIGTemperature"
lgm <- rast(here("data", "env", "california_chelsa_pmip_ccsm4.tif"))
names(lgm) <- "LGMTemperature"

# Get gHM layers
ghm <- rast(here("data", "env", "california_global_human_modification_2016.tif"))

# Get fire layers # CHANGE PATHS
model_df <- read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv"))
fri <- rast(here("analysis", "wildfire", "california_fri.tif"))
vdep <- rast(here("analysis", "wildfire", "california_vdep.tif"))
fri_1km <- rast(here("analysis", "wildfire", "california_fri_aggregate1km.tif"))
```

```{r}
envlist <- list(
  `Current_temperature` = bio1,
  `Current_NDVI` = ndvi,
  `LIG_temperature` = lig,
  `LGM_temperature` = lgm,
  `Human_modification` = ghm
)

agg_lyr <- terra::aggregate(bio1, fact = 4, fun = mean)
ca <- get_ca()
env_agg <- map(envlist, function(x) {
  x <- terra::resample(x, agg_lyr, method = "bilinear")
}, .progress = TRUE)
envstack <- rast(env_agg)
```

# GDM
```{r, eval = FALSE}
coords_proj <- gendist_coords[,c("x", "y")] %>% st_as_sf(coords = c("x", "y"), crs = 4326) 
env <- 
  map(envlist, ~{
    terra::extract(.x, coords_proj)[,2]
  }) %>% 
  bind_cols() %>%
  mutate(SampleID = gendist_coords$SampleID) %>%
  left_join(model_df) %>%
  select(fire_severity, fire_frequency, Current_temperature, Current_NDVI, LIG_temperature, LGM_temperature, lh, eh, mh, Human_modification) 

cor(env, use = "pairwise.complete.obs")

source(here("analysis", "ibdibe", "gdm.R")) # BUG IN GDM PACKAGE, USING FIXED VERSION
gdm <- gdm_do_everything(gendist = gendist, coords = gendist_coords[,c("x", "y")], env = env, quiet = TRUE, model = "best", nperm = 99)

print(gdm$coeff_df)
```

```{r}
# Final variables
env_sub <- env[, c("LIG_temperature", "LGM_temperature")]
gdm_sub <- gdm_do_everything(gendist = gendist, coords = gendist_coords[,c("x", "y")], env = env_sub, quiet = TRUE, model = "full")

coords_proj <- gendist_coords[,c("x", "y")] %>% st_as_sf(coords = c("x", "y"), crs = 4326)
pdf(here("gdm_out.pdf"))
envstack[["fire_severity"]] <- envstack[[1]]
env_agg[["fire_severity"]] <- env_agg[[1]]
maps <- gdm_map(gdm_sub$model, envstack, coords_proj, plot_vars = FALSE)
dev.off()

coords_rgb <-
  cbind(coords_proj, terra::extract(maps$pcaRastRGB, coords_proj, ID = FALSE)) %>%
  mutate(across(starts_with("PC"), ~ scales::rescale(.x, to = c(0, 1)))) %>%
  drop_na()

rgb_df <- 
  as.data.frame(maps$pcaRastRGB, xy = TRUE) %>%
  mutate(across(starts_with("PC"), ~ scales::rescale(.x, to = c(0, 1))))

rgb_map <-
  ggplot(rgb_df) +
  geom_sf(data = ca) +
  #geom_raster(aes(x = x, y = y, fill = rgb(PC1, PC2, PC3))) +
  geom_sf(data = coords_rgb, aes(fill = rgb(PC1, PC2, PC3)), col = "black", pch = 21, alpha = 1, cex = 3) +
  theme_void() +
  scale_fill_identity() +
  theme(legend.position = "none")

```
```{r}
# Get prettier diss plotting functions
source(here("analysis", "ibdibe", "functions_ibdibe.R"))

rgb_legend <- 
  gdm_pc(gdm_sub$model, env_agg, coords_proj, scl = 1) +
  theme(
    plot.background = element_rect(fill = NA, color = NA),       # transparent background
    panel.background = element_rect(fill = NA, color = NA)
  ) +
  coord_equal(clip = "off")

rgb_plt <- 
  ggdraw() +
  draw_plot(rgb_map) +  # main plot
  draw_plot(rgb_legend, 
            x = 0.5, y = 0.5, 
            width = 0.45, height = 0.45)  # inset

plt1 <- gdm_plot_diss(gdm_sub$model) 
sig_vars <- gdm_sub$coeff_df$predictor[gdm_sub$coeff_df$predictor != "Geographic"] 
plt2 <- gdm_plot_isplines(gdm_sub$model, scales = "free_x", env = env[,sig_vars], coords = coords, nrow = 1)
plt1 <- plt1 + theme(plot.margin = margin(t = 20, r = 5, b = 5, l = 20))
plt2 <- plt2 + theme(plot.margin = margin(t = 20, r = 5, b = 5, l = 20))

group1 <- plot_grid(plt1, plt2, ncol = 1, labels = c("A", "B"), label_size = 16)

pdf(here(plotpath, "gdm_outputs.pdf"), width = 15, height = 7)
plot_grid(group1, rgb_plt, ncol = 2, rel_widths = c(1, 0.8), labels = c("", "C"), label_size = 16) 
dev.off()

png(here(plotpath, "gdm_outputs.png"), width = 15*300*0.9, height = 7*300*0.9, res = 300)
plot_grid(group1, rgb_plt, ncol = 2, rel_widths = c(1, 0.8), labels = c("", "C"), label_size = 16)
dev.off()

```

```{r}
# Calculate variable importance
map(gdm$varimp, ~.x[,3])

pvalues <- gdm$varimp$`Predictor p-values`
final_col <- which(apply(pvalues, 2, function(x) all(x <= 0.05, na.rm = TRUE)))
varimp <- map(gdm$varimp, ~.x[,final_col])
varimp <- map(varimp, ~.x[!is.na(.x)])

df <- 
  varimp[-1] %>% 
  bind_rows(.id = "Statistic") %>%
  pivot_longer(-Statistic) %>%
  pivot_wider(names_from = Statistic, values_from = value) %>%
  rename(Predictor = name) %>%
  mutate(Predictor = ifelse(Predictor == "matrix_1", "Geographic distance", Predictor))

df
varimp[1]
```