---
title: "GREG_SDM"
output: html_document
---
```{r}
library("raster")
```

```{r}
liz <- read.csv("lizard_coords.csv")
plot(liz$x, liz$y)
```


```{r, }
wclim <- getData('worldclim', var='bio', res=0.5, lon=-121.6, lat=36.8)
wclimEast <- getData('worldclim', var='bio', res=0.5, lon=-118, lat=36.8)
```

```{r, }
bio1 <- wclim$bio1_11 
bio12 <- wclim$bio12_11 #annual precip.

bio1East <- wclimEast$bio1_12 #temp
bio12East <- wclimEast$bio12_12 #annual precip.

stackWest <- stack(bio1, bio12) # make a raster stack
stackEast <- stack(bio1East, bio12East)
bioStack <- merge(stackWest, stackEast) # now make a new stack by merging the East and West stacks
bioStack
```

```{r, }
env <- crop(bioStack, extent(-125, -110, 32, 42))
names(env) <- c("temp","prec")
```

```{r}
plot(env[[1]])
points(liz$x, liz$y)
```

```{r}
library(randomForest)
pts <- liz[liz$ï..genus == "Sceloporus",c("x","y")]
vals <- raster::extract(env, pts)
vals <- data.frame(vals)
vals$occ <- 1
vals <- vals[complete.cases(vals),]

pts0 <- liz[liz$ï..genus == "Sceloporus",c("x","y")]
vals0 <- raster::extract(env, pts0)
vals0 <- data.frame(vals0)
vals0$occ <- 0
vals0 <- vals0[complete.cases(vals0),]
vals0 <- vals0[sample(nrow(vals0), 150),]

vals <- rbind(vals, vals0)

mod <- lm(occ ~ ., vals)
map <- predict(env, mod)
plot(map)
points(pts)
```

```{r, fig.width = 6, fig.height = 6}
library(terra)
library(viridis)
library(sf)
wg <- rast("wingen_map.tif")
sfpt <- st_as_sf(pts, coords = c("x", "y"))

plot(wg, col = magma(100), box = FALSE, axes = FALSE)

points(pts, pch = 16, cex = 1, col = mako(1, begin = 0.75))

wg2 <- disagg(wg, 5)
plot(wg2, col = magma(100))
```

