
# SDM

BIOMOD: https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html

```{r}
library(countrycode)
library(CoordinateCleaner)
library(rgbif)
library(sp)
library(here)
library(raster)
library(dismo)
library(tidyverse)
library(viridis)
library(biomod2)
library(sf)
library(terra)
library(ggpubr)
# devtools::install_github('adamlilith/enmSdm', dependencies=TRUE)
library(enmSdm)
library(RStoolbox)
source(here("analysis", "sdm", "bias.R"))
source(here("analysis", "sdm", "sdm.R"))
source(here("analysis", "sdm", "get_coords.R"))
source(here("analysis", "sdm", "paleovars.R"))
source(here("general_functions.R"))

# set maxent path
# put maxent.jar in your working directory (what you get when you run getwd()) or set manually: https://rdrr.io/cran/biomod2/man/BIOMOD_ModelingOptions.html
Sys.setenv(JAVA_HOME='/usr/lib/jvm/java-11-openjdk-amd64')

# get env data
env_list <- get_paleovars()
env_list_agg <- map(env_list, ~aggregate(.x, 2))
cur <- env_list[["cur"]]
lh <- env_list[["lh"]]

# pca
selected_vars <- pc_var_selection(cur)
```

```{r}
# Get species list
df <- get_ccgp_meta()
head(df)

# Download occurrence data
occ_coords <- get_occ_coords("Sceloporus occidentalis", data_source = "gbif", occ_limit = 10000, cache = TRUE)
```
```{r}
# get coordinates
occ_coords <- get_occ_coords("Sceloporus occidentalis", data_source = "both", occ_limit = 10000, cache = TRUE)

# get or create bias background layer
bias_class <- get_bias("Sceloporus occidentalis", rank = "class", limit = 10000, n = 10000, cache = TRUE)

envlayers <- cur[[selected_vars]]
envlayers <- rast(here("data", "env", "CLEANED_ENVDATA_NOCOR.tif"))

# run SDM
sdm_mod <- 
  sdm(
    coordinates = occ_coords,
    envlayers = envlayers, 
    biasdat = bias_class, 
    models = "RF", 
    BIOMOD_name = "BIOMOD", 
    tune = FALSE
    )

sdm_raster <- sdm_mod$raster
#writeRaster(sdm_raster, here("analysis", "sdm", "outputs", "sdm.tif"))
sdm_raster <- rast(here("analysis", "sdm", "outputs", "sdm.tif"))

cutoff <- 
  sdm_mod$eval %>% 
  filter(metric.eval == "TSS") %>% 
  pull(cutoff) 
  
bin_raster <- sdm_raster
bin_raster[bin_raster > cutoff/1000] <- 1
bin_raster[bin_raster <= cutoff/1000] <- 0
plot(bin_raster)

# hindcast SDMs
hindcast_sdms <- 
  map(
    env_list[c("lig", "lgm", "hs1", "ba", "yds", "eh", "mh", "lh", "cur")],
   ~hindcast(sdm_mod$myBiomodModelOut, new_env = .x[[selected_vars]])
   )
hindcast_sdms <- rast(hindcast_sdms)
writeRaster(hindcast_sdms, here("outputs", "hindcast_sdms.tif"))

# calculate change and stability
# TODO: PLAY AROUND WITH TIMEPERIOD USED TO CALCULATE DIF_SDM AND STABILITY
cur_sdm <- sdm_mod$raster 
dif_sdm <- cur_sdm - hindcast_sdms[["lh"]]

hindcast_subset <- subset(hindcast_sdms, c("hs1", "ba", "yds", "eh", "mh", "lh", "cur"))
stability <- app(hindcast_subset, mean, na.rm =TRUE)
variability <- app(hindcast_subset, sd, na.rm =TRUE)
plot(stability, col = mako(100))
plot(variability, col = mako(100))
plot(dif_sdm, col = viridis(100))

trend <- global(hindcast_subset, mean, na.rm = TRUE)
trend <- data.frame(mean = trend, tp = rownames(trend)) %>% mutate(tp = factor(tp, levels = names(hindcast_subset)))
ggplot(trend) + geom_line(aes(x = tp, y = mean, group = 1))

# compare to genetic diversity
het <- get_het()
roh <- get_roh()
coords <- get_coords(sf = TRUE) %>% left_join(het) %>% left_join(roh)
change_vals <- extract(dif_sdm, coords, ID = FALSE)
stability_vals <- extract(stability, coords, ID = FALSE)
cur_vals <- extract(cur_sdm, coords, ID = FALSE)
# df <- data.frame(cur = cur_vals, coords)
df <- data.frame(change = change_vals[,1], stability = stability_vals[,1],  cur = cur_vals[,1], coords)
ggplot(df, aes(x = change, y = Ho)) +
  geom_point() +
  stat_regline_equation(
      aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
      formula = y ~ x
    ) +
  geom_smooth(method = "lm") +
  stat_cor(label.y = 0) +
  theme_classic()

ggplot(df, aes(x = stability, y = Ho)) +
  geom_point() +
  stat_regline_equation(
      aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
      formula = y ~ x
    ) +
  geom_smooth(method = "lm") +
  stat_cor(label.y = 0) +
  theme_classic()

ggplot(df, aes(x = cur, y = Ho)) +
  geom_point() +
  stat_regline_equation(
      aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
      formula = y ~ x
    ) +
  geom_smooth(method = "lm") +
  stat_cor(label.y = 0) +
  theme_classic()

ggplot(df, aes(x = change, y = froh0)) +
  geom_point() +
  stat_regline_equation(
      aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
      formula = y ~ x
    ) +
  geom_smooth(method = "lm") +
  stat_cor(label.y = 0) +
  theme_classic()

ggplot(df, aes(x = cur, y = froh0)) +
  geom_point() +
  stat_regline_equation(
      aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
      formula = y ~ x
    ) +
  geom_smooth(method = "lm") +
  stat_cor(label.y = 0) +
  theme_classic()

# grouped
df_group <- 
  df %>% 
  mutate(stability = stability > 3) %>%
  drop_na(stability)

# play around with this:
ggplot(df_group) +
  geom_boxplot(aes(x = stability, y = froh0))
```