---
title: "CCGP"
output:
  github_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r}
library("rpaleoclim")
library("here")
library("tidyverse")
library("ggpubr")
library("terra")
library("sf")
library("gridExtra")
source(here("general_functions.R"))
source(here("analysis", "genetic_diversity", "genetic_diversity.R"))
source(here("ccgp_test", "get_ccgp_data.R"))
ca <- get_ca()
```

# Get heterozygosity Data
```{r}
het <- get_ccgp_het()
coords <- get_ccgp_coords()

df <- 
  inner_join(het, coords, by = c("project", "SampleID")) %>%
  drop_na(project, SampleID)

taxa_df <- 
  data.frame(project = df$project) %>%
  mutate(genus = gsub("[^A-Za-z]", "", project)) %>%
  distinct()
a <- taxize::classification(taxa_df$genus, db = "itis")
b <- map(1:length(a), ~a[[.x]])
names(b) <- taxa_df$project
taxa_df <- 
  bind_rows(b, .id = "project") %>%
  filter(rank %in% c("kingdom", "phylum", "class", "order", "family"))
```

# Paleoclim
## Get paleoclim data
```{r}
env_stack <- rast(here("data", "env", "paleoclim", "paleoclim.tif"))
env_stack <- env_stack[[grepl("lgm|lig|lh|cur", names(env_stack))]]

tp <- unique(map_chr(str_split(names(env_stack), "_"), 1))
env_list <- map(tp, ~{
  r <- env_stack[[grepl(.x, names(env_stack))]]
  names(r) <- gsub(paste0(.x, "_"), "", names(r))
  return(r)
})
names(env_list) <- tp

cur <- env_list$cur
env_stack_vals <- extract(env_stack, df[,c("x", "y")], ID = FALSE)
env_stack_vals <- bind_cols(df, env_stack_vals)

ggplot(env_stack_vals) +
  geom_point(aes(x = lig_bio_1, y = Ho, col = project)) +
  theme(legend.position = "none")
```

## running linear models
```{r}
# use data list to get vars 
env_df_vals <- map(env_list, ~ data.frame(df, extract(.x, df[,c("x", "y")], ID = FALSE)))
diff_vars <- names(env_list) %>% setdiff("cur")
diff_vals <- map(diff_vars, ~ {
  diff <- env_list[["cur"]] - env_list[[.x]]
  return(data.frame(df, extract(diff, df[,c("x", "y")], ID = FALSE)))
})
env_df_vals <- c(env_df_vals, diff_vals)
names(env_df_vals) <- c(names(env_list), paste0("dif_", diff_vars))

# check for strong correlations
cor_result <- 
  imap(env_df_vals, \(x, idx){
    possibly_cor <- possibly(cor, NA)
    result <- 
      x %>%
      group_by(project) %>%
      summarise(across(starts_with("bio"), ~possibly_cor(Ho, ., use = "complete.obs"))) %>% 
      pivot_longer(contains("bio"), names_to = "var", values_to = "r") %>%
      mutate(timeperiod = !!idx)
  }) %>% 
  bind_rows() %>%
  mutate(timeperiod = factor(timeperiod, levels = names(env_df_vals)))

cor_result %>% 
  filter(abs(r) > 0.4) %>% 
  group_by(var, timeperiod) %>% 
  count() %>% 
  arrange(desc(n)) %>%
  mutate(mean = n/length(unique(cor_result$project)), n = n) %>%
  head(n = 10)


gg_df <- 
  env_df_vals[["dif_lig"]] %>%
  group_by(project) %>%
  mutate(Ho_scaled = scale(Ho)) %>%
  bind_rows()

ggplot(gg_df) +
  geom_point(aes(x = bio_5, y = Ho, col = project), alpha = 0.5) +
  geom_smooth(aes(x = bio_5, y = Ho), method = "lm") +
  theme_classic() +
  theme(legend.position = "none")
```

```{r}
run_lm <- function(project, timeperiod, env_df_vals){
  # subset df
  env_df <- env_df_vals[[timeperiod]] %>% filter(project == !!project)

  # test for collinearity and drop correlated vars as suggested
  #bio <- env_df %>% select(contains("bio")) %>% drop_na()
  #cormat <- cor(bio)
  #safe_cor <- possibly(caret::findCorrelation)
  #drop_vars <- safe_cor(cormat, cutoff = 0.6, names = TRUE, verbose = FALSE)
  #if (is.null(drop_vars)) return(NULL)
  #uncorrelated <- names(bio) %>% setdiff(drop_vars)

  # if (length(drop_vars) == 0) {
  #   uncorrelated <- names(bio)
  #   correlated <- data.frame(corvars = NA, var = uncorrelated, timeperiod = timeperiod, project = project)
  # } else {
  #   cormat <- cor(bio)
  #   correlated <- 
  #     map(uncorrelated, ~ data.frame(corvars = names(which(abs(cormat[.x,]) > 0.5)), var = .x)) %>% 
  #     bind_rows() %>%
  #     mutate(timeperiod = timeperiod, project = project)
  # }

  if (all(is.na(select(env_df, contains("bio"))))) {
     return(NULL)
  }
  
  #fHo <- formula(paste0("Ho ~", paste0(uncorrelated, collapse = " + ")))
  fHo <- formula("Ho ~ bio_1")

  mod <- summary(lm(fHo, data=env_df))

  result <- 
    data.frame(mod$coefficients) %>% 
    mutate(adj_rsqr = mod$adj.r.squared) %>%
    mutate(var = rownames(.)) %>% 
    filter(var != "(Intercept)") %>%
    mutate(project = project, timeperiod = timeperiod) #%>%
    #left_join(correlated, by = "var") 
  return(result)
}

combos <- expand.grid(project = unique(df$project), timeperiod = names(env_df_vals))
lm_result <- pmap(combos, ~run_lm(project = .x, timeperiod = .y, env_df_vals = env_df_vals), .progress = TRUE) 
lm_df <- 
  lm_result %>%# come back to figure out why some have 0 rows
  compact() %>%
  map(~ {
    if (nrow(.x) == 0)
      return(NULL)
    else
      return(.x)
  }) %>%
  compact() %>% 
  bind_rows()

sigvars <- 
  lm_df %>% 
  filter(`Pr...t..` < 0.05) %>% 
  arrange(desc(adj_rsqr)) 

lm_df %>% count(`Pr...t..` < 0.05)
sigvars %>% group_by(timeperiod, var) %>% count() %>% arrange(desc(n)) %>% head()

direction <- 
  lm_df %>% 
  filter(var == "bio_1") %>% 
  filter(`Pr...t..` < 0.05)  %>% 
  mutate(neg = Estimate < 0)

sig1 <- 
  lm_df %>% 
  filter(var == "bio_1") %>%
  mutate(sig = `Pr...t..` < 0.05) 

mod_df <- 
  taxa_df %>%
  select(project, rank, name) %>%
  distinct() %>%
  pivot_wider(names_from = rank, values_from = name) %>%
  left_join(lm_df) %>%
  filter(var == "bio_1", timeperiod == "dif_lig") %>%
  drop_na(`Pr...t..`) %>%
  mutate(significant = `Pr...t..` < 0.05)

anova(lm(significant ~ phylum + class, data = mod_df))

ggplot(summarize(group_by(mod_df, phylum), proportion = mean(`Pr...t..` < 0.05, na.rm = TRUE))) +
  geom_col(aes(y = phylum, x = proportion)) +
  xlim(0, 1)

writeLines(paste0(round(mean(sig1$sig, na.rm = TRUE), 2)*100, "% of the relationships were significant"))
writeLines(paste0(round(mean(direction$neg, na.rm = TRUE), 2)*100, "% of significant relationships were negative"))

```

```{r}
combos <- sigvars %>% select(var, project, timeperiod) %>% distinct()
plts <-
map(1:nrow(combos), ~ {
  sig_df <- left_join(combos[.x,], sigvars)

  sig_env_df <- 
    env_df_vals[[sig_df$timeperiod]] %>% 
    pivot_longer(contains("bio"), names_to = "var") %>%
    filter(project %in% sig_df$project) %>%
    filter(var == sig_df$var)

  title <- paste(sig_df$project, "|", sig_df$timeperiod)

  if (nrow(sig_env_df) == 0) return(NULL)

  plt <-
    ggplot(sig_env_df, aes(value, Ho)) +
      geom_point(alpha = 0.7) +
      facet_wrap(~var, scales = "free") +
      stat_regline_equation(
        aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
        formula = y ~ x
      ) +
      geom_smooth(method = "lm") +
      stat_cor(label.y = min(sig_env_df$Ho, na.rm = TRUE)) +
      theme_classic() +
      ggtitle(title)

  plt
})

pdf(here("ccgp_test", "ccgp_test.pdf"), width = 5, height = 5)
walk(plts, print)
dev.off()

dif_lig <- env_df_vals[["dif_lig"]]
pdf(here("ccgp_test", "bio1_test.pdf"), width = 20, height = 20)
ggplot(dif_lig, aes(bio_1, Ho)) +
  geom_point(alpha = 0.7) +
  facet_wrap(~project, scales = "free") +
  #stat_regline_equation(
  #  aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
  #  formula = y ~ x
  #) +
  geom_smooth(method = "lm") +
  stat_cor() +
  theme_classic()
dev.off()

pdf(here("ccgp_test", "y_test.pdf"), width = 20, height = 20)
ggplot(dif_lig, aes(y, Ho)) +
  geom_point(alpha = 0.7) +
  facet_wrap(~project, scales = "free") +
  #stat_regline_equation(
  #  aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
  #  formula = y ~ x
  #) +
  geom_smooth(method = "lm") +
  stat_cor() +
  theme_classic()
dev.off()

```

# Stability
```{r}
csi <- rast(here("data", "env", "stability", "csi.tif"))

csi_vals <- extract(csi, df[,c("x", "y")], ID = FALSE)

csi_df <- data.frame(csi_vals, df)

names(csi_df)
```

```{r}
# check for significant correlations
possibly_cor <- possibly(cor, NA)
result <- 
  csi_df %>%
  group_by(project) %>%
  summarise(across(c("Past", starts_with("SSP")), ~possibly_cor(Ho, ., use = "complete.obs"))) %>% 
  pivot_longer(c("Past", starts_with("SSP")), names_to = "model", values_to = "r") 

result %>% count(r > 0)

ggplot(result, aes(x = model, y = project, fill = r)) +
  geom_tile() +
    labs(col = "r") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_minimal()
```

```{r}
sigcor <- function(x, y, use = "complete.obs") {
  ct <- cor.test(x, y, use = use)
  c(r = ct$estimate, p = ct$p.value)
}

possibly_sigcor <- possibly(sigcor, c(r.cor = NA, p = NA))
result <- 
  csi_df %>%
  group_by(project) %>%
  summarize(cor_results = list(possibly_sigcor(Ho, Past, use = "complete.obs"))) %>%
  tidyr::unnest_wider(cor_results, names_sep = "_") %>%
  rename(r = cor_results_r.cor, p = cor_results_p) 

result %>%
  mutate(significant = p < 0.05) %>%
  count(significant)

result %>%
  filter(p < 0.05) %>%
  count(r > 0)
```

```{r}
csi_long <-  
  csi_df %>% 
  pivot_longer(c("Past", starts_with("SSP")), names_to = "model", values_to = "csi") 

csi_ls <- 
  csi_long %>% 
  group_by(project) %>% 
  group_split()

plts <- map(csi_ls, ~{
  if (all(is.na(.x$csi))) return(NULL)
  ggplot(.x, aes(x = csi, y = Ho)) +
    geom_point() +
    facet_wrap(~model, scales = "free", nrow = 1) +
    stat_regline_equation(
      aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
      formula = y ~ x
    ) +
    geom_smooth(method = "lm") +
    stat_cor(label.y = min(.x$Ho, na.rm = TRUE)) +
    theme_classic() +
    xlab("Climate Stability Index (Degree of Past Climate Fluctuations)") +
    ggtitle(unique(.x$project))
}) %>% compact()

pdf(here("ccgp_test", "csi_test.pdf"), width = 20, height = 5)
walk(plts, print)
dev.off()

ggplot(csi_long, aes(x = csi, y = Ho)) +
  geom_point(alpha = 0.5, cex = 0.5, col = "gray") +
  stat_regline_equation(
    aes(label =  paste(after_stat(eq.label), after_stat(adj.rr.label), sep = "~~~~")),
    formula = y ~ x
  ) +
  facet_wrap(~model, scales = "free", nrow = 1) +
  geom_smooth(method = "lm") +
  stat_cor(label.y = min(csi_long$Ho, na.rm = TRUE)) +
  theme_classic() +
  xlab("Climate Stability Index (Degree of Past Climate Fluctuations)")
```

# Rangemap
```{r}
library("rangemap")
```

# Building SDMs
```{r}
spps <- c("Sceloporus occidentalis", "Setophaga", "Ursus americanus")

# get coordinates
occ_coords <- get_occ_coords("Sceloporus occidentalis", data_source = "both", occ_limit = 10000, cache = TRUE)

# get or create bias background layer
bias_class <- get_bias("Sceloporus occidentalis", rank = "class", limit = 10000, n = 10000, cache = TRUE)

# run SDM
sdm_mod <- 
  sdm(
    coordinates = occ_coords,
    envlayers = cur[[selected_vars]], 
    biasdat = bias_class, 
    models = "RF", 
    BIOMOD_name = "BIOMOD", 
    tune = FALSE
    )

```

# Test with other variables
```{r}
env_stack_other <- rast(here("data", "env", "california_env_stack.tif")) 
coords <- df[,c("x", "y")] %>% st_as_sf(coords = c("x", "y"), crs = 4326) %>% st_transform(st_crs(env_stack_other))
env_stack_other <- env_stack_other[[!grepl("CHELSA", names(env_stack_other))]]
env_stack_other_vals <- extract(env_stack_other, coords, ID = FALSE)
env_df_other_vals <- bind_cols(df, env_stack_other_vals)

env_stack <- rast(here("data", "env", "paleoclim", "paleoclim.tif"))
env_stack <- env_stack[[grepl("lgm|lig|lh|cur", names(env_stack))]]
env_stack_vals <- extract(env_stack, df[,c("x", "y")], ID = FALSE)
env_stack_vals <- bind_cols(df, env_stack_vals) %>% mutate(lig_dif_bio_1 = lig_bio_10 - cur_bio_10)

big_env <- left_join(env_df_other_vals, env_stack_vals)

summary(lm(Ho ~ cur_bio_1 * project + lig_dif_bio_1 * project + project, data = big_env))

data.frame(summary(lm(Ho ~ cur_bio_1*project + lig_dif_bio_1*project + project + BurnDate*project + NDVI*project + gHM*project, data = big_env))$coefficients) %>% 
mutate(var = row.names(.)) %>% 
filter(!grepl("project", var)) %>%
filter(`Pr...t..` < 0.05)

data.frame(summary(lm(Ho ~  BurnDate+ NDVI + gHM + cur_bio_1 + lig_dif_bio_1 + project, data = big_env))$coefficients) %>% 
mutate(var = row.names(.)) %>% 
filter(!grepl("project", var)) %>%
filter(`Pr...t..` < 0.05)

ggplot(big_env, aes(x = cur_bio_1, y = Ho)) +
  geom_point(aes(col = project)) +
  geom_smooth(method = "lm") +
  theme_classic() +
  theme(legend.position = "none")

ggplot(big_env, aes(x = NDVI, y = Ho)) +
  geom_point(aes(col = project)) +
  geom_smooth(method = "lm") +
  theme_classic() +
  theme(legend.position = "none")
```


### wingen
```{r}
library("wingen")

coords <- st_as_sf(df, coords = c("x", "y"), crs = 4326)

# Project coordinates and boundary to equal area projection (California Albers)
coords_proj <- st_transform(coords, 3310)
ca_proj <- st_transform(ca, 3310)

# Convert coordinates to a raster layer with 10km resolution
lyr <- coords_to_raster(coords_proj, buffer = 10, res = 10000)

run_wingen <- function(project){
  coords_proj <- coords_proj %>% filter(project == !!project)
  # Calculate windowed mean of Ho
  window_Ho <- window_general(coords_proj$Ho, coords = coords_proj, lyr = lyr, wdim = 9, stat = mean, na.rm = TRUE)
  return(window_Ho)
}

possibly_wingen <- possibly(run_wingen, NULL)
wingen_maps <- map(unique(df$project), ~possibly_wingen(.x), .progress = TRUE)

# Plot masked kriging result
ggplot_gd(mask_Ho, bkg = ca_proj, col = magma(100)) +
  labs(fill = "Ho") +
  scale_fill_viridis_c(labels = scales::scientific, option = "magma")
```
