```{r}
library(tidyverse)
# Downloaded from: https://www.ccgproject.org/s/CCGP_FullSpeciesList.xlsx
# Species list
species <- readxl::read_excel(here("ccgp_test", "data", "CCGP_FullSpeciesList.xlsx"))

# Downloaded from: https://docs.google.com/spreadsheets/d/1kTyfzGJ52jgxWY16lipq8oSp__fuDCuTI3iBlQmJSL0/edit#gid=502099427
# Project list 
projects <- 
  read_csv(here("ccgp_test", "data", "WGS_METADATA_DB - edit.csv")) %>% 
  rename(project = `ccgp-project-id`) %>%
  # Remove project number and symbol 
  mutate(Genus = gsub("[^[:alpha:]]", "", project)) %>%
  select(Genus, project) %>%
  distinct()

# Make a dataframe with species and projects
df <- 
  species %>% 
  select(Genus, GenusSpeciesSuborVar, contains("Status"), "CommonName") %>%
  left_join(projects, by = c("Genus"), relationship = "many-to-many") %>%
  select(project, Genus, GenusSpeciesSuborVar, everything()) %>%
  drop_na(GenusSpeciesSuborVar)

# Use gbif to get phylum/class/etc
backbone <- map(df$GenusSpeciesSuborVar, ~rgbif::name_backbone(.x), .progress = TRUE)
backbone_df <- 
  bind_rows(backbone) %>%
  select(kingdom, phylum, class, order, family, species)

df <- 
  df %>%
  left_join(backbone_df, by = c("GenusSpeciesSuborVar" = "species")) 
head(df)
```

```{r}
# Life history traits from: https://springernature.figshare.com/collections/CaliPopGen_A_genetic_and_life_history_database_for_the_fauna_and_flora_of_California/5518389/1

animals <- read_csv(here("ccgp_test", "data", "CaliPopGen_dataset_3_animal_life_history_traits_CSV.csv"))
plants <- read_csv(here("ccgp_test", "data", "CaliPopGen_dataset_4_plant_life_history_traits_CSV.csv"))
traits <- bind_rows(animals, plants)

df <- 
  df %>%
  left_join(traits, by = c("GenusSpeciesSuborVar" = "ScientificName")) %>%
  drop_na(project, Genus, GenusSpeciesSuborVar)

info <- df %>% filter(Genus == "Sceloporus") %>% unlist()
info[complete.cases(info)]

# Plot the number of species represetnign each class
ggplot(df, aes(class)) + geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(df, aes(phylum)) + geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(df, aes(HabitatType)) + geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(df, aes(x = log(as.numeric(Fecundity)))) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(df, aes(x = (as.numeric(AgeSexMatMin)))) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(df, aes(ReprodMode)) + geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(df, aes(x = (as.numeric(BodyLength)))) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggplot(df, aes(x = (as.numeric(AdultMass)))) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))

# PROBLEM: RGBIF doesn't catch everything
df %>% filter(is.na(class))

```