---
title: "genomic_offset"
output:
  github_document:
    toc: TRUE
---

```{r setup, include=FALSE}
# Set global options for caching
knitr::opts_chunk$set(
  cache = TRUE,
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  result = FALSE)

library(algatr)
library(here)
library(tidyverse)
library(tidyterra)
library(RColorBrewer)
library(sf)
library(terra)
library(raster)
library(cowplot)
library(RStoolbox)
library(tigris)
library(viridis)

source(here("analysis", "adaptive", "adaptive_index.R"))
source(here("analysis", "adaptive", "genomic_offset.R"))
source(here("general_functions.R"))
```

## Specify model to examine

```{r}
path = here("analysis", "adaptive", "outputs")
prefix = "58-Sceloporus_bio1ndvi_gea" # "58-Sceloporus_bio1ndvi_gea_genes_nonsyn"
```

## 1. Get input files

```{r}
coords <- get_coords()
# If `gdm_result` isn't loaded, do:
gdm_result <- readRDS(here("analysis", "adaptive", "outputs", "GDM_GEA_model.RDS"))
envlayers <- get_envlayers(future = TRUE)

# Extract layers
env_pres <- envlayers$env_pres
env_fut_26 <- terra::subset(envlayers$env_fut, c("CHELSA_bio1_2071-2100_gfdl-esm4_ssp126_V.2.1", "NDVI"))
env_fut_85 <- terra::subset(envlayers$env_fut, c("CHELSA_bio1_2071-2100_gfdl-esm4_ssp585_V.2.1", "NDVI"))

# Make env names consistent
names(env_fut_26) <- names(env_pres)
names(env_fut_85) <- names(env_pres)

# Check that layers look good for each RCP
terra::compareGeom(env_pres[[1]], 
                   env_fut_26[[1]], 
                   lyrs = TRUE, 
                   crs = TRUE, 
                   ext = TRUE, 
                   rowcol = TRUE)
terra::compareGeom(env_pres[[1]], 
                   env_fut_85[[1]], 
                   lyrs = TRUE, 
                   crs = TRUE, 
                   ext = TRUE, 
                   rowcol = TRUE)
```

Run GDM-based offset:

```{r}
gdmoff_26 <- predict_gdm(object = gdm_result$model,
                         data = env_pres,
                         time = TRUE,
                         predRasts = env_fut_26,
                         filename = here("analysis", "adaptive", "outputs", "58-Sceloporus_GDMoffset_RCP26_IBSdist.tif"),
                         overwrite = TRUE)

gdmoff_85 <- predict_gdm(object = gdm_result$model,
                         data = env_pres,
                         time = TRUE,
                         predRasts = env_fut_26,
                         filename = here("analysis", "adaptive", "outputs", "58-Sceloporus_GDMoffset_RCP85_IBSdist.tif"),
                         overwrite = TRUE)

# Check against old results
gdm_old <- readRDS(here("analysis", "adaptive", "outputs_apr22", "GDM_GEA_model.RDS"))
old_gdmoff_26 <- predict_gdm(object = gdm_old$model,
                         data = env_pres,
                         time = TRUE,
                         predRasts = env_fut_26,
                         filename = here("analysis", "adaptive", "outputs", "58-Sceloporus_GDMoffset_RCP26_IBSdist.tif"),
                         overwrite = TRUE)

old_gdmoff_85 <- predict_gdm(object = gdm_old$model,
                         data = env_pres,
                         time = TRUE,
                         predRasts = env_fut_26,
                         filename = here("analysis", "adaptive", "outputs", "58-Sceloporus_GDMoffset_RCP85_IBSdist.tif"),
                         overwrite = TRUE)
```

Plot GDM results

```{r}
map <- custom_gdm_map(gdm_result$model, env_pres, coords %>% dplyr::select(x, y))
# GDM PCA layers
writeRaster(map$pcaRastRGB, here("analysis", "adaptive", "outputs", "58-Sceloporus_GDMGEA_pcaRastRGB_IBSdist.tif"))
# GDM-transformed raster layers
writeRaster(map$rastTrans, here("analysis", "adaptive", "outputs", "58-Sceloporus_GDMGEA_rastTrans_IBSdist.tif"))

# GDM rainbow map
p_gdm_rainbow <- ggplot() +
  geom_spatraster_rgb(data = map$pcaRastRGB, r = 1, g = 2, b = 3) +
  theme_map() +
  ggtitle("GDM RDA")

# Loadings 'legend'
p_vars <-
  gdm_plot_vars(map$pcaSamp, map$pcaRast, map$pcaRastRGB, 
                coords = coords %>% dplyr::select(x, y), 
                x = "PC1", y = "PC2", 
                scl = 1, display_axes = FALSE)

pdf(here("analysis", "adaptive", "plots", "58-Sceloporus_GDMGEA_rainbow_IBSdist.pdf"))
plot_grid(p_gdm_rainbow, p_vars, nrow = 1, rel_widths = c(2, 1))
dev.off()
```

Plot GDM-based offset

```{r}
ca <- get_ca()
range <- get_range()

# If you haven't run above code, load tifs:
gdmoff_26 <- terra::rast(here("analysis", "adaptive", "outputs", "58-Sceloporus_GDMoffset_RCP26_IBSdist.tif"))
gdmoff_85 <- terra::rast(here("analysis", "adaptive", "outputs", "58-Sceloporus_GDMoffset_RCP85_IBSdist.tif"))

p_gdm_offset_26 <- ggplot() +
  geom_sf(data = ca, fill = "lightgrey") +
  geom_spatraster(data = gdmoff_26) +
  # scale_fill_viridis_c(option = "F", na.value = "transparent", direction = -1) +
  scale_fill_distiller(palette = "Spectral", na.value = "transparent", direction = -1) +
  geom_sf(data = ca, fill = NA, size = 0.1) +
  xlab("Longitude") +
  ylab("Latitude") +
  ggplot2::guides(fill = guide_legend(title = "GDM-based genomic offset (RCP 2.6)")) +
  # facet_grid(~lyr) +
  theme_map() +
  theme(panel.grid = element_blank(), plot.background = element_blank(),
        panel.background = element_blank(), strip.text = element_text(size = 11))

p_gdm_offset_85 <- ggplot() +
  geom_sf(data = ca, fill = "lightgrey") +
  geom_spatraster(data = gdmoff_85) +
  # scale_fill_viridis_c(option = "F", na.value = "transparent", direction = -1) +
  scale_fill_distiller(palette = "Spectral", na.value = "transparent", direction = -1) +
  geom_sf(data = ca, fill = NA, size = 0.1) +
  xlab("Longitude") +
  ylab("Latitude") +
  ggplot2::guides(fill = guide_legend(title = "GDM-based genomic offset (RCP 8.5)")) +
  # facet_grid(~lyr) +
  theme_map() +
  theme(panel.grid = element_blank(), plot.background = element_blank(),
        panel.background = element_blank(), strip.text = element_text(size = 11))


pdf(here("analysis", "adaptive", "plots", "58-Sceloporus_GDMGEA_IBSdist.pdf"), width = 20, height = 8)
plot_grid(p_gdm_offset_26, p_gdm_offset_85, nrow = 1)
dev.off()

# Mask to Sceloporus species range
mask_gdmoff_85 <- terra::mask(gdmoff_85 %>% terra::project(crs(range)), range)
mask_gdmoff_26 <- terra::mask(gdmoff_26 %>% terra::project(crs(range)), range)
p_gdm_offset_26_masked <- ggplot() +
  geom_sf(data = ca, fill = "lightgrey") +
  geom_spatraster(data = mask_gdmoff_26) +
  # scale_fill_viridis_c(option = "F", na.value = "transparent", direction = -1) +
  scale_fill_distiller(palette = "Spectral", na.value = "transparent", direction = -1) +
  geom_sf(data = ca, fill = NA, size = 0.1) +
  xlab("Longitude") +
  ylab("Latitude") +
  ggplot2::guides(fill = guide_legend(title = "GDM-based genomic offset (RCP 2.6)")) +
  # facet_grid(~lyr) +
  theme_map() +
  theme(panel.grid = element_blank(), plot.background = element_blank(),
        panel.background = element_blank(), strip.text = element_text(size = 11))

p_gdm_offset_85_masked <- ggplot() +
  geom_sf(data = ca, fill = "lightgrey") +
  geom_spatraster(data = mask_gdmoff_85) +
  # scale_fill_viridis_c(option = "F", na.value = "transparent", direction = -1) +
  scale_fill_distiller(palette = "Spectral", na.value = "transparent", direction = -1) +
  geom_sf(data = ca, fill = NA, size = 0.1) +
  xlab("Longitude") +
  ylab("Latitude") +
  ggplot2::guides(fill = guide_legend(title = "GDM-based genomic offset (RCP 8.5)")) +
  # facet_grid(~lyr) +
  theme_map() +
  theme(panel.grid = element_blank(), plot.background = element_blank(),
        panel.background = element_blank(), strip.text = element_text(size = 11))


pdf(here("analysis", "adaptive", "plots", "58-Sceloporus_GDMGEA_IBSdist_masked.pdf"), width = 20, height = 8)
plot_grid(p_gdm_offset_26_masked, p_gdm_offset_85_masked, nrow = 1)
dev.off()
```

Check against old files:

```{r}
p_gdm_offset_26_old <- ggplot() +
  geom_sf(data = ca, fill = "lightgrey") +
  geom_spatraster(data = old_gdmoff_26) +
  scale_fill_viridis_c(option = "F", na.value = "transparent", direction = -1) +
  geom_sf(data = ca, fill = NA, size = 0.1) +
  xlab("Longitude") +
  ylab("Latitude") +
  ggplot2::guides(fill = guide_legend(title = "GDM-based genomic offset (RCP 2.6)")) +
  # facet_grid(~lyr) +
  theme_map() +
  theme(panel.grid = element_blank(), plot.background = element_blank(),
        panel.background = element_blank(), strip.text = element_text(size = 11))

p_gdm_offset_85_old <- ggplot() +
  geom_sf(data = ca, fill = "lightgrey") +
  geom_spatraster(data = old_gdmoff_85) +
  scale_fill_viridis_c(option = "F", na.value = "transparent", direction = -1) +
  geom_sf(data = ca, fill = NA, size = 0.1) +
  xlab("Longitude") +
  ylab("Latitude") +
  ggplot2::guides(fill = guide_legend(title = "GDM-based genomic offset (RCP 8.5)")) +
  # facet_grid(~lyr) +
  theme_map() +
  theme(panel.grid = element_blank(), plot.background = element_blank(),
        panel.background = element_blank(), strip.text = element_text(size = 11))


pdf(here("analysis", "adaptive", "plots", "58-Sceloporus_GDMGEA_IBSdist_OLD.pdf"), width = 20, height = 8)
plot_grid(p_gdm_offset_26_old, p_gdm_offset_85_old, nrow = 1)
dev.off()
```