# Adaptive index

```{r setup, include=FALSE}
# Set global options for caching
knitr::opts_chunk$set(
  cache = TRUE,
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  result = FALSE)

library(algatr)
library(here)
library(tidyverse)
library(RColorBrewer)
library(sf)
library(terra)
library(raster)
library(vegan)
library(cowplot)
library(tidyterra)

source(here("analysis", "adaptive", "adaptive_index.R"))
source(here("analysis", "adaptive", "genomic_offset.R"))
source(here("general_functions.R"))
```

## Specify models to examine

```{r}
gea_method = "bio1ndvi" # "pca" or "bio1ndvi"
path = here("analysis", "adaptive", "outputs")
RCP = "85" # "26"
```

## 1. Get input files

```{r}
# Retrieve offset estimations for given RCP
offset_genes <- terra::rast(paste0(path, "/58-Sceloporus_bio1ndvi_gea_genes_nonsyn_offset_load_RCP", RCP, ".tif"))
offset_nonsyn <- terra::rast(paste0(path, "/58-Sceloporus_bio1ndvi_gea_genes_nonsyn_offset_load_RCP", RCP, ".tif"))

# Retrieve coords for samples on which RDA was run
coords <- read_tsv(here(path, "/RDA_genes_coords.txt"), col_names = TRUE)
ca <- get_ca()

# Retrieve envlayers used for calculating offset
if (gea_method == "bio1ndvi") envlayers <- import_env_files(type = "ind_layers", future = FALSE)
```

## 2. Select env layers


