```{r}
library(tidyverse)
library(sf)
library(terra)
library(here)
source(here("analysis", "gea", "functions_go.R"))
source(here("analysis", "gea", "functions_selection_stats.R"))
source(here("general_functions.R"))
outpath <- here("analysis", "gea", "outputs")
plotpath <- here("analysis", "angrypancake", "plots")
```

# PCA
```{r}
# Get non-synonymous GEA SNPs
df <- read_csv(here(outpath, "bio1ndvi_gea_genes_nonsyn.csv"))

# Get gene structure
gene_struc <- get_gene_structure()

# Load dosage data
dos <- read_table(here("analysis", "gea", "outputs", "nonsyn.raw"))

# Load env data
current_env <- rast(here("data" ,"env", "chelsa", "CHELSA_bio1_1981-2010_V.2.1.tif"))
ndvi <- rast(here("data", "env", "california_ndvi_mean_2000_2020.tif"))
names(current_env) <- "bio1"
names(ndvi) <- "ndvi"

# Load coords and model dataframe
coords <- 
  get_coords(sf = TRUE) %>% 
  filter(SampleID %in% dos$IID) %>% 
  st_transform(3310) 
coords$bio1 <- terra::extract(current_env, coords, method = "bilinear", ID = FALSE)[,1]
coords$ndvi <- terra::extract(ndvi, coords, method = "bilinear", ID = FALSE)[,1]

# Subset to only samples in coords
dos <- dos[dos$IID %in% coords$SampleID, ]

# Confirm orders are the same
stopifnot(all(dos$IID == coords$SampleID))

# CORRECT DOS NAMES (remove trailing _[A-Z] from dos names, but keep the rest)
colnames(dos) <- gsub("_[A-Z]$", "", colnames(dos))
```

```{r}
# Get HSP gene loci
# This filter makes sure to catch things like "heat shock 70 kDA protein", but exclude things like "heat shock transcription factor"
hsp <- 
  df %>% 
  #filter(grepl("heat shock", full_name) & grepl("protein", full_name) & grepl("70", full_name))
  filter(grepl("heat shock", full_name) & grepl("protein", full_name))

gene_struc_hsp <- 
  hsp %>%
  left_join(gene_struc, by = c("scaffold", "full_name", "gene_start", "gene_end"), relationship = "many-to-many") %>%
  mutate(gene_name = ifelse(is.na(gene_name), description, gene_name)) 
names(gene_struc_hsp)

plt0 <- 
  ggplot(gene_struc_hsp) +
  geom_rect(aes(xmin = gene_start, xmax = gene_end, ymin = 0, ymax = 1, fill = "gene"), color = "black") +
  geom_rect(aes(xmin = exon_start, xmax = exon_end, ymin = 0, ymax = 1, fill = "exon"), color = "black") +
  geom_rect(aes(xmin = cds_start, xmax = cds_end, ymin = 0, ymax = 1, fill = "CDS"), color = "black") +
  scale_fill_manual(values = c("gene" = "lightblue", "exon" = "blue", "CDS" = "darkblue")) +
  geom_vline(aes(xintercept = start), color = "red") +
  facet_wrap(~gene_name, scales = "free_x") +
  theme_void() +
  theme(axis.text = element_blank(), legend.position = "top")
pdf(here(plotpath, "hsp70_gene_regions.pdf"), width = 10, height = 5)
plt0
dev.off()

hsp %>% pull(full_name)
nrow(hsp)
gene_loci <- hsp$locus

gene_dos <- dos[, gene_loci]
gene_dos$SampleID <- dos$IID
stopifnot(ncol(gene_dos) - 1 == length(hsp$locus))

nona_dos <- 
  gene_dos %>%
  mutate(across(everything(), ~ ifelse(is.na(.), median(., na.rm = TRUE), .)))

gene_df <- 
  coords %>% 
  left_join(gene_dos, by = "SampleID")  %>%
  pivot_longer(starts_with("chr"), names_to = "locus", values_to = "dos")

ca <- get_ca()
plt1 <- 
  ggplot(gene_df) +
  geom_sf(data = ca) +
  geom_sf(aes(col = factor(dos))) +
  theme_void() +
  scale_color_viridis_d(option = "viridis") +
  facet_wrap(~locus)

# Run PCA
gene_pca <- prcomp(dplyr::select(nona_dos, -SampleID))

# Get variable loadings
gene_loadings <- 
  as.data.frame(gene_pca$rotation) %>%
  rownames_to_column("locus") %>%
  left_join(gene_struc_hsp, by = "locus")

pc_df <- 
  coords %>% 
  left_join(gene_dos, by = "SampleID") %>%
  mutate(PC1 = gene_pca$x[, 1], PC2 = gene_pca$x[,2]) 

gene_df <-
  pc_df %>%
  pivot_longer(starts_with("chr"), names_to = "locus", values_to = "dos")

plt2 <-
  ggplot(gene_df) +
  geom_sf(data = ca) +
  geom_sf(aes(fill = PC1), pch = 21, size = 2, color = "black") +
  scale_fill_viridis_c(option = "turbo") +
  theme_void() +
  theme(legend.position = "bottom")

gene_loadings_unique <- gene_loadings %>% distinct(PC1, PC2, gene_name)
plt3 <- 
  ggplot(pc_df) +
  geom_hline(yintercept = 0, color = "gray", linetype = "solid") +
  geom_vline(xintercept = 0, color = "gray", linetype = "solid") +
  annotate("text", x = max(pc_df$PC1), y = 0.1, label = "PC1", hjust = -0.1, vjust = 0.1, color = "gray") +
  annotate("text", x = 0.1, y = max(pc_df$PC2), label = "PC2", vjust = 0.1, color = "gray") +
  #geom_point(aes(x = PC1, y = PC2, col = PC1)) +
  geom_segment(data = gene_loadings_unique, aes(x = 0, y = 0, xend = PC1 * 5, yend = PC2 * 5), 
         arrow = arrow(length = unit(0.2, "cm")), color = "black") +
  ggrepel::geom_text_repel(data = gene_loadings_unique, aes(x = PC1 * 5, y = PC2 * 5, label = gene_name),
                           color = "black", size = 3, segment.color = "grey50", max.overlaps = Inf) +
  scale_color_viridis_c(option = "turbo") +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))


plt4 <- 
  ggplot(pc_df) +
  geom_hline(yintercept = 0, color = "gray", linetype = "solid") +
  geom_vline(xintercept = 0, color = "gray", linetype = "solid") +
  annotate("text", x = max(pc_df$PC1), y = 0.1, label = "PC1", hjust = -0.1, vjust = 0.1, color = "gray") +
  annotate("text", x = 0.1, y = max(pc_df$PC2), label = "PC2", vjust = 0.1, color = "gray") +
  geom_point(aes(x = PC1, y = PC2, col = bio1)) +
  geom_segment(data = gene_loadings_unique, aes(x = 0, y = 0, xend = PC1 * 5, yend = PC2 * 5), 
         arrow = arrow(length = unit(0.2, "cm")), color = "black") +
  ggrepel::geom_text_repel(data = gene_loadings_unique, aes(x = PC1 * 5, y = PC2 * 5, label = gene_name),
                           color = "black", size = 3, segment.color = "grey50", max.overlaps = Inf) +
  scale_color_viridis_c(option = "turbo") +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))

plt5 <- 
  ggplot(pc_df) +
  geom_hline(yintercept = 0, color = "gray", linetype = "solid") +
  geom_vline(xintercept = 0, color = "gray", linetype = "solid") +
  annotate("text", x = max(pc_df$PC1), y = 0.1, label = "PC1", hjust = -0.1, vjust = 0.1, color = "gray") +
  annotate("text", x = 0.1, y = max(pc_df$PC2), label = "PC2", vjust = 0.1, color = "gray") +
  geom_point(aes(x = PC1, y = PC2, col = ndvi)) +
  geom_segment(data = gene_loadings_unique, aes(x = 0, y = 0, xend = PC1 * 5, yend = PC2 * 5), 
         arrow = arrow(length = unit(0.2, "cm")), color = "black") +
  ggrepel::geom_text_repel(data = gene_loadings_unique, aes(x = PC1 * 5, y = PC2 * 5, label = gene_name),
                           color = "black", size = 3, segment.color = "grey50", max.overlaps = Inf) +
  scale_color_viridis_c(option = "turbo") +
  coord_cartesian(clip = "off") +
  theme_void() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))


plt6 <-
  ggplot(pc_df, aes(x = bio1, y = PC1)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  theme_classic() +
  ggpubr::stat_cor()

plt7 <-
  ggplot(pc_df, aes(x = ndvi, y = PC1)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  theme_classic() +
  ggpubr::stat_cor()

pdf(here(plotpath, "hsp70_locus_maps.pdf"), width = 12, height = 12)
plt1
dev.off()

pdf(here(plotpath, "hsp70_pca_maps.pdf"), width = 5, height = 5)
plt2
plt3
plt4
plt5
plt6
plt7
dev.off()
```

# angrypancake
```{r}
library(tidyverse)
library(algatr)
library(here)
library(raster)
library(terra)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)

datapath <- here("analysis", "angrypancake", "data")
plotpath <- here("analysis", "angrypancake", "plots")

# IDEA ADD REDUNDANT ALLELES?
coords <- 
  read_table(here(datapath, "58-Sceloporus.coords.txt"), col_names = c("SampleID", "x", "y")) %>%
  st_as_sf(coords = c("x", "y"), crs = 4326) %>%
  st_transform(3310) 

coords <- coords %>% filter(SampleID %in% gene_dos$SampleID)

# Confirm order of samples is the same
stopifnot(all(coords$SampleID == gene_dos$SampleID))

dos <- gene_dos %>% dplyr::select(-SampleID)
allele <- dos
allele[allele > 0] <- 1

current_env <- rast(here(datapath, "CHELSA_bio1_1981-2010_V.2.1.tif"))
names(current_env) <- "bio1"
future_env <- rast(here(datapath, "CHELSA_bio1_2071-2100_gfdl-esm4_ssp585_V.2.1.tif"))
names(future_env) <- "bio1"

# Extract environmental vars
env <- raster::extract(current_env, coords, method = "bilinear")
env <- data.frame(env)

na <- ne_countries(scale = "medium", returnclass = "sf") 
na_coords <- coords %>% st_buffer(500000) %>% st_transform(st_crs(na))
na <- st_crop(st_make_valid(na), st_bbox(na_coords)) %>% st_transform(3310)

latlon <- na %>% st_transform(4326)
current <- crop(current_env, latlon)
future <- crop(future_env, latlon)
current <- project(current, "EPSG:3310")
future <- project(future, "EPSG:3310")
# # TEMPORARY
# current <- aggregate(current, 2)
# future <- aggregate(future, 2)
current <- mask(current, na)
future <- mask(future, na)

# plot(current)
# points(coords)
tp <- function(x) {
  png(here("TEMP.png"))
  plot(x)
  dev.off()
}

library(randomForest)
# GO OVER MAP1/2 thing (maybe change ot A/B for clarity)
predict_allele <- function(snp, coords, current, future, maxdist = 50000, admix_thresh = 0.1) {
  current_vals <- extract(current, coords, ID = FALSE, method = "bilinear")
  future_vals <- extract(future, coords, ID = FALSE, method = "bilinear")

  # Model current allele presence/absence
  current_df <- data.frame(allele_ref = snp %in% c(0, 1), allele_alt = snp %in% c(1, 2), current_vals)

  # Remove NA values (caused by some samples near coast, come back to this)
  current_df <- current_df %>% drop_na(bio1)
  
  # mod_ref <- glm(allele_ref ~ bio1, data = current_df, family = binomial)
  # mod_alt <- glm(allele_alt ~ bio1, data = current_df, family = binomial)
  
  mod_ref <- randomForest(allele_ref ~ bio1, data = current_df, ntree = 500, mtry = 1)
  mod_alt <- randomForest(allele_alt ~ bio1, data = current_df, ntree = 500, mtry = 1)

  # Predict current distribution
  current_map_ref <- terra::predict(current, mod_ref, type = "response")
  current_map_ref <- ifel(current_map_ref < 0, 0, current_map_ref)
  current_map_ref <- ifel(current_map_ref > 1, 1, current_map_ref)
  current_map_bin_ref <- current_map_ref > 0.5
  current_map_alt <- terra::predict(current, mod_alt, type = "response")
  current_map_alt <- ifel(current_map_alt < 0, 0, current_map_alt)
  current_map_alt <- ifel(current_map_alt > 1, 1, current_map_alt)
  current_map_bin_alt <- current_map_alt > 0.5

  # Predict which allele needs to be present in the future
  future_map_ref <- terra::predict(future, mod_ref, type = "response")
  future_map_ref <- ifel(future_map_ref < 0, 0, future_map_ref)
  future_map_ref <- ifel(future_map_ref > 1, 1, future_map_ref)
  future_map_bin_ref <- future_map_ref > 0.5
  future_map_alt <- terra::predict(future, mod_alt, type = "response")
  future_map_alt <- ifel(future_map_alt < 0, 0, future_map_alt)
  future_map_alt <- ifel(future_map_alt > 1, 1, future_map_alt)
  future_map_bin_alt <- future_map_alt > 0.5

  # Combine according to conditions:
  # (ref, !alt) → 0
  # (!ref, alt) → 1
  # (ref, alt) → 0.5
  current_map_bin <- cover(
    ifel(current_map_bin_ref & !current_map_bin_alt, 0,    NA),
    ifel(!current_map_bin_ref &  current_map_bin_alt, 1,    NA)
  )
  # Deal with hets: if both are TRUE, set to 0.5, then see if one is clearly more likely than the other (by > 0.1), if so set to that allele, otherwise keep as 0.5
  current_map_bin[current_map_bin_ref & current_map_bin_alt] <- 0.5
  current_map_bin[current_map_bin == 0.5 & (current_map_ref - current_map_alt) > admix_thresh] <- 0
  current_map_bin[current_map_bin == 0.5 & (current_map_alt - current_map_ref) > admix_thresh] <- 1

  future_map_bin <- cover(
    ifel(future_map_bin_ref & !future_map_bin_alt, 0,    NA),
    ifel(!future_map_bin_ref &  future_map_bin_alt, 1,    NA)
  )
  # Deal with hets: if both are TRUE, set to 0.5, then see if one is clearly more likely than the other (e.g., by > 0.1), if so set to that allele, otherwise keep as 0.5
  future_map_bin[future_map_bin_ref & future_map_bin_alt] <- 0.5
  future_map_bin[future_map_bin == 0.5 & (future_map_ref - future_map_alt) > admix_thresh] <- 0
  future_map_bin[future_map_bin == 0.5 & (future_map_alt - future_map_ref) > admix_thresh] <- 1
 
  #plot(future_map_bin
  # Get difference (and treat 0.5 as no difference)
  diff_map <- ifel(
    # If the same, no difference
    future_map_bin == current_map_bin, 0,
    # If either are 0.5, no difference, if not → difference
    ifel(future_map_bin == 0.5 | current_map_bin == 0.5, 0, 1)
  )
  # Get raw difference
  raw_diff_map <- future_map_bin != current_map_bin
  # Get difference between raw_diff_map and diff_map to quantify how much heterozygosity is the saving difference
  # diff_map (A) will always be < raw_diff_map (B)
  # 0 = no change, 1 = change
  # Possible values: B = 0, A = 0 → 0 (no change, no difference)
  #                  B = 1, A = 0 → 1 (change, and difference due to het)
  #                  B = 1, A = 1 → 0 (change, and no difference due to het)
  het_diff_map <- raw_diff_map - diff_map
  #plot(diff_map)

  # ADAPTING
  # Targets for distance(): set target cells to 1 and everything else to NA
  cur_ref_targets <- ifel(current_map_bin_ref == 1, 1, NA)   # where allele ref is present now
  cur_alt_targets <- ifel(current_map_bin_alt == 1, 1, NA)   # where allele alt is present now

  # Distance (map units) to nearest needed-allele cell in the CURRENT map
  # MASK to current map so distances are only calculated for land cells
  d_current_ref <- mask(distance(cur_ref_targets), current)
  d_current_alt <- mask(distance(cur_alt_targets), current)

  # Combine
  adapt_distance <- 
    # If the allele persists at the same cell or is 0.5 → distance = 0
    ifel(current_map_bin == future_map_bin | current_map_bin == 0.5 | future_map_bin == 0.5, 0,
      # Otherwise → distance to nearest CURRENT occurrence of that allele
      # In other words: if future needs ref (0), then get the distance in the current to 0. The else just means that if future needs alt (1), get the distance in the current to 1
      ifel(future_map_bin == 0, d_current_ref, d_current_alt))
  adapt_met <- adapt_distance <= maxdist

  # MOVING
  # Future targets: where each allele will exist in the FUTURE
  fut_ref_targets <- ifel(future_map_bin_ref == 1, 1, NA)
  fut_alt_targets <- ifel(future_map_bin_alt == 1, 1, NA)

  # Distances (map units; meters if CRS is projected) to nearest FUTURE cell with that allele
  d_future_ref <- mask(distance(fut_ref_targets), future)
  d_future_alt <- mask(distance(fut_alt_targets), future)

  # Movement needed to keep the same allele (track forward):
  # - 0 if current allele is 0.5
  # - 0 if the allele persists in place (because that cell is also a future target)
  # - else distance to nearest FUTURE location holding that allele
  # CHECK THIS
  move_distance <- 
    # If the allele persists at the same cell or is 0.5 → distance = 0
    ifel(current_map_bin == future_map_bin | current_map_bin == 0.5 | future_map_bin == 0.5, 0,
        # Otherwise → distance to nearest FUTURE occurrence of that allele
        # In other words: if current is ref (0), then get the distance in the future to 0. The else just means that if current is alt (1), get the distance in the future to 1
        ifel(current_map_bin == 0, d_future_ref, d_future_alt))
  move_met <- move_distance <= maxdist
  
  result <- c(adapt_distance, adapt_met, move_distance, move_met, diff_map, raw_diff_map, het_diff_map, current_map_bin, future_map_bin)
  names(result) <- c("adapt_distance", "adapt_bin", "move_distance", "move_bin", "diff", "raw_diff", "het_diff", "current_bin", "future_bin")
  result <- as.list(result)
  return(result)
}

snp_names <- colnames(dos)
names(snp_names) <- snp_names
current_agg <- aggregate(current, 5)
future_agg <- aggregate(future, 5)

availability <- 
  map(snp_names, ~{
    # .x = "chr10_20210652_T_C"
    snp <- dos %>% pull(.x)
    predict_allele(snp, coords, current_agg, future_agg, maxdist = 10000, admix_thresh = 0.1)
  }, .progress = TRUE) 

ca <- 
  rnaturalearth::ne_states(country = "United States of America", returnclass = "sf") %>%
  filter(name == "California") %>%
  st_transform(3310)

current_ca <- mask(current_agg, ca)
avail_crop <- map(availability, ~as.list(crop(mask(rast(.x), current_ca), ca)), .progress = TRUE)

avail_stack <- list_transpose(avail_crop)
names(avail_stack) <- names(rast(availability[[1]]))

avail_stack <- map(avail_stack, rast)
mean_stack <- map(avail_stack, ~mean(.x), na.rm = TRUE) %>% rast()
dist_stack <- mean_stack[[c("adapt_distance", "move_distance")]]
dist_stack[dist_stack < 1000] <- NA

gg_df <- 
  extract(mean_stack, coords, ID = FALSE, method = "bilinear") %>% 
  as.data.frame() %>%
  bind_cols(coords) %>%
  st_as_sf()

plot_map <- function(var){
  ggplot() +
    geom_sf(data = ca, fill = "lightgrey", color = "darkgrey") +
    geom_sf(data = gg_df, aes(col = .data[[var]])) +
    scale_color_viridis_c(option = "plasma", direction = 1, na.value = "transparent") +
    coord_sf() +
    theme_void() +
    labs(col = var)
}

pdf(here(plotpath, "hsp_angrypancake_summary_maps.pdf"), width = 12, height = 10)
plot(mean_stack, col = viridis::plasma(100, direction = 1))
plot(dist_stack, col = viridis::plasma(100, direction = 1))
plts <- map(names(mean_stack), ~(plot_map(.x)))
cowplot::plot_grid(plotlist = plts, ncol = 3)
dev.off()


pdf(here(plotpath, "hsp_angrypancake_maps.pdf"), width = 12, height = 10)
iwalk(avail_stack, \(x, i) {
  x_df <- as.data.frame(x, xy = TRUE) %>% pivot_longer(-c(x, y), names_to = "name", values_to = "value")
  plt <- 
    ggplot(x_df) +
    geom_sf(data = ca[,1], fill = "lightgrey", color = "darkgrey") +
    geom_raster(aes(x = x, y = y, fill = value)) +
    scale_fill_viridis_c(option = "plasma", direction = 1, na.value = "transparent") +
    facet_wrap(~name) +
    theme_void() +
    labs(fill = i)
  print(plt)
})
dev.off()

# Plot example
example1 <- avail_crop[[1]] %>% rast()
snp1 <- dos %>% pull(colnames(dos)[1]) 

dist_map1 <- c(example1$adapt_distance, example1$move_distance)
dist_map1[dist_map1 < 1000] <- NA
dist_map1_df <- as.data.frame(dist_map1, xy = TRUE) %>% pivot_longer(-c(x, y), names_to = "name", values_to = "distance")

net_dist1 <- c(dist_map1$adapt_distance, dist_map1$move_distance)
dist_map1_div <- 
  as.data.frame(net_dist1, xy = TRUE) %>%
  mutate(net_dist = adapt_distance - move_distance) %>%
  mutate(net_dist = ifelse(adapt_distance < 1000 | move_distance < 1000, NA, net_dist)) %>%
  mutate(strategy = case_when(
    adapt_distance < move_distance ~ adapt_distance,
    move_distance < adapt_distance ~ -move_distance,
    adapt_distance == move_distance ~ 0
  )) %>%
  mutate(strategy = ifelse(is.na(net_dist), NA, strategy)) %>%
  mutate(net_dist_bin = 
    case_when(
      # ORDER MATTERS!
      abs(net_dist) > 100000 ~ "Neither",
      net_dist > 0 ~ "Move", # Adapt - move = positive → move is smaller
      net_dist < 0 ~ "Adapt", # Adapt - move = negative → adapt is smaller
      net_dist == 0 ~ "Either"
    )
  ) 
range(dist_map1_div$net_dist)
unique(dist_map1_div$net_dist_bin)

bivcols <- c("#515151", "#52b6b6", "#ad5b9c", "#434e87")
names(bivcols) <- c("Neither", "Move", "Adapt", "Either")
legend_df <- data.frame(Strategy = names(bivcols), col = bivcols, x = c(1,2,1,2), y = c(1,1,2,2))

pdf(here(plotpath, "hsp_angrypancake_example.pdf"), width = 6, height = 6)
plot(example1, box = FALSE, axes = FALSE)

ggplot(dist_map1_df) +
  geom_sf(data = ca[,1], fill = "lightgrey", color = "darkgrey") +
  geom_raster(aes(x = x, y = y, fill = distance/1000)) +
  scale_fill_viridis_c(option = "plasma", direction = 1, na.value = "transparent") +
  facet_wrap(~name) +
  theme_void() +
  labs(fill = "Distance (km)")

ggplot(dist_map1_div) +
  geom_sf(data = ca[,1], fill = "lightgray", color = "darkgrey") +
  geom_raster(aes(x = x, y = y, fill = net_dist/1000), data = dist_map1_div) +
  scale_fill_gradientn(
  colours = c("#1f6c6c", "#52b6b6", "white", "#ad5b9c", "#762866"),
  values = scales::rescale(c(-1, -0.5, 0, 0.5, 1)),
  na.value = "transparent",
  name = "adapt - move"
  ) +
  theme_void() +
  labs(fill = "Adapt - Move (km)")

ggplot(dist_map1_div) +
  geom_sf(data = ca[,1], fill = "lightgray", color = "darkgrey") +
  geom_raster(aes(x = x, y = y, fill = strategy/1000), data = dist_map1_div) +
  scale_fill_gradientn(
    colours = c("#1f6c6c", "#52b6b6", "white", "#ad5b9c", "#762866"),
    values = scales::rescale(c(-1, -0.5, 0, 0.5, 1)),
    na.value = "transparent",
    name = "+ adapt, - move"
  ) +
  theme_void() +
  labs(fill = "Minimum distance")

biplt <- 
  ggplot(dist_map1_div) +
  geom_sf(data = ca[,1], fill = "#e9e9e9", color = "darkgrey") +
  geom_tile(aes(x = x, y = y, fill = net_dist_bin), data = dist_map1_div) +
  scale_fill_manual(values = bivcols, na.value = "transparent") +
  theme_void() +
  labs(fill = "Strategy") +
  theme(legend.position = "none")

bilegend <- 
  ggplot(legend_df) +
  geom_tile(aes(x = x, y = y, fill = Strategy)) +
  geom_text(aes(x = x, y = y, label = Strategy), color = "white", size = 5) +
  scale_fill_manual(values = bivcols) +
  theme_void() +
  coord_equal() +
  theme(legend.position = "none")

cowplot::plot_grid(biplt, bilegend, rel_widths = c(4, 2))

ggplot() +
  geom_sf(data = ca, fill = "lightgrey", color = "darkgrey") +
  geom_sf(data = coords, aes(fill = factor(snp1)), size = 4, pch = 21) +
  scale_fill_viridis_d(option = "viridis", direction = 1, na.value = "transparent") +
  coord_sf() +
  theme_void() +
  labs(fill = colnames(dos)[1])
dev.off()

source(here("analysis", "genetic_diversity", "functions_genetic_diversity.R"))
het <- get_het()
gg_df <- gg_df %>% left_join(het)
summary(lm(adapt_distance ~ Ho, data = gg_df))

pdf(here(plotpath, "hsp_adapt_distance_vs_het.pdf"), width = 5, height = 5)
ggplot(gg_df, aes(x = Ho, y = het_diff)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_classic() +
  ggpubr::stat_cor() +
  labs(x = "Observed Heterozygosity", y = "Adaptation Distance (m)")
dev.off()
```

# DIVERGENT/BIVARIATE SCALE
## by locus
```{r}
adap_dist_df <- 
  avail_stack$adapt_distance %>% 
  as.data.frame(xy = TRUE) %>% 
  pivot_longer(-c(x, y), names_to = "locus", values_to = "adapt_distance")

move_dist_df <- 
  avail_stack$move_distance %>% 
  as.data.frame(xy = TRUE) %>% 
  pivot_longer(-c(x, y), names_to = "locus", values_to = "move_distance")

mega_df <- 
  left_join(adap_dist_df, move_dist_df, by = c("x", "y", "locus")) %>%
  mutate(net_dist = adapt_distance - move_distance) %>%
  mutate(net_dist = adapt_distance - move_distance) %>%
  mutate(net_dist = ifelse(adapt_distance < 500 | move_distance < 500, NA, net_dist)) %>%
  mutate(strategy = case_when(
    adapt_distance < move_distance ~ adapt_distance,
    move_distance < adapt_distance ~ -move_distance,
    adapt_distance == move_distance ~ 0
  )) %>%
  mutate(strategy = ifelse(move_distance < 500 | adapt_distance < 500, NA, strategy)) %>%
  mutate(net_dist_bin = 
    case_when(
      # ORDER MATTERS!
      abs(net_dist) > 100000 ~ "Neither",
      net_dist > 0 ~ "Move", # Adapt - move = positive → move is smaller
      net_dist < 0 ~ "Adapt", # Adapt - move = negative → adapt is smaller
      net_dist == 0 ~ "Either",
      is.na(net_dist) ~ "No change needed"
    )
  ) %>%
  mutate(net_dist_bin = factor(net_dist_bin, levels = c("Adapt", "Move", "Either", "Neither", "No change needed")))

mega_summary_df <-
  mega_df %>%
  group_by(x, y) %>%
  summarize(
    strategy = mean(strategy, na.rm = TRUE), 
    adapt_dist = mean(adapt_distance, na.rm = TRUE), 
    move_dist = mean(move_distance, na.rm = TRUE)
    ) %>%
  mutate(net_dist_bin = 
    case_when(
      # ORDER MATTERS!
      abs(strategy) > 100000 ~ "Neither",
      strategy < 0 ~ "Move", # Move coded negative
      strategy > 0 ~ "Adapt", # Adapt coded positive
      strategy == 0 ~ "Either",
      is.na(strategy) ~ "No change needed"
    )
  ) %>%
  mutate(min_dist = min(c(adapt_dist, move_dist), na.rm = TRUE))

mega_count_df <-
  mega_df %>%
  count(x, y, net_dist_bin) %>%
  group_by(x, y) %>%
  mutate(prop = n / sum(n), count = n)

m <- max(c(
  max(mega_summary_df$move_dist, na.rm = TRUE),
  max(mega_summary_df$adapt_dist, na.rm = TRUE)
))
plt1 <- 
  ggplot(mega_summary_df) +
  geom_sf(data = ca, fill = "lightgrey", color = "darkgrey") +
  geom_raster(aes(x = x, y = y, fill = adapt_dist/1000)) +
  scale_fill_viridis_c(option = "plasma", direction = 1, na.value = "transparent") +
  theme_void() +
  labs(fill = "Adapt Distance (km)")

plt2 <-
  ggplot(mega_summary_df) +
  geom_sf(data = ca, fill = "lightgrey", color = "darkgrey") +
  geom_raster(aes(x = x, y = y, fill = move_dist/1000)) +
  scale_fill_viridis_c(option = "plasma", direction = 1, na.value = "transparent") +
  theme_void() +
  labs(fill = "Move Distance (km)")

m <- max(abs(range(mega_summary_df$strategy, na.rm = TRUE)))/1000
plt3 <- 
  ggplot(mega_summary_df) +
  geom_sf(data = ca, fill = "lightgrey", color = "darkgrey") +
  geom_raster(aes(x = x, y = y, fill = strategy/1000)) +
  scale_fill_gradientn(
    colours = c("#1f6c6c", "#52b6b6", "white", "#ad5b9c", "#762866"),
    values  = scales::rescale(c(-1, -0.5, 0, 0.5, 1)),
    limits  = c(-m, m),               # fix min/max so 0 stays centered
    na.value = "transparent",
    name = "+ adapt, - move"
  ) +
  theme_void() 

biplt <- 
  ggplot() +
  geom_sf(data = ca[,1], fill = "#e9e9e9", color = "darkgrey") +
  geom_tile(aes(x = x, y = y, fill = net_dist_bin), data = mega_summary_df) +
  scale_fill_manual(values = bivcols, na.value = "transparent") +
  theme_void() +
  labs(fill = "Strategy") +
  theme(legend.position = "none")

bilegend <- 
  ggplot(legend_df) +
  geom_tile(aes(x = x, y = y, fill = Strategy)) +
  geom_text(aes(x = x, y = y, label = Strategy), color = "white", size = 5) +
  scale_fill_manual(values = bivcols) +
  theme_void() +
  coord_equal() +
  theme(legend.position = "none")
  
pdf(here(plotpath, "hsp_strat_by_loci_summary.pdf"), width = 20, height = 4)
cowplot::plot_grid(plt1, plt2, plt3, cowplot::plot_grid(biplt, bilegend, rel_widths = c(4, 2)), nrow = 1)
dev.off()

pdf(here(plotpath, "hsp_min_dist_plot.pdf"), width = 5, height = 5)
ggplot(mega_summary_df) +
  geom_sf(data = ca, fill = "lightgrey", color = "darkgrey") +
  geom_raster(aes(x = x, y = y, fill = min_dist/1000)) +
  scale_fill_viridis_c(option = "plasma", direction = 1, na.value = "transparent") +
  theme_void() +
  labs(fill = "Min Distance (km)")
dev.off()

pdf(here(plotpath, "hsp_net_summary_plots.pdf"), width = 12, height = 3)
ggplot(mega_count_df) +
  geom_sf(data = ca, fill = "lightgrey", color = "darkgrey") +
  geom_tile(aes(x = x, y = y, fill = prop)) +
  facet_wrap(~net_dist_bin, nrow = 1) +
  scale_fill_viridis_c(option = "plasma", direction = 1, na.value = "transparent") +
  theme_void() +
  labs(fill = "Proportion of Loci")
ggplot(mega_count_df) +
  geom_sf(data = ca, fill = "lightgrey", color = "darkgrey") +
  geom_tile(aes(x = x, y = y, fill = n)) +
  facet_wrap(~net_dist_bin, nrow = 1) +
  scale_fill_viridis_c(option = "plasma", direction = 1, na.value = "transparent") +
  theme_void() +
  labs(fill = "# Loci")
dev.off()
```


# BIVARIATE
```{r}
library(biscale)
dim = 4
data <- bi_class(gg_df, x = adapt_distance, y = move_distance, style = "quantile", dim = dim)
r_df <- as.data.frame(dist_stack, xy = TRUE) %>% drop_na()
data2 <- bi_class(r_df, x = adapt_distance, y = move_distance, style = "quantile", dim = dim)
map2 <- 
  ggplot() +
  geom_sf(data = ca, col = "lightgray", fill = "lightgray") + 
  geom_raster(data = drop_na(data2), mapping = aes(x = x, y = y, fill = bi_class), show.legend = FALSE) +
  bi_scale_fill(pal = "DkBlue2", dim = dim) +
  bi_theme() +
  theme(axis.title = element_blank())
map1 <- 
  ggplot() +
  geom_sf(data = ca, col = "lightgray", fill = "lightgray") + 
  geom_sf(data = drop_na(data), mapping = aes(fill = bi_class), col = "black", show.legend = FALSE, pch = 21, cex = 2) +
  bi_scale_fill(pal = "DkBlue2", dim = dim) +
  bi_theme() +
  theme(axis.title = element_blank())
legend <- 
  bi_legend(
    pal = "DkBlue2",
    dim = dim,
    xlab = "Adapt",
    ylab = "Move",
    size = 8
  )
bivplot <- cowplot::plot_grid(map1, legend, rel_widths = c(4, 1))
bivplot2 <- cowplot::plot_grid(map2, legend, rel_widths = c(4, 1))
# TO MAKE THIS BETTER NEED TO PUT ON SAME SCALE
pdf(here(plotpath, "hsp_bivariate_plot.pdf"), width = 6, height = 4)
bivplot
bivplot2
dev.off()
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(biscale)
library(cowplot)
library(grid)   # unit()
library(terra)

# --- 1) Choose a shared scale (km) and fixed breaks ---
dim <- 2
max_km <- ceiling(max(
  gg_df$adapt_distance, gg_df$move_distance,
  global(dist_stack$adapt_distance, "max", na.rm=TRUE)[[1]],
  global(dist_stack$move_distance,  "max", na.rm=TRUE)[[1]],
  na.rm = TRUE
) / 10) * 10             # round up to a nice number (10 km here)

breaks <- seq(0, max_km, length.out = dim + 1)

# helper: equal-interval classification to "i-j" strings biscales expects
bi_class_equal <- function(df, x, y, breaks) {
  xi <- cut(df[[x]], breaks = breaks, include.lowest = TRUE, labels = FALSE)
  yi <- cut(df[[y]], breaks = breaks, include.lowest = TRUE, labels = FALSE)
  df$bi_class <- factor(paste(xi, yi, sep = "-"),
                        levels = as.vector(outer(1:dim, 1:dim, paste, sep = "-")))
  df
}

# --- 2) Points (gg_df) on equal bins ---
data_pt <- gg_df %>%
  bi_class_equal(x = "adapt_distance", y = "move_distance", breaks = breaks)

# --- 3) Raster grid on equal bins ---
r_df <- as.data.frame(dist_stack, xy = TRUE) %>% drop_na(adapt_distance, move_distance)
data_rs <- bi_class_equal(r_df, x = "adapt_distance", y = "move_distance", breaks = breaks)

# also compute difference for the 0-isoline
r_df$move_minus_adapt <- r_df$move_distance - r_df$adapt_distance

# --- 4) Plot: points map + legend ---
map1 <-
  ggplot() +
  geom_sf(data = ca, col = "lightgray", fill = "lightgray") +
  geom_sf(data = drop_na(data_pt), aes(fill = bi_class), color = "black", pch = 21, size = 2, show.legend = FALSE) +
  bi_scale_fill(pal = "DkBlue2", dim = dim) +
  bi_theme() +
  theme(axis.title = element_blank()) +
  labs(subtitle = paste0("Equal bins on 0–", max_km, " km (", dim, "×", dim, ")"))

legend <-
  bi_legend(
    pal  = "DkBlue2",
    dim  = dim,
    xlab = "Adapt (km)",
    ylab = "Move (km)",
    size = 8
  )

bivplot <- cowplot::plot_grid(map1, legend, rel_widths = c(4, 1))

# --- 5) Plot: raster map + 0-contour where move == adapt ---
map2 <-
  ggplot() +
  geom_sf(data = ca, col = "lightgray", fill = "lightgray") +
  geom_raster(data = drop_na(data_rs), aes(x = x, y = y, fill = bi_class), show.legend = FALSE) +
  # 0-level contour of (move - adapt): move > adapt above the line, < below
  geom_contour(data = r_df, aes(x = x, y = y, z = move_minus_adapt),
               breaks = 0, linewidth = 0.4, color = "black") +
  bi_scale_fill(pal = "DkBlue2", dim = dim) +
  bi_theme() +
  theme(axis.title = element_blank()) +
  labs(subtitle = paste0("Equal bins on 0–", max_km, " km; black line: move = adapt"))

bivplot2 <- cowplot::plot_grid(map2, legend, rel_widths = c(4, 1))

# --- 6) Save ---
pdf(here(plotpath, "hsp_bivariate_plot_equalbins.pdf"), width = 6, height = 4)
bivplot
bivplot2
dev.off()

```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(biscale)
library(cowplot)
library(grid)   # unit()
library(terra)

# -------- log helpers --------
# use log10(1 + x) so zeros are OK and the scale is interpretable
logify  <- function(x) log10(1 + x)
unlog10 <- function(x) (10^x) - 1

# --- 1) Shared LOG scale and fixed breaks ---
dim <- 2

# compute global max in LINEAR km first (across points + raster)
max_km <- max(
  gg_df$adapt_distance, gg_df$move_distance,
  global(dist_stack$adapt_distance, "max", na.rm=TRUE)[[1]],
  global(dist_stack$move_distance,  "max", na.rm=TRUE)[[1]],
  na.rm = TRUE
)

# convert to LOG10(1+km) and make equal-width breaks there
max_log <- logify(max_km)
breaks_log <- seq(0, max_log, length.out = dim + 1)

# helper: classify two columns using LOG breaks -> "i-j" bi_class
bi_class_logbins <- function(df, x, y, breaks_log) {
  xi <- cut(logify(df[[x]]), breaks = breaks_log, include.lowest = TRUE, labels = FALSE)
  yi <- cut(logify(df[[y]]), breaks = breaks_log, include.lowest = TRUE, labels = FALSE)
  df$bi_class <- factor(paste(xi, yi, sep = "-"),
                        levels = as.vector(outer(1:dim, 1:dim, paste, sep = "-")))
  df
}

# --- 2) Points on LOG bins ---
data_pt <- gg_df %>%
  bi_class_logbins(x = "adapt_distance", y = "move_distance", breaks_log = breaks_log)

# --- 3) Raster grid on LOG bins ---
r_df <- as.data.frame(dist_stack, xy = TRUE) %>%
  drop_na(adapt_distance, move_distance)

data_rs <- bi_class_logbins(r_df, x = "adapt_distance", y = "move_distance", breaks_log = breaks_log)

# equality boundary (keep in linear km)
r_df$move_minus_adapt <- r_df$move_distance - r_df$adapt_distance

# --- 4) Plots ---
map1 <-
  ggplot() +
  geom_sf(data = ca, col = "lightgray", fill = "lightgray") +
  geom_sf(data = drop_na(data_pt), aes(fill = bi_class), color = "black",
          pch = 21, size = 2, show.legend = FALSE) +
  bi_scale_fill(pal = "DkBlue2", dim = dim) +
  bi_theme() +
  theme(axis.title = element_blank()) +
  labs(subtitle = paste0("Equal-width bins in log10(1+km), ",
                         dim, "×", dim, "; max ≈ ", round(max_km), " km"))

legend <-
  bi_legend(
    pal  = "DkBlue2",
    dim  = dim,
    xlab = "Adapt (log10(1+km))",
    ylab = "Move (log10(1+km))",
    size = 8
  )

bivplot <- cowplot::plot_grid(map1, legend, rel_widths = c(4, 1))

map2 <-
  ggplot() +
  geom_sf(data = ca, col = "lightgray", fill = "lightgray") +
  geom_raster(data = drop_na(data_rs), aes(x = x, y = y, fill = bi_class), show.legend = FALSE) +
  # exact boundary (move == adapt) in linear units
  geom_contour(data = r_df, aes(x = x, y = y, z = move_minus_adapt),
               breaks = 0, linewidth = 0.4, color = "black") +
  bi_scale_fill(pal = "DkBlue2", dim = dim) +
  bi_theme() +
  theme(axis.title = element_blank()) +
  labs(subtitle = "Bins in log10(1+km); black line: move = adapt (linear km)")

bivplot2 <- cowplot::plot_grid(map2, legend, rel_widths = c(4, 1))

# --- 5) Save ---
pdf(here(plotpath, "hsp_bivariate_plot_logbins.pdf"), width = 6, height = 4)
bivplot
bivplot2
dev.off()

```