---
title: "SMC++"
output:
  github_document:
    toc: TRUE
---

```{r, include = FALSE}
library(here)
library(tidyverse)
library(scales)
library(sf)
library(terra)
library(ggpubr)
source(here("analysis", "smcpp", "functions_smcpp.R"))
source(here("general_functions.R"))
source(here("analysis", "genetic_diversity", "functions_paleovars.R"))

plotpath <- here("analysis", "smcpp", "plots")

# Set global options
knitr::opts_chunk$set(
  cache = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  result = FALSE
)
```

```{r}
trace <- rast(here("data", "env", "california_chelsa_trace21k.tif"))

# Extract values at coordinates
coords <- get_coords(sf = TRUE)
mod_df <- read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv"))
time_key <- data.frame(timeid = rev(seq(-200, 20, 1)), timepoint = seq(0, 22, 0.1))
trace_vals <- 
  terra::extract(trace, coords, ID = FALSE) %>%
  mutate(SampleID = coords$SampleID) %>% 
  pivot_longer(-SampleID, names_to = "variable", values_to = "value") %>%
  filter(grepl("_bio01_", variable)) %>%
  mutate(timeid = gsub("_V1.0", "", gsub("CHELSA_TraCE21k_bio01_", "", variable))) %>%
  mutate(timeid = as.numeric(timeid)) %>%
  # Convert to k BP
  left_join(time_key) %>%
  # Convert to BP
  mutate(yearbp = timepoint*1000) %>%
  left_join(mod_df) %>%
  drop_na(Ho)

stopifnot(all(!is.na(trace_vals$yearbp)))

pdf(here(plotpath, "trace21k_vals.pdf"))
ggplot(trace_vals, aes(x = yearbp, y = value)) + 
  geom_line(aes(group = SampleID, col = Ho)) + 
  theme_classic() + 
  xlab("Time (years ago)") + 
  ylab("Temperature (C)") +
  scale_color_viridis_c(option = "turbo")
ggplot(trace_vals, aes(x = yearbp, y = value)) + 
  geom_line(aes(group = SampleID, col = Ho), alpha = 0.1) + 
  geom_line(data = filter(trace_vals, Q > 0.2), aes(group = SampleID, col = Ho)) + 
  theme_classic() + 
  xlab("Time (years ago)") + 
  ylab("Temperature (C)") +
  scale_color_viridis_c(option = "turbo")
dev.off()

paleovars <- get_paleovars()
```

```{r, fig.width = 13, fig.height = 6}
smcpp <- get_smcpp(K = 8, i = 10)
```

```{r}
ca <- get_ca()
coords <- get_coords(sf = TRUE)
paleobio1 <- map(paleovars, ~.x[[1]]) %>% rast()
# Convert to C
paleobio1 <- paleobio1/10
paleokey <- get_paleokey()

# Divergence 
div_df <- 
  data.frame(
    split = c("Initial", "SCA", "PNW-WSN", "ESN-GB"),
    year = c(0.7e6, 391e3, 95.2e3, 87.4e3)
  ) 

pop_df <- 
  list.files(here("analysis", "admixture", "outputs"), full.names = TRUE, pattern = "k8") %>%
  map(~{
    pop <- read_lines(.x)
    pop_df <- tibble(SampleID = pop, pop = basename(.x) %>% gsub(".txt", "", .) %>% gsub("k8_pop", "", .))
    return(pop_df)
  }) %>%
  bind_rows() %>%
  left_join(coords, by = "SampleID") 

paleokey_split <- 
  get_paleokey() %>%
  #filter(id != "mis19") %>%
  mutate(time = 
    case_when(
      period == "Current" ~ "1.979-2.013 ka", 
      .default = time
      )
    ) %>%
  separate(time, into = c("start_time", "end_time"), sep = "-", convert = TRUE, fill = "right") %>%
  mutate(across(c(start_time, end_time), ~ case_when(
    # Only end_time has the unit for some and start_time has unit for others
    str_detect(end_time, "ka") | str_detect(start_time, "ka") ~ as.numeric(str_remove(str_remove(.x, "ka"), "ca.")) * 1000,
    str_detect(end_time, "Ma") | str_detect(start_time, "Ma")  ~ as.numeric(str_remove(str_remove(.x, "Ma"), "ca.")) * 1000000,
    TRUE ~ as.numeric(.x)
  )))

# get values
clim_df <- extract(paleobio1, coords, ID = FALSE) 
clim_df$SampleID <- coords$SampleID
change_df <- 
  clim_df %>%
  pivot_longer(all_of(names(paleovars))) %>%
  left_join(paleokey_split, by = c("name" = "id")) %>%
  pivot_longer(c(start_time, end_time), names_to = "start_end", values_to = "time") %>%
  drop_na(time) %>%
  left_join(pop_df) %>%
  drop_na(pop)

pop_mean_change <-
  change_df %>%
  group_by(pop, time) %>%
  summarize(value = mean(value, na.rm = TRUE), .groups = "drop") 

all_mean_change <- 
  change_df %>%
  group_by(time) %>%
  summarize(value = mean(value, na.rm = TRUE), .groups = "drop") %>%
  # Scale value between high and low of pop size
  mutate(value = scales::rescale(value, to = range(filter(smcpp, T == 2, !is.na(pop), years != 0)$y))) 

# plot of population assignments
plt2 <- 
  ggplot() +
  geom_sf(data = ca) +
  geom_sf(data = st_as_sf(pop_df), aes(col = pop)) +
  labs(col = "Population") +
  #scale_color_manual(values = c("purple2", "orange2", "turquoise4", "tomato", "blue2", "magenta"))  +
  theme_void() +
  theme(
    legend.position.inside = c(0.8, 0.75),
    legend.key.size = unit(0.8, "cm"), # Increase the size of the legend keys
    legend.text = element_text(size = 14), # Increase the size of the legend text
    legend.title = element_text(size = 16) # Increase the size of the legend title
  )
 

plt1 <-
  ggplot(data = filter(smcpp, T == 2, !is.na(pop), years != 0)) +
  geom_rect(aes(xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf), fill = "slategray1") +
  geom_rect(aes(xmin = 20e3, xmax = 26e3, ymin = 0, ymax = Inf), fill = "slategray1") +
  geom_rect(aes(xmin = 115e3, xmax = 130e3, ymin = 0, ymax = Inf), fill = "slategray1") +
  annotate("text", x = 17e3, y = 1e7, label = "LGM", hjust = 0, col = "#5180b2", cex = 6)+
  annotate("text", x = 100e3, y = 1e7, label = "LIG", hjust = 0, col = "#5180b2", cex = 6) +
  annotate("text", x = 9e2, y = 1e7, label = "Holocene", hjust = 0, col = "#5180b2", cex = 6) +
  geom_vline(data = div_df, aes(xintercept = year), col = "slategray4", lty = "dashed", lwd = 0.5) +
  geom_line(data = all_mean_change, aes(x = time, y = value), col = "#5180b2", lwd = 2) +
  geom_point(data = all_mean_change, aes(x = time, y = value), col = "#5180b2", cex = 1) +
  geom_line(lwd = 1, aes(x = years, y = y, col = factor(pop), group = i), alpha = 0.9) +
  scale_x_continuous(trans = "log10", limits = c(200, 4e5), expand = c(0,0)) +
  scale_y_continuous(trans = "log10") +
  theme_classic() +
  #scale_color_manual(values = c("purple2", "orange2", "turquoise4", "tomato", "blue2", "magenta", "cyan", "")) +
  ylab("Ne") +
  xlab("years") +
  theme(legend.position = "none", strip.text = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1))

ggdf <- filter(smcpp, T == 2, !is.na(pop), years != 0) %>% mutate(group = paste0(i, pop))

plt1 <-
  ggplot(ggdf) +
  geom_line(lwd = 1, aes(x = years, y = y, col = factor(pop), group = group), alpha = 0.9) +
  scale_x_continuous(trans = "log10", limits = c(200, 4e5), expand = c(0,0)) +
  scale_y_continuous(trans = "log10") +
  theme_classic() +
  #scale_color_manual(values = c("purple2", "orange2", "turquoise4", "tomato", "blue2", "magenta", "cyan", "")) +
  ylab("Ne") +
  xlab("years") +
  theme(legend.position = "none", strip.text = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1))
pdf(here(plotpath, "smcpp.pdf"), width = 12, height = 5)
cowplot::plot_grid(plt2, plt1, ncol = 2, rel_widths = c(2, 3))
dev.off()
```

```{r}
group1 <- c("8", "6", "2")
group2 <- c("4", "3", "7")
group3 <- c("1", "5")


gg_df <- 
  filter(smcpp, T == 2, !is.na(pop), years != 0) %>%
  mutate(pop = factor(pop, levels = c(group1, group2, group3 ))) %>%
  mutate(group = case_when(
    pop %in% group1 ~ "Group 1",
    pop %in% group2 ~ "Group 2",
    pop %in% group3 ~ "Group 3"
  )) %>%
  mutate(index = paste0(i, pop)) 

gg_df_mean <- 
  gg_df %>%
  group_by(pop, years, group) %>%
  summarise(y_sd = sd(y, na.rm = TRUE), y_mean = mean(y, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(ymax = y_mean + y_sd, ymin = y_mean - y_sd) %>%
  mutate(ymax = ifelse(ymax > 7e6, 7e6, ymax), ymin = ifelse(ymin < 0, 0, ymin))


# Color scales
hiroshige_cols <- rev(c("#042346", "#295580", "#6bb2cc", "#9cd3dd", "#fecd6d", "#f7a957", "#ec7b4c", "#f04f32"))
cs1 <- hiroshige_cols[1:3]
names(cs1) <- group1
cs2 <- hiroshige_cols[4:6]
names(cs2) <- group2
cs3 <- hiroshige_cols[7:8]
names(cs3) <- group3

plt1 <-
  ggplot(data = gg_df) +
  annotate("rect", xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("rect", xmin = 19e3, xmax = 26e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("rect", xmin = 115e3, xmax = 130e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("text", x = 17e3, y = max(gg_df_mean$y_mean) * 1.1, label = "LGM", hjust = 0, col = "#065663", cex = 6)+
  annotate("text", x = 100e3, y = max(gg_df_mean$y_mean) * 1.1, label = "LIG", hjust = 0, col = "#065663", cex = 6) +
  annotate("text", x = 9e2, y = max(gg_df_mean$y_mean) * 1.1, label = "Holocene", hjust = 0, col = "#065663", cex = 6) +
  geom_vline(data = div_df, aes(xintercept = year), col = "slategray4", lty = "dashed", lwd = 0.5) +
  #geom_line(data = all_mean_change, aes(x = time, y = value, group = var), col = "#5180b2", lwd = 2) +
  #geom_point(data = all_mean_change, aes(x = time, y = value), col = "#5180b2", cex = 4) +
  #geom_ribbon(data = gg_df_mean, aes(x = years, ymin =  y_mean - y_sd, ymax = y_mean + y_sd, fill = factor(pop)), alpha = 0.2) +
  #geom_line(lwd = 0.1, aes(x = years, y = y, col = factor(pop), group = index), alpha = 0.2) +
  geom_line(data = gg_df_mean, lwd = 1.1, aes(x = years, y = y_mean, col = factor(pop)), alpha = 0.9) +
  scale_x_continuous(trans = "log10", limits = c(200, 1e+06), expand = c(0,0)) +
  scale_y_continuous(trans = "log10") +
  theme_classic() +
  scale_color_manual(values = c(cs1, cs2, cs3)) +
  ylab("Effective population size (Ne)") +
  xlab("") +
  theme(legend.position = "none", strip.text = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1)) 

pop_gg_df <-
  pop_df %>%
  mutate(pop = factor(pop, levels =  c(group1, group2, group3))) %>%
  st_as_sf()

# plot of population assignments
plt2 <- 
  ggplot() +
  geom_sf(data = ca) +
  geom_sf(data = pop_gg_df, aes(col = pop)) +
  labs(col = "Population") +
  scale_color_manual(values = c(cs1, cs2, cs3))  +
  theme_void() +
  theme(
    legend.position = "none"
  )

# Plot temperature change
plt3 <-
  ggplot(drop_na(pop_mean_change), aes(x = time, y = value, col = factor(pop))) +
  annotate("rect", xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("rect", xmin = 19e3, xmax = 26e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("rect", xmin = 115e3, xmax = 130e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  geom_vline(data = div_df, aes(xintercept = year), col = "slategray4", lty = "dashed", lwd = 0.5) +
  geom_line(lwd = 1.1) +
  geom_point(cex = 1.1) +
  scale_x_continuous(trans = "log10", limits = c(200, 1e+06), expand = c(0,0)) +
  scale_y_continuous(expand = c(0, 0), limits = c(-1, 17)) +
  scale_color_manual(values = c(cs1, cs2, cs3)) +
  theme_classic() +
  theme(legend.position = "none", strip.text = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
  labs(x = "Years", y = "Temperature (C)")


pop_label <- 
  st_drop_geometry(pop_gg_df) %>% 
  bind_cols(st_coordinates(pop_gg_df)) %>%
  group_by(pop) %>%
  summarize(x = mean(X), y = mean(Y)) %>%
  left_join(distinct(select(gg_df_mean, group, pop))) %>%
  drop_na()

gg_df2 <- gg_df %>% mutate(pop = factor(pop, levels = 1:8))

pop_mean_change <-
  pop_mean_change %>%
  mutate(scaled_value = scales::rescale(value, to = range(filter(smcpp, T == 2, !is.na(pop), years != 0)$y))) %>%
  drop_na()

plt4 <-
  ggplot(data = gg_df2) +
  annotate("rect", xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("rect", xmin = 19e3, xmax = 26e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("rect", xmin = 115e3, xmax = 130e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("text", x = 17e3, y = max(gg_df_mean$y_mean) * 3, label = "LGM", hjust = 0, col = "#065663", cex = 4)+
  annotate("text", x = 100e3, y = max(gg_df_mean$y_mean) * 3, label = "LIG", hjust = 0, col = "#065663", cex = 4) +
  annotate("text", x = 9e2, y = max(gg_df_mean$y_mean) * 3, label = "Holocene", hjust = 0, col = "#065663", cex = 4) +
  geom_line(lwd = 0.5, aes(x = years, y = y, col = factor(pop), group = index), alpha = 0.6) +
  geom_line(data = gg_df_mean, lwd = 1.1, aes(x = years, y = y_mean, col = factor(pop)), alpha = 0.9) +
  geom_point(data = pop_label, aes(x = min(gg_df_mean$years) + 1e2, y = max(gg_df_mean$y_mean) + 3e6, fill = factor(pop), group = group), cex = 6, alpha = 0.7, col = "black", pch = 21) +
  geom_text(data = pop_label, aes(x = min(gg_df_mean$years) + 1e2, y = max(gg_df_mean$y_mean) + 3e6, group = group, label = pop), cex = 4) +
  scale_x_continuous(trans = "log10", limits = c(200, NA), expand = c(0,0)) +
  scale_y_continuous(trans = "log10", limits = c(NA, 7e6)) +
  theme_classic() +
  scale_color_manual(values = c(cs1, cs2, cs3)) +
  scale_fill_manual(values = c(cs1, cs2, cs3)) +
  ylab("Effective population size (Ne)") +
  xlab("Years") +
  theme(legend.position = "none", strip.text = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
  facet_wrap(~pop, nrow = 4) 

plt5 <- 
  ggplot() +
  geom_sf(data = ca, col = NA) +
  geom_sf(data = pop_gg_df, aes(fill = pop), cex = 2, pch = 21, col = "NA")+
  geom_point(data = pop_label, aes(x = x, y = y, fill = pop), cex = 7, pch = 21, alpha = 0.7) +
  geom_text(data = pop_label, aes(x = x, y = y, label = pop), cex = 5) +
  labs(col = "Population") +
  scale_fill_manual(values = c(cs1, cs2, cs3))  +
  theme_void() +
  theme(
    legend.position = "none"
  )

png(here(plotpath, "smcpp_bypop.png"), width = 12*300, height = 9*300, res = 300)
plt5adj <- cowplot::plot_grid(plt5, NULL, ncol = 1)
cowplot::plot_grid(plt5adj, plt4, ncol = 2, rel_widths = c(0.3, 0.7), align = "v")
dev.off()

combo <- cowplot::plot_grid(plt1, plt3, ncol = 1, rel_heights = c(0.6, 0.4), align = "hv")
pdf(here(plotpath, "smcpp.pdf"), width = 13, height = 7)
cowplot::plot_grid(plt5, combo, nrow = 1, rel_widths = c(0.35, 0.65))
dev.off()
```

```{r}
# Color scales
hiroshige_cols <- rev(c("#042346", "#295580", "#6bb2cc", "#9cd3dd", "#fecd6d", "#f7a957", "#ec7b4c", "#ee5c42"))
cs1 <- hiroshige_cols[1:3]
names(cs1) <- group1
cs2 <- hiroshige_cols[4:6]
names(cs2) <- group2
cs3 <- hiroshige_cols[7:8]
names(cs3) <- group3

gg_df_mean <- 
  gg_df_mean %>% 
  # Reorder so that the lines are plotted in the correct order
  mutate(pop = factor(pop, levels = rev(c(group1, group2, group3))))

plt1 <-
  ggplot(data = gg_df) +
  annotate("rect", xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("rect", xmin = 19e3, xmax = 26e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("rect", xmin = 115e3, xmax = 130e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("text", x = 17e3, y = max(gg_df_mean$y_mean) * 1.1, label = "LGM", hjust = 0, col = "#065663", cex = 6)+
  annotate("text", x = 100e3, y = max(gg_df_mean$y_mean) * 1.1, label = "LIG", hjust = 0, col = "#065663", cex = 6) +
  annotate("text", x = 9e2, y = max(gg_df_mean$y_mean) * 1.1, label = "Holocene", hjust = 0, col = "#065663", cex = 6) +
  #geom_vline(data = div_df, aes(xintercept = year), col = "slategray4", lty = "dashed", lwd = 0.5) +
  geom_line(data = gg_df_mean, lwd = 1.1, aes(x = years, y = y_mean, col = factor(pop)), alpha = 0.9) +
  scale_x_continuous(trans = "log10", limits = c(200, 1e+06), expand = c(0,0)) +
  scale_y_continuous(trans = "log10") +
  theme_classic() +
  scale_color_manual(values = c(cs1, cs2, cs3)) +
  ylab("Effective population size (Ne)") +
  xlab("Year") +
  theme(
    legend.position = "none", 
    strip.text = element_blank(), 
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.title = element_text(size = 16), 
    axis.text = element_text(size = 12)
  ) 

plt5 <- 
  ggplot() +
  geom_sf(data = ca, col = NA) +
  geom_sf(data = pop_gg_df, aes(fill = pop), cex = 2, pch = 21, col = "NA")+
  geom_point(data = pop_label, aes(x = x, y = y, fill = pop), cex = 7, pch = 21, alpha = 0.7) +
  geom_text(data = pop_label, aes(x = x, y = y, label = pop), cex = 5) +
  labs(col = "Population") +
  scale_fill_manual(values = c(cs1, cs2, cs3))  +
  theme_void() +
  theme(
    legend.position = "none"
  )

pdf(here(plotpath, "simple_smcpp.pdf"), width = 11.5, height = 4.5)
cowplot::plot_grid(plt1, plt5, ncol = 2, rel_widths = c(0.7, 0.3), labels = c("A", "B"))
dev.off()

png(here(plotpath, "simple_smcpp.png"), width = 11.5  * 300, height = 4.5 * 300, res = 300)
cowplot::plot_grid(plt1, plt5, ncol = 2, rel_widths = c(0.65, 0.35), labels = c("A", "B"))
dev.off()
```

# Colored by paleoclimate change
```{r}
mod_df <- read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv"))
mod_df <- pop_gg_df %>% left_join(mod_df)
pop_mod_df <- mod_df %>% group_by(pop) %>% summarize(csi_past = mean(csi_past, na.rm = TRUE))
gg_df_mean <- gg_df_mean %>% left_join(pop_mod_df)

plt1 <-
  ggplot(data = gg_df_mean) +
  annotate("rect", xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf, fill = "slategray1") +
  annotate("rect", xmin = 19e3, xmax = 26e3, ymin = 0, ymax = Inf, fill = "slategray1") +
  annotate("rect", xmin = 115e3, xmax = 130e3, ymin = 0, ymax = Inf, fill = "slategray1") +
  annotate("text", x = 17e3, y = 1e7, label = "LGM", hjust = 0, col = "#5180b2", cex = 6)+
  annotate("text", x = 100e3, y = 1e7, label = "LIG", hjust = 0, col = "#5180b2", cex = 6) +
  annotate("text", x = 9e2, y = 1e7, label = "Holocene", hjust = 0, col = "#5180b2", cex = 6) +
  geom_vline(data = div_df, aes(xintercept = year), col = "slategray4", lty = "dashed", lwd = 0.5) +
  geom_line(data = gg_df_mean, lwd = 1.1, aes(x = years, y = y_mean, col = csi_past, group = factor(pop)), alpha = 0.9) +
  scale_x_continuous(trans = "log10", limits = c(200, NA), expand = c(0,0)) +
  scale_y_continuous(trans = "log10") +
  theme_classic() +
  scale_color_viridis_c(option = "viridis") +
  ylab("Ne") +
  xlab("Years") +
  theme(legend.position = "none", strip.text = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1)) 

# plot of population assignments
plt2 <- 
  ggplot() +
  geom_sf(data = ca) +
  geom_sf(data = pop_mod_df, aes(col = csi_past)) +
  labs(col = make_pretty_names("csi_past")) +
  scale_color_viridis_c(option = "viridis")  +
  theme_void() +
  theme(
    legend.position = "right"
  )

pdf(here(plotpath, "paleochange.pdf"), width = 13, height = 5)
cowplot::plot_grid(plt2, plt1, ncol = 2, rel_widths = c(0.35, 0.65))
dev.off()
```

# Paloclimate change test
```{r}
paleoclim <- rast(here("data", "env", "paleoclim", "paleoclim.tif"))[[c("lgm_bio_1", "lig_bio_1")]]

mod_df <- read_csv(here("analysis", "genetic_diversity", "outputs", "model_df.csv"))
mod_df <- 
  pop_gg_df %>% 
  left_join(mod_df) %>%
  st_as_sf() 
mod_df$lgm <- extract(paleoclim, mod_df, ID = FALSE)[,"lgm_bio_1"]
mod_df$lig <- extract(paleoclim, mod_df, ID = FALSE)[,"lig_bio_1"]
mod_df$cur <- extract(paleobio1, mod_df, ID = FALSE)[,"cur"]
mod_df$eh <- extract(paleobio1, mod_df, ID = FALSE)[,"eh"]
mod_df$eh_lgm <- mod_df$eh - mod_df$lgm

pop_mod_df <- 
  mod_df %>% 
  group_by(pop) %>% 
  summarize(across(c(lgm_lig, cur_lgm, eh_lgm, lgm, lig, Q), ~ mean(.x, na.rm = TRUE)))

smcpp_df <-
  filter(smcpp, T == 2, !is.na(pop), years != 0) %>%
  mutate(index = paste0(i, pop)) %>%
  group_by(pop, years) %>%
  summarise(y_sd = sd(y, na.rm = TRUE), y_mean = mean(y, na.rm = TRUE))

smcpp_paleo_group <- 
  smcpp_df %>%
  mutate(period  = case_when(
    years > 5e3 & years < 1e4 ~ "EH",
    years > 25e3 & years < 45e3 ~ "LGM",
    years > 115e3 & years < 130e3 ~ "LIG",
    years < 500 ~ "cur"
  )) %>%
  group_by(pop, period) 
  
smcpp_paleo <-
  smcpp_paleo_group %>%
  summarise(y_mean = mean(y_mean, na.rm = TRUE)) %>%
  drop_na(period) %>%
  pivot_wider(names_from = period, values_from = y_mean) %>%
  mutate(lgm_lig = LGM - LIG, cur_lgm = cur - LGM, cur_lgm = cur - LGM, eh_lgm = EH - LGM) %>%
  pivot_longer(-pop) %>%
  left_join(st_drop_geometry(pop_mod_df))

pdf(here(plotpath, "paleochange_test.pdf"))
ggplot(smcpp_paleo, aes(x = lgm_lig, y = value)) + 
geom_point() + 
facet_wrap(~name, scales = "free") + 
stat_cor() + 
stat_smooth(method = "lm")
ggplot(smcpp_paleo, aes(x = cur_lgm, y = value)) + 
geom_point() + 
facet_wrap(~name, scales = "free") + 
stat_cor()+ 
stat_smooth(method = "lm")

ggplot(smcpp_paleo, aes(x = lgm, y = value)) + 
geom_point() + 
acet_wrap(~name, scales = "free") + 
stat_cor()+ stat_smooth(method = "lm")
dev.off()


make_pretty2 <- function(x){
  if (x == "eh_lgm") return("Holocene Start Ne - LGM Ne")
  if (x == "Hend_lgm") return("Holocene End Ne - LGM Ne")
  if (x == "lgm_lig") return("LGM Ne - LIG Ne")
  if (x == "cur_lgm") return("Current Ne - LGM Ne")
  if (x == "cur") return("Current Ne")
  if (x == "cur_lig") return("Current Ne - LIG Ne")
  return(paste(x, "Ne"))
}

plot_ne <- function(x_var, y_var = c("LGM", "LIG", "cur_lgm", "lgm_lig", "eh_lgm")) {
  map(y_var, ~{
    sub <- filter(smcpp_paleo, name == .x)
    ylab <- make_pretty2(.x)
    ggplot(sub, aes(x = .data[[x_var]], y = value)) + 
      geom_point(aes(label = pop, col = factor(pop)), cex = 5, alpha = 0.7) + 
      geom_text(aes(label = pop), col = "black") + 
      stat_cor(label.y = min(sub[["value"]], na.rm = TRUE)) + 
      stat_smooth(method = "lm", se = FALSE) +
      labs(x = make_pretty_names(x_var), y = ylab) +
      scale_color_manual(values = c(cs1, cs2)) +
      theme_classic() +
      theme(legend.position = "none")
  })
}

plts <- map(c("cur_lgm", "lgm_lig", "lgm", "eh_lgm"), plot_ne)

pdf(here(plotpath, "paleochange_test.pdf"), width = 14, height = 3)
pltref <- 
  ggplot(smcpp_paleo_group, aes(x = years, y = y_mean, group = pop)) + 
  geom_line(aes(col = factor(pop))) +
  geom_point(data = drop_na(smcpp_paleo_group, period), aes(pch = period)) + 
  theme_classic() +
  scale_x_continuous(trans = "log10", limits = c(200, NA), expand = c(0,0)) +
  scale_y_continuous(trans = "log10") +
  scale_color_manual(values = c(cs1, cs2)) 

pltref

map(plts, ~do.call(cowplot::plot_grid, c(.x, nrow = 1)))
dev.off()

cor.test(mod_df$Ho, mod_df$lgm_lig)
cor.test(mod_df$Ho, mod_df$cur_lgm)
cor.test(mod_df$Ho, mod_df$eh_lgm)

pdf(here(plotpath, "paleochange_test2.pdf"), width = 4, height = 4)
gglm("lgm_lig", "Ho", mod_df)
gglm("eh_lgm", "Ho", mod_df)
gglm("cur_lgm", "Ho", mod_df)
ggpartial("lgm_lig", "Ho", c("lgm_lig", "Q"), drop_na(mod_df, lgm_lig, Q, Ho))
ggpartial("eh_lgm", "Ho", c("eh_lgm", "Q"),drop_na(mod_df, lgm_lig, Q, Ho))
ggpartial("cur_lgm", "Ho", c("cur_lgm", "Q"),drop_na(mod_df, lgm_lig, Q, Ho))
dev.off()
```

# Nevada test
```{r}
a <- get_paleovars(process = FALSE)

bio1 <- map(a, ~.x[[1]])[c("cur", "lh", "lgm", "lig")]

# get Nevada data from tigris
# Load the U.S. state boundaries data
states <- tigris::states(cb = TRUE)
# Extract the boundary of California (CA)
nv <- states[states$STUSPS == "NV", "STUSPS"]
nv <- sf::st_transform(nv, sf::st_crs(4326))

bio1_nv <- map(bio1, ~raster::crop(.x, nv))
bio1_nv <- map(bio1_nv, ~raster::mask(.x, nv))
bio1_nv <- rast(bio1_nv)

ca <- get_ca()
bio1_ca <- map(bio1, ~raster::crop(.x, ca))
bio1_ca <- map(bio1_ca, ~raster::mask(.x, ca))
bio1_ca <- rast(bio1_ca)

bio1_nv_df <- 
  values(bio1_nv) %>%
  data.frame() %>%
  pivot_longer(everything()) %>%
  group_by(name) %>%
  summarize(value = mean(value, na.rm = TRUE)) %>%
  mutate(name = factor(name, levels = c("cur", "lh", "lgm", "lig")))

bio1_ca_df <-
  values(bio1_ca) %>%
  data.frame() %>%
  pivot_longer(everything()) %>%
  group_by(name) %>%
  summarize(value = mean(value, na.rm = TRUE)) %>%
  mutate(name = factor(name, levels = c("cur", "lh", "lgm", "lig")))

pdf(here(plotpath, "nevada_test.pdf"))
ggplot() +
  geom_line(data = bio1_nv_df, aes(x = name, y = value, group = 1, col = "NV")) +
  geom_line(data = bio1_ca_df, aes(x = name, y = value, group = 1, col = "CA")) +
  theme_classic()
dev.off()
```