---
title: "SMC++"
output:
  github_document:
    toc: TRUE
---

```{r, include = FALSE}
library(here)
library(tidyverse)
library(scales)
library(sf)
library(terra)
library(ggpubr)
source(here("analysis", "smcpp", "functions_smcpp.R"))
source(here("general_functions.R"))
source(here("analysis", "genetic_diversity", "functions_paleovars.R"))

plotpath <- here("analysis", "smcpp", "plots")

# Set global options
knitr::opts_chunk$set(
  cache = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  result = FALSE
)
```

```{r}
coords <- get_coords(sf = TRUE)
smcpp <- get_smcpp(K = 8, i = 10)
ca <- get_ca()
```

# Climate plots

```{r}
# Divergence 
div_df <- 
  data.frame(
    split = c("Initial", "SCA", "PNW-WSN", "ESN-GB"),
    year = c(0.7e6, 391e3, 95.2e3, 87.4e3)
  ) 

pop_df <- 
  map(1:8, ~{
    pop <- read_lines(here("analysis", "admixture", "outputs", paste0("k8_pop", .x, ".txt")))
    pop_df <- tibble(SampleID = pop, pop = .x)
    return(pop_df)
  }) %>%
  bind_rows() %>%
  left_join(coords, by = "SampleID") 

paleokey_split <- 
  get_paleokey() %>%
  mutate(time = 
    case_when(
      period == "Current" ~ "1.979-2.013 ka", 
      .default = time
      )
    ) %>%
  separate(time, into = c("start_time", "end_time"), sep = "-", convert = TRUE, fill = "right") %>%
  mutate(across(c(start_time, end_time), ~ case_when(
    # Only end_time has the unit for some and start_time has unit for others
    str_detect(end_time, "ka") | str_detect(start_time, "ka") ~ as.numeric(str_remove(str_remove(.x, "ka"), "ca.")) * 1000,
    str_detect(end_time, "Ma") | str_detect(start_time, "Ma")  ~ as.numeric(str_remove(str_remove(.x, "Ma"), "ca.")) * 1000000,
    TRUE ~ as.numeric(.x)
  )))
```

# Figures 
```{r}
pop_key <- read_csv(here("analysis", "admixture", "outputs", "pop_cols.csv"))
ordered_pops <- pop_key$new_numbers
pop_cols <- pop_key %>% arrange(new_numbers) %>% pull(colors)
fill_cols <- setNames(pop_cols, pop_key$original_numbers)

gg_df <- 
  filter(smcpp, T == 2, !is.na(pop), years != 0) %>% 
  filter(!near(years, 1e6)) %>% # Remove the 1 million year point which is an artefact of the method and messes with plotting
  mutate(pop = as.character(match(as.numeric(pop), ordered_pops))) %>%
  mutate(pop = factor(pop, levels = 1:8)) %>%
  mutate(index = paste0(i, pop)) 

gg_df_mean <- 
  gg_df %>%
  group_by(pop, years) %>%
  summarise(y_sd = sd(y, na.rm = TRUE), y_mean = mean(y, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(ymax = y_mean + y_sd, ymin = y_mean - y_sd) %>%
  mutate(ymax = ifelse(ymax > 7e6, 7e6, ymax), ymin = ifelse(ymin < 0, 0, ymin))

pop_gg_df <-
  pop_df %>%
  mutate(pop = as.character(match(as.numeric(pop), ordered_pops))) %>%
  mutate(pop = factor(pop, levels = 1:8)) %>%
  st_as_sf()                               

pop_label <- 
  st_drop_geometry(pop_gg_df) %>% 
  bind_cols(st_coordinates(pop_gg_df)) %>%
  group_by(pop) %>%
  summarize(x = mean(X, na.rm = TRUE), y = mean(Y, na.rm = TRUE)) %>%
  left_join(distinct(select(gg_df_mean, pop))) %>%
  drop_na()

plt1 <-
  ggplot(data = gg_df) +
  annotate("rect", xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("rect", xmin = 19e3, xmax = 26e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("rect", xmin = 115e3, xmax = 130e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("text", x = 17e3, y = max(gg_df_mean$y_mean) * 3, label = "LGM", hjust = 0, col = "#065663", cex = 4)+
  annotate("text", x = 100e3, y = max(gg_df_mean$y_mean) * 3, label = "LIG", hjust = 0, col = "#065663", cex = 4) +
  annotate("text", x = 9e2, y = max(gg_df_mean$y_mean) * 3, label = "Holocene", hjust = 0, col = "#065663", cex = 4) +
  geom_line(lwd = 0.5, aes(x = years, y = y, col = factor(pop), group = index), alpha = 0.6) +
  geom_line(data = gg_df_mean, lwd = 1.1, aes(x = years, y = y_mean, col = factor(pop)), alpha = 0.9) +
  geom_point(data = pop_label, aes(x = min(gg_df_mean$years) + 1e2, y = max(gg_df_mean$y_mean) + 3e6, fill = factor(pop)), cex = 6, alpha = 0.7, col = "black", pch = 21) +
  geom_text(data = pop_label, aes(x = min(gg_df_mean$years) + 1e2, y = max(gg_df_mean$y_mean) + 3e6, label = pop), cex = 4) +
  scale_x_continuous(trans = "log10", limits = c(200, NA), expand = c(0,0)) +
  scale_y_continuous(trans = "log10", limits = c(NA, 7e6)) +
  theme_classic() +
  scale_color_manual(values = fill_cols) +
  scale_fill_manual(values = fill_cols) +
  ylab("Effective population size (Ne)") +
  xlab("Years") +
  theme(legend.position = "none", strip.text = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
  facet_wrap(~pop, nrow = 4) 

plt2 <- 
  ggplot() +
  geom_sf(data = ca, col = NA) +
  geom_sf(data = pop_gg_df, aes(fill = pop), cex = 2, pch = 21, col = "NA")+
  geom_point(data = pop_label, aes(x = x, y = y, fill = pop), cex = 7, pch = 21, alpha = 0.7) +
  geom_text(data = pop_label, aes(x = x, y = y, label = pop), cex = 5) +
  labs(col = "Population") +
  scale_fill_manual(values = fill_cols)  +
  theme_void() +
  theme(
    legend.position = "none"
  )

png(here(plotpath, "smcpp_bypop.png"), width = 12*300, height = 9*300, res = 300)
cowplot::plot_grid(plt1, plt2, ncol = 2, rel_widths = c(0.7, 0.3), align = "v")
dev.off()
```

```{r}
hybrid_breaks <- c(
  1e3, 2e3, 5e3, # fine spaced recent
  1e4, 2e4, 5e4, 1e5, 2e5, 5e5    # log spaced long-term
)

plt1 <-
  ggplot(data = gg_df) +
  annotate("rect", xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("rect", xmin = 19e3, xmax = 26e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("rect", xmin = 115e3, xmax = 130e3, ymin = 0, ymax = Inf, fill = "#ddf3fa") +
  annotate("text", x = 17e3, y = max(gg_df_mean$y_mean) * 1.1, label = "LGM", hjust = 0, col = "#065663", cex = 6)+
  annotate("text", x = 100e3, y = max(gg_df_mean$y_mean) * 1.1, label = "LIG", hjust = 0, col = "#065663", cex = 6) +
  annotate("text", x = 9e2, y = max(gg_df_mean$y_mean) * 1.1, label = "Holocene", hjust = 0, col = "#065663", cex = 6) +
  #geom_vline(data = div_df, aes(xintercept = year), col = "slategray4", lty = "dashed", lwd = 0.5) +
  geom_line(data = gg_df_mean, lwd = 1.1, aes(x = years, y = y_mean, col = factor(pop)), alpha = 0.9) +
  scale_x_continuous(
    trans = "log10",
    limits = c(200, max(gg_df$years)),
    breaks = hybrid_breaks,
    expand = c(0, 0),
    labels = scales::label_comma()
  ) +
  scale_y_continuous(trans = "log10") +
  theme_classic() +
  scale_color_manual(values = fill_cols) +
  ylab("Effective population size (Ne)") +
  xlab("Years before present") +
  theme(
    legend.position = "none", 
    strip.text = element_blank(), 
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.title = element_text(size = 16), 
    axis.text = element_text(size = 12),
    axis.text.x = element_text(angle = 20, hjust = 1, vjust = 1)
  ) 

pop_gg_df <-
  pop_df %>%
  mutate(pop = as.character(match(as.numeric(pop), ordered_pops))) %>%
  mutate(pop = factor(pop, levels = rev(1:8))) %>%
  st_as_sf()

pop_label <- 
  st_drop_geometry(pop_gg_df) %>% 
  bind_cols(st_coordinates(pop_gg_df)) %>%
  group_by(pop) %>%
  summarize(x = mean(X, na.rm = TRUE), y = mean(Y, na.rm = TRUE)) %>%
  left_join(distinct(select(gg_df_mean, pop))) %>%
  drop_na()

plt5 <- 
  ggplot() +
  geom_sf(data = ca, col = NA) +
  geom_sf(data = pop_gg_df, aes(fill = pop), cex = 2, pch = 21, col = "NA")+
  geom_point(data = pop_label, aes(x = x, y = y, fill = pop), cex = 7, pch = 21, alpha = 0.5) +
  geom_text(data = pop_label, aes(x = x, y = y, label = pop), cex = 5) +
  scale_fill_manual(values = fill_cols)  +
  theme_void() +
  theme(
    legend.position = "none"
  )

pdf(here(plotpath, "figure_smcpp.pdf"), width = 11.5, height = 4.5)
cowplot::plot_grid(plt1, plt5, ncol = 2, rel_widths = c(0.7, 0.3), labels = c("A", "B"), label_size = 18)
dev.off()

png(here(plotpath, "figure_smcpp.png"), width = 11.5  * 300, height = 4.5 * 300, res = 300)
cowplot::plot_grid(plt1, plt5, ncol = 2, rel_widths = c(0.65, 0.35), labels = c("A", "B"), label_size = 18)
dev.off()
```
