---
title: "SMC++"
output:
  github_document:
    toc: TRUE
---

```{r, include = FALSE}
library(here)
library(tidyverse)
library(scales)
source(here("analysis", "smcpp", "smcpp.R"))
source(here("general_functions.R"))

# Set global options
knitr::opts_chunk$set(
  cache = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  result = FALSE
)
```

```{r, fig.width = 13, fig.height = 6}
#log_years <- smcpp %>% filter(GenusSpecies == "Rallus limicola") %>% filter(T ==1) %>% pull(years) %>% log()
#inc <- log_years[2] - log_years[3]
#vira_start = exp(log_years[2] - inc)
smcpp <- 
  get_smcpp(folder = "outputs/k6", K = 6) %>%
  group_by(pop) %>%
  # Generation time of 2 years for S. occidentalis (Jameson & Allison, 1976).
  filter(T == 2) %>%
  filter(!is.na(pop))

ggplot(smcpp) +
  geom_rect(aes(xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf), fill = "grey", alpha = 0.1) +
  geom_vline(xintercept = 21e3) +
  geom_vline(xintercept = 130e3) +
  geom_line(lwd = 1, aes(x = years, y = y, col = factor(pop))) +
  scale_x_continuous(trans = "log10") +
  scale_y_continuous(trans = "log10") +
  theme_classic() +
  #scale_color_manual(values = c("purple2", "orange2", "turquoise4", "#575757")) +
  # added so that 10^2 is shown on the graph
  #geom_vline(xintercept = 100, alpha = 0) +
  ylab("Ne") +
  xlab("years")
```

```{r}
library(sf)
library(terra)
source(here("analysis/sdm/paleovars.R"))
ca <- get_ca()
coords <- get_coords(sf = TRUE)
paleovars <- rast(here("data", "env", "paleoclim", "paleoclim.tif"))
paleokey <- get_paleokey()
# isolate paleovars that end in 1 and no following numebers
bio <- paleovars[[grepl("bio_1$", names(paleovars))]]
bio <- bio[[!grepl("mis19", names(bio))]]
biovals <- extract(bio, coords, ID = FALSE)
clim_df <- bind_cols(coords, biovals)

pop_df <- 
  list.files(here("analysis", "admixture", "outputs"), full.names = TRUE, pattern = "k9") %>%
  map(~{
    pop <- read_lines(.x)
    pop_df <- tibble(SampleID = pop, pop = basename(.x) %>% gsub(".txt", "", .) %>% gsub("k9_pop", "", .))
    return(pop_df)
  }) %>%
  bind_rows() %>%
  left_join(coords, by = "SampleID") 

paleokey_split <- 
  get_paleokey() %>%
  filter(id != "mis19") %>%
  mutate(time = 
    case_when(
      period == "Current" ~ "0 ka", 
      .default = time
      )
    ) %>%
  separate(time, into = c("start_time", "end_time"), sep = "-", convert = TRUE, fill = "right") %>%
  mutate(across(c(start_time, end_time), ~ case_when(
    # Only end_time has the unit for some and start_time has unit for others
    str_detect(end_time, "ka") | str_detect(start_time, "ka") ~ as.numeric(str_remove(str_remove(.x, "ka"), "ca.")) * 1000,
    str_detect(end_time, "Ma") | str_detect(start_time, "Ma")  ~ as.numeric(str_remove(str_remove(.x, "Ma"), "ca.")) * 1000000,
    TRUE ~ as.numeric(.x)
  )))

# Divergence 
div_df <- 
  data.frame(
    split = c("Initial", "SCA", "PNW-WSN", "ESN-GB"),
    year = c(7.5e6, 391e3, 95.2e3, 87.4e3)
  ) %>%
  filter(split != "Initial") 

# get values
change_df <- 
  clim_df %>%
  pivot_longer(all_of(names(bio))) %>%
  # split based on underscore using tidyvrse
  separate(name, into = c("name", "var", "varn"), sep = "_") %>%
  mutate(var = paste(var, varn, sep = "_")) %>%
  left_join(paleokey_split, by = c("name" = "id")) %>%
  pivot_longer(c(start_time, end_time), names_to = "start_end", values_to = "time") %>%
  drop_na(time) %>%
  left_join(pop_df)

mean_change <-
  change_df %>%
  group_by(time, pop, var) %>%
  summarize(value = mean(value, na.rm = TRUE)) %>%
  drop_na(time, pop, var) %>%
  # scale value between min and max of smcpp y
  group_by(var) %>%
  mutate(value = scale(value)) %>%
  group_by(pop, var) %>%
  mutate(value = scales::rescale(value, to = c(1e5, 1e6)))

all_mean_change <- 
  change_df %>%
  group_by(time, var) %>%
  summarize(value = mean(value, na.rm =TRUE)) %>%
  drop_na(time, var) %>%
  # scale value between min and max of smcpp y
  group_by(var) %>%
  mutate(value = scale(value)) %>%
  mutate(value = scales::rescale(value, to = c(21259.24, 2004553)))

color_df <- 
  pop_df %>%
  st_as_sf() %>%
  bind_cols(st_coordinates(.)) %>%
  st_drop_geometry() %>%
  group_by(pop) %>%
  summarize(pop_color = mean(Y))
smcpp <- left_join(smcpp, color_df, by = "pop")  

plt1 <-
  ggplot(data = smcpp) +
  geom_rect(aes(xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf), fill = "slategray1") +
  geom_vline(xintercept = 21e3, lwd = 1, col = "slategray2") +
  geom_vline(xintercept = 130e3, lwd = 1, col = "slategray2") +
  geom_vline(data = div_df, aes(xintercept = year), col = "slategray4", lty = "dashed", lwd = 0.5) +
  geom_line(data = all_mean_change, aes(x = time, y = value), col = "#596678", lty = "dashed", lwd = 0.8, alpha = 0.6) +
  #geom_point(data = all_mean_change, aes(x = time, y = value), col = "#3b4657", cex = 0.5) +
  geom_line(data = mean_change, aes(x = time, y = value, col = factor(pop)), alpha = 0.7) +
  geom_point(data = mean_change, aes(x = time, y = value, col = factor(pop))) +
  annotate("text", x = 25e3, y = 1e7, label = "LGM", hjust = 0, col = "#5180b2")+
  annotate("text", x = 160e3, y = 1e7, label = "LIG", hjust = 0, col = "#5180b2") +
  annotate("text", x = 5e2, y = 1e7, label = "Holocene", hjust = 0, col = "#5180b2") +
  geom_text(aes(label = pop), x = Inf, y = Inf,  hjust = 1.5, vjust = 1.5, size = 4) +
  geom_line(lwd = 1.5, aes(x = years, y = y, col = factor(pop))) +
  scale_x_continuous(trans = "log10", limits = c(200, NA), expand = c(0,0)) +
  scale_y_continuous(trans = "log10") +
  facet_wrap(~factor(pop)) +
  theme_classic() +
  #scale_color_manual(values = c("purple2", "orange2", "turquoise4", "tomato", "blue2", "magenta", "cyan")) +
  ylab("Ne") +
  xlab("years") +
  theme(legend.position = "none", strip.text = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1))

# plot of population assignments
plt2 <- 
  ggplot() +
  geom_sf(data = ca) +
  geom_sf(data = st_as_sf(pop_df), aes(col = pop)) +
  labs(col = "Population") +
  #scale_color_manual(values = c("purple2", "orange2", "turquoise4", "tomato", "blue2", "magenta", "cyan"))  +
  theme_void() +
  theme(
    legend.position = c(0.8, 0.75),
    legend.key.size = unit(0.8, "cm"), # Increase the size of the legend keys
    legend.text = element_text(size = 14), # Increase the size of the legend text
    legend.title = element_text(size = 16) # Increase the size of the legend title
  )
 

pdf(here("analysis", "smcpp", "smcpp.pdf"), width = 18, height = 6)
cowplot::plot_grid(plt2, plt1, ncol = 2, rel_widths = c(1, 2))
dev.off()


plt1 <-
  ggplot(data = smcpp) +
  geom_rect(aes(xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf), fill = "slategray1") +
  geom_vline(xintercept = 21e3, lwd = 1, col = "slategray2") +
  geom_vline(xintercept = 130e3, lwd = 1, col = "slategray2") +
  geom_vline(data = div_df, aes(xintercept = year), col = "slategray4", lty = "dashed", lwd = 0.5) +
  geom_line(data = all_mean_change, aes(x = time, y = value, group = var), col = "#5180b2", lwd = 2) +
  geom_point(data = all_mean_change, aes(x = time, y = value), col = "#5180b2", cex = 1) +
  annotate("text", x = 25e3, y = 1e7, label = "LGM", hjust = 0, col = "#5180b2", cex = 6)+
  annotate("text", x = 160e3, y = 1e7, label = "LIG", hjust = 0, col = "#5180b2", cex = 6) +
  annotate("text", x = 9e2, y = 1e7, label = "Holocene", hjust = 0, col = "#5180b2", cex = 6) +
  geom_line(lwd = 1, aes(x = years, y = y, col = factor(pop)), alpha = 0.9) +
  scale_x_continuous(trans = "log10", limits = c(200, NA), expand = c(0,0)) +
  scale_y_continuous(trans = "log10") +
  theme_classic() +
  #scale_color_viridis_c() +
  #scale_color_manual(values = c("purple2", "orange2", "turquoise4", "tomato", "blue2", "magenta", "cyan")) +
  ylab("Ne") +
  xlab("years") +
  theme(legend.position = "none", strip.text = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1))

pdf(here("analysis", "smcpp", "smcpp2.pdf"), width = 12, height = 5)
cowplot::plot_grid(plt2, plt1, ncol = 2, rel_widths = c(2, 3))
dev.off()
 

plt1 <-
  ggplot(data = filter(smcpp, years != 0)) +
  geom_rect(aes(xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf), fill = "slategray1") +
  geom_vline(xintercept = 21e3, lwd = 1, col = "slategray2") +
  geom_vline(xintercept = 130e3, lwd = 1, col = "slategray2") +
  geom_vline(data = div_df, aes(xintercept = year), col = "slategray4", lty = "dashed", lwd = 0.5) +
  geom_line(data = all_mean_change, aes(x = time, y = value, group = var), col = "#5180b2", lwd = 2) +
  geom_point(data = all_mean_change, aes(x = time, y = value), col = "#5180b2", cex = 1) +
  annotate("text", x = 25e3, y = 1e7, label = "LGM", hjust = 0, col = "#5180b2", cex = 6)+
  annotate("text", x = 160e3, y = 1e7, label = "LIG", hjust = 0, col = "#5180b2", cex = 6) +
  annotate("text", x = 9e2, y = 1e7, label = "Holocene", hjust = 0, col = "#5180b2", cex = 6) +
  geom_line(lwd = 1, aes(x = years, y = y, col = factor(pop)), alpha = 0.9) +
  scale_x_continuous(trans = "log10", limits = c(200, NA), expand = c(0,0)) +
  scale_y_continuous(trans = "log10") +
  theme_classic() +
  facet_wrap(~var) +
  #scale_color_manual(values = c("purple2", "orange2", "turquoise4", "tomato", "blue2", "magenta")) +
  ylab("Ne") +
  xlab("years") +
  theme(legend.position = "none", panel.border = element_rect(colour = "black", fill = NA, size = 1))

pdf(here("analysis", "smcpp", "smcpp3.pdf"), width = 25, height = 10)
plt1
dev.off()
```

```{r}

gg_df <- 
  smcpp %>%
  mutate(color_group = 
    case_when(
      pop %in% c(3,6:9) ~ "Group 1",
      pop %in% c(1,5) ~ "Group 2", 
      pop == 2 ~ "Group 3", 
      pop == 4 ~ "Group 4")
    )

pop_df2 <- left_join(pop_df, distinct(select(gg_df, pop, color_group)))

# plot of population assignments
plt2 <- 
  ggplot() +
  geom_sf(data = ca) +
  geom_sf(data = st_as_sf(pop_df2), aes(col = color_group)) +
  labs(col = "Population") +
  #scale_color_manual(values = c("purple2", "orange2", "turquoise4", "tomato", "blue2", "magenta", "cyan"))  +
  theme_void() +
  theme(
    legend.position = c(0.8, 0.75),
    legend.key.size = unit(0.8, "cm"), # Increase the size of the legend keys
    legend.text = element_text(size = 14), # Increase the size of the legend text
    legend.title = element_text(size = 16) # Increase the size of the legend title
  ) 

plt1 <-
  ggplot(data = gg_df) +
  geom_rect(aes(xmin = 0.3e3, xmax = 11.7e3, ymin = 0, ymax = Inf), fill = "slategray1") +
  geom_vline(xintercept = 21e3, lwd = 1, col = "slategray2") +
  geom_vline(xintercept = 130e3, lwd = 1, col = "slategray2") +
  geom_vline(data = div_df, aes(xintercept = year), col = "slategray4", lty = "dashed", lwd = 0.5) +
  geom_line(data = all_mean_change, aes(x = time, y = value, group = var), col = "#5180b2", lwd = 2) +
  geom_point(data = all_mean_change, aes(x = time, y = value), col = "#5180b2", cex = 1) +
  annotate("text", x = 25e3, y = 1e7, label = "LGM", hjust = 0, col = "#5180b2", cex = 6)+
  annotate("text", x = 160e3, y = 1e7, label = "LIG", hjust = 0, col = "#5180b2", cex = 6) +
  annotate("text", x = 9e2, y = 1e7, label = "Holocene", hjust = 0, col = "#5180b2", cex = 6) +
  geom_line(lwd = 1, aes(x = years, y = y, col = factor(color_group), group = pop), alpha = 0.9) +
  scale_x_continuous(trans = "log10", limits = c(200, NA), expand = c(0,0)) +
  scale_y_continuous(trans = "log10") +
  theme_classic() +
  facet_wrap(~color_group) +
  #scale_color_viridis_c() +
  #scale_color_manual(values = c("purple2", "orange2", "turquoise4", "tomato", "blue2", "magenta", "cyan")) +
  ylab("Ne") +
  xlab("years") +
  theme(legend.position = "none", strip.text = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1))

pdf(here("analysis", "smcpp", "smcpp4.pdf"), width = 18, height = 7)
cowplot::plot_grid(plt2, plt1, ncol = 2, rel_widths = c(2, 3))
dev.off()
 
```