# Activate conda env:
source activate ccgpscelop 

# INSALLING MSMC & DEPENDENCIES ----------------

# install dmd
curl -fsS https://dlang.org/install.sh | bash -s dmd
source ~/dlang/dmd-2.105.3/activate
# find dmd with `which dmd` and add to path
echo 'export PATH=$PATH:/home/wanglab/dlang/dmd-2.105.3/linux/bin64' >> ~/.bashrc
source ~/.bashrc

# install GSL
sudo apt-get install libgsl-dev

# install MSMC2 and msmc-tools
git clone https://github.com/stschiff/msmc-tools.git
git clone https://github.com/stschiff/msmc2.git
cd msmc2
# note: first need to add paths to Makefile as GSLDIR=/usr/lib/x86_64-linux-gnu/ (can be found using locate libgsl.a)
# i.e. nano Makefile; add GSLDIR=/usr/lib/x86_64-linux-gnu/
make
# check if msmc has been succesfully installed:
cd build/release
./msmc2 --help

# Install snpable source code (for creating mask)
#dhttps://lh3lh3.users.sourceforge.net/snpable.shtml 
wget https://lh3lh3.users.sourceforge.net/download/seqbility-20091110.tar.bz2
tar -xvjf seqbility-20091110.tar.bz2
cd seqbility-20091110
make

# install bwa
conda install -c bioconda bwa

# install msmc tool
git clone https://github.com/stschiff/msmc-tools.git

# MAPPABILITY MASK -------------------------
# run in msmc2 directory
cd ../..

# create paths
BASE_PATH="../../data"
PREFIX="58-Sceloporus"
GENOME="$BASE_PATH/genome/ncbi_dataset/data/GCA_023333645.1/GCA_023333645.1_rSceOcc1.0.p_genomic.fna"
GENOME_NAME="GCA_023333645.1_rSceOcc1.0.p_genomic"
CALLABLE="$BASE_PATH/raw_data/58-Sceloporus_callable_sites.bed"

# 1. copy refer
cp $GENOME .
cp $GENOME.fai .

# 2. run k-mer split (takes a bit, generates a bunch of files starting with x)
seqbility-20091110/splitfa $GENOME_NAME.fna 100 | split -l 20000000

# 3. index genome
# do this in the same directory or for the alignment step it won't be able to find the index
bwa index $GENOME_NAME.fna

# 4. align with reference
# Concatenate all files starting with "xa" and create a single FASTQ file 
# done to combine multiple sequencing read files into one file.
cat xa* > reads.fq
# Align the sequencing reads in "test_reads.fq" to the reference genome "GCA_022605955.1_bRalLim1.0.p_genomic.fna" 
# (indexed before, the prefix of the index files are GCA_022605955.1_bRalLim1.0.p_genomic.fna)
# -R 1000000 sets the number of alignments to output, -O 3 and -E 3 set the gap open and extension penalties.
# The output is saved in the Sequence Alignment/Map (SAM) Index format as "test_reads.sai".
bwa aln -R 1000000 -O 3 -E 3 $GENOME_NAME.fna reads.fq > reads.sai
# Convert the alignment index file "test_reads.sai" back to the SAM format
# The SAM file contains detailed alignment information
# This step uses the same reference genome for the alignment.
bwa samse -f reads.sam $GENOME_NAME.fna reads.sai reads.fq

# 5. Generate a raw mask file from the alignment data
cat reads.sam | seqbility-20091110/gen_raw_mask.pl  > rawMask_100.fa

# 6. Generate the final mask file using "gen_mask".
seqbility-20091110/gen_mask -l 100 -r 0.5 rawMask_100.fa > mask_100_50.fa

# 7. Generate the mappability mask
# IMPORTANT: you have to manually edit the makeMappabilityMask.py file to change the paths to the paths to your fa file (TODO: make this better)
# I also had to manually change the addCalledPosition method of the MaskGenerator class from:
#self.file.write("{}\t{}\t{}\n".format(self.chr, self.lastStartPos - 1, self.lastCalledPos))
# to this:
# self.file.write("{}\t{}\t{}\n".format(self.chr, self.lastStartPos - 1, self.lastCalledPos).encode('utf-8'))
# because of an error related to the python version
# this step converts the .fa file to a .bed file
msmc-tools/makeMappabilityMask.py 
# several files are generated by this, I think this is because we split the genome into 20 million snps in step (2)
# TODO: figure out how to partition everything by scaffold

# Set paths
VCF_FILE="${BASE_PATH}/processed_data/58-Sceloporus_maf05_minDP5_maxDP50_rmsamp60_mm80_rmsamp40.vcf.gz"
CALLABLE="$BASE_PATH/raw_data/58-Sceloporus_callable_sites.bed"

# view to get individual IDs 
bcftools view -h $VCF_FILE
bcftools index -s $VCF_FILE

# get individuals and contigs
individuals=("Scelocci_MNW16-047-S58" "Scelocci_MLY21" "Scelocci_MLY75" "Scelocci_CAS241780" "Scelocci_CAS262282" "Scelocci_IW3258")
contig_string=$(bcftools view -h $VCF_FILE | grep '##contig' | cut -d ',' -f 1 | cut -d '=' -f 3 | head -n 10)

# Convert the contig string to an array
readarray -t contigs <<<"$contig_string"

for individual in "${individuals[@]}"
do
  for contig in "${contigs[@]}"
  do
    # picked a individual and scaffold
    bcftools view -s ${individual} -r ${contig} ${VCF_FILE} -Oz -o msmc.vcf.gz
    
    # removing any missing data
    bcftools view -i 'F_MISSING=0' msmc.vcf.gz -Oz -o msmc_nomiss.vcf.gz
    
    # generating inputs to MSMC
    msmc-tools/generate_multihetsep.py --mask=$CALLABLE \
                                       msmc_nomiss.vcf.gz > input_${individual}_${contig}.multihetsep.txt
    # running MSMC
    msmc2/build/release/msmc2  -t 2 -o test_${individual}_${contig}.msmc2 input_${individual}_${contig}.multihetsep.txt -p 1*4+25*2+1*4+1*6

    # remove intermediates
    rm msmc.vcf.gz
    rm msmc_nomiss.vcf.gz
  done
done

# testing with mappability mask
MASK=JALMGF010000001.1.mask.bed.gz
msmc-tools/generate_multihetsep.py --mask=$CALLABLE \
                                   --mask=$MASK \
                                   msmc_nomiss.vcf.gz > input.multihetsep.txt

msmc2/build/release/msmc2  -t 2 -o callable_mask_test.msmc2 input.multihetsep.txt -p 1*4+25*2+1*4+1*6

msmc-tools/generate_multihetsep.py --mask=$mask \
                                   msmc_nomiss.vcf.gz > input.multihetsep.txt

msmc2/build/release/msmc2  -t 2 -o mask_test.msmc2 input.multihetsep.txt -p 1*4+25*2+1*4+1*6