```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(sf)
```

```{r}
source(here("general_functions.R"))
source(here("analysis", "admixture", "admixture.R"))
ca <- get_ca()
q <- get_Q(6) %>% select(SampleID, cluster)
pop <- 
  read_table(here("data", "processed_data", "sample_depth_info.idepth")) %>%
  rename(SampleID = INDV) %>%
  left_join(get_coords()) %>% 
  left_join(q) %>%
  drop_na(cluster) 

depth <- 
  pop %>%
  group_by(cluster) %>%
  filter(MEAN_DEPTH == max(MEAN_DEPTH))

# TEST INDV: Scelocci_CAS241780

ggplot(depth) +
  geom_sf(data = ca) +
  geom_point(aes(x = x, y = y)) +
  geom_text(aes(label = SampleID, x = x, y = y), size = 5, vjust = 2) +
  theme_void()
```
```{r}
mu <- 1.17e-8
gen <- 2

samples <- depth$SampleID
names(samples) <- samples

msmc_files <- list.files(here("analysis", "msmc2"), pattern = "msmc2.final.txt", full.names = TRUE)

contigs <- msmc_files[grepl("Scelocci_MLY75_", msmc_files)]
contigs <- 
  str_extract(contigs, "test_(.*)\\.msmc2.final.txt") %>% 
  str_remove("test_") %>% 
  str_remove("Scelocci_MLY75_") %>%
  str_remove(".msmc2.final.txt") %>%
  unique()

combos <- expand.grid(sample = samples, contig = contigs)
msmc <-
  pmap(combos, \(sample, contig){
    read.table(here("analysis", "msmc2", paste0("test_", sample, "_", contig, ".msmc2.final.txt" )), header=TRUE) %>% mutate(SampleID = sample, contig = contig)
  }) %>%
  bind_rows() %>%
  left_join(depth) 
```

```{r}
source(here("analysis/sdm/paleovars.R"))
paleokey_split <- 
  get_paleokey() %>%
  filter(id != "mis19") %>%
  mutate(time = 
    case_when(
      period == "Current" ~ "0 ka", 
      .default = time
      )
    ) %>%
  separate(time, into = c("start_time", "end_time"), sep = "-", convert = TRUE, fill = "right") %>%
  mutate(across(c(start_time, end_time), ~ case_when(
    # Only end_time has the unit for some and start_time has unit for others
    str_detect(end_time, "ka") | str_detect(start_time, "ka") ~ as.numeric(str_remove(str_remove(.x, "ka"), "ca.")) * 1000,
    str_detect(end_time, "Ma") | str_detect(start_time, "Ma")  ~ as.numeric(str_remove(str_remove(.x, "Ma"), "ca.")) * 1000000,
    TRUE ~ as.numeric(.x)
  ))) %>%
  filter(id %in% c("lh", "lgm", "lig")) %>%
  mutate(id = case_when(
    id == "lh" ~ "Holocene",
    id == "lgm" ~ "LGM",
    id == "lig" ~ "LIG"
  ))

```
```{r}
msmc <- 
  msmc %>%
  mutate(
    x = left_time_boundary/mu*gen, 
    y = (1/lambda)/(2*mu)) %>%
  mutate(group = paste0(SampleID, "_", contig)) 

ggplot(msmc, aes(x = x, y = y)) +
  geom_vline(data = paleokey_split, aes(xintercept = start_time), col = "slategray3", lwd = 1) +
  geom_text(data = paleokey_split, aes(x = start_time, y = max(msmc$y), label = id), col = "slategray4", hjust = -0.2, cex = 5) +
  geom_step(aes(col = cluster, group = group)) +
  theme_classic() +
  scale_x_log10(labels = scales::comma) 

plt1 <- 
  ggplot(filter(msmc, x < 1e5, x > 2e3), aes(x = x, y = y)) +
  geom_vline(data = paleokey_split, aes(xintercept = start_time), col = "slategray3") +
  #geom_text(data = paleokey_split, aes(x = start_time, y = max(msmc$y), label = id), col = "slategray4", hjust = -0.2, cex = 5) +
  geom_step(aes(col = cluster, group = group), lwd = 1) +
  facet_wrap(~cluster, scales = "free_y") +
  theme_classic() +
  scale_x_log10(labels = scales::comma)

plt2 <-
  ggplot(depth) +
  geom_sf(data = ca) +
  geom_point(data = pop, aes(x = x, y = y, col = cluster)) +
  geom_point(aes(x = x, y = y)) +
  #geom_text(aes(label = cluster, x = x, y = y, col = cluster), size = 5, vjust = 2) +
  theme_void()

pdf(here("analysis", "msmc2", "msmc2.pdf"), width = 16, height = 4)
cowplot::plot_grid(plt2, plt1, ncol = 2, rel_widths = c(1, 3))
dev.off()
```