---
title: "adaptive_index"
output:
  github_document:
    toc: TRUE
---

```{r setup, include=FALSE}
# Set global options for caching
knitr::opts_chunk$set(
  cache = TRUE,
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  result = FALSE)

library(algatr)
library(here)
library(tidyverse)
library(RColorBrewer)
library(sf)
library(terra)
library(raster)
library(cowplot)

source(here("analysis", "anne", "adaptive_index.R"))
source(here("general_functions.R"))
```

-   [1a. Get input files]
-   [1b. Get input files]
-   [2. Calculate adaptive index]
-   [3. Build map of adaptive index]
-   [4. Build biplots]
-   [5. Knit everything together and export]

# 1a. Get input files

```{r}
scafs = list.dirs(here("outputs/RDA/"), full.names = FALSE, recursive = FALSE)
scaf_name = scafs[[9]]
path_to_output = paste0(here("outputs/RDA"), "/", scaf_name, "/")
```

```{r}
# The following will be unnecessary once newer RDA code has been run, which
# will no longer generate .rds files at all.
mod <- readRDS(paste0(path_to_output, "/58-Sceloporus_RDA_model_full.RDS"))
biplot <- data.frame(mod$CCA$biplot)
scaled_loadings <- vegan::scores(mod, choices = 1:ncol(mod$CCA$v), tidy = TRUE)
unscaled_loadings <- vegan::scores(mod, choices = 1:ncol(mod$CCA$v), tidy = TRUE, scaling = 0)

# Save outputs so I don't have to reload RDS file again
biplot %>% rownames_to_column(var = "var") %>% write_csv(file = paste0(path_to_output, "58-Sceloporus_biplot.csv"), col_names = TRUE)
scaled_loadings %>% write_csv(file = paste0(path_to_output, "58-Sceloporus_scaledloadings.csv"), col_names = TRUE)
unscaled_loadings %>% write_csv(file = paste0(path_to_output, "58-Sceloporus_unscaledloadings.csv"), col_names = TRUE)

# Load old env until new RDA results come back with new env layers:
load_algatr_example()
env_pres = CA_env
```

# 1b. Get input files

```{r}
# TODO write a function to import all the output RDA files?
# Uncomment below four lines once correct output files generated
# biplot <- read_csv(paste0(path_to_output, "58-Sceloporus_biplot.csv"))
# scaled_loadings <- read_csv(paste0(path_to_output, "58-Sceloporus_scaledloadings.csv"))
# unscaled_loadings <- read_csv(paste0(path_to_output, "58-Sceloporus_unscaledloadings.csv"))

rdadapt <- read_csv(paste0(path_to_output, "58-Sceloporus_RDA_outliers_full_rdadapt.csv"))

# env_pres <- raster::stack(here("data/env/california_chelsa_bioclim_1981-2010_V.2.1_pca.tif"))

coords <- read_tsv(here("data/ccgp_data/58-Sceloporus.coords.txt"), col_names = c("INDV", "x", "y"))
# coords <- get_coords(sf = TRUE)
ca <- get_ca()
```

# 2. Calculate adaptive index

```{r}
adap_ind <- adaptive_index(biplot, K = ncol(biplot), env_pres, 
                           coords = coords %>% dplyr::select(x, y), range = NULL, 
                           method = "loadings")
```

# 3. Build map of adaptive index

```{r}
p_adapt <- plot_adaptiveindex(Proj_data = adap_ind, scaf_name, bkg = ca, to_mask = FALSE)
p_adapt
ggsave(paste0(path_to_output, "58-Sceloporus_", scaf_name, "_adaptiveindex.png"), width = 12, height = 4)
```

# 4. Build biplots

```{r}
# TODO automatically uses q.values column from rdadapt
plt_biplot <- biplot_plot(biplot, loadings = scaled_loadings, 
                          pvals = rdadapt, sig = 0.01, biplot_type = "separate")
biplots <- plot_grid(plt_biplot$p_rda1, plt_biplot$p_rda2, plt_biplot$p_rda3, nrow = 1)
biplots
ggsave(paste0(path_to_output, "58-Sceloporus_", scaf_name, "_biplot.png"), width = 12, height = 4)
```

# 5. Knit everything together and export

```{r}
plot_grid(p_adapt, biplots, nrow = 2, rel_heights = c(1, 0.75))
ggsave(paste0(path_to_output, "58-Sceloporus_", scaf_name, "_adaptiveindexcompplot.png"), width = 12, height = 8) # add dpi arg
```
