
# format genetic distances
```{r}
library(tidyverse)
library(here)
library(terra)
library(sf)
library(algatr)
source(here("gendist.R"))

```

```{r}
# Load the U.S. state boundaries data
states <- states(cb = TRUE)
# Extract the boundary of California (CA)
ca <- states[states$STUSPS == "CA", "STUSPS"]

# sample coords
coords <- read_table(here("data/58-Sceloporus.coords.txt"), col_names = FALSE)
colnames(coords) <- c("ID", "x", "y")
```

```{r}
load_algatr_example()
format_dist()

gendist <- get_gendist()

row.names(gendist)[!(row.names(gendist) %in% coords$ID)]

i <- which(row.names(gendist) == "Array")
row.names(gendist)[i] <- colnames(gendist)[i] <- "Array#33"

row.names(gendist)[!(row.names(gendist) %in% coords$ID)]

gendist_coords <- 
  coords %>% 
  filter(ID %in% row.names(gendist)) %>%
  mutate(ID = factor(ID, levels = row.names(gendist))) %>%
  arrange(ID)

stopifnot(gendist_coords$ID == row.names(gendist))

gdm <- gdm_do_everything(gendist = gendist, coords = gendist_coords[,c("x", "y")], envlayers = CA_env, quiet = TRUE)
gdm_map(gdm$model, CA_env, gendist_coords[,c("x", "y")], plot_vars = FALSE)
gdm$coeff_df


#id_n <- which(gendist_coords$y < 34.62 & gendist_coords$x < -117.4)
mmrr <- mmrr_do_everything(gendist = gendist, coords = gendist_coords[,c("x", "y")], env = CA_env, quiet = FALSE)
mmrr$coeff_df

# Extract enviro vars
env <- extract(CA_env, gendist_coords[,c("x", "y")])
# Calculate environmental distances
X <- env_dist(env)
# Add geographic distance to X
X[["geodist"]] <- geo_dist(gendist_coords[,c("x", "y")])
Y <- as.matrix(gendist)
mod <- mmrr_run(Y, X, model = "best")

wmmrr <- function(idx){
  Xsub <- map(X, ~.x[idx, idx])
  Ysub <- Y[idx, idx]
  mod <- mmrr_run(Ysub, Xsub)
  ibd <- mod$coeff_df %>% filter(var == "CA_rPCA2") %>% pull(estimate)
  return(ibd)
}
library(wingen)

wcoords <- gendist_coords %>% st_as_sf(coords = c("x", "y"), crs = 4326) %>% st_transform(3310)
lyr <- aggregate(CA_env, 20)[[1]] %>% rast() %>% project(crs(wcoords))
preview_gd(lyr, wcoords, wdim = 11, min_n = 9)

load_middle_earth_ex()
wg <- window_general(x = 1:nrow(wcoords), coords = wcoords, lyr = lyr, stat = wmmrr, wdim = 11, min_n = 9)
# why are there values > 1?
wg_pc2 <- window_general(x = 1:nrow(wcoords), coords = wcoords, lyr = lyr, stat = wmmrr, wdim = 11, min_n = 9)
# why are there values > 1?

plot_gd(wg)
```

