---
title: "notebook"
output: html_document
date: "2023-09-25"
---

**Ideas:**
- algatr pipeline - GDM (+ kmeans clustering), MMRR, LFMM, RDA
- wingen
- DUI/IUD/UDI?
- EEMS
- Human footprint vs ROH - idea: geographic weighted regression to see where human impacts have a larger affect than expected (for example, does pi affect response?)
- Suitability vs ROH
```{r}
library(vcfR)
library(here)
library(algatr)
library(terra)
library(viridis)
```


```{r}
# Genetic data
vcf <- read.vcfR(here("data", "populations_r20.haplotypes.filtered_m70_randomSNP.vcf"))

# Coordinates
coords <- read.table(here("data", "Scelop.coord"))
coords_longlat <- st_as_sf(coords, coords = c("V1", "V2"), crs = "+proj=longlat") 
coords_proj <- st_transform(coords_longlat, crs = 3085)
plot(coords_proj)

# Environmental data
envlayers <- rast("data/CLEANED_ENVDATA_NOCOR.tif")
```
```{r}
gendist <- algatr::gen_dist(vcf, dist_type = "euclidean")
```

```{r}
plot(envlayers$CA_rPCA2)
envlayers2 <- envlayers[[c("CA_rPCA1", "CA_rPCA2","CA_rPCA3")]]
gdm <- gdm_do_everything(gendist, coords = coords, envlayers = envlayers2, scale_gendist = TRUE)
```

```{r, fig.width = 8, fig.height = 8}
# CCGP samples 
ccgp_seq <- read_table("data/58-Sceloporus.coords.txt", col_names = FALSE) 
names(ccgp_seq) <- c("SampleID", "x", "y")

worldclim <- get_worldclim(coords = ccgp_seq[, c("x", "y")])

ggplot() +
  geom_raster(data = as.data.frame(envlayers$CA_rPCA1, xy = TRUE), aes(x = x, y= y, fill = CA_rPCA1)) +
  geom_point(data = ccgp_seq, aes(x = x, y = y, col = "CCGP samples"), cex = 2.5, pch = 16) +
  scale_fill_viridis(option = "mako") +
  theme_void() +
  scale_color_manual(values = "tomato") +
  theme(legend.text = element_text(size = 18)) +
  coord_quickmap()
```
```{r}

```

